### ISSUE TITLE
Error on running Plotly with batch jobs on remote server

### ISSUE THREAD

**Issue by apal90** [plotly/plotly.py#1068]
I am a regular user of Plotly with python, but only on my own computer, where I don't run more than a couple of instances of plotly at the same time. However, I now need to run several copies of my program, which uses plotly, simultaneously on a remote server. I use the following lines at the top of my code:

import plotly.plotly as py
py.sign_in('id','key') ## necessary for server simulations
This has worked for me all along, but I now get the error message:

plotly.exceptions.PlotlyError: Sign in failed.

So, what is going on? Do I need to pay even for offline use of Plotly?

**Comment by jonmmease** [comment]
Hi @apal90 ,

If you run just a single job on the remote server does it work? I'm wondering if it's something about the server configuration, or it it's some issue with having a bunch of jobs trying to sign in at the same time.

Also, what version of plotly.py are you running?  I ask because in version 3 we added logic to automatically retry server requests if they fail at first.

And finally, what is your desired visualization output from the server jobs?  You might consider just using plotly.py's offline mode (Where there is no sign-in involved and no communication with the plot.ly servers). This forum post might be helpful: https://community.plot.ly/t/plotly-plots-on-server/10780

**Comment by apal90** [comment]
@jonmmease  Indeed, a single job does work fine. Even upto 10-12 jobs work without problems. If I try to submit more than than simultaneously, several of them terminate with one of two errors:

> /usr/local/lib/python2.7/dist-packages/plotly/tools.py:103: UserWarning:
>Looks like you don't have 'read-write' permission to your 'home' ('~') directory or to our '~/.plotly' >directory. That means plotly's python api can't setup local configuration files. No problem though! >You'll just have to sign-in using 'plotly.plotly.sign_in()'. For help with that: 'help(plotly.plotly.sign_in)'.
>Questions? Visit https://support.plot.ly

or 
>import plotly.plotly as py
>py.sign_in('id','key') ## necessary for server simulations
>This has worked for me all along, but I now get the error message:
>plotly.exceptions.PlotlyError: Sign in failed.

Here is the sum total of my Plotly declarations --

`#from plotly.tools import set_credentials_file`
`set_credentials_file(username='aas', api_key='asdasdasdasd') #, stream_ids=['xx', 'xx'])`
`from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot`

Is this not sufficient to run plotly offline? I don't see where I am trying to connect online. I only used the `set_credentials_file` because of the first error message displayed above. I thought I could not access Plotly even offline without credentials. 

My Plotly version is 2.5.1, and my desired output is simple 3D scatter plots and triplots. I will look at the forum post and see if it helps. Please let me know if the above information tells you anything.

**Comment by jonmmease** [comment]
Hi @apal90 ,

Yes, you can use plotly offline without any credentials. But I'm not sure I'm following your example any more.  Can you remove the call to`set_credentials_file` and then copy the full stack trace that you get for the first error? I want to understand which top-level plotly method is resulting in the error.

It would also be helpful if you could update to the current version (3.1.0). I don't expect that it will fix the issue, but it will make debugging easier.

**Comment by apal90** [comment]
Hi @jonmmease ,

I am sorry, but I had made an error in reporting my code. Also, I upgraded to the latest version, but that does not solve my problems. My Plotly declarations are as follows --

```
import plotly.plotly as py
py.sign_in('apal90','asasdasd') ## necessary for server simulations

import plotly.graph_objs as go
import plotly.figure_factory as FF
from plotly.offline import plot, iplot
```
So, as you see, I already use the offline versions of `plot, iplot`. Also, it seems that at some time I had read something online that had made me think that signing in was necessary for server simulations. Perhaps it was the same error as below that prompted it; I don't remember any more.

The error I get is the following:
```
/usr/local/lib/python2.7/dist-packages/plotly/tools.py:102: UserWarning:

Looks like you don't have 'read-write' permission to your 'home' ('~') directory or to our '~/.plotly' directory. That means plotly's python api can't setup local configuration files. No problem though! You'll just have to sign-in using 'plotly.plotly.sign_in()'. For help with that: 'help(plotly.plotly.sign_in)'.
Questions? Visit https://support.plot.ly
```

And that's it. The other error message stopped appearing. Does that make anything clearer?

**Comment by jonmmease** [comment]
Ok, I think I might see what's going on here. It looks like we're automatically checking for read-write permissions on the `~/.plotly` directory even if we don't need it for credentials etc.

This warning message is a bit misleading since you still don't need to call `plotly.plotly.sign_in()` if you're working offline. My guess is that this message predates plotly.py's offline support.

Please remove the `sign_in` call and try again. This is a warning and not an error so your code should continue to execute after the warning is raised. Do you get the expected output for instances that raise the warning?

Once we sort this out I'll create an issue to work on removing this check when it's not needed and not raise the warning when working offline, but I don't expect the warning itself to cause a problem.

Thanks

**Comment by apal90** [comment]
@jonmmease  I removed the `sign_in` call, and I still get the same error. But yes, as you said, the code continued to execute, so I am thankful for that. Thanks!

**Comment by jonmmease** [comment]
Great! So you can just ignore the warning for now (and if it really bothers you, you could also suppress it altogether: https://docs.python.org/3/library/warnings.html)

I'm going to close this issue in favor of #1076 now. Thanks for reporting this!

**Comment by jonmmease** [comment]
See #1195 for full resolution
