### ISSUE TITLE
Histogram tick labels are offset

### ISSUE THREAD

**Issue by notagadget** [plotly/plotly.py#1083]
I noticed on the Histogram example, as well as in my own work, that the tick labels on some histograms are not in line with the values they represent. For instance, if you look at the ["Styled Histogram" example](https://plot.ly/python/histograms/#styled-histogram), the '0' marker is to the left of the bar for the '0' results.

**Comment by jonmmease** [comment]
Hi @notagadget ,

I think what you're seeing is that the `xbins` values specified to the `histogram` trace represent the *edges* of the bins, not the centers of the bins.

The example you linked to has this `xbins` definition
```python
    xbins=dict(
        start=-4.0,
        end=3.0,
        size=0.5
    )
```

This means that the bin edges will be at -4, -3.5, 3, etc.  So the bin centers are at -3.75, -3.25, -2.75, etc.  Plotly.js places the bars (or bar group in this case) so that they are centered on the bin center values.

If I change the `xbins` definition to:

```python
    xbins=dict(
        start=-3.75,
        end=3.25,
        size=0.5
    ),
```

Then the centers will fall at -3.5, 3, -2.5, etc. And the plot looks like this:

![newplot](https://user-images.githubusercontent.com/15064365/43676673-9e3838ce-97c3-11e8-88a1-96b0fec92990.png)

I hope that helps clear things up.  If you'd like to propose an option for an alternative bar placement behavior, feel free to open an issue on the plotly.js tracker (any change in trace options would have to flow through plotly.js before making it into plotly.py)
