### ISSUE TITLE
legend markers

### ISSUE THREAD

**Issue by guenp** [plotly/plotly.py#111]
when I create a legend

```
lg = ax.legend(loc = 'center left', bbox_to_anchor = (0, 0.8), fontsize=16)
lg.draw_frame(False)
```

the label markers are not converted properly.
mpl:
![legend_mpl](https://cloud.githubusercontent.com/assets/4041805/3999887/b68e413e-2954-11e4-8ab3-479c7fc42714.png)
plotly:
![legend_ply](https://cloud.githubusercontent.com/assets/4041805/3999886/b68c53d8-2954-11e4-9387-21abb6b063c7.png)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
