### ISSUE TITLE
Static image export via Xvfb not working

### ISSUE THREAD

**Issue by rselvak6** [plotly/plotly.py#1184]
Hi all,

I am running a Jupyter notebook on a Google Cloud VM instance and am trying to export plots to static images. I tried to configure orca to use Xvfb, as instructed in the [github](https://github.com/plotly/orca) page. When I type `orca --help` I am able to see the help instructions. However, I still get the `Return code: 1` error. Any thoughts? Thanks!

![image](https://user-images.githubusercontent.com/7735922/45655929-83458700-ba97-11e8-9db7-915c8688ed21.png)

**Comment by jonmmease** [comment]
Hi @rselvak6 , did you make a bash file like this?

```
#!/bin/bash
xvfb-run /path/to/orca-X.Y.Z-x86_64.AppImage "$@"
```

If so, set the `plotly.io.orca.config.executable` property to the full path to this bash script.  The plotly.py orca logic doesn't know anythign about `xvfb`, so you'll need to make sure that the executable it finds is your script that runs orca using `xvfb`.

**Comment by rselvak6** [comment]
@jonmmease I did have this in my bash script. Do I set the `plotly.io.orca.config.exectuable` property in the bash script as well? I tried setting it from the command line, but it tells me that property was not found.

**Comment by jonmmease** [comment]
You assign `plotly.io.orca.config.exectuable` from Python:

```python
import plotly
plotly.io.orca.config.executable = '/path/to/xvfb-orca.sh'

# Once it's working, save for future sessions
plotly.io.orca.config.save()
```

How does that work for you?

**Comment by rselvak6** [comment]
@jonmmease The bash script is in one folder, while the `AppImage` and orca executable are in another folder. Does the `plotly.io.orca.config.executable` point to the orca executable or the bash script? Appreciate the help!

`which orca` yields the path to the bash script, for reference.

**Comment by jonmmease** [comment]
Hi @rselvak6,

The `plotly.io.orca.config.executable` should point to the bash script (with `xvfb-run`). Also, you're initial error message shows that plotly.py found an orca executable under `/miniconda/bin`. Is that something you installed through conda, the AppImage, or your xvfb bash script? (If it's a conda install, go ahead and uninstall it).

And, if `which orca` shows path to the xvfb bash script, what do you get from the terminal when you run `orca --help`?

Thanks!

**Comment by rselvak6** [comment]
Hi @jonmmease ,

`/miniconda3/bin` contains the xvfb bash script (full script included below).
`orca --help` displays the normal help instructions into terminal (also included below)

![image](https://user-images.githubusercontent.com/7735922/45769079-60c88080-bbf3-11e8-9b79-d9c4bf895e99.png)

![image](https://user-images.githubusercontent.com/7735922/45769117-7c338b80-bbf3-11e8-82db-522deca94c0a.png)

Thanks!

**Comment by jonmmease** [comment]
Hi @rselvak6 , ok I think you're close.  Thanks for including the contents of your orca bash script.

It looks like there's a mix of things going on here.  This file is the auto-generated bash script generated by installing orca using conda, with your `xfvb-run` command at the top. Based on the output of `orca --help` it looks like the `xfvb-run` command is working fine.  I think the exit code 1 error is due to the fact that the conda generated orca command is running right after the `xfvb-run` orca command.

Please remove you conda orca install `conda uninstall plotly-orca`. I think this will delete this orca bash script, and then create a bash script (or edit the one you have if conda didn't remove it) that contains only

```
#!/bin/bash
xfvb-run ...
```
Also, I wouldn't recommend placing the orca AppImage in the `orca_app` directory, as this is a directory auto generated by conda.

**Comment by jonmmease** [comment]
So this message indicates that plotly.py is still finding the bash script in `/home/data/miniconda3/bin/orca`.  Maybe conda didn't clean it up since it was edited.   Let's do this next:

1) Delete the `/home/data/miniconda3/bin/orca` file

2) In your bash terminal, test that your `~/bin/orca` script still works by running
```
$ ~/bin/orca --help
```
Hopefully this still displays the orca help info

3) From python, configure plotly.py to explicitly point to this new bash script (the one with the `xvfb-run` command that references the AppImage).

```python
import plotly
plotly.io.orca.config.executable = '/path/to/home/bin/orca'

# Once it's working, save for future sessions
plotly.io.orca.config.save()
```

4) Try running an image export operation again.

5) If something goes wrong. Please include the contents of `~/bin/orca`, the result of the command in step (2), and the resulting error message raised by plotly.py.

We'll get there 🙂

**Comment by rselvak6** [comment]
Hi @jonmmease,

Apologies for the delay in getting back to you. 

There is still an error in Jupyter saying that `xvfb failed to start`. Please note the following: 

`/bin/orca` : 
![image](https://user-images.githubusercontent.com/7735922/46179837-0c1baa00-c272-11e8-810f-456fd42d3c9f.png)

Output from command window from typing `/bin/orca --help`:
![image](https://user-images.githubusercontent.com/7735922/46179886-50a74580-c272-11e8-812d-59578307018d.png)

Plotly error: 
![image](https://user-images.githubusercontent.com/7735922/46179908-687ec980-c272-11e8-926d-ad7435dccd2a.png)

Interestingly plotly claims that it can't start Xvfb when it tries `/bin/orca --version` but I get a value for this command from the command window (1.1.1). Any thoughts to this update? Thanks again for all the help so far 👍

**Comment by jonmmease** [comment]
Hi @rselvak6, I'm not sure that it's going to work to have the `sudo` command in your `/bin/orca` script. Could you remove `sudo` and try all of the above again?

**Comment by rselvak6** [comment]
I removed `sudo` but the outcome is the same, so that didn't do it.. other suggestions?

**Comment by jonmmease** [comment]
To be honest I'm running out of ideas. It sounds like the Python runtime is somehow not sharing the same environment as your shell.  What does this Python command do?

```python
import subprocess
subprocess.check_output(['orca', '--help'])
```

**Comment by jonmmease** [comment]
Hi @rselvak6, did you even have any luck with this?

**Comment by rselvak6** [comment]
Hi @jonmmease, apologies for the prolonged response. I believe the following is the expected output from the aforementioned command?

![image](https://user-images.githubusercontent.com/7735922/47685346-6d95a800-db93-11e8-8945-a87a2bb36e91.png)

There was no indication of the Python/Orca directories, but I'm unsure if that's expected.

**Comment by rselvak6** [comment]
@sondos4 this worked for me as well, thank you for the suggestion!
