### ISSUE TITLE
inf values dont work as they do in matplotlib

### ISSUE THREAD

**Issue by arsenovic** [plotly/plotly.py#125]
a small discontinuity in matplotlib-> plotly  conversion. matplotlib can plot a vector with values of -inf, inf. they simply dont display the values. 
mpld3 (@jakevdp)  stops plotting at the last value, and plotly just fails, 

http://nbviewer.ipython.org/gist/arsenovic/6a05b79b5224ae35ad9f

i think expected behavior should be that of matplotlib, because you can see the inf's, but you dont have to clean the data.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
