### ISSUE TITLE
tools.make_subplots should accept a Layout kwarg

### ISSUE THREAD

**Issue by erichiggins** [plotly/plotly.py#1253]
The `tools.make_subplots` utility function [creates an instance of `go.Layout` without any arguments](https://github.com/plotly/plotly.py/blob/master/plotly/tools.py#L1009). This creates quite a bit of headache for developers who want to change the fonts of the entire graph.  Essentially, we have to update the `Layout`, as well as all of the titles, axes, and [legend annotations](https://github.com/plotly/plotly.py/issues/985).  The inheritance does not appear to [work as expected when updating the "global font"](https://plot.ly/python/font/) in the `Layout` after the fact.

To simplify, it'd be helpful for `tools.make_subplots` to include a keyword argument for a `Layout` instance to be passed in. If one is not included, then one can be created as it is now.

```
...
layout = go.Layout(
  font=dict(family='Courier New, monospace', size=18, color='#7f7f7f')
)
figure = tools.make_subplots(rows=2, cols=1, layout=layout)
...

**Comment by jonmmease** [comment]
Hi @erichiggins, thanks for the suggestion.  I think there are two things going on here.

 1. `make_subplots` creates an empty `go.Layout` object.
 2. `make_subplots` [hard-codes the size of the subplot title annotations to 16](https://github.com/plotly/plotly.py/blob/be25c5043cd04ef6b9feb5b09dbe2a3f09660d7e/plotly/tools.py#L1381).

Having `make_subplots` start with a custom `go.Layout` object wouldn't result in a different outcome than making the layout updates after `make_subplots` is called.  For example, here's how you could change the font family to Rockwell after calling `make_subplots`

```python
from plotly import tools
import plotly.plotly as py
import plotly.graph_objs as go

# Create figure with 2 subplots
fig = tools.make_subplots(rows=2, cols=1, subplot_titles=('Plot 1', 'Plot 2'))
                          
# Add traces
fig.add_trace(go.Scatter(x=[1, 2, 3], y=[4, 5, 6]), row=1, col=1)
fig.add_trace(go.Scatter(x=[20, 30, 40], y=[50, 60, 70]), row=2, col=1)

# Customize title
fig.layout.title = 'Customizing Subplot Font'

# Customize global font family
fig.layout.font.family='Rockwell'

# Display as FigureWidget
go.FigureWidget(fig)
```
![newplot 3](https://user-images.githubusercontent.com/15064365/47954169-89b39380-df5d-11e8-81d4-a29d37c81187.png)

Here the global font family is inherited by the subplot titles (tick labels, legend labels, etc.). The global font size, however, will not affect the size of the subplot titles because of this hardcoded value of 16.

Would having the ability to specify subplot title font properties in `make_subplots` cover your usecase?  There is an old PR that started down this path https://github.com/plotly/plotly.py/pull/441/files

**Comment by erichiggins** [comment]
@jonmmease I tried this but it raised an exception.

`AttributeError: 'module' object has no attribute 'FigureWidget'`
Running the latest version of Plotly.py

**Comment by jonmmease** [comment]
Hi @erichiggins, using `FigureWidget` requires having `ipywidgets` installed.  You can replace `FigureWidget` with `Figure` in the example above and display it with `plot` or `iplot` instead.

Oh interesting, the comma separated list of fonts *should* work, and by work I mean it the figure should use the left-most font that is available on the system.

Here's what I'm seeing. if `figure.layout.font.family` is set to `'Times, Courier, Arial'` all of the text has "Times" font, if set to `'invalidFont, Courier, Arial'` then all of the text has "Courier" font, and if set to `'invalidFont, invalidFont, Arial'` all of the text has "Arial" font. What do you see?
