### ISSUE TITLE
Histogram in 3.4.0

### ISSUE THREAD

**Issue by sursu** [plotly/plotly.py#1257]
Hi, I think there is an issue with FigureWidget in 3.4.0. The behavior I will describe below did not exist in 3.3.0.

I use Jupyter Lab.

```
import numpy as np

import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)
```

```
# Simulations
n = 100
A = np.arange(1,n+1, dtype=float).reshape(n,1)**(-2)
X = 2*np.random.randint(2, size=(n,1000000))-1
```

Now, this works:
`iplot([go.Histogram(x=np.sum(A*X,axis=0))])`

![newplot](https://user-images.githubusercontent.com/12001304/47952656-1452bd80-df73-11e8-8795-244e701c7cda.png)

This does not work (even though it did before):
```
# Histogram for S_n
fig = go.FigureWidget()
fig.add_histogram(x=np.sum(A*X,axis=0),
                  opacity=0.75,
                  histnorm='probability density')
fig['layout'].update(title='Distribution of $S_{'+str(n)+'}$', 
                  showlegend=False, height=700)
fig
```

![newplot 1](https://user-images.githubusercontent.com/12001304/47952659-1ae13500-df73-11e8-9326-ea61d3da594c.png)

Also, note that part of the title is not displayed.

**Comment by jonmmease** [comment]
Hi @sursu ,

Thanks a lot for taking the time to report this, and for providing the reproducible example. It looks like you caught a regression in plotly.js 1.42. I've opened a corresponding issue over there https://github.com/plotly/plotly.js/issues/3210.  In the meantime, you can work around the issue by converting your histogram `x` value to a list. e.g.

```python
fig.add_histogram(x=np.sum(A*X,axis=0).tolist(), ...)
```

The reason this only shows up in `FigureWidget` is because all of the other plotting approaches automatically convert numpy arrays to lists internally. For efficiency `FigureWidget` preserves numpy arrays as binary buffers and converts them to JavaScript TypedArrays in the browser.  And this regression is in the handling of TypedArrays by plotly.js.

**Comment by sursu** [comment]
I hope the fix will preserve the efficiency of `FigureWidget`.

What do I do wrong in the second plot that only the LaTeX expression is displayed as title?

**Comment by jonmmease** [comment]
Tracking upstream fix in https://github.com/plotly/plotly.js/pull/3211

**Comment by sursu** [comment]
@jonmmease Yes. Issue fixed.

Thank you! :+1:

**Comment by jonmmease** [comment]
Great! Thanks for giving the release candidate a try
