### ISSUE TITLE
Templates overwrite colorscale property of traces.

### ISSUE THREAD

**Issue by SaschaJust** [plotly/plotly.py#1454]
Hi,

first of all, thank you for introducing template support to plotly.

As far as I understand, template settings should only "replace" default values but never overwrite explicit properties of a plot. However, when using `colorscale` in heatmaps, the colorscale is always overwritten by the template, no matter if it's specified by alias or as a list. 

Consider the following example:

```python
import plotly.graph_objs as go
import plotly.offline as py
from plotly import __version__ as V
py.init_notebook_mode(connected=True)

print(V)

trace = go.Heatmap(
    x = list(range(1,10)),
    y = list(range(1,10)),
    z = list(range(1,10)),
    colorscale = [[0, 'rgb(255,0,0)'], [1, 'rgb(0,255,0)']]
)

layout = go.Layout(
    title = 'Colorscale templating test',
    template = 'ggplot2'
)

fig = go.Figure([trace], layout)

py.iplot(fig)
```
![Result](http://users.own-hero.net/~methos/plotly_heatmap_template_colorscale.png)

In this case, the `ggplot2` theme's colorscale will be used rather the one explicitly specified in the trace.

**Comment by jonmmease** [comment]
Hi @SaschaJust ,

Glad you're enjoying templates and thanks for the report.  It looks like the issue is that you templates set `autocolorscale` to `True` which overrides the explicit colorscale.  It will take a little digging to figure out whether the issue is with the plotly.py template or with the plotly.js template engine.

In the meantime, you can set `autocolorscale` to `False` in your heatmap definition

```python
import plotly.graph_objs as go
import plotly.offline as py
from plotly import __version__ as V
py.init_notebook_mode(connected=True)

print(V)

trace = go.Heatmap(
    x = list(range(1,10)),
    y = list(range(1,10)),
    z = list(range(1,10)),
    colorscale = 'Viridis',
    autocolorscale = False
)

layout = go.Layout(
    title = 'Colorscale templating test',
    template = 'ggplot2'
)

fig = go.Figure([trace], layout)

py.iplot(fig)
```
![newplot 11](https://user-images.githubusercontent.com/15064365/53955089-0a1e0880-40a6-11e9-87ac-d9143374b664.png)

**Comment by SaschaJust** [comment]
Hi @jonmmease,

thanks for getting back to me so quickly. That workaround does just fine.

**Comment by SaschaJust** [comment]
Just to confirm: tested with the 3.9.0 rc and works as expected.
Thanks!
