### ISSUE TITLE
Feature Request: Read file from disk for Layout

### ISSUE THREAD

**Issue by Belval** [plotly/plotly.py#1495]
Hi, I have been trying to use Plotly.py to replace matplotlib in new visualizations and from reading the documentation and going around the GitHub issues, I couldn't find a way to display images that are only available on disk.

Minimal code snippet
```
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=True)

trace=go.Scatter("relevant arguments here")

layout=go.Layout(
    images=[
        dict(
            xref="x",
            yref="y",
            sizex=max_x/10,
            sizey=max_y/10,
            xanchor="center",
            yanchor="middle",
            x=x[i],
            y=y[i],
            source='/my/absolute/path.jpg',
        )
    ],
    title= 'Title here',
    hovermode='closest',
    showlegend= False
)
fig = go.Figure(data=[trace], layout=layout)
iplot(fig)
```

I would expect this to show the image that can be found at `/my/absolute/path.jpg` but it just does not display anything. Furthermore, there seems to be no error regarding the failure to open/read the image which is a bit strange in itself.

I also tried `file:///my/absolute/path.jpg` but that did not work.

**Comment by jonmmease** [comment]
Hi @Belval,

The best way to do this is to embed the image in the figure. This can be done by loading the image as a `PIL.Image.Image` object (this requires the `pillow` package) and passing that image object as the `image.source` property. This will convert the image into a base64 encoded string and embed it in the figure so that it no longer depends on the file on the filesystem.  See https://github.com/plotly/plotly.py/issues/1401#issuecomment-457167863 for a full example.

**Comment by Belval** [comment]
That's perfectly suitable, so suitable in fact that I think it might be useful to mention it in the documentation somewhere?

Either here: https://plot.ly/python/images/

Or directly in the documentation for the source attributes, whivh only mentions URL and not PIL images being automatically converted.

Is this something you'd accept a PR for?

**Comment by jonmmease** [comment]
> Is this something you'd accept a PR for?

Absolutely! Documentation help is always appreciated. Here is the documentation repo https://github.com/plotly/documentation.

Documenting in the src attribute docstring would be great as well, but that's a little trickier because these docstring are auto generated from the plotly.js schema.  Let me know if you're interested in working on that and I can walk you through an approach.  Thanks!
