### ISSUE TITLE
go.Figure clobbers user uids

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.py#1512]
default usage of `go.Figure` does not allow users to enter `uid` for traces. That seems to be because it calls `self._data_validator = DataValidator(set_uid=True)` that triggers:

https://github.com/plotly/plotly.py/blob/bb5c998a5e08efd0d2badb604e79ff08aab2b659/_plotly_utils/basevalidators.py#L2359-L2361

Can we override `uid` only if it wasn't set by the user?

Discovered while debugging https://community.plot.ly/t/preserving-ui-state-like-zoom-in-dcc-graph/15793/34

**Comment by alexcjohnson** [comment]
In fact for `uirevision` purposes it would be better if `uid` were never set (then as far as `uirevision` is concerned, the trace order becomes the `uid`). What was the purpose to include this in the first place?

**Comment by jonmmease** [comment]
Thanks for tracking that down @alexcjohnson.  The reason that the trace uid was being set on the Python side was to support the needs of `FigureWidget`.  In this case the front end sends the default properties back to the Python side after every figure update and so plotly.py uses the `uid` to associate these updates with the proper trace.  Trace index isn't enough because the updates are sent from JavaScript to Python asynchronously and so trace reordering could have occurred in the meantime.

But, I think we should be able to work out a way to only set the UID when traces are added to a `FigureWidget` instance.  `FigureWidget` doesn't user `react`, so the uirevision considerations shouldn't be a factor there.

**Comment by alexcjohnson** [comment]
Ah, yes - would be great if only `FigureWidget` added `uid`, not `Figure`. That way Dash users wouldn't have to think about `uid` at all unless they want to preserve trace user interactions across reordered traces.

Even for `FigureWidget` I wonder if you could honor user-provided `uid` and only fill in missing ones, but there may not be an actual use case for that.

**Comment by jonmmease** [comment]
Alright if we take care of this for v4 (a couple of months out)? I think there is a *small* chance that this could be a breaking change for some applications built on top of plotly.py.

> Even for FigureWidget I wonder if you could honor user-provided uid and only fill in missing ones, but there may not be an actual use case for that.

I think I was concerned that things would fail badly if a user ended up adding multiple traces with the same not-unique `uid`.
