### ISSUE TITLE
autosize not working as expected in plotly.offline.plot

### ISSUE THREAD

**Issue by marcotama** [plotly/plotly.py#1524]
The height of plots stored in html via `plotly.offline.plot` is set to 450px when height is not specified (at least in my test).

Example:
```python
import numpy as np
import pandas as pd
import plotly
from plotly import graph_objs as go
from plotly.offline import plot

N = 1000
df = pd.DataFrame({
    't': np.random.random(N),
    'x': np.random.random(N),
    'y': np.random.random(N)
})

traces = [
    go.Scatter3d(
        x=df['x'],
        y=df['y'],
        z=df['t'],
        mode='markers',
        marker=dict(size=1)
    )
]

layout = go.Layout(
    autosize=True,
    scene=go.layout.Scene(
        xaxis=go.layout.scene.XAxis(title='X'),
        yaxis=go.layout.scene.YAxis(title='Y'),
        zaxis=go.layout.scene.ZAxis(title='Time'),
    )
)
fig = go.Figure(data=traces, layout=layout)

filename = f"demo.html"
plotly.offline.plot(fig, filename=filename, auto_open=False)
```

The picture below shows the entire browser page in `Firefox 66.0.3` on `macOS High Sierra 10.13.6`. The file looks the same in `Chrome 73.0.3683.103`. I am using `plotly 3.8.0` on `Python 3.7`.

<img width="2048" alt="Screen Shot 2019-04-16 at 12 04 42 pm" src="https://user-images.githubusercontent.com/1052500/56176933-249db700-6040-11e9-92bf-a1820213a13d.png">

**Comment by marcotama** [comment]
Pardon me, I am using plotly 3.8.0, currently the latest version.

**Comment by marcotama** [comment]
I should add, the size is adjusted correctly when used in Jupyter notebook.

**Comment by jonmmease** [comment]
Thanks for the report @marcotama.  Do you know if this worked differently prior to 3.8.0?  I ask because the reponsive resizing logic was updated to use the Plotly.js `responsive` config flag (https://plot.ly/javascript/responsive-fluid-layout/) instead of custom callbacks.

@antoinerg is the `responsive` flag expected to resize the plot vertically as well as horizontally?

**Comment by ijustmadethisforplotly** [comment]
I'm having the same issue immediately after updating from `plotly 3.7.0`  to `plotly 3.8.0`, I suspect it is related to

**Comment by antoinerg** [comment]
> @antoinerg is the responsive flag expected to resize the plot vertically as well as horizontally?

It will do different things depending on the context. If `plotly.js` is drawing into a DOM element with zero height, it will revert to its default value of 450.

My guess is this could be fixed by sizing the element in the produced HTML document. A good default could be to have it fill the viewport using CSS `width:100vw; height:100vh;`.

**Comment by jonmmease** [comment]
Thanks @antoinerg, that sounds very promising.  I'll take a look at the generated HTML and let you know if that's not enough for me to figure out what needs to be done :slightly_smiling_face:

**Comment by marcotama** [comment]
@jonmmease I confirm the problem was not present in 3.7.1.

**Comment by jonmmease** [comment]
@marcotama and @ijustmadethisforplotly, could you give the dev build in #1525 a try and confirm that it takes care of the problems you're seeing?

Installation instructions are in https://github.com/plotly/plotly.py/pull/1525#issuecomment-484235115.
Thanks!

**Comment by marcotama** [comment]
@jonmmease Confirmed! The problem disappears with the build you linked!

**Comment by marcotama** [comment]
@jonmmease Confirmed! The problem disappears with the build you linked! Thanks for the quick response!
