### ISSUE TITLE
Allow configure orca to send requests to remote server

### ISSUE THREAD

**Issue by cooperok** [plotly/plotly.py#1570]
According to [code](https://github.com/plotly/plotly.py/blob/master/plotly/io/_orca.py#L1228) static image export will work only if orca is installed on same server as plotly.py

`server_url = 'http://{hostname}:{port}'.format(hostname='localhost', port=orca_state['port'])`

But, there is an [option](https://github.com/plotly/orca/tree/master/deployment) to run orca as standalone server. Would be greate if param hostname can be specified in options same as port.

My case is that I have Google App Engine application, and it's problematic to install orca. So I want to set up standalone image server and still use plotly to get images like plotly.io.to_image(...)

**Comment by jonmmease** [comment]
Hi @cooperok, yes this is a great idea.
Happy to help someone through a PR on this if anyone is interested in tackling this.

I think we could probably add a `plotly.io.orca.config.server_url` parameter. Setting this would then unset (or override) the `executable`, `port`, and `timeout`, `mathjax`, `topojson`, and `mapbox_access_token` properties.

**Comment by maresb** [comment]
For a quick-and-dirty workaround to specify a custom hostname, I found the following two possibilities. 

1. If you are able to edit the source code, then edit `_orca.py` and manually set the desired hostname and port in the `server_url = ` command.  Since we won't be using the `orca` executable, at the end of `_orca.py` add the line `ensure_server = lambda: None` to disable the corresponding checks.  (This sets `ensure_server` to the do-nothing function.)

2. If for some reason you are unable or unwilling to edit the `plotly.py` source code, then on the machine running `plotly.py`, run the command 

        socat tcp-listen:9091,reuseaddr,fork,bind=127.0.0.1 tcp:orca-host:9091

    where `orca-host` is the hostname of the orca server.  This creates a tunnel to access `orca-host` from `localhost` of the machine running plotly.py, using the default port 9091.  Finally, import plotly.io with the following extra commands:

        import plotly.io as pio
        pio._orca.ensure_server = lambda: None
        pio._orca.orca_state["port"] = 9091


With either of these techniques, I can set up docker-compose to run [Jupyter](https://github.com/jupyter/docker-stacks) + plotly.py, and [orca](https://github.com/plotly/orca/tree/master/deployment).

**Comment by miriad** [comment]
@jonmmease  , Any chance you could review the PR on this?

**Comment by jonmmease** [comment]
done in #1850
