### ISSUE TITLE
Empty bar chart when plotting a single point using a date range

### ISSUE THREAD

**Issue by GabrielPereyra** [plotly/plotly.py#1601]
`plotly==3.10.0`

```python
import datetime
from plotly.offline import plot

plot({
    'data': [{
        'x': [datetime.datetime(2019, 6, 6)],
        'y': [5],
        'type': 'bar'
    }],
    'layout': {
        'xaxis': {
            'range': [datetime.datetime(2019, 6, 1), datetime.datetime(2019, 6, 30)]
        }
    }
})
```

The following code leads to an empty chart. If I plot a single point with numeric values instead of datetimes, change the type to scatter, add a another datapoint or double-click the chart to zoom in, I get the expected behavior.

**Comment by jonmmease** [comment]
Thanks for the report @GabrielPereyra,

The problem here is that if you specify only a single bar, then you'll need to specify the bar width manually.  The bar width is specified using the `width` parameter, and for a date axis, the width is specified in milliseconds.  So here's an example of specifying a bar width of 1 day.

```python
import datetime
from plotly.offline import plot
import plotly.graph_objs as go

fig = go.FigureWidget({
    'data': [{
        'x': [datetime.datetime(2019, 6, 6)],
        'y': [5],
        'type': 'bar',
        'width': 24*60*60*1000
    }],
    'layout': {
        'xaxis': {
            'range': [datetime.datetime(2019, 6, 1), datetime.datetime(2019, 6, 30)]
        }
    }
})
plot(fig)
```
![newplot (4)](https://user-images.githubusercontent.com/15064365/59199831-e49d1100-8b64-11e9-9e4d-61cdd1ba7cb9.png)

If you have multiple bars, then plotly.js can automatically compute reasonable bar widths. But if you have only a single bar then you need to specify the width yourself.  Does that make sense?
