### ISSUE TITLE
uploading a second unnamed figure using chart-studio 1.0.0a2 causes error

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/plotly.py#1622]
For context, I was curious to see how the new chart_studio package would handle the switch to using the v2 rest API so I did a little QA and ran into the below issue.

I get `PlotlyRequestError: Sorry, a file named 'plot from API' already exists` after trying to upload a second unnamed plot to plot.ly using chart-studio 1.0.0a2. 

Steps to reproduce:
```python
import plotly.graph_objs as go
import chart_studio.plotly as py

f = go.Figure()
f.add_scatter(y=[3,4,3,5])
py.plot(f)

f.add_bar(y=[3,4,3,5])

py.plot(f)
```

**Comment by jonmmease** [comment]
Thanks for giving it a try @michaelbabyn,

I'm not able to reproduce your exact error, but I am seeing something weird on repeated calls to `plot`.  I think part of the problem is that it looks like the `update` endpoint (https://api.plot.ly/v2/files#update) only updates the metadata of a file, not the content.  So we may need to delete existing files first and the use create to upload.

Do you get the error if you wait a couple of seconds in between calls to `plot`?  I'm wondering if there may also be a race condition there.

**Comment by jonmmease** [comment]
Thanks for giving it a try @michaelbabyn,

I'm not able to reproduce your exact error, but I am seeing something weird on repeated calls to `plot`.  I think part of the problem is that it looks like the `update` endpoint (https://api.plot.ly/v2/files#update) only updates the metadata of a file, not the content.  So we may need to delete existing files first and the use create to upload.

Do you get the error if you wait a couple of seconds in between calls to `plot`?  I'm wondering if there may also be a race condition there.

**Comment by michaelbabyn** [comment]
I don't think there's a race condition, I get the issue even after waiting a few seconds between the calls. I think there might be a couple of bugs here. What I was expecting was that a new plot and grid would be created on Chart Studio but plotly.py is trying to overwrite an existing plot named "plot from API".

The other bug is that plotly.py cannot update "plot from API".

**Comment by michaelbabyn** [comment]
Also, I only see that error if I change the number of traces in the grid. For example the code below works although the data in the grid is unchanged.

```python
import chart_studio.plotly as py

f = go.Figure()
f.add_scatter(y=[3,4,3,5])
py.plot(f)

f = go.Figure()
f.add_bar(y=[9,9,9,9])

py.plot(f)
```

So it looks like the plot gets updated properly but the grid doesn't.

**Comment by jonmmease** [comment]
Please try out `chart_studio==1.0.0a3` when you have a chance and let me know how it goes.  Thanks!

**Comment by michaelbabyn** [comment]
@jonmmease , Sorry I didn't see this until now but I've been going through the chart studio docs using 1.0.0a4 and I'm now able to update the data in an existing grid but if I want to create a new grid without passing a filename argument, it will write over whatever plot has the name "plot from API". 

I think we need to get rid of the [default plot name](https://github.com/plotly/plotly.py/blob/v4_integration/packages/python/chart-studio/chart_studio/plotly/plotly.py#L48) now that fileopt is gone.

**Comment by jonmmease** [comment]
Ahh, yeah, a grid shouldn't overwrite a plot.  But what do you expect to happen when a grid is uploaded without a name?  Should it be called "grid from API" or something?

**Comment by michaelbabyn** [comment]
@jonmmease I edited my comment above to make it more clear that my issue is the default filename. Calling iplot without a specific filename (e.g `chart_studio.plotly.iplot(fig)`) always gives a default filename of "plot from API". In version 3, plotly.py would create a new file named "plot from API (1)" if "plot from API" already existed but now it overwrites it.

I find this behaviour a little weird since I'm used to not having to name every plot I want to send to the cloud.

**Comment by nicolaskruchten** [comment]
What happens if we just provide no name at all? I thought Chart Studio handled adding the "(1)" or otherwise deduping names, no?

**Comment by jonmmease** [comment]
Hmm, the file name "plot from API" was passed along before through the clientresp I believe.  If we don't specify the name at all, we get names like `Grid 122` and `Plot 123`, without overwriting.

That works for me, I'll do this in the next alpha. but let me know what you think

**Comment by jonmmease** [comment]
@michaelbabyn ok, please try out `1.0.0a5` when you have a change 🙂

**Comment by michaelbabyn** [comment]
@jonmmease , chart_studio version 1.0.0a5 works as I expect it to. I'll go ahead and close this issue.
