### ISSUE TITLE
python Scatter uid different from the data uid in .js

### ISSUE THREAD

**Issue by Mendes11** [plotly/plotly.py#1635]
Hi,

I’m currently creating an app that has a graph with stream update using extendTrace function.
The app creates multiples Scatters in python and then send the plot to a HTML page.

Since this app can graph N scatters, acconding to the variables the user adds. I need to identify each one in the .JS so I can update it.

So to identify each scatter, I add an uid to it:

```
scatters.append(go.Scatter(
        uid=f'{equipment_uuid}',
        x=input_df['timestamp'].tolist(),
        y=input_df['value'].tolist(),
        name=f'{equipment.name} - {input_name}',
    ))
```
I though it was enough to identify it in the JS but when I get the element with:

`document.getElementById('graph').data`
it lists all the graphs, but the uid is different from the one I setted in the python Scatter class…

Am I doing something wrong or is this a bug? Is there any other way to identify each scatter (except by the name which I don’t trust to use as a unique identifier)

Thanks

**Comment by jonmmease** [comment]
From https://community.plot.ly/t/uid-setted-in-go-scatter-is-not-passed-to-the-js/24873/2

----
Hi @Mendes,

This is a known issue (See https://github.com/plotly/plotly.py/issues/1512) that will be fixed in plotly.py version 4 (to be released in a the next month or so).  You can opt-in to the new behavior with plotly.py 3.10 by activating the `trace_uids` future flag. See https://github.com/plotly/plotly.py/pull/1580.

Here's how that would look

```python
from _plotly_future_ import trace_uids
import plotly.graph_objs as go
print(go.Figure(data=[go.Scatter(y=[1, 2, 3], uid='foo123')]))
```
```plain
Figure({
    'data': [{'type': 'scatter', 'uid': 'foo123', 'y': [1, 2, 3]}], 'layout': {}
})
```

Hope that helps!
-Jon
