### ISSUE TITLE
Add orca support for .emf

### ISSUE THREAD

**Issue by maresb** [plotly/plotly.py#1680]
Orca, at least the Docker version of it, supports writing to .emf.  Plotly.py however [does not permit .emf](https://github.com/plotly/plotly.py/blob/168398e89f581bf3ae451c6bfec29bfc3b7ac9a5/packages/python/plotly/plotly/io/_orca.py#L27).  It appears to simply work, either by adding `".emf"`to `valid_formats` in the source, or by running 

```.py
import plotly.io as pio
pio._orca.format_conversions.update({"emf": "emf"})
```
Given that the fix is so simple, I have to wonder if there's a good reason why it has been left out?

**Comment by jonmmease** [comment]
Hi @maresb,

> Given that the fix is so simple, I have to wonder if there's a good reason why it has been left out?

Only reason is that plotly.py's orca support predates orca's  EMF support.  We would want to add `'emf'` to 

https://github.com/plotly/plotly.py/blob/168398e89f581bf3ae451c6bfec29bfc3b7ac9a5/packages/python/plotly/plotly/io/_orca.py#L27

and add it to all of the docstrings in this file that list all of the valid formats. e.g.

https://github.com/plotly/plotly.py/blob/168398e89f581bf3ae451c6bfec29bfc3b7ac9a5/packages/python/plotly/plotly/io/_orca.py#L571-L577

Additionally, since EMF export requires external dependencies (just Inkscape I think), we should figure out what error code plotly.js returns when these dependencies are not available, and add a helpful error message when this happens.  Something very similary to what we do for `pdf` export when `poppler` isn't installed in 

https://github.com/plotly/plotly.py/blob/168398e89f581bf3ae451c6bfec29bfc3b7ac9a5/packages/python/plotly/plotly/io/_orca.py#L1598-L1614

Happy to accept a pull request if you're interested in making these updates!

**Comment by maresb** [comment]
Closing.

Orca is old, and Kaleido now supports EMF thanks to https://github.com/plotly/Kaleido/issues/5.

Sorry I didn't get around to making a PR despite your explanation, and thanks so much for your hard work to make this happen regardless!
