### ISSUE TITLE
Legend Title

### ISSUE THREAD

**Issue by terryphi** [plotly/plotly.py#1708]
Hello,

there doesn't appear to be any method for adding a legend title.

Can you please add this?

**Comment by jonmmease** [comment]
Hi @terryphi, 

I agree that this would be nice. Here's a plotly.js issue discussing the request: https://github.com/plotly/plotly.js/issues/689. As mentioned there, it's possible to add text annotations in `paper` coordinates to act as a legend title (https://plot.ly/python/text-and-annotations/#adding-annotations-with-xref-and-yref-as-paper).

But because plotly.js has a bit of default placement logic for legends, this won't be something that we could reliably automate from Python. So I think this would need to handled in plotly.js.  @nicolaskruchten do you agree?

**Comment by nicolaskruchten** [comment]
This was implemented in 4.5 :)
