### ISSUE TITLE
Parallel coordinate plot in Jupyter notebooks: Cannot move Latex labelled column

### ISSUE THREAD

**Issue by renatobellotti** [plotly/plotly.py#1805]
Issue:
=====
When a column of a parallel coordinate plot contains Latex commands, the column cannot be dragged around. The issue does not exist for other columns. It is also possible to drag other columns past Latex columns.

Minimal example:
==============
Execute the following code in a Jupyter notebook:

```python
import numpy as np
import plotly
import plotly.graph_objects as go

dims = [
    {'label': 'Normal label', 'values': np.random.uniform(size=100)},
    {'label': '$\LaTeX$ label', 'values': np.random.uniform(size=100)},
]
data = [go.Parcoords(dimensions=dims)]
fig = go.Figure(data=data)
fig
```

**Comment by renatobellotti** [comment]
Can anybody reproduce this?

**Comment by renatobellotti** [comment]
I am still experiencing the issue. The labels are plotted at a weird location, too.
It also happens with Plotly Express.

**Comment by brian101bedrockAi** [comment]
Same issue when using LaTex. Labels are below the max value number for each axis.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
