### ISSUE TITLE
Reset axes via double click not working with Heatmapgl 

### ISSUE THREAD

**Issue by nvaytet** [plotly/plotly.py#1815]
Dear `plotly` team, 

On a plot that uses `heatmapgl`, after having zoomed in on the image, I cannot reset the axes by double-clicking. It just seems to select the bottom tick label on the colorbar, just the normal behaviour when double-clicking on some text in the web-broswer.

This happens in the Jupyter notebook, and in the online examples, such as here: https://plot.ly/python/v3/heatmap-webgl/

The only way to reset the axes is to use the reset axes button in the toolbox.

This does not happen with the non-GL version of `heatmap`.

**Comment by ned2** [comment]
I've run into this intermittently with basic Plotly figures in JupyterLab. The only thing that I've been able to observe co-relating with the issue ocurring is the size of the notebook. The same simple figure will reset on double click fine in a relatively empty notebook, fail to reset intermittently on medium sized notebooks, and never work on large notebooks with a lot of outputs. 

The workaround I found in a comment on this [Stack Overflow post](https://stackoverflow.com/questions/54394360/plotly-double-click-unzoom-not-working-for-me) is to increase the double-click delay threshold from the default 300ms to 1000ms:

```python
figure.show(config={"doubleClickDelay": 1000})
```

This made me wonder if there's some kind of issue with rendering lag or something along those lines in some combination of JupyterLab and/or my browser (Chrome), so I tried in Firefox and double-clicking works reliably every time.

This lead me to this post in the [Jupyter](https://discourse.jupyter.org/t/cripplingly-slow-ui-am-i-the-only-one/5351) community forum, which gave me some ideas. It turns out that turning off some extensions (in particular Adblock Plus) makes  double clicking work much more reliably. I also found that enabling the Simple Interface (Ctrl + Shift + D) also improved the reliability.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
