### ISSUE TITLE
making movies of Plotly outputs?

### ISSUE THREAD

**Issue by Dragonmasterx87** [plotly/plotly.py#1821]
Hello Devs! I am not sure if this is the correct place to ask this question, so please let me know if it isnt.

I was wondering how to make a movie of a 3D output generated using plotly? I have implemented plotly to generate 3D UMAP graphics of single cell RNA sequencing data. It would be nice to be able to make a video to place in a powerpoint presentation.

You can find my code [here](https://github.com/Dragonmasterx87/Interactive-3D-Plotting-in-Seurat-3.0.0)

Thank you very much for the help!

**Comment by emmanuelle** [comment]
What would the different frames of your video represent? The rotation of a 3D object? You could be interested in the tutorial on camera controls https://plot.ly/python/3d-camera-controls/ since you could set the position of the camera in a for loop, and save a png image for every frame. Another (less pythonic and reproducible!) solution is to use a screen capture program to generate a video by capturing your screen while you are interacting with the figure.

**Comment by sorenwacker** [comment]
It would be useful if the rotation could be linked to an animation frame and to have a quick way to export it to a video. 
To make quick and dirty videos for presentations I use the capture tool on Windows `Win+G`.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
