### ISSUE TITLE
Unable to plot python ggplot geom_area()

### ISSUE THREAD

**Issue by kforeman** [plotly/plotly.py#187]
I'm unable to create an area plot that uses ggplot's `geom_area()`. Here's an example to produce the ggplot figure:

``` python
%matplotlib inline
from ggplot import *
import plotly.plotly as py
import pandas as pd
import numpy as np

# py.sign_in('','')

data = pd.DataFrame({'x': np.arange(1,11), 'y': np.arange(1,11), 'ymin': np.arange(1,11)*.9, 'ymax': np.arange(1,11)*1.1})

p = ggplot(aes(x='x', y='y', ymin='ymin', ymax='ymax'), data=data) +\
    geom_area(aes(alpha=0.5)) +\
    geom_line()

p.draw()
```

![image](https://cloud.githubusercontent.com/assets/275114/6072991/2ce21720-ad5d-11e4-875b-8e2ad5d44421.png)

And then if I draw to draw in plotly:

``` python
py.iplot_mpl(p.draw())
```

![image](https://cloud.githubusercontent.com/assets/275114/6073003/5a992d2a-ad5d-11e4-8c41-9e12265977ae.png)

Any suggestions?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
