### ISSUE TITLE
Bold/Italics/other formatting as layout option

### ISSUE THREAD

**Issue by schlich** [plotly/plotly.py#1883]
Hi folks,

I'm hoping to make all of the fonts in my plot axes and such bolded.  I saw on a stack overflow thread that I can use an html tag but that's insufficient since i would like to be able to use it in a template and such

**Comment by gvwilson** [comment]
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson
