### ISSUE TITLE
Edit (workspace) url cannot be pasted into get_figure.

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#189]
This works: `https://plot.ly/~user/66`
This doesn't work: `https://plot.ly/66/~user`

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
