### ISSUE TITLE
Access _fullLayout, _fullData and JS errors from Python

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1967]
Just to record my pie-in-the-sky idea: if [Orca](https://github.com/plotly/orca) had a mode where  instead of returning an image, it returned a JSON object that contained `_fullLayout`, `_fullData` and some warning objects, then we could make it much easier for users to understand the defaulting logic and various other-wise opaque error messages. From Python this could be accessed via a new renderer as `fig.show("full_json")` or something?

**Comment by nicolaskruchten** [comment]
@antoinerg heads-up!

**Comment by nicolaskruchten** [comment]
The JSON bit is going to be pretty awesome, based on Kaleido... basically something as simple as:

```python
import plotly.io as pio
import json
import plotly.graph_objects as go

def coerce(fig):
    return go.Figure(json.loads(pio.kaleido.scope.transform(fig, format="json")), skip_invalid=True)
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
