### ISSUE TITLE
get fid from filename

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#200]
With our new API endpoints (https://api.plot.ly/v2/), we'll need an easy way to either get the file-id from the filename, or allow the filename and the file-id to be interchangable in the functions that we expose.

**Comment by BRONSOLO** [comment]
:+1: related: https://github.com/plotly/streambed/issues/1558

**Comment by theengineear** [comment]
Hey! Recently closed that issue ^^ so we can do this!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
