### ISSUE TITLE
Custom Task ordering for Gantt Charts with grouped tasks?

### ISSUE THREAD

**Issue by zacharyneveu** [plotly/plotly.py#2081]
The current behaviour of Gantt charts is to start with the earliest task at the top of the page and work downwards. I am looking for a method to pass either an ordered list of tasks or a function to sort tasks to determine their vertical ordering. Is anything like this in the works or are there any ways to hack this?

Current behavior: ![newplot](https://user-images.githubusercontent.com/23347363/72484601-c0787100-37d2-11ea-87c4-ec80ddea7f4c.png)
Desired behavior: categories on Y axis are sorted numerically or via custom ordering

**Comment by nicolaskruchten** [comment]
As of the recent version 4.9 release we recommend using `px.timeline()` as a replacement for `ff.create_gantt()`, and it allows better control over ordering: https://plotly.com/python/gantt/

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
