### ISSUE TITLE
Graphs auto shrunk with Voila

### ISSUE THREAD

**Issue by b060149ee** [plotly/plotly.py#2083]
Hi,

We use plotly, jupyter lab and voila for our work. Recently we have started facing an issue with plotly graphs in our notebook files shrinking completely. This behaviour is experienced with standalone voila execution of notebooks and also when a voila button is clicked in Jupyter Lab.

The current plotly version that we use is 4.4.1 and voila is at 0.1.20.

Please note that this behavior is not consistent. Sometimes both the graphs shrink, sometimes just one graph shrinks, other times both do not shrink. Also, most importantly, as soon as I resize the window that has these graphs, the graphs come back and autofit properly.

See the 'svg-container' div element's width and height attributes in the below image - one graph's width and heights are in px values, whereas the other graph's in %. 

![image](https://user-images.githubusercontent.com/55535963/72516887-6df19000-3878-11ea-87a5-00712d1f6197.png)

By shrink, I mean this: 

![image](https://user-images.githubusercontent.com/55535963/72517387-549d1380-3879-11ea-8d7b-e56fccfaa2c3.png)

Any kind of help is appreciated. I'm unable to give a reproducible notebook, so I apologize in advance. My only hope is that ppl who are aware of plotly's svg-container div elements would understand the issue right away with the way the width elements are sometimes pixels and %s.

Thanks,

**Comment by jg1141** [comment]
Seeing identical issue with plotly==4.2.1, voila==0.1.18

**Comment by emmanuelle** [comment]
Hi @b060149ee and @jg1141 thanks for the report. It would really help if you could share a standalone notebook reproducing the issue, because I made a quick test with a plotly figure in a notebook and the voila rendered app looked good, so it's hard to investigate. Thanks!

**Comment by jg1141** [comment]
@emmanuelle In [this notebook](https://gist.github.com/jg1141/6149384615321b2020b14e9628f86ff9), I reproduced your success with a SINGLE plot, then kept adding plots until the issue came up (after 4th plot) as shown in screenshot
<img width="1225" alt="Screen Shot 2020-01-22 at 1 19 57 PM" src="https://user-images.githubusercontent.com/239906/72854741-2062a080-3d1a-11ea-8adc-fa5f2ede0b2c.png">


.

**Comment by jg1141** [comment]
Note that in re-testing this example just now, if I render the plots in JupyterLab FIRST, then Voilà works perfectly, but if I reset the kernel and JUST run the notebook in Voilà, the first and second plots are shrunk as shown.

**Comment by deangoodmanson** [comment]
Noticed this today myself.  Has anyone identified a workaround?

**Comment by Okroshiashvili** [comment]
I also encountered this issue today while tried Voila first time. Some plots were rendering by Voila but some not. I tried almost everything to solve this problem but nothing worked. After that, I noticed that indicating ```width``` and ```height``` parameters in figure layout solved the issue.

In this example, I introduced  ```width=900, height=700``` parameters and works perfectly.

```labels = sorted(df['social-network'].unique())

values = df['social-network'].value_counts().sort_index().tolist()

fig = go.Figure(data=[go.Pie(labels=labels,
                             values=values,
                             text=labels,
                             textposition='auto',
                             hoverinfo='label+percent')])

fig.update_layout(title_text='Social Network Distribution',width=900, height=700)

fig.show(renderer='notebook')```

**Comment by jitendra123609** [comment]
Thank u so much dear. Okroshiashvili. 
It perfectly worked. 
God bless u. 
Om Shanti.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
