### ISSUE TITLE
Animation glitch with missing data

### ISSUE THREAD

**Issue by JulianWgs** [plotly/plotly.py#2126]
When having missing at the start time. Scatter markers are not being draw. When another marker has no values after a certain point in time this point "converts" to the no drawn point.

Im using plotly 4.5.0 in Python 3.7 with Anaconda.

Here is an example:
``` python
df = pd.DataFrame([
    {"time": 0, "id": "A", "x": 0, "y": 0}, # No data for B at timestep 0
    {"time": 1, "id": "A", "x": 0, "y": 1},
    {"time": 1, "id": "B", "x": 1, "y": 0},
    {"time": 2, "id": "A", "x": 0, "y": 2},
    {"time": 2, "id": "B", "x": 1, "y": 1},
    {"time": 3, "id": "B", "x": 1, "y": 2}, # No data for A at timestep 3
])

fig = px.scatter(
    data_frame=df,
    x="x", y="y",
    color="id",
    animation_frame="time",
    hover_data=df.columns,
    range_x=(-1, 3),
    range_y=(-1, 3),
)
fig.show()
```
![grafik](https://user-images.githubusercontent.com/31596773/73073691-2abaa100-3eb8-11ea-8d08-751af722b650.png)

Unfortunately I can't upload an animation of the "conversion".

Thanks in advance!

**Comment by JulianWgs** [comment]
Could anyone replicate the bug with the minimum working example?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by JulianWgs** [comment]
I just reproduced the bug on 5.22.0. Please reopen the issue. Thank you!

**Comment by gvwilson** [comment]
Thanks @JulianWgs - I've assigned it to myself, and I'll see if we can get it into our backlog.
