### ISSUE TITLE
Plotly Fails to plot on EMR Notebook

### ISSUE THREAD

**Issue by ndolev** [plotly/plotly.py#2137]
Hi,

I have an AWS EMR Notebook attached to an EMR cluster running PySpark. If I try the following:

```{Python}
import plotly.graph_objects as go
H = [10,20,30,40,50,60]
bins= [1,2,3,4,5,6]
fig = go.Figure()
fig.add_trace(
    go.Scattergl(
        x = bins[:-1],
        y = H,
        mode = 'markers',
        marker = dict(
            line = dict(
                width = 1,
                color = 'DarkSlateGrey'))))
fig.show()
```

I receive the following error:
```{Python}
llegal character ((CTRL-CHAR, code 27)): only regular white space (\r, \n, \t) is allowed between tokens at [Source: Getting http://127.0.0.1:35375/; line: 1, column: 2]
```
The plotly version is 4.5.0.

Any idea what the problem is? 

Best.
Noah

**Comment by NaveenSrikanth** [comment]
I am also facing this issue . Is there any solution

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
