### ISSUE TITLE
Allow px parcoords to accept categorical data

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2143]
With the tickvals/ticktext trick

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
