### ISSUE TITLE
Changing blending mode of the drawing paper 

### ISSUE THREAD

**Issue by harisbal** [plotly/plotly.py#2175]
Hello,

I was wondering whether is it possible to change the color blending-mode of traces so that overlapping data points are "cancelled out".
For instance, in this [plot](https://chart-studio.plot.ly/~harisbal/184/#/) I would like to mix blue and yellow points so that they cancel each other out by producing white. I've tried lowering opacity but it didn't help.

Can you suggest anything ?

Kind Regards

**Comment by emmanuelle** [comment]
Hi @harisbal I don't think this is possible unfortunately. Markers are considered as "light-absorbing" objects, corresponding to a subtractive color model (https://en.wikipedia.org/wiki/Subtractive_color). They are not "light sources" which would correspond to additive colors (https://en.wikipedia.org/wiki/Additive_color). So far this is the only mode available. Since this behaviour is directly inherited from the `plotly.js` library, please open an issue on https://github.com/plotly/plotly.js if you want to discuss about adding such a feature.

**Comment by harisbal** [comment]
Thank you for the reply @emmanuelle !
I hoped that this was somehow available in plotly.js and it was just a matter of exposing for python.
Cheers!
