### ISSUE TITLE
CSS Named Colors for the Docs

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2192]
Here is a list of colors matching nicely together, to be used for the tutorials.

MidnightBlue / LightSkyBlue
Aquamarine / LightSeaGreen
Orange / Gold
DarkBlue / LightPink
DarkBlue / RoyalBlue / Cyan
LightSalmon / PaleTurqoise / LightCyan
Gold / MediumTurqoise / LightGreen 
MediumSlateBlue / Lavender / DarkOrange
IndianRed / LightSalmon
RebeccaPurple / MediumPurple
LightSlateGray / LightSteelBlue
Crimson / PaleTurqoise

![image](https://user-images.githubusercontent.com/263366/74480146-6674d500-4e7e-11ea-8c2e-64056ca35be6.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
