### ISSUE TITLE
More flexible config / credentials

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#225]
We should revamp (not necessarily in a backwards compatible way) how we do the `.config` and `.credentials`. Since we can migrate old/new credentials/confic files, backwards compatibility isn't 100% important. However, to keep us in sync with the other libraries, we should try.

It'd be cool if we could support the following:
- default plot_options, i believe we have the machinery to do this, but we just don't.
- multiple profiles, might be cool, in a major way for devs, actually.

**Comment by chriddyp** [comment]
+1. setting a default `world_readable` setting is going to a new step in configuring the library

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
