### ISSUE TITLE
better matplotlylib support

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#226]
This really hinges on getting serialization into matplotlib. However, even after that serialization happens, we'll need to do a significant amount of dev in matplotlylib to get everything in line.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
