### ISSUE TITLE
Problems with getting-started documentation

### ISSUE THREAD

**Issue by shirriff** [plotly/plotly.py#2283]
The [documentation](https://plot.ly/python/getting-started/) has the example:
```
import plotly.graph_objects as go
fig = go.FigureWidget(data=go.Bar(y=[2, 3, 1]))
fig
```

This fails with:
```>>> fig = go.FigureWidget(data=go.Bar(y=[2, 3, 1]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'plotly.graph_objects' has no attribute 'FigureWidget'
```

Also, shouldn't `fig` be `fig.show()` like the other examples?

**Comment by nicolaskruchten** [comment]
The example as written works for me locally... It is indeed intended to be `fig` rather than `fig.show()` because the `FigureWidget`s work differently from `Figure`s.

I'm rather puzzled by the error message you're seeing. It seems like you might have multiple versions of `plotly` installed, one 3.x and one 4.x...  I would recommend following the instructions here https://plot.ly/python/troubleshooting/#import-problems to remove all versions and then try reinstalling.

**Comment by shirriff** [comment]
I did a fresh install with "pip install plotly". But I've been having problems with my Python installation, so it's quite possible that the problem is on my side.  I'll close this bug since the documentation seems to be correct.
