### ISSUE TITLE
API v2 spec

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#229]
now that so many resources have endpoints, we should probably outline some type of spec for how we want to abstract out all of the API endpoints in the python client:
- exposing private url
  
  ```
  py.plot(fig, filename='priv', world_readable=False, secret_link=True)
  ```
- moving, renaming files and folders
  
  ```
  py.files.move(old_path, new_path)
  py.files.rename(old_path, new_path)
  ```
- listing files
  
  ```
  files = py.files.list(path='') 
  # what gets returned? json objects or `plotly.file_objs` that you can take action on?
  files[0].rename('new_name') # ?
  files[0].download() # ?
  ```
- revisiting `plotly.grid_objs` and `py.grid`
- etc

**Comment by theengineear** [comment]
Interesting point about file objects. I'm not exactly sure. Maybe we can add some code to make figures *file objects* as well which is maybe a mixin that grids will also get?

**Comment by chriddyp** [comment]
@theengineear lol something tells me you've gone through this same train of thought on the backend...

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
