### ISSUE TITLE
No mapbox map shows on google colab notebook

### ISSUE THREAD

**Issue by leo-smi** [plotly/plotly.py#2326]
Fisrt of all I installed the latest version !pip install plotly==4.5.4
Second, for the following code I didn't used token api because from [this source](https://community.plotly.com/t/use-of-mapbox-token/28646) I can ommit the line

the screenshot is [here](https://pasteboard.co/J184whB.png)

`import plotly.express as px

df = px.data.carshare()
fig = px.scatter_mapbox(df, lat="centroid_lat", lon="centroid_lon",     color="peak_hour", size="car_hours",
                  color_continuous_scale=px.colors.cyclical.IceFire, size_max=15, zoom=10)
fig.show()`

**Comment by IuryBAS** [comment]
I think i am facing a similar issue. Suddenly, the maps using choropleth_mapbox from plotly.express are not rendering anymore, just the legend bar like in your image. However, if i just use choropleth, the plot is ok.

**Comment by leo-smi** [comment]
Solved: it's just de version, I have updated to 4.6 and worked fine

**Comment by IuryBAS** [comment]
> Solved: it's just de version, I have updated to 4.6 and worked fine

Yes, that seems to be solved now. But when I commented here i was already using version 4.6. I think that this was a bug more general. But as a said, now its seems solved.

**Comment by surajPowerWeave** [comment]
No, still I am getting blank page for above function

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
