### ISSUE TITLE
get_figure by url doesn't work with enterprise urls

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#235]

**Comment by Kully** [comment]
@charleyferrari

I opened an issue in streambed for this same thing, so I'll close it now and write the code that Charley wrote to demonstrate the issue in the most bare bones way:

```
import requests

credentials = py.get_credentials()
username, api_key,  = 'newton', 'xz4ujfectn'
headers = {'plotly-username': username,
           'plotly-apikey': api_key,
           'plotly-version': plotly.version.__version__,
           'plotly-platform': 'python'}

resource = "/apigetfile/{username}/{file_id}".format(username=username, file_id='118')

#resource = "/apigetfile/{username}/{file_id}".format(username='charleyferrari', file_id='894')

plotly_rest_url = 'https://buildly.plot.ly'

response = requests.get(plotly_rest_url + resource,
                        headers=headers,
                        verify=py.get_config()['plotly_ssl_verification'])
```

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
