### ISSUE TITLE
document the datasets

### ISSUE THREAD

**Issue by afeld** [plotly/plotly.py#2351]
Hello! I'm using plotly to teach [a Python class](https://github.com/afeld/python-public-policy), and was showing an example using `px.data.tips()`. A student asked where that data came from and what others they could access, and I didn't have a good answer. While examples use it, I'm not seeing any documentation of `px.data` itself on the Plotly site. [The module itself](https://github.com/plotly/plotly.py/blob/4ef310fb87d0b15992032fa21a315f630aca64de/packages/python/plotly/plotly/data/__init__.py) has docstrings for each, but that doesn't seem to be surfaced anywhere. Maybe should be part of [the datasets page](https://plotly.github.io/datasets/)?

Thanks!

**Comment by emmanuelle** [comment]
Thank you for the report @afeld , we should indeed make sure the docstrings appear on https://plotly.com/python-api-reference/plotly.express.html#px. In fact the page already exists https://plotly.com/python-api-reference/generated/plotly.data.html but we are not linking to it at the moment.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
