### ISSUE TITLE
sunburst/treemap: implement aggregation for continuous hover_data

### ISSUE THREAD

**Issue by pinglewang** [plotly/plotly.py#2353]
Following Sunburst example code: if we add "gdpPercap" into hover_data, the average 'gdpPercap' is missing for continent. Is there a way for Sunburst to show average 'gdpPercap' for each continent as well as for countries? 
```
import plotly.express as px 
import numpy as np 
df = px.data.gapminder().query("year == 2007") 
fig = px.sunburst(df, path=['continent', 'country'], values='pop', 
                  color='lifeExp', hover_data=['iso_alpha','gdpPercap'], 
                  color_continuous_scale='RdBu', 
                  color_continuous_midpoint=np.average(df['lifeExp'], weights=df['pop'])) 
fig.show()
```

**Comment by emmanuelle** [comment]
Hi @pinglewang indeed we don't use an aggregation function for `hover_data` columns with continuous values, only for discrete values (with the simple heuristic that a parent takes the same name as children if they all share the same name).

The reason why we haven't implemented this feature yet is that several aggregation functions are possible (should it be sum, mean, count etc.) and that it's hard to decide for the user. What we could do is to have a dictionary of aggregation functions which could take either predefined names such as `sum`, `mean` etc. or accept user-provided functions. I'll therefore label your issue as a feature request. Of course we love community contributions ;-).

**Comment by firmai** [comment]
This would be great to have, can't do much with sum in my analysis, need a mean aggregation.

**Comment by soerenetler** [comment]
This feature would also be very useful for me (also for treemaps). Has there been any progress on this issue?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
