### ISSUE TITLE
Location outlines from custom GeoJSON not properly displayed on px.Choropleth

### ISSUE THREAD

**Issue by RafaelUL** [plotly/plotly.py#2354]
I have a custom GeoJSON outlining the five geographical regions of Brazil. Here’s what it looks like on an online visualizer:

![chrome_ffrGgglPm1](https://user-images.githubusercontent.com/8020922/78396776-5350cc80-75c6-11ea-84c4-e663ae7c6327.png)

[Here's a link to the full GeoJSON.](https://pastebin.com/4PfFAv1Y)
And what my code looks like:

```
with open('regions.geojson') as f:
        geojson = json.load(f)

    data = {
        "region": ["sudeste", "sul", "nordeste", "centro-oeste", 'norte'],
        "abbreviation": ["SE", "S", "NE", "CO", "N"],
        "english_name": ["southeast", "south", "northeast", "center-west", "north"],
        "parity": ["odd", "even", "odd", "even", "odd"],
        "region_id": [1,2,3,4,5]
    }

    df = pd.DataFrame(
        data,
        columns = ["region", "abbreviation", "english_name", "parity", "region_id"]
    )

    figure = px.choropleth(
        df,
        geojson = geojson,
        color = "parity",
        locations = "region",
        featureidkey="properties.region",
        projection="mercator",
        hover_data=["abbreviation", "english_name"]
    )

    figure.update_geos(fitbounds="locations", visible=False)
    figure.update_layout(margin={"r":0,"t":0,"l":0,"b":0})

    figure.show()
```

I expected a trace similar to the one in the image above, however, I get these, when even and odd are selected, respectively:

![chrome_SMKJcUv7LE](https://user-images.githubusercontent.com/8020922/78397000-c5291600-75c6-11ea-9809-fa9c3b6e07ad.png)

![chrome_kpQLileWlD](https://user-images.githubusercontent.com/8020922/78397010-ca866080-75c6-11ea-9a53-afd238c6cf19.png)

**Comment by MishaVeldhoen** [comment]
This may be similar to an issue that I am experiencing, and it may have something to do with the ordering of the coordinates, e.g., the left- or right-handedness. Here, I've made a minimal example, that just puts a square on the map.

I use the following two helper functions:
```
def create_polygon_geojson(coords):
    return {
        'type': 'FeatureCollection',
        'features': [
            {
                'id': 1,
                'type': 'Feature',
                'properties': {},
                'geometry': {
                    'type': 'Polygon',
                    'coordinates': coords
                }   
            }
        ] 
    }

def plot_polygon(coords): 
    
    return px.choropleth(
        data_frame=pd.DataFrame({"id": [1], "value": [1]}),
        geojson=create_polygon_geojson(coords),
        color="value",
        locations="id",
        scope="europe",
    ).update_geos(fitbounds="locations", visible=True)
```

When I use left-handed coordinates `coords_left = [ [[6, 53], [7, 53], [7, 52], [6, 52], [6, 53] ] ]` the function `create_polygon_json(coords_left)` yields an invalid geojson according to http://geojsonlint.com/, since it is left-handed. Plotting it with plotly: `plot_polygon(coords_left)` works just fine.
![left_handed](https://user-images.githubusercontent.com/2463292/83663640-3ab26200-a5c9-11ea-9205-812fa7ce2e5c.png)

Doing the same, but with the reversed (right-handed) coordinates  `coords_right = [ [[6, 52], [7, 52], [7, 53], [6, 53], [6, 52] ] ]`, yields a valid geojson, but plotly will plot it "inside-out".
![right_handed](https://user-images.githubusercontent.com/2463292/83663661-430a9d00-a5c9-11ea-8ce9-edc395574272.png)

**Comment by MishaVeldhoen** [comment]
OK, it indeed seems to be an issue with the winding of the polygons. To change the winding of your polygons you can use https://github.com/chris48s/geojson-rewind, but make sure to use the inverse winding orientation by setting the `rfc7946` parameter to `False`.
```
geojson_rewind.rewind(some_geojson, rfc7946=False)
````

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
