### ISSUE TITLE
Update shapes examples to use annotations instead of mode='markers+text'

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#2356]
![image](https://user-images.githubusercontent.com/1280389/78410688-e9362880-75c1-11ea-99e4-5909fdc848c4.png)

It would be great if the examples showed how to position annotations right on top or right below the shapes using `xref: x`, `xanchor: middle`, `yanchor: bottom`. This way, the annotation text is positioned exactly one text-line-height above (or below) the line or rect.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
