### ISSUE TITLE
On_selection callback on sankey diagram

### ISSUE THREAD

**Issue by xanderwallace85** [plotly/plotly.py#2360]
Hi! In the attempt of fully personalizing the sankey plot (in python) I found that when selecting more than 1 node, then these are merged into a single node and the graph is updated. I am trying to override this behavior with sankey_figure.on_selection(new_function)  -where "new_function" is defined below- but it doesn't work.
Is there a way to disable the default selection event?
Thank you in advance!

```
def new_function(trace,points,selector):
    with fig.batch_update():
        fig.data[0].node.color[points.point_inds[0]] = 'red'  
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
