### ISSUE TITLE
Issue warning in Jupyterlab when extension version is not synced with plotly.py release

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2364]
Today I was debugging a very weird behaviour with users, with some plotly.py hover and labels features behaving strangely inside Jupyterlab. Turns out they had the last plotly.py release but a very old version of the extension. I don't know if this is possible but it would be great to issue a warning when import plotly or doing `fig.show` if we can detect that the extension is out of sync.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
