### ISSUE TITLE
Orca claims is cannot find psutil

### ISSUE THREAD

**Issue by warloc9000** [plotly/plotly.py#2365]
Hi,

I am having the exact same issue as this user on stackoverflow: https://stackoverflow.com/questions/58957131/plotly-io-doesnt-see-the-psutil-package-even-though-its-installed

I am fairly new to python, but the issue seems to stem from plotly.io.orca.ensure_server

If I change line 1360 of plotly/plotly/io/_orca.py such that it validates psutil in the same way you do it for requests (ie. from: "if psutil is None:" to: "if not get_module("psutil"):") then everything works swimmingly.

As I said, I am not great on python so I have no idea if I actually fixed it or if I just stopped it raising the error. However, my figures save now and that is good enough for me.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
