### ISSUE TITLE
The append variable of the callback function is not correctly implemented 

### ISSUE THREAD

**Issue by xanderwallace85** [plotly/plotly.py#2367]
Hi!

The help says "If False (the default), this callback **replaces** any previously defined on_click callbacks for this trace.". However, I have been trying to override the sunburst on_click function but the default animation (zoom in)  is still present (together with the customized one). Am I right?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
