### ISSUE TITLE
display issue in Azure (empty plot)

### ISSUE THREAD

**Issue by vladconq** [plotly/plotly.py#2380]
I adore plotly and want to use it everywhere. In DASH applications, locally in JupyterLab, and in Azure Jupyter - it works perfectly! But in Azure JupyterLab graphics are not displayed. I know about the extension for Jupyterlab, it is installed.

So how to show graphs? Please help!

I really did not find a solution to the problem anywhere.

![image](https://user-images.githubusercontent.com/41647156/79223454-0a203880-7e62-11ea-8f72-3dd6b429215f.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
