### ISSUE TITLE
Hide px express choropleth legend?

### ISSUE THREAD

**Issue by jiecai1997** [plotly/plotly.py#2384]
Is there any way to hide the choropleth legend for Dash? I tried the following and it didn't work:

fig = px.express(...)
fig.update_layout(showlegend=False)

**Comment by emmanuelle** [comment]
Hi @jiecai1997 what you did should work, for example here is a full example
```
import plotly.express as px

df = px.data.election()
geojson = px.data.election_geojson()

fig = px.choropleth(df, geojson=geojson, color="winner",
                    locations="district", featureidkey="properties.district",
                    projection="mercator", hover_data=["Bergeron", "Coderre", "Joly"]
                   )
fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0}, showlegend=False)
fig.show()
```
Or did you want to mention the colorbar maybe? For hiding the colorbar you can do
```
import plotly.express as px

df = px.data.gapminder().query("year==2007")
fig = px.choropleth(df, locations="iso_alpha",
                    color="lifeExp", # lifeExp is a column of gapminder
                    hover_name="country", # column to add to hover information
                    color_continuous_scale=px.colors.sequential.Plasma)
fig.update_coloraxes(showscale=False)
fig.show()
```
It is useful to do `print(fig)` to know what is inside the figure so that you can modify its different attributes with `fig.update_traces` or `fig.update_layout`. Finally, please note that support requests (as opposed to feature requests or bug reports) should be asked preferably on the community forum https://community.plotly.com/ if you have other questions another time (for the choropleth legend we can follow-up here of course).

**Comment by jiecai1997** [comment]
@emmanuelle perfect thank you! I'll close this issue.
