### ISSUE TITLE
Bug on y axis when plotting time format

### ISSUE THREAD

**Issue by rbdm-qnt** [plotly/plotly.py#2393]
![Screen Shot 2020-04-18 at 00 29 58](https://user-images.githubusercontent.com/61274891/79619000-e7b14800-810b-11ea-83ff-5c129e1f5aaa.png)

I have a timeseries in a Dataframe, and one of the things I keep track of is the time that passes between one datapoint and the other in my database. I wanted to plot this time duration of every measurement as a Scatter in a subplot, but as you can see it's like Plotly doens't understand that they are numbers and just reorganizes them to make the line straight. I have plotted other parameters (int and float, not exactly identical format as the time duration) without any issue. This is the code I'm using:

fig = plotly.subplots.make_subplots(rows=3, shared_xaxes=True, shared_yaxes=False, print_grid=True)
fig.add_trace(go.Scatter(x=df.index, y=df['time_duration'], name='Time Duration'), 3,1)

I'm on Python 3.7, Mac OS 10.12.6, on Pycharm, latest version of all libraries.

**Comment by nicolaskruchten** [comment]
Unfortunately Plotly doesn’t have an axis type for time deltas ... they’re not quite dated so our date axis doesn’t work for them. In effect you’re using a categorical axis here. You have two options: turn your deltas into full dates or turn them into numbers.

**Comment by rbdm-qnt** [comment]
> Unfortunately Plotly doesn’t have an axis type for time deltas ... they’re not quite dated so our date axis doesn’t work for them. In effect you’re using a categorical axis here. You have two options: turn your deltas into full dates or turn them into numbers.

I understand... I'll try to turn them into numbers, hope epoch can do the trick

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
