### ISSUE TITLE
'Edit in Chart Studio' button not directing to plotly.com

### ISSUE THREAD

**Issue by dennislabvisualizations** [plotly/plotly.py#2398]
Ever since plotly has moved to plotly.com, the option to edit exported plots in chart studio no longer works, since the 'edit in chart studio' button is directing to the wrong URL. The updated code does not fix this issue.

**Comment by nicolaskruchten** [comment]
Yes, you'll need to set the configuration option `"plotlyServerURL": "https://chart-studio.plotly.com" as well as `"showLink": True`.

**Comment by VMois** [comment]
Where `plotlyServerURL` should be specified in Python?

**Comment by VMois** [comment]
Got it. `plotlyServerURL` and `showLink` are part of the config of `Graph`. 

I was thinking that `plotlyServerURL` should be somehow placed in the global config.
Thanks.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
