### ISSUE TITLE
Hover over filled area: incorrect text

### ISSUE THREAD

**Issue by gv-collibris** [plotly/plotly.py#2399]
I'm trying to build a stacked area chart, starting from the example provided [here](https://plotly.com/python/filled-area-plots/#select-hover-points).

However, the hover text does not always match the hovered area. In the following screen shot, I'm actually over the blue area, close to `y = 0`. 
![image](https://user-images.githubusercontent.com/64086670/79877166-300e8580-83ec-11ea-9ca9-db9d000913c0.png)

I'm using the following code to plot online (the aim is to use this in a Dash application).
```
import plotly.graph_objects as go

fig = go.Figure()
for i, y in enumerate([0, 1]):
    values=[i, 1 + i, 2 + i, 1 + i, i]
    fig.add_trace(go.Scatter(x=[0, 1, 2, 3, 4], y=values,
                             stackgroup="one",
                             hoveron = 'points+fills', # select where hover is active
                             name=f"Trace {y}",
                             text=[f"<span>Value: {v}</span>" for v in values],
                             hoverinfo = 'text+x'))
fig.update_layout(
    title = "hover on <i>points</i> or <i>fill</i>",
)
```

Also, with the same setting, the label is wrong : with`hoverinfo='text+x'`, the text in the hover is the name of the trace. Note that the hovers on the markers are correct.

**Comment by meakbiyik** [comment]
I second to this. Hover markers simply do not show the correct label, especially when there are many stacked zero areas on top of each other.

**Comment by nicolaskruchten** [comment]
Today, hovering on areas gives very limited information: just the trace name. This isn't a bug so much as an incompletely-implemented feature :)

**Comment by meakbiyik** [comment]
![Sample-72-Subtype-3-Jupyter-Note](https://user-images.githubusercontent.com/23424198/81078502-9d431000-8eee-11ea-8eb7-d13799de9184.gif)

@nicolaskruchten if this behavior is not a bug, I do not know what is. The hover info is far from stable, and it usually misses the line or area that I want. First I thought it was related to [this](https://github.com/plotly/plotly.js/issues/2165), but the error persists even without `fills` parameter.

**Comment by nicolaskruchten** [comment]
Ah, I see. I was referring to the contents of the hover-label, and confirming that indeed when hovering on fills, you only get to see the trace name and this is by design today.

If you're seeing issues where the wrong hover-label is showing up, this is probably something that we need to bring up in the Plotly.js repo. I'll try to pull together a minimal JS-only CodePen.

**Comment by thibaultdaoulas** [comment]
I am having the same issue, has there been any update on this?

**Comment by warren-oneill** [comment]
a workaround could be to use `fig.update_layout(hovermode='x unified')`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
