### ISSUE TITLE
mobile usability for choropleth map

### ISSUE THREAD

**Issue by artdgn** [plotly/plotly.py#2408]
First, thanks for the great package! I've tried searching, but didn't find anything related in issues or general search.

I'm quite new to the package, and have been playing around with Choropleth maps (this one in particular: https://artdgn.github.io/pages/covid-world-maps/ ).

And while it's great on desktop, I can't figure out or find how to make it behave in a usable way on mobile (at least on mine, firefox / android):
1) Dragging or zooming happens to both map and page at the same time.
2) Changes in map happen with a very large delay (so are confusing / disorienting). 
3) The drop down buttons initially work (without zooming), but than if zooming / panning is triggered they seem to stop responding and require a reload of the page.

Am I using something wrong, or perhaps missing some settings?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
