### ISSUE TITLE
plotly creates huge git diff

### ISSUE THREAD

**Issue by lytex** [plotly/plotly.py#2411]
First submitted to [nbdime](https://github.com/jupyter/nbdime/issues/520)
Using [nbdime](https://github.com/jupyter/nbdime) and plotly results in huge commit diffs because all the plotly javascript code is considered in each commit. However if we embed the plotly figures into the notebook (as matplotlib does) nbdime tracks only the python code that is changing.
I've created an [example github repository](https://github.com/lytex/plotly_nbdime_test) to show the issue.

Maybe a solution would be writing a suitable ipython magic`%plotly inline` similar to matplotlib's, to have the plotly figures rendered as images embedded in the notebook.

**Comment by emmanuelle** [comment]
Hi @lytex, the size of the diffs would decrease a lot if you set explicitly a renderer which will not include the plotlyjs with each figure, but download the library from the CDN instead. For example
```
import plotly.io as pio
pio.renderers.default = 'notebook_connected'
```
Please see the [tutorial on renderers](https://plotly.com/python/renderers/) for more info about renderers.

**Comment by lytex** [comment]
Also it seems that another possible solution would be to write a custom IPython magic / function to display the figure embedded in the notebook the same way matplotlib does:

```
from IPython.core.magic import register_line_magic
from IPython.display import Image

@register_line_magic
def plotly_inline(plotly_figure):
    display(Image(eval(plotly_figure).to_image()))

import plotly.express as px
fig = px.line([1, 2, 3], [1, 2, 1])
%plotly_inline fig
# Displays figure as an image
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
