### ISSUE TITLE
Make animation example more Python-idiomatic

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2428]
https://plotly.com/python/animations/#using-a-slider-and-buttons is an example which hasn't really been restyled to use the object-oriented syntax of plotly.py 4+, it uses a lot of dicts and is very verbose.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
