### ISSUE TITLE
 how to add text to Choropleth Maps?

### ISSUE THREAD

**Issue by heishanmao** [plotly/plotly.py#2429]
Hi, i'd like to add state name to Choropleth Maps for each state. but didn't in this project. So Could I add text to the map?

**Comment by RamiSketcher** [comment]
+1

**Comment by RacerChen** [comment]
Same here, wish to have this feature!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
