### ISSUE TITLE
Specify line color with integers

### ISSUE THREAD

**Issue by niowniow** [plotly/plotly.py#2434]
One can specify a color by integer value for markers but not for lines. I'm basically repeating what is mentioned in [this post](https://stackoverflow.com/questions/58955557/python-plotly-scatter-specify-line-color-with-integer-value) on stackoverflow (not my post though).
I think it is either a bug or a feature that should be implemented. Is there a reason for this behaviour?

This works fine:

```
go.Scatter(x=x,
           y=y,
           mode='markers',
           marker=dict(color=i))
```

This does not work:

```
go.Scatter(x=x,
           y=y,
           mode='lines',
           line=dict(color=i))
```

I'm reproducing this issue with
`plotly                    4.6.0              pyh9f0ad1d_0    conda-forge`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
