### ISSUE TITLE
Plotly express histogram size HTML

### ISSUE THREAD

**Issue by gianlucaperna** [plotly/plotly.py#2435]
Good morning,

I am trying to make graphs using px.express, but, with large data sets, when I save the figure on an offline HTML file, they weigh more than 100MB.
Opening the HTML file, I saw that all the values ​​are written inside to calculate the histogram.
Is there a way to calculate the figure "first" and save only that?
I don't need to change the bins in the HTML file, just zoom in.

Thank you

**Comment by wdecoster** [comment]
I'm looking into this as well, and I found a related question at https://github.com/plotly/plotly.py/issues/1226

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
