### ISSUE TITLE
How can I directly save the vector image in the website?

### ISSUE THREAD

**Issue by antecede** [plotly/plotly.py#2440]
The image can be downloaded as png, but we usually use a vector image in paper.I understand that we can use `plotly.io.to_image` to produce pdf, but I am using visdom based on plotly to supervise the training process,so it only return 'download as png'.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
