### ISSUE TITLE
Py2 unicode strings in px

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.py#2446]
When we use strings in `px` to refer to columns, can we accept unicode strings as well? An important place this comes up is if those strings come from a Dash callback - `json.loads` will always give you unicode strings, but ATM to use in `px` you need to explicitly convert with `str()`

Originally reported in https://github.com/plotly/dash-core-components/issues/783

In the Dash back end we have a special type collection that includes [both string and unicode but not bytestring in Py3](https://github.com/plotly/dash/blob/439e13b673e8e8f3d4223e905d44c08c9f11eef2/dash/_utils.py#L18-L20):

```py
# py2/3 json.dumps-compatible strings - these are equivalent in py3, not in py2
# note because we import unicode_literals u"" and "" are both unicode
_strings = (type(""), type(utils.bytes_to_native_str(b"")))
```

which you can then use like `isinstance(argument, _strings)` in places like:

https://github.com/plotly/plotly.py/blob/ecb635a171ba494f64713804979804aa9c1c0ea0/packages/python/plotly/plotly/express/_core.py#L1006

Not that I want to spend a *whole* lot of time on Py2 at this point but this seems like a pretty easy one and would allow us to simplify our docs examples, reverting stuff like https://github.com/plotly/dash-docs/pull/813/commits/c13e5b282f1c1eb9ff3bab0aef4a6d28f12dbe18

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
