### ISSUE TITLE
PX color by datetime

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2450]
At the moment we don't support coloring by datetime, but we should try to do something more graceful.

**Comment by harahu** [comment]
It would be amazing if you could get this done. I love Plotly for its interactivity, but as an engineer working mainly with time series data, this is one of my big pain points with your tool chain.

It has gotten to the point where we have written complex custom wrappers for a selection of `px` functions, in order to handle coloring by Datetime, as well as gracefully dealing with Timedelta data types (see: #799, #801 and #3368).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
