### ISSUE TITLE
Documentation on plot.ly and plotly.com is not accessible from Crimea because of sanctions

### ISSUE THREAD

**Issue by 6jlarogap** [plotly/plotly.py#2459]
Hi dears, it seems you are following US sanctions regime - so your documentation and even contacts form are not accessible by all people in the world. Is it your choise or a mistake?

https://plot.ly/products/consulting-and-oem/
https://plot.ly/python
 
![image](https://user-images.githubusercontent.com/62824780/81641786-80489880-942a-11ea-8c97-43ffc031f366.png)

**Comment by nicolaskruchten** [comment]
I'm sorry you're unable to access our plotly.com website... It's hosted on US-based Google infrastructure and hence subject to all of Google's interpretations of its obligations to various international events. 

We don't have an alternative hosting option, unfortunately, but all of our documentation is in this repo and can be downloaded and inspected: https://github.com/plotly/plotly.py/tree/master/doc

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
