### ISSUE TITLE
textpositions only have nine ,but sometimes the text maybe shield the curve, so if I can add some offsets, some pixels, I can avoid the text obscuring curve.

### ISSUE THREAD

**Issue by antecede** [plotly/plotly.py#2460]
plotly version ==4.7
![结果](https://user-images.githubusercontent.com/46232487/81644287-06300800-945a-11ea-95e2-2860c179915d.png)
textposition='bottom right'
textpositions only have nine ,but sometimes the text maybe shield the curve, so if I can add some offsets, some pixels, I can avoid the text obscuring curve.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
