### ISSUE TITLE
Feature Request: a dist that combines gl2d and cartesian

### ISSUE THREAD

**Issue by rhamner** [plotly/plotly.py#2465]
This might be a niche request, but it feels likely to me that people using the plotly-cartesian plots would also use the gl versions of them (scattergl, contourgl, and heatmapgl) sometimes. I'd like to be able to get those + bar, box, etc. but not 3d plots, map plots, etc. For my current app, plotly is by far the largest part of the build and this would theoretically reduce it significantly.

Also...I might be dumb and missing an easy way to merge these on my own so I would welcome that if it exists.

**Comment by nicolaskruchten** [comment]
When you say “app” here are you referring to a Dash app or some other kind of app? If it’s Dash, you should be able to drop your own Plotly.js bundle into the assets directory and that one gets used instead of the built-in one, and we already distribute various partial bundles of Plotly.js so one there might meet your needs...

**Comment by rhamner** [comment]
I'm building my own Vue app and using plotly in it. I'm using the plotly.js-dist from npm instead of something like plotly.js-cartesian-dist because I need the gl versions of the plots that have them. I'm basically asking if it's possible to have a partial bundle that is the cartesian one but also includes the gl version of the ones in there that have it.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
