### ISSUE TITLE
Site cannot be reached when plot simple graphs

### ISSUE THREAD

**Issue by whtitefall** [plotly/plotly.py#2466]
I'm trying to use plotly to plot a simple graph

My code is shown as follow 
    
    import plotly.express as px

    x = [1,2,3]
    y = [1,2,3]
    fig = px.line(x=x, y=y,labels={'x':x_name,'y':y_name})
    fig.show()

when I run this code, sometimes the browser is showing ``` This site can’t be reached ``` 

I've searched on this question [1](https://community.plotly.com/t/this-site-cant-be-reached-error-when-clicking-zoom-in-r/29697) [2](https://community.plotly.com/t/can-t-reach-my-first-dash/20994) [3](https://community.plotly.com/t/first-figure-never-loads-show-getting-this-site-can-t-be-reached-browser-error/35363) , but did not got any answer.

How should I solve this problem when the browser shows ``` This site can’t be reached ``` ? 
(I'm using visual studio code)

**Comment by kurt-rhee** [comment]
I have the same issue in Pycharm

`test = pd.DataFrame({'a': [1,2,3,4,5]})
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=test.index,
    y=test['a'],
    name='test',
    mode='markers'
    ))`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
