### ISSUE TITLE
Double-clicking on legend should only filter associated subplot

### ISSUE THREAD

**Issue by jqnatividad** [plotly/plotly.py#2471]
In a graph with several subplots, double-clicking on a legend filters all the subplots, not just the subplot where the trace is.

See this page with several subplots...

https://data.beta.nyc/pages/nj-covid19-county-level-breakdown

It'd be preferable if only the associated subplot is filtered.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
