### ISSUE TITLE
Treemap's infotext does not apply to parents

### ISSUE THREAD

**Issue by RoryWatts** [plotly/plotly.py#2482]
When generating a treemap figure, specifying

`textinfo = "label+value+percent parent+percent entry"`

or variants of this do not apply to parents. Is this a bug, or is there something i'm missing?

[imgur link to an example output without parent infotext](https://imgur.com/9Sthv6X)

**Comment by Lawiss** [comment]
Hello,
I have the same issue for the texttemplate. The template is applied only on the innermost tiles, the parents only display labels.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
