### ISSUE TITLE
change format of number in hover Text 

### ISSUE THREAD

**Issue by Jacques2101** [plotly/plotly.py#2498]
Hi, my question Is simple but I cannot find an answer. 
I run :

```
import plotly.express as px
df = px.data.tips()
fig = px.box(df, x="time", y="total_bill")
fig.update_layout(
    hoverlabel=dict(
        bgcolor="white", 
        font_size=12, 
    )
)
fig.show()
```

It works fine but when I put my cursor on the graph, I would like to change the format (ie 1 decimal) on the numbers. 

How can I do ? 
Thanks 
<img width="825" alt="Capture d’écran 2020-05-25 à 20 30 07" src="https://user-images.githubusercontent.com/49912455/82836564-005d0c80-9ec7-11ea-9406-c6a80f9b6d2a.png">

**Comment by builder173** [comment]
Also would like to be able to easily customize which of these calculated data points show up. To show only q1, median, q3 for example,  I think we'd have to duplicate the calculations done by the px.box() to create custom_data and then create a new hover template with the customdata[] elements.

**Comment by Coding-with-Adam** [comment]
I don't think it's currently possible to customize the hover template of a box plot.  
@archmoj Can you please correct me if I'm wrong.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by operdeck** [comment]
@gvwilson This still is an issue. I'd like to have more control over the hovers of the box parts of a box plot. It currently is only possible for the points. I'm on 6.2.0. Can you consider to re-open?

**Comment by operdeck** [comment]
Ah, I see https://github.com/plotly/plotly.py/issues/3334 is a duplicate of this. +1 on that one :)

**Comment by leavor** [comment]
6.5.0 ,  the hoverinfo still cannot be customized
