### ISSUE TITLE
plotly.__version__ reports 4.6.0 for version 4.8.0

### ISSUE THREAD

**Issue by zrosgit** [plotly/plotly.py#2503]
I have installed version 4.8.0 using `sudo pip3 install plotly --upgrade` 

From within Python, I import plotly and check the version number as follows:
`import plotly`
`plotly.__version__`

and it returns '4.6.0'

Perhaps I don't understand, but I believe it should be reporting 4.8.0.

**Comment by nicolaskruchten** [comment]
It should definitely report 4.8.0, and indeed it does on my machine... Are you certain the Python process was launched from the same environment where you installed `plotly` and did you restart your Python process since upgrading? 

If yes, then you may be in a situation where `plotly` was installed twice, once with `conda` and once with `pip`, in which case I would recommend uninstalling with both, and reinstalling with one or the other: https://plotly.com/python/troubleshooting/

**Comment by nicholas-esterer** [comment]
Do you have `virtualenv` installed? For example on my machine `which pip` shows `/home/myusername/.local/bin/pip` but `which python3` shows `/usr/bin/python3`. So if you normally work by just running `python3` try installing like this: `python3 -m pip install plotly --upgrade`. This will force using the `pip` that writes to the user-wide site files.

**Comment by zrosgit** [comment]
Looks like you nailed it with the `virtualenv`.  I had a bad uninstall of `virtualenv` for Python 2.7 although I am running Python 3.7 for all this work. Using your suggested install of `python3 -m pip install plotly --upgrade` found the existing installation of 4.6.0, uninstalled it, and successfully installed 4.8.0.  Thanks - I'm good to go. Sorry for reporting this as a bug.
