### ISSUE TITLE
IIS 10 write_image() fails on POpen()

### ISSUE THREAD

**Issue by andyp05** [plotly/plotly.py#2509]
I originally posted this in plotly/orca, but I realized the code in question is in this repository. 

I think I have found the issue of IIS launching the orca server.
In _orca.py ensure_server()

```
    stderr = DEVNULL if "CI" in os.environ else None  # fix for CI
    orca_state["proc"] = subprocess.Popen(
        cmd_list, stdout=DEVNULL, stderr=stderr
    )
```
fails with orca_state["proc"] = None
If you change to:

```
    orca_state["proc"] = subprocess.Popen(
        cmd_list, stdout=subprocess.PIPE,
        stderr=subprocess.PIPE, stdin=subprocess.DEVNULL)
```
it works as expected.

Can I set stdout, stdin, and stderr in a configuration setting instead of modifying source code?

Thanks

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
