### ISSUE TITLE
Sankey Chart - Automatic re-aligning of nodes breaks after first drag-and-drop

### ISSUE THREAD

**Issue by cvesteghem** [plotly/plotly.py#2519]
After drag-and-dropping a node in a sankey chart and a proper re-alignment of the nodes, the next drag-and-drop is not followed by a realignment.

**Step to reproduce**
- Go to https://plotly.com/python/sankey-diagram/
- On a the diagram, drag-and-drop a node (B2 in the screenshot), the re-alignment works
- Drag-and-drop another node, there is no re-alignment (see C2 node on the screenshot)
![Screenshot 2020-05-30 at 12 27 10](https://user-images.githubusercontent.com/28856239/83325978-eded2500-a270-11ea-88ff-583c9c9fe73f.png)

**Expected behaviour**
The nodes are re-aligned every time.

**Environment**
- MacOS 10.15.4
- Firefox 76.0.1 & Safari 13.1

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
