### ISSUE TITLE
Allow "Sliders" to have number values

### ISSUE THREAD

**Issue by pfbuxton** [plotly/plotly.py#2523]
It would be very useful if sliders could have number values.

**Important:** At present sliders are set-up for strings and have a uniform spacing between "Sliders". If you look in the example screenshot you see the last slider has a value of 228, and "should" be very far to the right compared to the other steps.

**Would be useful:** Also, if the sliders were to allow number types the slider labels could format themselves, i.e. rounding to a few decimal places.
 
![plotly_sliders](https://user-images.githubusercontent.com/4923588/83432105-4880af80-a430-11ea-80cc-e0600d1ef369.png)

Thanks

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
