### ISSUE TITLE
[Bug] Auto-detection of vscode renderer is too general and sometimes fails when in Jupyter Notebook

### ISSUE THREAD

**Issue by FlorianWetschoreck** [plotly/plotly.py#2533]
Hi,

sometimes I am working with VSCode notebooks and later with Jupyter Notebooks.
This (sometimes) leads to the fact that the environment variable `VSCODE_PID` is still set although I am currently in the Jupyter notebook.

In those scenarios, the default renderer is detected to be "vscode" which does not work in the Jupyter Notebook.
When the bug appeared the first time, this was quite a hassle because I was not sure which part of my setup was broken eg the extensions, the python library version, ... and later I found out about the default renderer.

Therefore, I propose to change the default renderer in the case that `VSCODE_PID` exists in the environment variables:

Here are some proposals:
1. Set the renderer to "vscode+notebook" because this works in both scenarios.
2. Or you might even set it to "plotly_mimetype+notebook" as long as the "vscode" keyword is only forwarding to the default `PlotlyRenderer`

**Comment by FlorianWetschoreck** [comment]
I don't want to rush, I just want to ask if you need any further information from my side?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
