### ISSUE TITLE
Is it possible to put series images on map?

### ISSUE THREAD

**Issue by ringsaturn** [plotly/plotly.py#2534]
I want to show a series images on map, but sliders seems doesn't come with images layers support?

https://plotly.com/python/reference/#layout-sliders

**Comment by emmanuelle** [comment]
Hi @ringsaturn you can adapt [the documentation example on sliders](https://plotly.com/python/sliders/) using the `relayout` method instead of the `update` method, so that you modify the layout instead of the traces when moving the slider. For an example using `relayout` you can take a look at the [documentation on custom buttons](https://plotly.com/python/custom-buttons/#relayout-button) and adapt it to the case of a slider.

Please note that support should preferably be asked on the community forum https://community.plotly.com/ instead of the issue tracker (which is more for bugs and feature requests).

**Comment by ringsaturn** [comment]
Thanks.

I will go to community forum next time
