### ISSUE TITLE
Feature Request: Add windy.com-like map visualisations

### ISSUE THREAD

**Issue by John-smith-889** [plotly/plotly.py#2566]
Hello all,

As far as I know in Plotly.py there are not many tools for visualize weather conditions yet.  
Last days I was reading about windy.com, which has beautiful visualisations of wind, but also temperature, precipitation, lightnings and so on. Windy.com visualisations are inspired by open source project Earth, which is based on D3.js, you may watch about [the project](https://www.youtube.com/watch?v=OLSmNZm1e0k). 
What do you think about implement something like this in Plotly? It would be great to have opportunity to build dash apps with those kinds of maps.

If we consider plotting temperature/precipitation/etc., actually plotly has great contour plot, but it would be good, if there will be an option for example to add contour plot as a layer with Plotly Express Mapbox map, where values would be associated with geographical coordinates.
It could be the same with wind animation, where we could provide as an input some array with U,V wind components, and coordinates on map.

Cheers,
JS

**Comment by emmanuelle** [comment]
Hi @John-smith-889 thanks for starting this discussion. As of today we indeed have contour plots in Cartesian axes and also [a quiver figure factory for Cartesian axes](https://plotly.com/python/quiver-plots/). Probably the code of the figure factory could be adapted to create another function using the `go.Scattermapbox` trace. As for contour plots it is a bit trickier because of the projection. However we have already implemented contour plots in a non-Cartesian geometry with the [ternary contour figure factory](https://plotly.com/python/ternary-contour/). With figure factories you can use (in Python) other scientific Python packages (for example scipy and its interpolation functions) but then the feature is not available for the other languages (Javascript, R).

I am sure @empet would have interesting ideas here!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
