### ISSUE TITLE
support matplotlib 1.4.x

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#257]
We've got an old dependency for matplotlib 1.3.1 :(

We need to upgrade this to be more current. It will likely require some tweaks to mplexporter/matplotlylib. It should be well tested though, which will help us along here.

Note that _when_ we make this change, we really need to either (a) support 1.3.1 still or (b) make it _very_ clear that the user needs to upgrade.

**Comment by alkamid** [comment]
The current stable version is [1.5](http://matplotlib.org/1.5.0/index.html). Has there been any progress on this?

**Comment by theengineear** [comment]
@alkamid Unfortunately, not yet. We'll post here when we get this updated.

**Comment by theengineear** [comment]
FWIW, always happy to look over PRs if anyone wants to dig into the `mplexporter` dep and update the `matplotlylib` code (for reference).

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
