### ISSUE TITLE
Rangebreaks broken with go.Scattergl (works with go.Scatter)

### ISSUE THREAD

**Issue by gygabyte017** [plotly/plotly.py#2573]
This code uses go.Scatter with rangebreaks and it works

```
import pandas as pd
import plotly.graph_objects as go
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')

fig = go.Figure()

fig.add_trace(
    go.Scatter( ### REPLACE WITH go.Scattergl
        x=df["Date"],
        y=df["AAPL.High"],
    )
)

fig.update_xaxes(
    rangebreaks=[
        dict(bounds=["sat", "mon"]), #hide weekends
        dict(values=["2015-12-25", "2016-01-01"])  # hide Christmas and New Year's
    ]
)
fig.show()
```

If you replace go.Scatter with go.Scattergl, the image is completely broken: it shows no data, with random values for the axes (year is 2000....)

**Comment by TheZepto** [comment]
I've observed the same but from `plotly.express.line` and `plotly.express.scatter` when the render mode is auto and the number of points is > 1000. Setting the render mode to `svg` is my current workaround.

**Comment by nicolaskruchten** [comment]
Yes, this is a known limitation, and I've added a note to this effect to our documentation: https://plotly.com/python/time-series/#hiding-weekends-and-holidays

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
