### ISSUE TITLE
Stem plot figure factory

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.py#258]
Here's another super easy wrapper for TraceFactory:
http://matplotlib.org/examples/pylab_examples/stem_plot.html

MATLAB syntax:
http://www.mathworks.com/help/matlab/ref/stem.html?refresh=true

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
