### ISSUE TITLE
Plotly not working with Streamlit

### ISSUE THREAD

**Issue by alphadatagamma** [plotly/plotly.py#2582]
I am having trouble getting plotly to work with streamlit. All other plotting libraries seem to be working fine.
I have tried installing and reinstalling the package sevaral times.

This is my code;

import os
import glob
import time
import multiprocessing

import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objs as go

fig = go.Figure(
    data=[go.Bar(y=[2, 1, 3],x = [1,2,5], )],
    layout_title_text="A basic potly graph" #Naming my graph
)
fig.show()

st.plotly_chart(fig)
_______________________________________________________________________________________________________
![img](https://user-images.githubusercontent.com/61600335/85217877-04b00480-b363-11ea-90eb-b0695397dac4.PNG)

**Comment by emmanuelle** [comment]
Hi @alphadatagamma I tried executing your script with `streamlit run script.py` and it works fine (on Ubuntu linux, Firefox). You should remove the `fig.show()` because it will open another tab in your browser but does not prevent the streamlit app to display correctly at least in my environment. Similar problems [have been reported in the streamlit community forum](https://discuss.streamlit.io/t/plotly-in-streamlit/1319/4) probably this is a good place to get help? Also are you using the latest version of plotly?

**Comment by alphadatagamma** [comment]
Thanks emmanuelle, I tried it on a different laptop and it worked. So I uninstalled all my python distributions and reinstalled and voila! it worked.
