### ISSUE TITLE
Make_subplots: specify only row/col if cols=1/rows=1

### ISSUE THREAD

**Issue by sursu** [plotly/plotly.py#2594]
When using `make_subplot()` with multiple rows and `cols=1`, I think it should suffice to specify only `row`.

For instnace, this should work:

```python
y = np.random.normal(scale=0.1, size=500)

fig = go.FigureWidget(make_subplots(rows=2, cols=1))
fig.add_scatter(y=np.cumsum(y), row=1)
fig.add_scatter(y=y, row=2)
fig.layout.update(showlegend=False)
fig
```
Similarly with `rows=1`.

**Comment by nb2838** [comment]
Hey, would it be ok I start working on the issue?

**Comment by nb2838** [comment]
Actually, it seems that the behaviour that you mention is actually implemented. 
For example, with the following code 
``
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(cols = 2)
fig.add_trace(
    go.Scatter(x=[1, 2, 3], y=[4, 5, 6]),
               row=1, col=1)
fig.add_trace(
    go.Scatter(x=[20,30,40], y=[50,60,70]),
               row=1, col=2
)

fig.show()

**Comment by sursu** [comment]
You're missing something. This won't work:

```python
fig = make_subplots(cols = 2)
fig.add_trace(x=[1, 2, 3], y=[4, 5, 6], col=1)
fig.add_trace(x=[20,30,40], y=[50,60,70], col=2)
fig.show()
```

**Comment by nicolaskruchten** [comment]
I’m not opposed to this change in principle but I would wait until the hline/vline PR is merged as it touches this row/col logic a fair bit

**Comment by nb2838** [comment]
@sursu  I see what you mean now. I was confused and thought you were referring to the make_subplots function itself. I will wait for the PR and take try to take a  look to it afterwards

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
