### ISSUE TITLE
Plotly graphics in conda spyder environment

### ISSUE THREAD

**Issue by DavidSamir907** [plotly/plotly.py#2612]
Hello, I am making graphics with the ploty library in spyder but the figure does not appear. I do not get any error and it creates the variable of the figure as I can get the resulting figure. I am using fig.show ()

**Comment by hitchenzhe** [comment]
Hello, I also have this issue, I installed plotly 4.9.0 and run the simple demo
`import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
fig.update_layout(title = 'Hello Figure')
fig.show()`

It does not return any figure in spyder,(not in the plot explorer). A bit weird that it.s nothing happened

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
