### ISSUE TITLE
plotly.express.choropleth color_discrete_map performance

### ISSUE THREAD

**Issue by eggers** [plotly/plotly.py#2633]
The performance on color_discrete_map is much worse than for a continuous scale. At least for choropleths.

I've put code below which transforms a category axis into a continuous colormap. The discrete map takes ~40secs on my machine vs ~3 for the transformed column.

```python
from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    geojson = json.load(response)

geojson['features'] = [f for f in geojson['features'] if f['id'][:2] == '06']
df = pd.DataFrame([[f['id'], 
                    str(np.random.randint(0,4)) + str(np.random.randint(0,4))
                   ] for f in geojson['features']], 
                  columns=['fips', 'color'])

df['color'] = df['color'].astype('category')

def performance(df, discrete = False):

    color_discrete_map = {
        "missingvalue": "#000000",
        "00": "#6EC361", "01": "#00B37D", "02": "#116580", "03": "#292472",
        "missingvalue2": "#000000",        
        "10": "#7FC66A", "11": "#3FB07D", "12": "#595083", "13": "#5F267F",
        "20": "#B9DA77", "21": "#B7B27C", "22": "#BD5384", "23": "#A11C82",
        "30": "#F6F37C", "31": "#FCBA7A", "32": "#F5627E", "33": "#F00084",        
    }
    
    color_sequence = [color_discrete_map[k] for k in color_discrete_map]
    value_map = {k: i for i,k in enumerate(color_discrete_map.keys())}

    
    if discrete:
        fig = px.choropleth(df,
                            geojson=counties, locations='fips',
                            projection="mercator",
                            color_discrete_map=color_discrete_map, color='color',                         
                              )
    else:
        df['value'] = df['color'].map(value_map).astype(int)
        fig = px.choropleth(df,
                            geojson=counties, locations='fips',
                            projection="mercator",
                            color_continuous_scale=color_sequence, color='value',
                            range_color=(0, len(color_sequence)-1),
                              )
        
    fig.update_geos(fitbounds="locations", visible=False)
                                 
    return fig
```

**Comment by TLouf** [comment]
Hey,

I came across the same issue while plotting a Choropleth Mapbox with discrete colours, and following the solution presented [on the plotly forum](https://community.plotly.com/t/discrete-colors-for-choroplethmapbox-with-plotly-graph-objects/37989). I found that, as in @emmanuelle 's solution, with plotly.express the whole GeoJSON data is duplicated as many times as there are categories. This can quickly become an issue when your GeoJSON has a size of the order of a few MB. The fix to @emmanuelle 's solution when avoiding plotly.express is rather simple:

```python
import plotly.express as px
import plotly.graph_objects as go

df = px.data.election()
geojson = px.data.election_geojson()

colorscales = [
    ((0.0, '#636efa'), (1.0, '#636efa')),
    ((0.0, '#EF553B'), (1.0, '#EF553B')),
    ((0.0, '#00cc96'), (1.0, '#00cc96'))
]

fig = go.Figure()
for i, winner in enumerate(df['winner'].unique()):
    mask = df['winner'] == winner
    dfp = df.loc[mask]
    rel_districts = df.loc[mask, 'district'].values
    rel_feat = [f for f in features if f['properties']['district'] in rel_districts]
    cat_geojson = geojson.copy()
    cat_geojson.update({'features': rel_feat})
    fig.add_choroplethmapbox(geojson=cat_geojson, locations=dfp['district'],
                             z=[i,] * len(dfp), featureidkey="properties.district",
                             showlegend=True, name=winner,
                             colorscale=colorscales[i], showscale=False)

fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0},
                  mapbox=dict(style="carto-positron", zoom=9,
                              center={"lat": 45.5517, "lon": -73.7073},))

```


If you have as input a GeoDataFrame, it's even simpler as you just have to apply the same mask to extract the necessary geometries, and then take the `__geo_interface__` attribute.

So I managed to identify the root of the problem, but I have too much of a hard time wrapping my head around what's going on in [there](https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/plotly/express/_core.py#L1856) to write a PR myself. If someone involved in the development of this code is willing to take some time to fix it that'd be great, otherwise maybe I can try whenever I find the time.

**Comment by empet** [comment]
@TLouf 
To avoid defining as many chroropleth traces as the number of involved categories/discrete colors, there is no need to
define new geojson data, derived from the given one.
You just have to add a new numerical column encoding the winners, and define a typical discrete colorscale, used 
by Plotly users for years. See also this discussion on Plotly forum
[https://community.plotly.com/t/add-geojson-polygons-seaborn-colored-by-specific-feature/40464](https://community.plotly.com/t/add-geojson-polygons-seaborn-colored-by-specific-feature/40464)
```
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
df = px.data.election()
geojson_data = px.data.election_geojson()

#define a numerical column to be mapped to a colorscale
winners = df["winner"].unique()
L = winners.shape[0]
vals = [round((k+1)/L-1/(2*L), 2) for k in range(L)]
my_dict= dict(zip(winners, vals))
df['num_winner'] = [my_dict[w]  for w in df["winner"]]

#define a discrete colorscale
color= ['#636efa', '#EF553B', '#00cc96']
colorscale =[]
for k in range(L):
    colorscale.extend([[k/L, color[k]], [(k+1)/L, color[k]]])

fig=go.Figure()
fig.add_choroplethmapbox(geojson=geojson_data, locations=df['district'],
                             z=df["num_winner"], featureidkey="properties.district",
                             customdata= np.stack((df["district"], df["winner"]), axis=-1),
                             hovertemplate= "%{customdata[0]}<extra>%{customdata[1]}</extra>",
                             colorscale=colorscale, showscale=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0},
                  mapbox=dict(style="carto-positron", zoom=9.7,
                              center={"lat": 45.5517, "lon": -73.7073}))
```

**Comment by TLouf** [comment]
@empet this is indeed the first thing I did, and you do get the same map. But starting from there I then wanted to add a legend, which, as in any "simple" plotly plot, I could click to show/hide categories. To better explain my use case, I cluster US counties and wish to visualize each cluster separately to quickly identify the counties belonging to the smallest clusters. In that case, the GeoJSON's size is far from negligible and my figure saved in HTML reached 40MB, which isn't practical at all. Of course your solution can have the same functionality if you add buttons, but I think it's more tedious to do it that way. 

(by the way I corrected my code above which had an undefined variable)

**Comment by nicolaskruchten** [comment]
It should be possible to have PX spilt the geojson one per trace, indeed. That hadn't occurred to me when initially building that feature because I had been intending to let traces "share" a common geojson definition in the layout portion of the figure, but we haven't gotten around to building that yet. 

The other option is to refer to an external geojson file by URL in the PX call, in which case all traces do share the same object but it's not part of the resulting figure or any exported HTML, and the geojson file must be separately hosted via HTTP.

**Comment by nicolaskruchten** [comment]
And yes, while hacking a continuous scale into discrete blocks gets you partway towards the desired static output visually, our continuous scales don't afford the same interactions that our legends do ... trade-offs abound!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
