### ISSUE TITLE
Y Axis Label Issues with Log Scaling

### ISSUE THREAD

**Issue by alex85301** [plotly/plotly.py#2637]
Hi team, please see my below code for a basic time series line graph.
I'm trying to make the Y axis a log scale, but the labels are not ordered correctly. 
When googling it seems it could be a automargin problem? Or maybe I'm just missing some basic code changes. 
Cheers!

import plotly.express as px 
import pandas as pd 
import numpy as np
import plotly.offline as plot
import yfinance as yf 

df_wide1 = yf.download("APT.AX ALC.AX ALU.AX APX.AX AMS.AX AD8.AX BTH.AX BVS.AX CAR.AX CAT.AX RBL.AX RAP.AX RHP.AX TNE.AX CGL.AX VHT.AX WEB.AX WTC.AX XRO.AX",
                   start="2020-03-01", end="2020-07-09")

df_wide1 = df_wide1[['Close']]
df_wide1 = df_wide1.reset_index()
#print(df_wide1)

#Colnames = df_wide1.columns.tolist()

df_long=pd.melt(df_wide1, id_vars=['Date'])

# plotly 
fig = px.line(df_long, x='Date', y='value', color='variable_1')
#fig = px.line(df_long, x='Date', y='value')

#fig.update_layout(yaxis_type="log")

fig.update_layout(autosize=True, yaxis_type="log")

# Show plot 
fig.show()

**Comment by nicolaskruchten** [comment]
Can you provide a screenshot of what you're seeing please?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
