### ISSUE TITLE
not possible to format `hover_data` with px.sunburst / treemap and path

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2642]
```python
import plotly.express as px
df = px.data.tips()
fig = px.treemap(df, path=['day', 'time', 'sex'], values='total_bill', hover_data={'parent':False})
fig.show()
```
raises
```python
ValueError: Value of 'hover_data_0' is not the name of a column in 'data_frame'. Expected one of ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'] but received: parent
```

**Comment by nicolaskruchten** [comment]
This one is kind of normal to an extent... you're trying to format the hover data of the "second" dataframe, which hasn't been constructed yet at the time that the check is happening.

**Comment by jblang** [comment]
I am hitting the same issue. 

What is the correct way to get rid of unwanted default values in the hover text then? The px.sunburst chart is showing labels, parent, and id in the hover text by default.  But I don't want those--only the fields I explicitly list.

I also was not able to get the hover template to work. I set the hovertemplate like this, which is what the docs say to do, but I just get the verbatim string that I specified rather than the values being interpolated:

fig.update_traces(hovertemplate="%{keyspace}.%{table} %{human_size}")

**Comment by shadiakiki1986** [comment]
@nicolaskruchten  Would the below fix work?

In `build_dataframe` on [line 1377](https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/plotly/express/_core.py#L1377), pass constructor to `process_args_into_dataframe`:

```
df_output, wide_id_vars = process_args_into_dataframe(
        args, wide_mode, var_name, value_name, constructor
    )
```

Then in `process_args_into_dataframe` on [line 1175](https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/plotly/express/_core.py#L1175), add an `elif`:

```
 elif constructor in [go.Sunburst]: # , go.Treemap also?
    if argument in ["parent", "id", "label"]:
      continue
```

**Comment by shadiakiki1986** [comment]
@jblang I got the `update_traces` to work for me by using `hovertemplate="%{id}: %{value:.2f}"`, where I didn't really have `value` as a column name, but I had passed the corresponding column name to the `values` field ([docs](https://plotly.com/python-api-reference/generated/plotly.express.sunburst.html))

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
