### ISSUE TITLE
Treemap click event

### ISSUE THREAD

**Issue by haseeb000001** [plotly/plotly.py#2645]
Hi. 
I want to open a link when i click on inner most item in treemap. I added html  <a></a> href link in the text. The text appers to be blue but it is not clickable.

Is there any alternate method like callback function of mouse click event or something. Thanks.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
