### ISSUE TITLE
Python-side aggregation in PX

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2649]
Right now Plotly Express hews pretty closely to the concept of "no computation in Python" modulo stuff like sunburst `path` and scatter `trendlines`... notably `histogram`, `box` and `density_heatmap` embed the entire dataset into the figure and let the front end handle the aggregation. This is not particularly scalable, and generally means we can't leverage the excellent Python-side tools for big data (e.g. Vaex https://github.com/plotly/plotly_express/issues/139 or RAPIDS).

We should come up with some consistent way of using PX for big-data aggregations. Datashader would be a natural backend for `density_heatmap` for example.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
