### ISSUE TITLE
Treemap figure factory

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.py#265]
Another wrapper that would be fairly straightforward. Could recycling code from here:
https://github.com/laserson/squarify

Color blocks could be done with heatmaps like this:
https://plot.ly/~MattSundquist/3492/golden-spiral-trace-1-fibonacci-numbers/

Or area plots like this:
https://plot.ly/~jackp/9536

^^^ This one came from the MATLAB tree map package.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
