### ISSUE TITLE
Is there a way to prevent the y-axis labelling 0 as a negative value?

### ISSUE THREAD

**Issue by anuraghuram** [plotly/plotly.py#2660]
I am having a similar issue to the one described [here](https://community.plotly.com/t/yaxis-labeling-0-as-negative/32227). I do see that when I click and drag the y axis upward, the '0%' y-tick on my plot corrects to 0%. However when I drag the y axis downward, the negative sign reappears in front of the 0% y-tick.

**Comment by anuraghuram** [comment]
Alternatively, is there a way to change just the -0% y-tick (leaving the others as is) to 0%?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
