### ISSUE TITLE
mkdirs returns an int, not a response object

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#267]
This makes it pretty hard to get a handle on the folder you just created, right?

It forces users to rely on using filename _paths_, which ends up requiring extra db hits on the backend.

Just opening this up for discussion?

https://github.com/plotly/python-api/blob/master/plotly/plotly/plotly.py#L729

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
