### ISSUE TITLE
United States ocean border visible when it shouldn't be

### ISSUE THREAD

**Issue by Coloradohusky** [plotly/plotly.py#2670]
![image](https://user-images.githubusercontent.com/45430066/88552477-2485b880-cff2-11ea-8e15-8e23ca1a7805.png)  

It goes away when `showland = False`, but not when `showcoastlines = False`.  

Code is taken from [Scatter Plots on Maps](https://plotly.com/python/scatter-plots-on-maps/), with color modifications to make it stand out.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
