### ISSUE TITLE
Remove breaks for OHLC Candlestick

### ISSUE THREAD

**Issue by RoyalGoose** [plotly/plotly.py#2679]
A question was asked on a nearby forum https://github.com/plotly/plotly.js/issues/1382
How to remove weekend whitespaces in python?

**Comment by nicolaskruchten** [comment]
Here is the relevant documentation: https://plotly.com/python/time-series/#hiding-weekends-and-holidays

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
