### ISSUE TITLE
How to disable "Export to plot.ly" in the Jupiter notebook ?

### ISSUE THREAD

**Issue by Rahulvks** [plotly/plotly.py#2686]
The output of ploty comes with the link  "Export to plot.ly" when we open the link it's connected to https://plot.ly/external with the dataset. How to remove the link for data privacy.

libraries

```
import pandas as pd
import os
import re
import numpy as np
cnf, dth, rec, act = '#393e46', '#ff2e63', '#21bf73', '#fe9801' 
# Standard plotly imports
import plotly.offline as py 
import plotly.graph_objs as go
import plotly.tools as tls
from plotly.offline import iplot, init_notebook_mode
import plotly.express as px
import cufflinks as cf
%matplotlib inline
from datetime import timedelta
# Using plotly + cufflinks in offline mode
init_notebook_mode(connected=False)
cf.go_offline(connected=False)
import os
import gc
gc.collect()
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 2000)
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>")) 

```

Fig generating 
```
fig2= fig2.iplot(kind='bar', barmode='group', 
                   title='PCR Results ', 
                   xTitle='Date', yTitle='Count'
                )
```

Referred this ticket https://gist.github.com/neo01124/449bc7df9f25c6ef055c7efbd2d89a3a

**Comment by nicolaskruchten** [comment]
It seems like you're using an older version of Plotly.py... these are off by default in version 4+

**Comment by Rahulvks** [comment]
Hi .. No still it is same 

```
import plotly
print(plotly.__version__)

```
`4.8.2`

*Kerenal restarted

**Comment by nicolaskruchten** [comment]
OK, in that case, this is probably something you have to control via `cufflinks`... The `iplot()` function you're calling here doesn't come from the `plotly` package.

**Comment by Rahulvks** [comment]
Okay. Do we have any reference for this ?

I am using iplot from  but if i disable the cufflinks I am getting this error `AttributeError: 'DataFrame' object has no attribute 'iplot'`

`from plotly.offline import iplot, init_notebook_mode
import cufflinks as cf

`

**Comment by nicolaskruchten** [comment]
you are importing `iplot` from `plotly.offline` but that's not the `iplot` you're calling on the object called `fig2` here... I can tell because `plotly.offline.iplot()` doesn't accept a keyword argument `xTitle` and because when you disable cufflinks it stops working :) 

You'll have to check out the cufflinks documentation for more information... we don't maintain cufflinks ourselves so there's not much more I can give you here.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
