### ISSUE TITLE
Ordering of x axis ignored if value looks like numeric

### ISSUE THREAD

**Issue by aamster** [plotly/plotly.py#2692]
I would expect, if given a string datatype as x axis, that the order of the dataframe would be maintained. Rather, the values are coerced to numeric by plotly and ordering is ascending, with no way to change it. This is confusing to me.

![Screen Shot 2020-08-06 at 4 19 53 PM](https://user-images.githubusercontent.com/5454341/89578910-e746d500-d800-11ea-9f20-29dd0a1f5f95.png)
![Screen Shot 2020-08-06 at 4 20 00 PM](https://user-images.githubusercontent.com/5454341/89578911-e7df6b80-d800-11ea-81aa-38a5719475c7.png)

**Comment by nicolaskruchten** [comment]
I agree this is confusing! 

You can force the x-axis to be categorical with `fig.update_xaxes(type="category")`:

![image](https://user-images.githubusercontent.com/203523/89579257-76ec8380-d801-11ea-8b69-34cbaca08bab.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
