### ISSUE TITLE
Datetime on Y axis at BoxPlot problem

### ISSUE THREAD

**Issue by luisfrossi** [plotly/plotly.py#2712]
Hello, I am creating a Boxplot on Dash with the Datetime on Y Axis, however when the minimum value of the Boxplot is on time 00:00 it displays as undefined. How should I proceed?

![image](https://user-images.githubusercontent.com/5166358/90428031-c6507080-e099-11ea-92e4-1887104e95a2.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
