### ISSUE TITLE
Seperate axis title for subplots while implementing updatemenus

### ISSUE THREAD

**Issue by UtkarshKhanna21** [plotly/plotly.py#2718]
Currently - on implementing dropdown using updatemenus, we can only provide xaxis and yaxis titles. Subplots being implemented with updatemenus gives undesirable results - due to the shared axis, the first subplot figure overlaps with all other subplots. 
Image attached as reference

Output:
![Messed up Image](https://user-images.githubusercontent.com/68686054/90822601-58829e00-e352-11ea-846d-2da323854aa9.png)

Required output:
Individual subplots with axis names for each subplot 

Support required @nicolaskruchten

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
