### ISSUE TITLE
Feature Request: Contours on Mapbox

### ISSUE THREAD

**Issue by jcfbeardsley** [plotly/plotly.py#2720]
Hi,

Having the ability to add contour plots to Mapbox would be fantastic for producing maps of 2D variables (e.g. temperature). At the moment I am manually calculating these using contours and adding each one as a `scattermapbox` line trace, but this is rather cumbersome an inefficient, particularly when used in interactive Dash callbacks. 

How challenging would it be to adapt the existing [Plotly Contours](https://plotly.com/python/contour-plots/) and its relevant functionality (e.g. smoothing, labelling) to something like `contoursmapbox`?

Thanks in advance.

**Comment by nicolaskruchten** [comment]
This is a cool idea! There are probably two ways to go about this: 

1. either add a [figure factory](https://plotly.com/python/figure-factories/) to Plotly.py, similar to [the recently-added `hexbin_mapbox`](https://plotly.com/python/hexbin-mapbox/), which does the work in Python and leverages the existing set of `plotly.graph_objects`, or
2. [add a new trace type to Plotly.js ](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md) similar to the [relatively-ly `densitymapbox` trace type](https://plotly.com/python/mapbox-density-heatmaps/), leveraging the full Mapbox GL JS API, in which case this would be available under `plotly.graph_objects` in the next Python release.

The former is likely easier :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
