### ISSUE TITLE
[Feature Request] Parallel coordinate plot for pandas backend

### ISSUE THREAD

**Issue by renatobellotti** [plotly/plotly.py#2721]
I believe plotly provides the best parallel coordinate implementation available for Python. I think making it available for the [pandas API](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.plotting.parallel_coordinates.html) would make this powerful tool just one line of code!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
