### ISSUE TITLE
Latex fonts in title/axis can't be increased in size

### ISSUE THREAD

**Issue by Helveg** [plotly/plotly.py#2729]
When you use Latex typesetting, it is impossible to increase the size of the title or axis labels above a quite limited size. Reducing it in size is possible down to font size `1`. It seems to have an upper limit of font size `10`.

```python
import plotly.graph_objects as go


fig = go.Figure()

fig.update_layout(
    title=r"$\mathcal{A}x$",
    xaxis=dict(title="x axis"),
    yaxis=dict(title=r"$\mathcal{L}$",title_font=dict(size=3000)),
    font=dict(size=30),
)

fig.show()
```

![image](https://user-images.githubusercontent.com/28923979/91351751-168da800-e7e9-11ea-9903-2b695d095ad4.png)

You can see that the xaxis label that doesn't use Latex is larger in size, but the title label or the extremely large value for the yaxis label have no effect on the size.

If you point me to the relevant source code on the Latex rendering I can try to make a PR.

**Comment by mariogeiger** [comment]
As a quick fix you can do
```
r"$\Huge\mathcal{L}$"
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
