### ISSUE TITLE
Unable to specify dash length on line shapes

### ISSUE THREAD

**Issue by jasonherngwang** [plotly/plotly.py#2734]
Is it possible to specify dash length on line shapes, or are we limited to the built-in solid, dot, dash, etc? The [documentation](https://plotly.com/python-api-reference/generated/plotly.graph_objects.layout.newshape.html#plotly.graph_objects.layout.newshape.Line) indicates that this should work. It works for Scatter plot lines, but not shape lines. Plotly version 4.9.0.
```
fig = go.Figure()
fig.add_shape(
    dict(
        type="line",
        x0=0,
        y0=0,
        x1=1,
        y1=1,
        xref="x",
        yref="y",
        line=dict(
            dash="2px,2px"
        )
))
fig.show()
```

Error:
```
ValueError: 
    Invalid value of type 'builtins.str' received for the 'dash' property of layout.shape.line
        Received value: '2px,2px'

    The 'dash' property is a string and must be specified as:
      - One of the following strings:
            ['solid', 'dot', 'dash', 'longdash', 'dashdot',
            'longdashdot']
      - A number that will be converted to a string
```

**Comment by mind6** [comment]
I ran into the same issue. I am interested in changing how "dense" dash looks to visualize its strength .

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
