### ISSUE TITLE
Stacking is reset after null value in FigureWidget

### ISSUE THREAD

**Issue by dmeescor** [plotly/plotly.py#2743]
Bar values don't stack correctly when all of the following hold
* Displaying a figure in a FigureWidget
* Using barmode = "stack" or "relative"
* A series other than the first or last has a null value for at least one data point

To reproduce in Jupyter:
```
import pandas as pd
import numpy as np
import plotly.graph_objects as go

df = pd.DataFrame({
    '0': [np.nan, 76, 77, 64, 60],
    '1': [30, np.nan, 27, 30, 30],
    '2': [46, 20, np.nan, 80, 85],
    '3': [57, 25, 30, np.nan, 87],
})

fig = go.Figure()
fig.update_layout(barmode='relative',)
fig.add_trace(go.Bar(y=df['0']))
fig.add_trace(go.Bar(y=df['1']))
fig.add_trace(go.Bar(y=df['2']))
fig.add_trace(go.Bar(y=df['3']))
fig.show() # Null values are treated as zero
```
```
# stacking works before and after null values in series 2 and 3, but resets at the null value
go.FigureWidget(fig) 
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
