### ISSUE TITLE
Rangeslider positioning in stacked plots

### ISSUE THREAD

**Issue by PhantoNull** [plotly/plotly.py#2755]
Hello!

I'm kinda new in plotly and python and I'm having troubles finding a way to set in good position the rangeslider while mantaining the vertical spacing kinda small.

I've been stacking up plots like this, but the range slider collides with the second row of the subplot (I've added some more vertical spacing between rows just for explaining better)

![image](https://user-images.githubusercontent.com/65261018/92532967-cb848380-f231-11ea-8977-8cfa7838451a.png)

The solution i'm using for now is just removing the rangeslider for axis1 and showing it for axis3 (but isn't showing the candles and neither is in a good position)

![image](https://user-images.githubusercontent.com/65261018/92533166-29b16680-f232-11ea-915a-ce7160cd705c.png)

What can I do to solve this layout problem?

Also, why `shared_axes = True` hide xaxes ticks values? Is there a way to show them back while mantaining a ?

Thank you for your understanding and any kind of help!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
