### ISSUE TITLE
Sorting the Y-axis bars of a stacked bar chart by value

### ISSUE THREAD

**Issue by TeodorIvanov** [plotly/plotly.py#2773]
I have this code example using plotly that builds a stacked bar chart:
```python
import plotly.graph_objects as go

x = ['2018-01', '2018-02', '2018-03']
fig = go.Figure(go.Bar(x=x, y=[10, 15, 3], name='Client 1'))
fig.add_trace(go.Bar(x=x, y=[12, 7, 14], name='Client 2'))

fig.update_layout(
    barmode='stack',
    yaxis={'title': 'amount'},
    xaxis={
        'type': 'category',
        'title': 'month',
    },
)
fig.show()
```

Which outputs the following plot:
![](https://i.stack.imgur.com/NZGGl.png)

I have struggled to find a way to tweak the plotly layout as to order each bar's Y-axis by value.
What I mean is that in the second bar (2018-02) Client 1 has a higher value for Y, the blue bar should be on top of the red one.
Is this feature available?

**Comment by nicolaskruchten** [comment]
In Plotly figures, each bar is always stacked in the same order, so I don't think there's a way to do what you're asking, unfortunately.

**Comment by TeodorIvanov** [comment]
To give an update on this issue, there is a workaround that someone posted on stack overflow that answers my question.
It consists of creating separate traces for each stacked bar.
https://stackoverflow.com/a/63922434/3103845
I'll close this issue for now.

**Comment by Shwetago** [comment]
In your stacked bar chart, you are creating a bar chart for client 1 first, that's why client 1 fig is at the bottom, and then you are tracing it for client 2 that's why it is at the top. 
This has nothing to do with values.
In Stack, Data Structure, what goes last comes out first. That's how it works!!  

Check out this link:  https://plotly.com/python/bar-charts/

I hope it helps!!
