### ISSUE TITLE
Scattermapbox not printing

### ISSUE THREAD

**Issue by Nahu-11** [plotly/plotly.py#2774]
Hello, many thanks for your work, Plotly is amazing!

I've experienced only one issue with Plotly. When plotting a scattermapbox, it displays and updates (with Dash) well, but when I try to print it as PDF in Firefox and in some Chrome versions it prints and empty box.

As I understand, the maps are based on Mapbox, so I've found a possible solution from its team here https://github.com/mapbox/mapbox-gl-js/issues/9810. It seems that setting "preserveDrawingBuffer" to True may fix the issue. However, Plotly doesn't allow the user to modify the "preserveDrawingBuffer" option.

Is there any chance of adding "preserveDrawingBuffer" as an input variable in the scattermapbox?

Many thanks, your work is great!

**Comment by Shwetago** [comment]
Why don't you create a PR? @Nahu-11

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
