### ISSUE TITLE
Only get limited information on single click of legend as compared to double click even though the same event restyleData gets triggered.

### ISSUE THREAD

**Issue by aryancodify** [plotly/plotly.py#2776]
Say my legend has 4 different attributes. On single/double click on one of them the restyleData event is triggered. But on double click I get the information for the whole legend like this: `[{'visible': [True, 'legendonly', 'legendonly', 'legendonly']}, [0, 1, 2, 3]]`

But on single click we get information of only one attribute: `[{'visible': [True]}, [0]]`

This makes it very hard to handle both these cases while writing a callback because we have to maintain the current legend state manually. Can you please address this.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
