### ISSUE TITLE
Histogram category order example

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#2779]
Searching google for "Plotly python sort histogram" comes up with this great example in the forum: https://community.plotly.com/t/plotly-express-histogram-any-way-to-sort-bar-by-value/23905

Would be nice if this was in the histogram docs

**Comment by hweecat** [comment]
First-time contributor here - I could try adding the sorted histogram example into the histogram docs, if that's okay. :)

**Comment by emmanuelle** [comment]
Hi @hweecat great! Please read https://github.com/plotly/plotly.py/blob/master/contributing.md and https://github.com/plotly/plotly.py/blob/master/doc/README.md to learn about our contributing guidelines.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
