### ISSUE TITLE
Allow the bar origin in Gauge to start at 0

### ISSUE THREAD

**Issue by mkschulze** [plotly/plotly.py#2780]
It would be great to have the chance to set the bar origin in the Gauge indicator to start at 0.

This would make it possible to better indicate negative values as described here:

https://community.plotly.com/t/set-bar-origin-in-angular-gauge-indicator-to-start-at-0/44838/3

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
