### ISSUE TITLE
px.bar: when base is used, hoverlabel label should be "base+y: %y"

### ISSUE THREAD

**Issue by eddy-geek** [plotly/plotly.py#2786]
Minimal example:

```python
tasks = pd.DataFrame([
    dict(Task="A", Start=0, Elapsed=10),
    dict(Task="B", Start=0, Elapsed=5),
    dict(Task="C", Start=5, Elapsed=10)
])
px.bar(tasks, base='Start', y='Elapsed', text='Task',)
```

![image](https://user-images.githubusercontent.com/2772505/93938296-5634aa80-fd29-11ea-9c41-9ffc997aaf9d.png)

Imagine an horizontal gantt-chart where `x=Elapsed` is Task duration in days. The issue is that Task C has "Elapsed=15" instead of "Elapsed=10". 

This also an issue in the `graph_objects` API in the default hover, but at least adding x as text shows the proper one.

```python
go.Figure(data=[go.Bar(base=tasks['Start'], y=tasks['Elapsed'], text=tasks['Elapsed'])])
```
![image](https://user-images.githubusercontent.com/2772505/93938505-a7449e80-fd29-11ea-9eca-57df79c691f0.png)

_Note:_ In `px.timeline` it's fine since user must give `Finish=`but in `px.bar` it's looks pretty misleading to "change" _x_ into _finish_ :-)

If my Task lasts 10 days, the fact that it ends at day 15 is an internal positioning detail.

@nicolaskruchten is it just an oversight from https://github.com/plotly/plotly.py/issues/2585 or do you intend it this way?

**Comment by eddy-geek** [comment]
I just noticed the following:

If I add x as explicit hover_data, it _changes_ the hover data to the correct one:

```python
px.bar(tasks, base='Start', y='Elapsed', text='Task',) # left
px.bar(tasks, base='Start', y='Elapsed', text='Task', hover_data=['Elapsed']) # right
```
![image](https://user-images.githubusercontent.com/2772505/93940282-7b76e800-fd2c-11ea-8de2-3658f44ecd18.png) ![image](https://user-images.githubusercontent.com/2772505/93940229-6a2ddb80-fd2c-11ea-8a1a-3d3378332081.png)

Maybe the second behaviour can be made default?

**Comment by nicolaskruchten** [comment]
This behaviour is intentional: when `orientation` is its default `"v"`, the value shown in the hover label for the "y" value is the y-position of the top of the bar, which is sum of what is provided as `base` and `y`. I agree this is confusing when you are passing a value into `y` which has the semantics of "elapsed", but changing this would be a backwards-incompatible change, so not something we can envision in the short term. This is also basically why we built `px.timeline()`, with explicit start/end arguments. Adding in automatic "elapsed" computation in PX would be an easy way forward here perhaps?

When you pass in `text` in `go.Bar` or `hover_data` in `px.bar`, you're effectively overwriting the hover label, so there is a workaround, thankfully.

**Comment by nicolaskruchten** [comment]
That said, maybe PX could format its hoverlabel here more clearly to say "start+elapsed: 15" to make this more explicit/less misleading

**Comment by eddy-geek** [comment]
I agree with not changing plotly.js, this is only about px.bar

> Adding in automatic "elapsed" computation in PX would be an easy way forward here perhaps?
> PX should really format its hoverlabel here more clearly to say "start+elapsed: 15"

This is good enough since it prevents confusion and makes it more obvious than adding `hover_data=['Elapsed']` will work as expected. Still, I wonder why not make it the default behaviour of `px.bar(base)`.

**Comment by nicolaskruchten** [comment]
> Still, I wonder why not make it the default behaviour of px.bar(base)

That's a good idea but the implementation under the hood is a bit more complicated :)

**Comment by Lxstr** [comment]
@nicolaskruchten I have been trying to pass in text to go.bar to avoid the effects of setting a base on an offset stacked bar chart but with no luck. 

```go.Bar(
            name="On Order",
            y = availability_df["Product"],
            x = availability_df["OnOrder"],
            base = on_order_base,
            text = availability_df["OnOrder"],
```

or

```
hoverinfo="text",
hovertext = availability_df["OnOrder"],
```

Is there anything I'm missing? Cheers

**Comment by Lxstr** [comment]
So the required code in the end was 
```
hoverinfo="text",
hovertext = [f'In stock: {val}' for val in availability_df["InStock"]],
```

I also had to remove this line
`fig.update_traces(hovertemplate="%{x}")`

However, I wonder is this the most effective and CPU efficient way to do it? I feel like these lines to replicate what could be default seems unusual?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
