### ISSUE TITLE
Optimize add_trace

### ISSUE THREAD

**Issue by henryrobbins** [plotly/plotly.py#2787]
I am currently working on a project that involves many traces (I have multiple 2d lines / 3d planes that need to change visibility independently). I am trying to optimize and am finding the `add_trace` method to be slow. I tried adding all my traces at once using `add_traces()` but found this to be significantly slower. After looking at the source code, I see that `add_trace()` just calls `add_traces()`. I then noticed the following line:

```
# Make deep copy of trace data (Optimize later if needed)
        new_traces_data = [deepcopy(trace._props) for trace in data]
```

Is anyone currently working to optimize this? Would it be possible to add the ability to not do a deepcopy at all? Or if there is a quicker way to add traces, please let me know. Thanks!

**Comment by nicolaskruchten** [comment]
I don't know of a faster way, and no one is looking at this at the moment, but we'd welcome some help if you want to take a crack at it :)

**Comment by eceforge** [comment]
I know this is a bit of an old ticket, but it still seems relavant as this is still part of the codebase. It is also still causing quite the slow-down for rather large datasets since the trace._props copies all the props including the underlying data. 

It strikes me that we don't actually need the deepcopy here unless the data is a python object. In the usual case (for large data) where the data is a numpy ndarray, calling deepcopy will trigger the `ndarray.__deepcopy__` function, which as the [numpy manual ](https://numpy.org/doc/stable/reference/generated/numpy.copy.html) calls out is not necessary unless the dtype of the ndarray is 'object'. For all other types calling the 'copy' function (rather than the deepcopy) will keep you safe from changing data. The copy function of course being much faster than deepcopy. 

I'm just assuming the _intent_ of the deepcopy here was to protect against changes in the underlying data between the add_trace call and the viewing of the data. If that's not the case then by all means disregard my comment. That step seems perhaps a bit conserative but I'm going to assume the developers had good reason for that.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
