### ISSUE TITLE
Support zoom parameter in function fig.update_layout

### ISSUE THREAD

**Issue by ikeszvpvb9ye** [plotly/plotly.py#2789]
As one of the options for solving the https://github.com/plotly/plotly.py/issues/2788 problem, you can consider support for the zoom parameter in the fig.update_layout function, for example:
`fig.update_layout(zoom=90%)`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
