### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in \node_modules\plotly.js\node_modules\image-size\lib\types

### ISSUE THREAD

**Issue by omryoz** [plotly/plotly.py#2790]
upgrade to 1.55.2, unable to compile using webpack:

ERROR in ./node_modules/plotly.js/node_modules/image-size/lib/index.js
Module not found: Error: Can't resolve 'fs' in xxxxxxxx\node_modules\plotly.js\node_modules\image-size\lib'

ERROR in ./node_modules/plotly.js/node_modules/image-size/lib/types/tiff.js
Module not found: Error: Can't resolve 'fs' in 'xxxxxxxx\node_modules\plotly.js\node_modules\image-size\lib\types'
i ｢wdm｣: Failed to compile.

**Comment by meriturva** [comment]
I had to add on package.json:

```
"browser": {
    "image-size": false
  }
```
to solve error

**Comment by r9mp** [comment]
Hi!
I'm using Webpack through NuxtJS.
For me the solution was to edit Webpack config:
```js
config.node = {
  fs: 'empty',
}
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
