### ISSUE TITLE
[Docs] No explanation for the mechanism of converting Figure object to dict/JSON

### ISSUE THREAD

**Issue by PlatonB** [plotly/plotly.py#2791]
I noticed that the print of any `plotly.graph_objects.Figure` object contains only a minimum of data, but after conversion to dictionary or JSON one can see the full set of chart attributes. I suggest to supplement the documentation with an explanation of this phenomenon. Are the `to_dict()`, `write_json()` and `to_json()` methods capable of extending `Figure` objects? Or are this objects initially completed and passed to the `print` in a reduced form?

**Comment by nicolaskruchten** [comment]
The `to_dict()`/`to_json()` methods return a faithful reproduction of what's in the figure, and `print()` does elide some details, notably the contents of the `layout.template` key, for brevity, given that this sub-tree is long and almost always the same... We could add a bit of docs to explain this discrepancy, yes :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
