### ISSUE TITLE
Selecting data on a subplot with a map also selects data on a scatter plot

### ISSUE THREAD

**Issue by cjroberts** [plotly/plotly.py#2793]
Hello,

When creating subplots with a Scattergeo or a Scattermapbox and a scatter plot, if I select data on the map then data on one of the scatter plots is also selected. This seems to be the first scatter plot that has been added only. I am trying to link the selection between plots and this affects the functionality, which is otherwise working using either ipywidgets or javascript event handlers. Here is a minimal reproducer:
```
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

lons = np.random.random(1000) * 360.0
lats = np.random.random(1000) * 180.0 - 90.0
z = np.random.random(1000) * 50.0

fig = make_subplots(rows=2, cols=1, specs=[[{'type': 'geo'}], [{}]])
fig.add_scattergeo(row=1, col=1, lon=lons, lat=lats, marker={'color': z})
fig.add_scatter(row=2, col=1, x=lons, y=z, mode='markers')
fig.update_layout(height=900)
fig.show()
```
The attached PDF also shows the issue.

Many thanks in advance for your help.

[subplots_issue.pdf](https://github.com/plotly/plotly.py/files/5275583/subplots_issue.pdf)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
