### ISSUE TITLE
plotlywidget.json install location in /usr/etc/ instead of /etc/

### ISSUE THREAD

**Issue by epsilon-0** [plotly/plotly.py#2794]
I am updating the package for gentoo and am wondering what should be the correct location for installing the `plotlywidget.json` file.

Currently it is being installed in `/usr/etc/jupyter/nbconfig/notebook.d` because of the data_files extension, which instead should have been installed to `/etc/jupyter/nbconfig/notebook.d`.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
