### ISSUE TITLE
Plotly parallel_coordinates not showing in Dataiku Notebook

### ISSUE THREAD

**Issue by dadounem** [plotly/plotly.py#2800]
Hi,

I have an issue with parallel_coordinates function: when i execute a code, it displays only  the colorbar. 

This is the code for the plot:

```
import plotly.express as px
dt = px.data.iris()
fig = px.parallel_coordinates(dt, color="species_id", labels={"species_id": "Species",
                "sepal_width": "Sepal Width", "sepal_length": "Sepal Length",
                "petal_width": "Petal Width", "petal_length": "Petal Length", },
                             color_continuous_scale=px.colors.diverging.Tealrose,
                             color_continuous_midpoint=2)
fig.show()
```

Plotly Version 4.10.0

Thanks for your help

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
