### ISSUE TITLE
String formatting error in "Column.__init__" (grid_objs.py)

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [plotly/plotly.py#2803]
Hello,

While analyzing plotly.py on SonarCloud I saw what looks like a bug in [`packages/python/chart-studio/chart_studio/grid_objs/grid_objs.py`](https://github.com/plotly/plotly.py/blob/73651942b51587086da1eee53f67995f28d68ee3/packages/python/chart-studio/chart_studio/grid_objs/grid_objs.py#L82-L83):

<img width="1838" alt="Screenshot 2020-10-02 at 15 14 33" src="https://user-images.githubusercontent.com/40498978/94927267-50c22780-04c2-11eb-8f46-708814d6d864.png">

You can see [the issue in SonarCloud here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_plotly.py&issues=AXToicCUzGVPSI2IQ9Di&open=AXToicCUzGVPSI2IQ9Di).

The current code will fail with a message `KeyError: 'data_string'`. This happens because the formatted string expects a field named `data_string` but the `format` method gets instead the keyword argument `data`.

It seems to me that the code should be either:
```
return string.format(name=self.name, data_string=data_string, id=self.id)
```
or
```
string = '<name="{name}", data={data}, id={id}>'
```

In case you want to scan Plotly on SonarCloud [here is what the configuration looks like with Github actions](https://github.com/nicolas-harraudeau-sonarsource/plotly.py/commit/9835e125a6372c30093d41ee9064fcf69fd7887f) and here is [the config if you prefer to let SonarCloud scan your project by itself](https://github.com/nicolas-harraudeau-sonarsource/plotly.py_autoscan/commit/463c45f56c2b08a360b63642d8be83ce10a5231d). It is free for open source projects.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
