### ISSUE TITLE
Overwritten "gridwidth" value in "create_facet_grid"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [plotly/plotly.py#2807]
Hello,

While analyzing plotly.py on SonarCloud I saw what looks like an error in [`packages/python/plotly/plotly/figure_factory/_facet_grid.py`](https://github.com/plotly/plotly.py/blob/73651942b51587086da1eee53f67995f28d68ee3/packages/python/plotly/plotly/figure_factory/_facet_grid.py#L1185-L1188):

<img width="1883" alt="Screenshot 2020-10-02 at 16 26 38" src="https://user-images.githubusercontent.com/40498978/94934949-a8fe2700-04cc-11eb-81a3-dba408be5928.png">

You can see [the issue in SonarCloud here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_plotly.py&issues=AXToibsAzGVPSI2IQ87q&open=AXToibsAzGVPSI2IQ87q).

`fig["layout"][axis_title]["gridwidth"]` is set to `GRID_WIDTH` and then to `2` without reading the value `GRID_WIDTH` in-between. It looks like the developer intended to use a different key for one of these assignments.

In case you want to scan Plotly on SonarCloud [here is what the configuration looks like with Github actions](https://github.com/nicolas-harraudeau-sonarsource/plotly.py/commit/9835e125a6372c30093d41ee9064fcf69fd7887f) and here is [the config if you prefer to let SonarCloud scan your project by itself](https://github.com/nicolas-harraudeau-sonarsource/plotly.py_autoscan/commit/463c45f56c2b08a360b63642d8be83ce10a5231d). It is free for open source projects.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
