### ISSUE TITLE
Plotly Python Polygon Area Lambda Error

### ISSUE THREAD

**Issue by irwanOyong** [plotly/plotly.py#2815]
Hi, thanks for the hardwork.

I am trying to implement what is shown in the documentation here https://plotly.com/python/v3/polygon-area/#area-of-a-polygon
But it gives me error like this here:
`  File "<ipython-input-24-6a89c07c0508>", line 10
    return map(lambda (x, y, an): (x, y), cornersWithAngles)
                      ^
SyntaxError: invalid syntax`

The pointer is on lambda arguments parentheses, lambda **(** x, y, an ). Tried to remove the parentheses but it gives another error. Anyone has insight for the update? Thank you.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
