### ISSUE TITLE
A function or attribute to make legend sizes bigger. 

### ISSUE THREAD

**Issue by Sulstice** [plotly/plotly.py#2818]
Thanks for your interest in plotly.py!!

There doesn't seem to be a clear way of making legend lines bigger in plotly and would benefit greatly if we could have more control over how legends are produced. 

In the image I depicted below you can see the "font" increases with size but not the line that accodomates it in the legend.

![figure](https://user-images.githubusercontent.com/11812946/95507432-654d6680-097f-11eb-9fe9-78320c2f0a6d.png)

The code I have is the following

```
fig.update_layout(
    title_text="Dipole Moment X (0 V/nm)",
    title_font=dict(size=44, family='Arial'),
    template='simple_white',
    xaxis_tickformat = 'i',
    bargap=0.2, # gap between bars of adjacent location coordinates,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1,  
        font = dict(family = "Arial", size = 60),
        bordercolor="LightSteelBlue",
        borderwidth=2,
    ),
    legend_title = dict(font = dict(family = "Arial", size = 60)),
)
```

What I would need is perhaps something like `legend_size`. It seems like matplotlib supports this type of functionality but plotly does not or, if it does, it's really not easy to find in the documentation

![Screen Shot 2020-10-08 at 4 03 40 PM](https://user-images.githubusercontent.com/11812946/95507745-dbea6400-097f-11eb-99a8-03e0109572ff.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
