### ISSUE TITLE
Graph plotting weirdly in jupyter notebook but works on google colab

### ISSUE THREAD

**Issue by Tanay0510** [plotly/plotly.py#2835]
When I am trying to plot a graph using plotly, It plots the graph on jupyter notebook but not on google colab

So, I added this, so that it plots both in jupyter notebook and google colab. 

colab = fig.show(renderer="colab")

fig.show(renderer="notebook" or colab)

The problem now is, when it plots the graph in jupyter notebook, it leaves a huge chunk of blank space and then shows the graph, so basically I have to scroll down a lot to see the graph. But it plots the graph just after the above code executes on google colab. Is there any way I can fix it for jupyter notebook?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
