### ISSUE TITLE
Mapbox Density Heatmap Request for Zoom Level

### ISSUE THREAD

**Issue by b-r-you-know** [plotly/plotly.py#2837]
Hi, 

first of all thank you for adding the Density Heatmap to the default graphing library

Im running my scripts using Plotly == '4.11.0'

using this example
https://plotly.com/python/mapbox-density-heatmaps/

In my case I do not have data (example attached) from all over the globe and it would be benefitial to have the possibility to define the zoom level or the Lat / Lon boundaries. As it is already available for other Map based plots:

```python

fig = px.choropleth_mapbox(df, geojson=counties, locations='fips', color='unemp',
                           color_continuous_scale="Viridis",
                           range_color=(0, 12),
                           mapbox_style="carto-positron",
                           zoom=3, center = {"lat": 37.0902, "lon": -95.7129},
                           opacity=0.5,
                           labels={'unemp':'unemployment rate'}
                          )

```

Thanks in advance
Dominik

![GPS Activity](https://user-images.githubusercontent.com/72976123/96252878-f3929f80-0fb2-11eb-85f3-dba4d309e3c8.png)

**Comment by nicolaskruchten** [comment]
The `zoom` and `center` arguments are available with `px.density_mapbox` already... Can you elaborate on what you're missing here please? https://plotly.com/python-api-reference/generated/plotly.express.density_mapbox.html

**Comment by b-r-you-know** [comment]
I‘m using the Graph Objects 
`
import plotly.graph_objects as go `

And there I could not find these settings on the docs. Is it recommended to use Express instead of Graph Objects?

BR
Dominik

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
