### ISSUE TITLE
How to export Mesh3d object as .obj or .stl

### ISSUE THREAD

**Issue by SnehithR** [plotly/plotly.py#2841]
Hi, I am new to plotly and performing Delaunay triangulation using plotly's  Mesh3d object. Is there any method in plotly to save the Mesh3d object as an wavefront obj or stl file.

TIA.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
