### ISSUE TITLE
dragMode for px.choropleth Maps

### ISSUE THREAD

**Issue by xanderwallace85** [plotly/plotly.py#2850]
Hi there!

Do you know if it's possible to disable the drag/pan mode in the choropleth maps (from plotly.express)? I am able to disable the zoom from the config settings but I cannot manage to disable the dragging. Not even via fig.update_xaxes(fixedrange=True) :(

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
