### ISSUE TITLE
Does plotly allow for multiple lines in the xaxis labels?

### ISSUE THREAD

**Issue by anurag0511** [plotly/plotly.py#2858]
Here, I am trying to plot a bar chart and in the case there is a really long label, the plotly figure resizes itself an changes the angle of the labels. 
What I want is this:
![image](https://user-images.githubusercontent.com/9338802/97254209-44d93500-17e4-11eb-94db-a665c13ad237.png)

I can get this by adding a `<br>` in the label, however, I am unable to generate this despite adjusting the parameters like `ticklen`, `tickwidth` and setting `automargin`. The plot I am getting looks like this.
![image](https://user-images.githubusercontent.com/9338802/97254352-8ec21b00-17e4-11eb-948c-789df7fd1e78.png)

There are more solutions regarding adjustment of margin, however I am still unable to get the label in two lines. Is there any documentation that could point me towards the solution?
I have attached the snippet here.

```python
x1 = ['A very long sentence that needs broken up fhasfb asfasfz cas wfwfer wrwnflf fwerf', 'Regular Length', "Cory", "Dave"]

y1 = [20, 30, 25, 40]

fig = go.Figure()

fig.add_trace(go.Bar(x=x1, y=y1))
fig.update_layout(
	xaxis={
	'ticklen' : 4,
	'automargin': True,
	'tickwidth' : 1.2}
)
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
