### ISSUE TITLE
large file crashed and how to draw the same scale in 3d

### ISSUE THREAD

**Issue by wjj31767** [plotly/plotly.py#2860]
Hi,

I plan to use plotly to draw pointcloud file which saved with `.bin`, but seems generated html file is too large, I tried several time to open it, but it crashed every time after few seconds when I opened it. Could u do some changes, which I could use it for large file? (actually I use mayavi, which could draw large file of pointcloud easily, but it seems can't generate a file which can easily reproduce the result by just clicking the generated file)

And still have another problem, which I didn't find the solution of  how to set same scale of xyz

https://community.plotly.com/t/creating-a-3d-scatterplot-with-equal-scale-along-all-axes/15108
https://plotly.com/python/3d-axes/

`
layout = go.Layout(title = '3D Scatter plot',scene_aspectmode='manual',scene_aspectratio=dict(x=1,y=1,z=1))
`
Best regards 
Jingjian

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
