### ISSUE TITLE
documentation for `select_*`, `for_each_*` could be more DRY

### ISSUE THREAD

**Issue by nicholas-esterer** [plotly/plotly.py#2864]
There is a lot of repetition in the generated doc strings, wondering if some abstraction could be made so changes only have to take place in one place. This could be what caused #2861

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
