### ISSUE TITLE
Feature request: icicle plots (cartesian sunburst plots)

### ISSUE THREAD

**Issue by pgkirsch** [plotly/plotly.py#2878]
Hello!

I really appreciate that plotly has sunburst plots. I often find, however, that icicle plots ([see D3.js](https://observablehq.com/@d3/zoomable-icicle)) are an even better representation of hierarchical data, because they allow for easier comparisons of sector size. They also transfer better to screens/presentations/documents because they use space more efficiently.

Would it be possible to add icicle plots to plotly, either as a separate class of plot (e.g. `go.Icicle`) or with an argument to `go.Sunburst` (e.g. `go.Sunburst(..., sectororientation="cartesian")`? I imagine you could similarly make it a specific formatting of `go.Treemap` (also wonderful plots, thank you), but I think sunburst plots are a closer analog.

I suspect you could use the same syntax and interface as `go.Sunburst()` and it would just ("just") be a matter of plotting the same sectors cartesian-ally.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
