### ISSUE TITLE
plotly.graph_objects.Image not working for gray images

### ISSUE THREAD

**Issue by lherrmann-uos** [plotly/plotly.py#2885]
Hey Folks, 

I just started to use plotly and I wanted to build a range of images within a subplot. 

The images that I'm trying to display are gray-scaled (e.g. loading the image via opencv and convert the image into gray), so they don't follow the necessary 3 or 4-dimensons required by the graph_objects.Image. Hence, they are not displayed via plotly. 

But for me it is necessary, to display the images in grey. I already figured out that plotly.express is able to show the image in the required form, but this cannot be added into a trace. 

Is there any way, how I could display gray images with plotly in subplots???

Thanks for any help

**Comment by emmanuelle** [comment]
Hi @lherrmann-uos indeed the `Image` trace is for RGB data only, for single-channel images you can use the `Heatmap` trace (https://plotly.com/python/heatmaps/). We should probably add an example to the heatmap doc where a grayscale image is represented, the code could be for example
```python
from skimage import data
import plotly.graph_objects as go
img = data.camera()
fig = go.Figure(go.Heatmap(z=img, colorscale='gray'))
fig.update_yaxes(autorange='reversed', scaleanchor='x', constrain='domain')
fig.update_xaxes(constrain='domain')
fig.show()
```
You need to configure the axes so that pixels are square (the `scaleanchor` parameter), the origin of the graph correspond to the top-left corner of the image, and only the image is displayed (`constrain='domain'`). The `Image` trace already imposes these settings to the axes but not the Heatmap trace which is more general.

As a workaround you could also add channels to your grayscale image (by replicating manually the intensity array so that all channels have the same intensity, or by using `skimage.color.gray2rgb` which does the above) and the use the multichannel array in an Image trace.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
