### ISSUE TITLE
Double <extra> tag in hovertemplate causes weird behavior

### ISSUE THREAD

**Issue by schradert** [plotly/plotly.py#2904]
I originally misunderstood the <extra> tags in the hoverlabel module to be non-unique identifiers that can be appended to the beginning and end of the hovertemplate string for a special box on both sides of the label. (I guess this submission could also be a Feature Request for this functionality.)

What I then discovered after running the following minimally reproducible case is that two <extra> tags break the hoverlabel in the following ways:
1. No special boxes appear at all and the text in all <extra> tags is converted to label body text
2. The vertical margins break and text is shifted up out of the parent element
3. The manual label alignment is overridden and goes to a left-center-right alignment by displacement from the center column

```
import random
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Heatmap(
    x=[f'col {i+1}' for i in range(5)],
    y=[f'row {5-i}' for i in range(5)],
    z=[[random.randint(1, 5) for i in range(5)] for i in range(5)],
    hovertemplate='<extra>first</extra>a bunch of extra information to make the label go long<br>x: %{x}<br>y: %{y}<br>z: %{z}<extra>second</extra>',
    hoverlabel_align='left'
))
fig.show()
```
![image](https://user-images.githubusercontent.com/9901294/99160368-ed700b80-26a3-11eb-96e1-07525e6f3ce5.png)

I am using **plotly.py 4.9.0** in python 3.7.9 64-bit on a locally served Jupyter notebook with ipython 7.18.1 support displayed in VSCode on Windows 10 Pro.

Expectations:
1. An error message for adding multiple <extra> tags
2. Clear indication in the documentation that there is only one secondary box supported
2. Possible support for a secondary box on each side of the label (this is certainly beneficial in my use case, but I don't know how common this need is to be honest)

**Comment by surchs** [comment]
Hi @schradert: The <extra> tags allow you to override the default behaviour of the part of the hoverlabel where the trace name is usually displayed ([see also this section of the docs](https://plotly.com/python/hover-text-and-formatting/#customizing-hover-text-with-a-hovertemplate)). 

The reason your example looks strange is because of the order of your <extra> tags, not the number of them. You start your hovertemplate with the <extra> tag and so there is no content defined for the "regular" area of the hover info (note the small brown bar on the left of your hover info). If you move your <extra> tag to the back of the hovertemplate, you can define both regions:
```
import random
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Heatmap(
    x=[f'col {i+1}' for i in range(5)],
    y=[f'row {5-i}' for i in range(5)],
    z=[[random.randint(1, 5) for i in range(5)] for i in range(5)],
    hovertemplate='a bunch of extra information to make the label go long<br>x: %{x}<br>y: %{y}<extra>first</extra><extra><br>z: %{z}<br>second</extra>',
    hoverlabel_align='left'
))
fig.show()
```
![image](https://user-images.githubusercontent.com/1302022/99307159-20410d80-2824-11eb-8e8a-491c9a057593.png)

however, as you point out yourself, since you only have one "extra" area of the hovertemplate, more than one <extra> tag is probably unneccessary

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
