### ISSUE TITLE
Sometimes `write_image` to png exports a blank chart when render_mode="auto"

### ISSUE THREAD

**Issue by robroc** [plotly/plotly.py#2929]
Plotly 4.12.0
Python 3.8.6
Jupyter Lab 2.1.2

Sample data, about 3500 rows:

![image](https://user-images.githubusercontent.com/1219001/100001903-cf846400-2d91-11eb-9578-4bd518c627a8.png)

Code:

```
px.line(res, x = 'date', y = 'rolling_mean', color = 'sub_region_1', 
        title = 'Percent change in time spent at home', color_discrete_map = colors,
        template = 'plotly_white').write_image('canada_res.png', width=1000, height= 590)
```

Image exported:

![image](https://user-images.githubusercontent.com/1219001/100002128-22f6b200-2d92-11eb-8f44-8bdb1acf5c1f.png)

The image is exported correctly when `render_mode='svg'` is added to the `px` call.

**Comment by nicolaskruchten** [comment]
Thanks Roberto! Just to confirm, you've got Kaleido installed right? cc @jonmmease @antoinerg this seems to be a webgl-related issue.

**Comment by robroc** [comment]
I don't see kaleido among my packages, no.

**Comment by jonmmease** [comment]
Are you exporting using the `write_image` Python function, or by clicking on the camera icon in the plot?

**Comment by robroc** [comment]
It was with the `write_image` function. But funny thing, I just tried it again and couldn't reproduce the error. It's rendering fine now, even without specifying the render_mode. I honestly don't know what changed since I first encountered this error a month ago.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
