### ISSUE TITLE
Plotly figure not loading in browser

### ISSUE THREAD

**Issue by thorstenkampe** [plotly/plotly.py#2941]
(all apps latest versions)

OS: Windows 10
Vivaldi is configured as OS default browser.

The issue does not seem to be isolated - see [Plotly not loading in browser](https://community.plotly.com/t/plotly-not-loading-in-browser/39108/2) which seems to describe the exact same issue.

### Problem description
`fig.show()` does not show in Vivaldi browser: a new tab is opened but the bar chart never appears. The URL `http://127.0.0.1:5960/` (for example) is displayed in the address bar. The Python script does not terminate.

* writing html file and open automatically in Vivaldi (`fig.write_html()`): bar chart loads
Conclusion: Vivaldi is correctly configured as default browser in Windows

* using `jupyter-lab` notebook (which like `show()` opens a server on localhost and opens the default browser): works
Conclusion: Vivaldi can open `http://127.0.0.1:<abcd>/` URLs

* switching the default browser to Firefox: bar chart loads
Conclusion: Plotly bar chart generation works fine

**Comment by brainlescoder** [comment]
use this...

**import plotly.offline as iplot
import plotly as py
py.offline.init_notebook_mode(connected = True)**

it will show 
I think this will definitely solve your problem...

**Comment by thorstenkampe** [comment]
[Mpld3](https://mpld3.github.io) - which provides `show()` for Matplotlib - has the same issue with Vivaldi. Changing the `http_server` parameter from the default `HTTPServer` to `ThreadingHTTPServer` solves the issue with Matplotlib and Mpld3.

So maybe Plotly has the same threading issue?

**Comment by brainlescoder** [comment]
yeah may be...

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
