### ISSUE TITLE
mpl_to_plotly does not draw arrows

### ISSUE THREAD

**Issue by AlexandreDubray** [plotly/plotly.py#2945]
The `mpl_to_plotly` function does seems to drop the arrows (from Dash as well as in a Jupyter Notebook).
When I try to plot the correlation circle from [this post](https://stackoverflow.com/a/50098503), the arrows are not on the graph.

Minimum reproducible example
```python
fig, ax = plt.subplots()
ax.arrow(0, 0, 1, 1, head_width=0.1, head_length=0.1)
plotly_fig = mpl_to_plotly(fig)
```

Thanks for your help:-)

Alexandre

**Comment by nicolaskruchten** [comment]
The `mpl_to_plotly` function is mostly unsupported at this point, so I would expect its compatibility with more recent versions of `matplotlib` to be spotty unfortunately, as in cases like this.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
