### ISSUE TITLE
Still on Graph Obj with no attribute FigureWidget

### ISSUE THREAD

**Issue by annunal** [plotly/plotly.py#2970]
I followed the posts on the subject but they appears closed without a definite solution because the problem is still present. 

Could please someone indicate how to get rid off this error ?   A user says " I cleaned the older version of plotly and everything worked. My suggestion is to make sure that you are using plotly 4.10.0 or higher" .  Which are the steps to make what he say ?    I tried and finally I was tarped by the syste  What is the way to clean the previous version and reinstall the new one ?

And why PythonAnywhere does not automatically load the latest version of this library ? 

thanks

_Originally posted by @annunal in https://github.com/plotly/plotly.py/issues/1630#issuecomment-743978467_

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by annunal** [comment]
In the latest installations on pythonanywhere I do not have any more this error. So ai think it can be closed
