### ISSUE TITLE
Creating a stacked, grouped bar chart

### ISSUE THREAD

**Issue by soungalo** [plotly/plotly.py#2976]
Hello,
I'm having some trouble creating a bar chart which is both stacked and grouped.
Created a [SO question](https://stackoverflow.com/questions/65289591/python-plotly-stacked-grouped-bar-chart?noredirect=1#comment115427589_65289591) - can you please take a look and try to help?
Thanks!

**Comment by soungalo** [comment]
Got an answer there. I should note that the solution is a bit messy. Maybe there should be an easier, built-in option for this type of plot.

**Comment by nicolaskruchten** [comment]
We are working on adding stacked-and-grouped bars as a first-class feature in the coming months :)

**Comment by apdekker93** [comment]
Is there any news on this feature request? I'm asking this since I couldn't find anything about it in the Plotly documentation.

**Comment by nicolaskruchten** [comment]
No update, no, we're still looking for someone from the community to step up and help us implement this :)

**Comment by apdekker93** [comment]
Ah, that's a shame. Thanks for your quick response!

**Comment by ba-tno** [comment]
It seems grouping and stacking *is* possible with the plotly express `facet_col` parameter as this [stackoverflow answer](https://stackoverflow.com/a/70672499) shows.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
