### ISSUE TITLE
Statistical annotations

### ISSUE THREAD

**Issue by jakob-tu** [plotly/plotly.py#2995]
Hi,

I would like to know whether adding statistical annotations such as p-values in categorical bar graphs will be made easier in the future? Although it is possible, see https://community.plotly.com/t/scatter-plot-with-conditional-error-bars/48297/5?u=windrose it seems too complicated and way too long; there should be an easier way of doing things, I think. If you have multiple p-brackets and p-values it just takes forever with absolute/paper positioning.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
