### ISSUE TITLE
Horizontal Color Scale Legends for Parallel Categories Diagram

### ISSUE THREAD

**Issue by YukunYangNPF** [plotly/plotly.py#3000]
Hi! I want to change the color scale of a px Parallel Categories plot into horizontal. I tried the following code but with no fruit.

My last variable values have long names that will overlap with the color scale bar. Is there any way to make the legend bar horizontal for parallel categories?

```
fig.update_layout(legend=dict(
    orientation="h",
    yanchor="bottom",
    y=1.02,
    xanchor="right",
    x=1
))
```

**Comment by nicolaskruchten** [comment]
We don't have any support for horizontal colorbars at the moment, unfortunately.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
