### ISSUE TITLE
Mouse wheel zoom not work in VSCode

### ISSUE THREAD

**Issue by GF-Huang** [plotly/plotly.py#3009]
The mouse wheel scroll the whole page rather than zoom the graph.

![9pwM2M8zLP](https://user-images.githubusercontent.com/4510984/103955961-78402480-5182-11eb-86d5-9ef045928d11.gif)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
