### ISSUE TITLE
Incorrect py.plot() / py.iplot() kwargs don't throw error

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.py#301]
Specifically sharing='...' 
(Ie if you type privacy='...' or something else)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
