### ISSUE TITLE
Is there a way to widen spaces between candlesticks?

### ISSUE THREAD

**Issue by breadum** [plotly/plotly.py#3015]
Hello,

I was looking for a way to adjust spaces between candlesticks.

I've tried searching a lot but there was no option like 'bargap' in bar chart.

What I want to do is make candlestick chart sparse so that,

eventually I can put some trade records with triangles on the left side of corresponding candle.

But for now it is quite overlapping each other no matter how I put markers in-between candles by adjusting time.

Is there a clear way or any work-around?

Thank you.

Below is my code with Plotly v4.14.1

```python
import plotly.graph_objects as go

# Candlestick chart
candle = go.Candlestick(
        x=df.index,
        open=df['Open'],
        high=df['High'],
        low=df['Low'],
        close=df['Close'],

        increasing=go.candlestick.Increasing(
            line=dict(width=1),
            fillcolor='red',
            line_color='red'
        ),
        decreasing=go.candlestick.Decreasing(
            line=dict(width=1),
            fillcolor='blue', 
            line_color='blue'
        )
)

# Buy, Sell markers
markers = list()
for executions in [long, short]:
        markers.append(
            go.Scatter(
                mode="markers", 
                x=executions['time''], 
                y=executions['price'], 
                marker_symbol=8,  # triangle
                marker_line_color='white',
                marker_color=color,
                marker_line_width=0.5, 
                marker_size=6,
            )
        )

# Draw
fig = go.Figure(data=[candle, *markers])
fig.show()
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
