### ISSUE TITLE
FEATURE: Expose relative width or height of a graph component (where possible)

### ISSUE THREAD

**Issue by andreamoro** [plotly/plotly.py#3017]
An implementation request which I couldn't satisfy lead me here in the hope this can become a feature to be added in the pipeline anytime soon.

GIVEN a graph
GIVEN any number of componenents
RETURN a dictionary or an array with the width/size/height of each component

Example:
- In a pie chart, this could be the % of each slice
- In a stacked bar chart (the case I was trying to figure out) this could be the total height of each stack, and eventually the one of each of the items

**Comment by nicolaskruchten** [comment]
Interesting! Could you provide an example of what you'd see the API for this looking like?

**Comment by andreamoro** [comment]
Hi @nicolaskruchten 

I would probably introduce two entry points:
- a get method called get_xxxx_items_size (where xxxx is the name of the invoked graph).
-- for a line, it would be a get_line_items_size(absolute=True). 
-- for a bar, it would be a get_bar_items_size(absolute=True) 

     So just one parameter, which when false it will return the relative value respect the main metric.

- Implement a list within the methods that already return the whole list of properties of a given graph. Apologies not to be clear here, but I literally started looking at plotly the other day and I'm not familiar yet.

The results can be something like:
- Area chart with 8 items, a list [item_name: item_width_value, .... ] the value is in percentage or absolute
- bar chart, a dictionary like [item_name: item_height_value, .... ]  /* if horizontal, doesn't really make any difference, still an height it is
- stacked bar char, a list as follow [[item_name, items_in_the_set, item_total_height, [{sub_item_name_1: sub_item_width, ....}]]]

Hope it makes sense.

**Comment by nicolaskruchten** [comment]
OK, thanks! So given this data in this format, what would you then want to do with it? Could you give me an example and how you might go about using these return values in a hypothetical Python program?

**Comment by andreamoro** [comment]
In my specific circumstance I was (in fact I still am) after finding the total height of a stacked bar chart, so to have the annotation written on top. 
The best I could achieve so far is a label at the very bottom, which is not pleasant to be seen.

But a quick example given my needs would be (for barstack):

```
fig = px.bar(data, ...)
labels = [.....] # Labels is expected to be a collection of the same size
total_labels = [dict(x=item, text=str(label[index])), showarrow=False, font=dict(color="black", size=10), ypos=height) 
                for index, item, height in enumerate(fig. get_bar_items_size())]
fig.update_layout(yaxis={'visible': False}, annotations=total_labels)
```

So basically, iterating through the collection, knowing what my figure has rendered, I can then annotate the graph properly showing some labels.

Other uses can be possible, but that's what lead me here.

**Comment by nicolaskruchten** [comment]
Got it. For the specific case of labelling bar stacks, this is still an open issue which we intend to resolve at some point :) As a workaround, though, you should be able to compute the height of each stack in Python in data coordinates pretty easily and then position an annotation using `xref='x'` and `yref='y'` and so bypass any need for the rendering engine to tell you where things are, no?

Implementing a general solution to this sort of thing is pretty challenging because the underlying rendering engine which actually knows about all the layout-related factors is written in Javascript, and doesn't really communicate any of this information back to the Python layer. The only mechanism we have for looking at the output of the renderer is documented here https://plotly.com/python/figure-introspection/ and I don't see any way of extending this mechanism to get you the information you're looking for...

**Comment by andreamoro** [comment]
I understand. In fact, it's great to understand there's another way to get all the stacks element, but u was not necessarily able to see each of the stack height exposed?

What's the method returning the array/dictionary?
Yesterday night I can't across a collection I believe it was the one with the stacks, but couldn't really see anything useful.

**Comment by nicolaskruchten** [comment]
Oh well for a bar chart you can just sum up the Y-values that have the same X-value and get the height in data coordinates... that's all that stacking does, right? Like in this case below, I know from the data that the bar at `Q` has a height of `2+1`, and I can position an annotation there exactly:

```python
import plotly.express as px

fig = px.bar(dict(a=["Q", "R", "S"], b=[2,3,4], c=[1,2,3]), x="a", y=["b","c"])
fig.add_annotation(text="hi Q", showarrow=False, xref="x", yref="y", x="Q", y=2+1, yanchor="bottom")
fig.show()
```

![image](https://user-images.githubusercontent.com/203523/104377683-dbb8b200-54f4-11eb-9b65-a3ccc662a321.png)

**Comment by andreamoro** [comment]
Thanks for the nuggets on how it works @nicolaskruchten 

I've tried as per your suggestion, and while I get the label positioned where I want now, unfortunately the bars completely disappear.

See below:

```
total_labels = [dict(x=col, text=str(pc), showarrow=False, font=dict(color="black", size=10), yref="y", y=pc, yanchor="top") 
                for col, pc in data[['ColorID', 'ProductsCount']].groupby(['ColorID']).sum().reset_index().values.tolist()]
fig.update_layout(yaxis={'visible': False}, showlegend=False, annotations=total_labels)
```

![image](https://user-images.githubusercontent.com/5256583/104434860-09046f00-558c-11eb-964c-5051378884b3.png)

whereas without setting the `y` argument everything is fine.

![image](https://user-images.githubusercontent.com/5256583/104435185-5ed91700-558c-11eb-9ac0-3b9d454bc936.png)

Any idea what's wrong? 
(Sorry if we have now diverted this feature request into something different).

**Comment by andreamoro** [comment]
Ignore me ... I just realised I was passing the wrong feature.
Thanks for your help.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
