### ISSUE TITLE
px.timeline() setting text to end column displays duration 

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#3019]
Broken off of https://github.com/plotly/plotly.py/issues/2934... Here the text will be the computed delta value because PX rewrites the data frame and reuses the column name `Finish` for `x`:

```python
import plotly.express as px
import pandas as pd

df = pd.DataFrame([
    dict(Task="Job A", Start='2009-01-01', Finish='2009-02-28', Resource="Alex"),
    dict(Task="Job B", Start='2009-03-05', Finish='2009-04-15', Resource="Alex"),
    dict(Task="Job C", Start='2009-02-20', Finish='2009-05-30', Resource="Max")
])
fig = px.timeline(df, x_start="Start", x_end="Finish", y="Task", text="Finish")
fig.update_yaxes(autorange="reversed")
fig.show()
```

The current unfortunate workaround is to set `text=df["Finish"]+""` which causes a separate column to be created in the internal data frame.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
