### ISSUE TITLE
ModuleNotFoundError: No module named '_plotly_utils'

### ISSUE THREAD

**Issue by nemar3** [plotly/plotly.py#3032]
hi

I am using windows 10

I did pip install plotly==4.14.3

now I get this error, and even the IDE doesn't start :

Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "D:\Anaconda3\envs\go38\Lib\site-packages\plotly\io\__init__.py", line 1, in <module>
ModuleNotFoundError: No module named '_plotly_utils'

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
