### ISSUE TITLE
No plot from Scatter3d if values are almost the same

### ISSUE THREAD

**Issue by amicitas** [plotly/plotly.py#3037]
I have run into an issue where no points are displayed If I plot a set of data where the values for one of the coordinates are ___almost___, but not _exactly_, the same. If the values are _exactly_ the same, this problem does not occur. This only happens if one or more numbers differ by less than `1e-8` (strict less than: `9.999...e-9` does not work, `1e-8 does`) . 

If axis ranges are not given, then no plot will show up at all. If axis ranges are given explicitly in the layout, then the plot will display with axes, but no data will be plotted. If any one number is different by equal to or more than `1e-8` (_exactly_), then the data plots normally. Behavior is the same for `x`, `y` and `z` coordinates. 

Minimal example:

```
import numpy as np
import plotly.graph_objects as go

num = 100
x = np.random.uniform(-1, 1, num)
y = np.random.uniform(-1, 1, num)
z = np.ones(num)

# Error will only occur if this line is present. If this number is >= 1e-8 the problem is resolved.
z[0] += 9.999e-9

fig = go.Figure()
data = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    )
fig.add_trace(data)
fig.show()
```

Version Tested:
- Plotly 4.14.3 (6c463ee500960000341cc735b2d95680ac48e3ad)
- Python 3.8.7
- Jupyter 6.1.5

Other versions that also have this issue:
- Plotly 4.10.0

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
