### ISSUE TITLE
go.Treemap returns blank file.

### ISSUE THREAD

**Issue by keonho-kim** [plotly/plotly.py#3044]
Hi,

I'm working with px.Treemap and go.Treemap.

px.Treemap works perfectly, but due to structrual issue, Now I want to try go.Treemap.

Now I have a dataset,

![image](https://user-images.githubusercontent.com/70115629/105618714-8748e880-5db8-11eb-9bef-ce346adb2353.png)

(Sorry for Korean, Name column is name of each company, and the parent is each companies' upper industry sector.) 

Based on this, I tried,

![image](https://user-images.githubusercontent.com/70115629/105618734-b8291d80-5db8-11eb-9be6-c6ec27a3ae15.png)

![image](https://user-images.githubusercontent.com/70115629/105618736-bc553b00-5db8-11eb-9e3c-5bfaa9cb5660.png)

However, both of codes returns blank figure, literally.

![image](https://user-images.githubusercontent.com/70115629/105618762-f1fa2400-5db8-11eb-93dc-442b1b16d10d.png)

What is problem? 
I don't think the language is not the problem as px.treemap gave me a nice work (but still with minor issues)

I also checked data states,

![image](https://user-images.githubusercontent.com/70115629/105619579-f414b080-5dc1-11eb-9f50-09888aada1b0.png)

It looks fine.

-- 

Additionally, I've tested other possibilities

![image](https://user-images.githubusercontent.com/70115629/105619291-f0cbf580-5dbe-11eb-8c10-856cb1773af8.png)

![image](https://user-images.githubusercontent.com/70115629/105619555-c0398b00-5dc1-11eb-814a-81be5485704c.png)

Problem remains :(

(I've also tested on Colab)

Thank you!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
