### ISSUE TITLE
How to plot a graph in HTML that is saved as JSON file using plotly.io.write_json

### ISSUE THREAD

**Issue by thomasjv799** [plotly/plotly.py#3056]
I am trying to plot a graph in html that i saved using plotly.io.write_json. I do not need to give trace or any layout or anything as my json file has all the requirements. I just need to visualize it directly in html by just giving the file location that i have saved in local disk.

**Comment by Alexboiboi** [comment]
Hi @wanderer799,

check here:

https://github.com/plotly/jupyterlab-chart-editor

 in the readme file, it is described how to do that ;)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
