### ISSUE TITLE
can not open example website with http://127.0.0.1:5050/

### ISSUE THREAD

**Issue by XFrankly** [plotly/plotly.py#3058]
hi, i am new one with plotly, and i am trying to understand the example code with port 5050 

when i  use the url localhost:5050, it was work normal, but when we use url 127..0.0.1:5050 , it can not be normal at chrome and edge.

if we need to access the example website by ip address like 127.0.0.1, how to do that?

attach is source when the website 
[source_127.0.0.1_5050.html.zip](https://github.com/plotly/plotly.py/files/5908398/source_127.0.0.1_5050.html.zip)
[source_localhost_5050.zip](https://github.com/plotly/plotly.py/files/5908399/source_localhost_5050.zip)

thanks.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
