### ISSUE TITLE
Character & breaking row height

### ISSUE THREAD

**Issue by gmsantos3** [plotly/plotly.py#3067]
fig = go.Figure(data=[go.Table(columnorder=[1, 2, 3, 4, 5, 6], columnwidth=[200, 100, 100, 100, 100, 100],
                               header=dict(values=['Company', 'Shares #', 'Invested', 'Value', 'PnL', '% PnL'],
                                           line_color='darkslategray',
                                           fill_color='#646464',
                                           font_color='#dcdcdc',
                                           align='left',
                                           font_size=13,
                                           ),
                               cells=dict(values=[names, shares, invested2, value2, pnl, percent_pnl],
                                          line_color='darkslategray',
                                          fill_color='#606060',
                                          font_color='#dcdcdc',
                                          align=['center']
                                          ))
                      ])

Some of the names of the companies have the character & on them, and that breaks the row height for some reason.

Screenshots show with default height, and then with height=40.
![Screenshot 2021-02-07 162313](https://user-images.githubusercontent.com/71523736/107152656-f732a380-6960-11eb-8c8e-e7a44f4ad022.png)
![Screenshot 2021-02-07 162347](https://user-images.githubusercontent.com/71523736/107152658-f7cb3a00-6960-11eb-8e9a-70e883e1e45a.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
