### ISSUE TITLE
px.imshow, facet_col_spacing, facet_row_spacing have no effect

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#3069]
It seems that there exist some hidden settings that make `facet_color_spacing` and `facet_row_spacing` ineffective. I successively reduced their values, but the horizontal and vertical spacing between facets is unchanged: [https://chart-studio.plotly.com/~empet/15879](https://chart-studio.plotly.com/~empet/15879).

**Comment by nicolaskruchten** [comment]
There seem to be a couple of things happening here, neither indicative of a problem with row-spacing and col-spacing IMO:

1. `imshow` will force the pixel aspect ratio to square by compressing one of the dimensions, so in this case the row spacing is near zero but there is extra spacing between the images
2.  the images appear to have a light-colored border around them (confirmed by looking at https://raw.githubusercontent.com/empet/Datasets/master/Gnomonic-Projs/i10.png)

You should be able to see these spacings in action if you increase them rather than decrease them?

**Comment by empet** [comment]
Thank you @nicolaskruchten ! Initially I saved all 20 images with the default `layout.margin`. Restricting all four margins to 5 pixels  I succeedded to  control the spacing.
