### ISSUE TITLE
Feature: legendgroup property should accept array to have multiple groups.

### ISSUE THREAD

**Issue by ievgennaida** [plotly/plotly.py#3076]
I would like to have legends grouped by a few criteria, ex: age, and gender.
Now it's possible to add a subgroups legend only by adding fake traces:

(comes from some plotly documentation)
```
fig.add_trace(go.Scatter(y=[None], mode='markers',
                         marker=dict(symbol='circle', color='black'),
                         name='Female',
                         ))
```

Only the gap that grouping is not working when legend is clicked from the frontend.
It would be possible to make it happened if the legendgroup property for each trace will accept an array. 
In this case, it will be possible to still keep it clickable and resolve traces visibility. 

Some related topics:
https://plotly.com/python/reference/#scatter-legendgroup
https://community.plotly.com/t/possible-to-have-nested-or-hierarchical-legends/2376/3
https://community.plotly.com/t/plotly-express-how-to-separate-symbol-and-color-in-legend/38950

**Comment by nicolaskruchten** [comment]
Per-attribute legends are definitely something we want to support, although doing it via `legendgroup` is probably not the API we will end up with. Support for this will have to be added to Plotly.js first, and here is the issue tracking this: https://github.com/plotly/plotly.js/issues/5099 ... right now there's no one working on it for lack of funding :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by ievgennaida** [comment]
For a people who are searching for the workaround: You can add traces in the specific order and also revert/control legends order .
