### ISSUE TITLE
Heatmap documentation: Different z-inputs

### ISSUE THREAD

**Issue by ndrezn** [plotly/plotly.py#3090]
In the documentation for heatmaps, all of the examples using `go.Heatmap` pass as input a 2-dimensional array. This may lead people to believe (myself included!) that the z-input must be reshaped into a 2D matrix in order to use the heatmap.

Luckily, this isn't true! `go.Heatmap` will happily accept `x`, `y`, and `z` inputs all as 1-dimensional arrays of the same length and will handle the rest on its own. It works fabulously. It would be great to see this functionality demonstrated on the docs so users don't go through the trouble of trying to reshape their data when that is fundamentally unnecessary.

Direct link to the documentation page in question: https://github.com/plotly/plotly.py/blob/doc-prod/doc/python/heatmaps.md

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
