### ISSUE TITLE
Issues in Gantt chart

### ISSUE THREAD

**Issue by saksham7778** [plotly/plotly.py#3092]
1) Can we put text instead of hower inside rectangular boxes of Gantt charts ?
2) Can we mark vertical lines on x axis so that we can see time stamps at both lines and the difference in time between those lines (something similar to :-> fig1.update_layout(hovermode="closest")  but to get two lines to get ht etime difference between these lines. 

If possible please suggest how can I implement this?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
