### ISSUE TITLE
Feature Request: Searchable plotly dropdown 

### ISSUE THREAD

**Issue by ryangdar** [plotly/plotly.py#3095]
Hi Plotly, 

I think it would be nice to have a searchable dropdown feature similar to how GitHub works when I'm trying to filter the issues by author, label, etc... Dropdowns can be quite annoying when there's hundreds of options to scroll from. A search bar would greatly improve the current dropdown architecture

**Comment by nicolaskruchten** [comment]
When you say "dropdown" are you referring to the Dash component or the dropdowns in `layout.buttons` inside a Plotly figure?

**Comment by ryangdar** [comment]
I'm referring to the layout.buttons inside a Plotly figure

**Comment by nicolaskruchten** [comment]
Gotcha. In general we're not putting a lot of energy into the in-figure controls like buttons, and sliders, and generally recommending that folks use Dash for this kind of thing. Dash isn't a perfect replacement because it does require a server, but it's much more powerful, and a better long-term plan for most applications.
