### ISSUE TITLE
Reversing colorscale in figure_factory.create_ternary_contour and removing lines from heatmap

### ISSUE THREAD

**Issue by mina-shahrooz** [plotly/plotly.py#3096]
I want to modify my ternary heatmap with figure_factory.create_ternary_contour and reverse the colorscale. I am using `Hot `colorscale, but I cannot reverse it to represent highest values with red color. Besides, I want to remove the contour lines from the heat map. As far as I have tried and searched, it was not possible. I'd be grateful if someone could help me.
`Hot_r` is not recognized to reverse the order.

Thanks.

```
import plotly.figure_factory as ff

fig = ff.create_ternary_contour(x1, x2, x3, T, showscale=True, colorscale='Hot')
```

![Capture](https://user-images.githubusercontent.com/46826765/109650056-fc989d80-7b5c-11eb-9698-bf53da17fbc2.PNG)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
