### ISSUE TITLE
How to edit the text alignment of ff table cells

### ISSUE THREAD

**Issue by bemac-honda** [plotly/plotly.py#3103]
Is there a way to edit the text alignment in the plotly.figure_factory table??

I created a table by ff.create_table(). I'd like to edit the cell text alignment from default 'left' to 'center'.

**Comment by sidhantagar** [comment]
Try using table.update_annotations(xanchor = 'center')

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
