### ISSUE TITLE
Please improve Plotly refrence documentation for Python APIs by including additional information/examples

### ISSUE THREAD

**Issue by MuqadderIqbal** [plotly/plotly.py#3107]
Plotly python APIs are highly feature-rich and with the depth of customization that are supported via various attributes, it becomes difficult to find out exactly what a certain property or attribute is going to do. The official documentation feels very minimalistic and the explanations of some of the class attributes are very vague.

For example: The description for Custom Data attribute of [Table trace] (https://plotly.com/python/reference/table/#table-customdata) reads "Assigns extra data each datum". What extra data is it referring to? How is it intended to be used? What are the possible/acceptable values? And how will a certain type of value reflect in the final table rendered? 

I'm witnessing this pattern across the board and I personally feel the reference documentation will immensely benefit from a slightly more descriptive and specific information being made available. Code snippets and examples (even one-liners) will also be highly valuable.

**Comment by nicolaskruchten** [comment]
Definitely! We'd love some help :)

**Comment by MuqadderIqbal** [comment]
@nicolaskruchten thanks for the acknowledgement of this suggestion. Just out of curiosity, I did a `fig.update_traces` to see if there was any mention of either the "table" trace or the "custom data" attributes in the doc string. I couldn't locate a reference. So, I'm curious where does one start looking in the absence of the documentation this issue is referring to? 

I'm by no means binding myself into a commitment I have no idea how to fulfill :), but it'll be good to at least know how people who are aware of these things do it.

**Comment by nicolaskruchten** [comment]
There are a bunch of different things going on here...

1. There are at least hundreds, possibly thousands (haven't counted recently!) of attributes between all the trace types, axis types and various parts of the layout object, and some of these attributes are shared between trace type (i.e. `customdata` is a valid attribute for all or most trace types)
2. The reference page you linked to is indeed just a reference for all the attributes, and we generally have "example style" docs in pages like https://plotly.com/python/table/. We don't have great links back and forth between these pages today.
3. We are very, very far from having one example per attribute, mostly because there are so many attributes! 
4. `update_traces()` is a generic function that can operate on traces of any type, not just table, so its docstring doesn't contain a full reference of all attributes (otherwise it would be enormous). That said, something like help(go.Table()) will give you a full docstring. Note that this docstring is auto-generated from the same set of strings as the contents of https://plotly.com/python/reference/table/.
5. `customdata` is a funny attribute in particular because its purpose is very generic and doesn't by default lead to any visual difference in the output: it's an attribute that developers can use to store arbitrary custom data, inside the JSON representation of a figure. One of the only user-visible ways of using `customdata` is coupled with the `hovertemplate` attribute as documented here https://plotly.com/python/hover-text-and-formatting/#adding-other-data-to-the-hover-with-customdata-and-a-hovertemplate ... this example isn't specific to `table` traces, but it applies to most trace types.
6. The ultimate source for the strings that are used to generate the reference docs and docstrings is within the code of Plotly.js, usually in files called `attributes.js`. `customdata` is not `table`-specific so you won't find it in something like [`src/traces/table`](https://github.com/plotly/plotly.js/blob/master/src/traces/table/attributes.js) but rather in [`src/plots/`](https://github.com/plotly/plotly.js/blob/master/src/plots/attributes.js) which is where we store generic cross-trace code.
7. The `table` trace-type is one that doesn't seem to get used all that often, because/so its docs aren't particularly well-developed.

Our docs will most likely always be a work-in-progress, and we're a very small core team, so this progress tends to be fairly slow unless outside folks help out. The easiest way to help is to contribute example docs to pages like https://plotly.com/python/table/ and our contributing guide is here https://github.com/plotly/plotly.py/blob/master/contributing.md

If you're interested in deeper contributions such as improving the attribute strings, then your contributions would be welcome in the Plotly.js repo, and if you want to tackle stuff like better cross-links between the reference and example pages, then you'll need to dive into the pipeline that we use to generate the reference page HTML from the Plotly.js source repo. This code is is https://github.com/plotly/graphing-library-docs.

**Comment by kdpenner** [comment]
+1000 to this issue.

I've been making a Scattermapbox animation and if it weren't for one person---hard to tell if they're a user or employed by plotly---that is, a single point of failure, my task would be 1000x more difficult that it should be.

To walk you through some of my frustrations:
1. I started at the Intro to Animations example. I need to use the graph objects API and saw that there is a `Frame` class. So I go to the API docs:
https://plotly.com/python-api-reference/plotly.graph_objects.html
linked from the main page:
https://plotly.com/python-api-reference/index.html
and no `Frame` class is listed! Because it turns out that `Frame` is documented here:
https://plotly.com/python-api-reference/generated/plotly.graph_objects.html#plotly.graph_objects.Frame
The difference in the URLs is `/generated/`. And I can't search for Frame on the main page because search is broken.
2. Next I want to add a button. The Visualizing MRI Slices example has a button:
```python3
                "buttons": [
                    {
                        "args": [None, frame_args(50)],
                        "label": "&#9654;", # play symbol
                        "method": "animate",
                    },
                    {
                        "args": [[None], frame_args(0)],
                        "label": "&#9724;", # pause symbol
                        "method": "animate",
                    },
                ],
```
where `frame_args` outputs a dictionary:
```python3
    return {
            "frame": {"duration": duration},
            "mode": "immediate",
            "fromcurrent": True,
            "transition": {"duration": duration, "easing": "linear"},
        }
```
and I have to cross reference the Intro example and docs to find out that `args`:

> Sets the arguments values to be passed to the Plotly method set in method on click.

but I can find no documentation on the `animate` method and thus no documentation on what its arguments are. The Intro page has a bulleted list of arg types under "Defining Button Arguments", but in the excerpt above the arguments are a mix of `None` and `dict`, and so the bulleted list makes no sense:

> None: Setting "args" to undefined (i.e. "args": [None]) will create a simple play button that will animate all frames.
> [{data: [], layout: {}, traces: []}, {...}]: Nearly identical to animating named frames; though this variant lets you inline data instead of adding it as named frames. This can be useful for interaction where it's undesirable to add and manage named frames for ephemeral changes.

Note that the dict output by `frame_args` doesn't have any of the keys in the dict in the bulleted list! So `args` accepted by `animate` doesn't at all conform to the docs.

3. See the `duration` above? Nowhere in the python docs is it specified that `duration` has units of milliseconds; I had to look at docstrings in the javascript code to find it out.

I understand the difficulty of documenting hundreds of attributes, but even ones used in the examples aren't documented, usage patterns similarly so.

**Comment by empet** [comment]
@kdpenner 
Meanwhile you can search the Plotly forum, [https://community.plotly.com/c/graphing-libraries/python/10](https://community.plotly.com/c/graphing-libraries/python/10), for animations,  to find answers to your  questions.

**Comment by kdpenner** [comment]
@empet I didn't ping you above but you're the single point of failure

**Comment by empet** [comment]
@kdpenner   This is my code for MRI scan animation [https://nbviewer.org/github/empet/Animating-MRI-scans/blob/master/scanning-the-head-classic.ipynb](https://nbviewer.org/github/empet/Animating-MRI-scans/blob/master/scanning-the-head-classic.ipynb). What you read on Plotly tutorials was written by someone else.

**Comment by kdpenner** [comment]
I meant single point of failure broadly. Every obstacle I've googled---many more than I mention here---has led to one of your posts on the community forum.

**Comment by nicolaskruchten** [comment]
Indeed, many of the gaps in our documentation are "filled" by enthusiastic folks in our forum (e.g. @empet) or Stack Overflow (e.g. `vestland`). Clearly some community members are able to use our existing docs to help others in this way, and the core process bottleneck we have is "upstreaming" some of this content/para-documentation into the official docs. We do what we can, and we'd appreciate any help anyone can provide, either with more forum posts, or pull requests into our docs. See [our contributing guide](https://github.com/plotly/plotly.py/blob/master/contributing.md) for more info on how to do that but TL;DR you can just click on "suggest an edit" on the top right of any page at plotly.com/python to easily open a PR.

**Comment by kdpenner** [comment]
I understand how daunting the task is, but asking users inexperienced with plotly (e.g. myself) to contribute documentation PRs is a dodge. To take the button example above, I still don't understand the usage pattern for `args` (`[None, {...}]`) because I can't find documentation on `animate`. I suspect I'd have to navigate and read the Javascript code, but I don't know Javascript.

**Comment by nicolaskruchten** [comment]
I understand your frustration, but this is a free library maintained by a very small team (I'm an unpaid volunteer now) so it's a bit of a "take what you can get" situation :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
