### ISSUE TITLE
Feature request: multiindex heatmap

### ISSUE THREAD

**Issue by noob-procrastinator** [plotly/plotly.py#3110]
I would like the possibility of generating a multiindex heatmap with multiple levels :
![image](https://user-images.githubusercontent.com/22256302/110836390-45103380-82a0-11eb-845a-2d95d1e55c79.png)

The input should be either a mutliindex dataframe, or a single index dataframe. 
Ex: px.imshow(multiindexdf, x_levels=["Country"], y_levels=["Occupation",Sex"], z="Z")

Currently I am using a dash datatable placed close to a subplot of heatmaps to fake it.

**Comment by JohannesWiesner** [comment]
Would be nice if this would be implemented. Posted a [StackOverflow](https://stackoverflow.com/questions/71926260/creating-grouped-heatmaps-with-fixed-cell-width-in-plotly/71934519?noredirect=1#comment127115532_71934519) post a couple of days ago which points to the same problem.

**Comment by mmore500** [comment]
Pandas' `Styler` feature may be of interest to you as a workable alternative in some circumstances. See [here](https://stackoverflow.com/a/50605020/17332200) and [here](https://stackoverflow.com/a/64234715/17332200).

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
