### ISSUE TITLE
Single-toggle of grouped traces in legend

### ISSUE THREAD

**Issue by elvis1020** [plotly/plotly.py#3116]
@mojoaxel started this issue on plotly.js https://github.com/plotly/plotly.js/issues/3135
and @mcstarioni described a desired behavior that suits perfectly for the problem.
In summary, It would be very useful that legendgroups have a separate handle to toggle the whole group and still be able to toggle the traces separately by specifying showlegend=True.
This issue was opened almost an year ago on plotly.js, any plans for a feature like this?

**Comment by nicolaskruchten** [comment]
That feature isn't being worked on by anyone as far as I know, but we'd happily accept a pull request :)

**Comment by rithwikjc** [comment]
@nicolaskruchten I am a noob, but this maybe something that I could perhaps accomplish, given enough time. Can you or someone please point me to the relevant code blocks for legendgroups, toggling traces via legends. This would help me get started. You maybe busy, so otherwise, I'll try to find it myself.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by Mo-Gul** [comment]
For the record:  
When I see it correctly, this feature was already implemented, see https://github.com/plotly/plotly.py/blob/ff43e4a07ead67c55acb62e979ad314fe2a3d49a/CHANGELOG.md?plain=1#L395
