### ISSUE TITLE
[Python] No documentation available for plotly.graph_objects.Scatter

### ISSUE THREAD

**Issue by RansSelected** [plotly/plotly.py#3118]
Hi!

Trying to get docs in python for plotly.graph_objects.Scatter - no docs found...

![image](https://user-images.githubusercontent.com/43318715/111783892-00e1ec00-88bb-11eb-8c1e-e2af84e2ede4.png)

For instance, the docs are available on the website - https://plotly.com/python-api-reference/generated/plotly.graph_objects.Scatter.html

**Comment by MHRiday** [comment]
@RansSelected You can use 'help()'
Example :
""" 
import plotly.graph_objs as go
help(go.scatter)

"""

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
