### ISSUE TITLE
The file "debug.log" is created when calling plotly.offline.plot

### ISSUE THREAD

**Issue by shipherd** [plotly/plotly.py#3121]
Hi, I am using plotly.offline.plot to plot my graph, and sometimes "debug.log" is created under my script folder.

The content of "debug.log" is simple, which contains only the ERROR:
`
[0322/111405.791:ERROR:registration_protocol_win.cc(130)] TransactNamedPipe: The pipe has been ended. (0x6D)
`

Not sure if it is the problem of code or the library itself. Anyway, my graph is plotted properly and it is shown in the Chrome Browser properly.

Is there a way to disable the output of this file?

Thank you.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
