### ISSUE TITLE
go.Box should be able to take a list of colors

### ISSUE THREAD

**Issue by tobemo** [plotly/plotly.py#3124]
Hi!

graph_objects.Box currently only accepts a single value for colors.
For example `go.Bar(.., marker_color=['red', 'green', 'red'], ..)` doesn't work, it only accepts a single string.
Passing a list of colors already works in go.Bar but for some reason not in go.Box.

My situation is that I already have a dataframe with as rows some descriptive statistics + a color. I pass these to go.Box using the q1, q3, median, etc attributes and I would like to be able just pass the column of colors to marker_color.  So something like:
`go.Box(x=df.index, q1=df.Q1, median=df.Median, q3=df.Q3, lowerfence=df.Min, upperfence=df.Max, marker_color=df.Color)`
Currently I resolve this using pandas' iterrows to loop through each row and add each box as a separate trace.

Thanks in advance,
T

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
