### ISSUE TITLE
Specify `kaleido` as an optional requirement

### ISSUE THREAD

**Issue by tmarice** [plotly/plotly.py#3126]
Kaleido is an optional requirement for Plotly's static image export functionality, but currently there's no way to specify this dependency relationship. E.g. we're using `pip-tools` and even though `kaleido` isn't our project's direct dependency, we still have to specify it in the `requirements.in` file:
```
plotly==4.14.3
kaleido==0.1.0  # Plotly's dependency for static image export
```

Is it possible to add Kaleido to setuptools `extras_require` section, in order to be able to write something like `pip install plotly[kaleido]`?

**Comment by nicolaskruchten** [comment]
@jonmmease thoughts?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
