### ISSUE TITLE
Add a stretch to the corners on the polar plot

### ISSUE THREAD

**Issue by rakhmaevao** [plotly/plotly.py#3127]
I love the polar charts in plotly.

I like the way the graph can be scaled along the R axis. But I sometimes want to take a closer look at the site presented below.

![image](https://user-images.githubusercontent.com/33318971/112972841-5e96f380-9159-11eb-8078-3600778824d2.png)
There is a gap in the picture that is very difficult to see.

But the raft has no corner stretch function.

I would like to do a full zoom.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
