### ISSUE TITLE
Sankey diagram: Target not properly generated

### ISSUE THREAD

**Issue by swaticolab** [plotly/plotly.py#3130]
Hello,
I am trying to plot a Sankey diagram for the below data:

```
data = go.Sankey(link = link, node=node,node_pad=20)
print(data)

```
Sankey({
    'link': {'source': [97, 97, 97, 97, 97, 97, 97], 'target': [2, 1, 0, 4, 5, 6, 7], 'value': [2, 7, 6, 4, 1, 5, 3]},
    'node': {'label': [2, 1, 0, 4, 5, 6, 7], 'pad': 50, 'thickness': 2}
})
```


# plot
print(data)
fig = go.Figure(data)
fig.show()
```

1. But the plot that I get does not have the values properly **aligned**. For eg. according to the data, label=0 has the second  highest value. But the plot shows the second highest label as "2".
2. Also, I get one of the target nodes as "**undefined**"(Represented in black color).

Attached is the plot.
![newplot (2)](https://user-images.githubusercontent.com/49306345/113132237-cfaed780-923b-11eb-9087-19059714eb2b.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
