### ISSUE TITLE
nan/inf values are not displayed correctly in hovertool

### ISSUE THREAD

**Issue by j-carson** [plotly/plotly.py#3133]
When a database query can return null, or a calculation results in nan or inf, the hovertool displays `%{customdata[i]}` rather than the value. 

I am currently working around this by casting the data to a string, but this is rather clumsy since now you can't do numbery things like setting the number of decimal places in your format string.

The following minimal example was written in a jupyter notebook, but I see the same behavior on my dash dashboard.

```python
import pandas as pd
import numpy as np

from plotly import graph_objects as go
from plotly import express as px
from plotly import io as pio

from IPython.display import display,HTML

x = pd.Series(name="x", data=[2,3,4])
y = pd.Series(name="y", data=[2,3,4])
bad = pd.Series(name="bad", data=[None, np.nan, np.inf]) # the one with the problem
bad2 = pd.Series(name="bad2", data=bad.astype(str)) # my hacky work-around
df = pd.concat([x,y,bad,bad2], axis=1)

fig = px.scatter(
     data_frame=df,
     x="x",
     y="y",
     hover_data=["bad", "bad2"]
)
display(HTML(fig.to_html()))
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
