### ISSUE TITLE
Feature Request: Ribbon Chart

### ISSUE THREAD

**Issue by tigerhawkvok** [plotly/plotly.py#3140]
Like these Microsoft plots available: https://docs.microsoft.com/en-us/power-bi/visuals/desktop-ribbon-charts

Literally just an implementation of the chart type with the options described in the Microsoft docs :-)

**Comment by areed145** [comment]
This or connected bar charts would be wonderful

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
