### ISSUE TITLE
Inconsistent title text updates

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.py#3148]
Updating a layout with new title text behaves differently whether you use the modern nested title->text form or the old-but-still-supported form of title as a string.

```py
>>> go.Layout(title=dict(font_color="red")).update(title=dict(text="hi"))
Layout({
    'title': {'font': {'color': 'red'}, 'text': 'hi'}
})
>>> go.Layout(title=dict(font_color="red")).update(title="hi")
Layout({
    'title': {'text': 'hi'}
})
```

Notice how the first one (using title->text) performs a deep merge, so existing title styling is preserved. The second form wipes out the title object, replacing it with just the new string and removing the styling. Ideally both of these should perform a deep merge.

I've seen this issue with other titles too, such as xaxis->title

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
