### ISSUE TITLE
Unresolvable parent causes silent failure in sunburst

### ISSUE THREAD

**Issue by athompso** [plotly/plotly.py#3153]
When using the sunburst class in PX, providing a parent value that is missing will cause plotly to neither throw an error _nor_ display a graph.  Quite difficult to troubleshoot when the data matrix is large.

Example, with _one additional character added to a parent_ taken from https://plotly.com/python/sunburst-charts/:
```python
import plotly.express as px
data = dict(
    character=["Eve", "Cain", "Seth", "Enos", "Noam", "Abel", "Awan", "Enoch", "Azura"],
    parent=["", "Evie", "Eve", "Seth", "Seth", "Eve", "Eve", "Awan", "Eve" ],
    value=[10, 14, 12, 10, 2, 6, 6, 4, 4])

fig =px.sunburst(
    data,
    names='character',
    parents='parent',
    values='value',
)
a=fig.show()
```
Note the deliberate typo of "Evie" instead of "Eve" in the parent=[] list.  This causes a totally silent failure, as far as I can see.  No exception is raised, no error output is visible in the HTML source, zip, zilch, nada.

Using plotly v0.8.0 installed via pip on python 3.8.3 Win64.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
