### ISSUE TITLE
[Feature Request] Unions of Colums/Rows for Facet Filters

### ISSUE THREAD

**Issue by tarfeef101** [plotly/plotly.py#3163]
For the express plots that support faceting, they all say to pick a row/column and use unique values of that to group data for separate plots. What would be cool is a feature whereby you can provide a list of row/column names, and the union of those would be used. e.g. if I had the dataframe:
```
     A          B            C   D   E      F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  2.0  3   test  foo
3  1.0 2013-01-02  2.0  3  train  foo
```
I might specify [C, E] as my `facet_col`, and I'd end up with 4 plots representing `[(1.0, test), (1.0, train), (2.0, test), (2.0, train)]`
This is more favourable than wasting memory+effort creating additional data structures outside of plotly, and **should** be simple to implement, if one knows where to do that (have not looked at the codebase at all, admittedly).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
