### ISSUE TITLE
go.Figure() crash on IIS

### ISSUE THREAD

**Issue by isetthestandard** [plotly/plotly.py#3182]
I have an python flask app which runs perfectly. When i try to run this app in IIS, the app crashes with no log (only generic error 500) at this line: fig = go.Figure()

This is my go import: import plotly.graph_objs as go

Does anybody know this Issue and can help me to fix this?

Best regards

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
