### ISSUE TITLE
add_annotation with row/col specification breaks xref="paper"

### ISSUE THREAD

**Issue by LukasAdamowicz** [plotly/plotly.py#3183]
If using subplots, and adding annotations, using row=<n> and col=<n> breaks/ignores setting xref="paper"

Does not work:
```
fig2 = make_subplots(
    rows=2, cols=1,
    shared_xaxes=True
)

fig2.add_trace(go.Scatter(x=[1, 2, 3], y=[3, 2, 1]), row=1, col=1)
fig2.add_trace(go.Scatter(x=[1, 2, 3], y=[1, 2, 3]), row=2, col=1)

fig2.add_annotation(
    text=u"test xref=paper",
    x=0.5,
    y=1,
    bgcolor="rgba(0.8, 0.8, 0.8, 1)",
    showarrow=False,
    row=2,
    col=1,
    xref="paper"
)
```

However - setting xref="x2 domain" does seem to work (but requires setting yref="y2" or yref="y2 domain"):

```
fig3 = make_subplots(
    rows=2, cols=1,
    shared_xaxes=True
)

fig3.add_trace(go.Scatter(x=[1, 2, 3], y=[3, 2, 1]), row=1, col=1)
fig3.add_trace(go.Scatter(x=[1, 2, 3], y=[1, 2, 3]), row=2, col=1)

fig3.add_annotation(
    text=u"test xref=paper",
    x=0.5,
    y=1,
    bgcolor="rgba(0.8, 0.8, 0.8, 1)",
    showarrow=False,
    xref="x2 domain",
    yref="y2"
)
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
