### ISSUE TITLE
Plot not showing inline in Jupyterlab

### ISSUE THREAD

**Issue by jzhou559** [plotly/plotly.py#3189]
I am trying to plot a choropleth in jupyterlab. I installed all the extensions needed for plotly, but the graph is still not showing up inline. For your information, the graph does show up in a new tab when I call fig.write_html(). Thank you so much!

**Comment by GF-Huang** [comment]
Not work.

![image](https://user-images.githubusercontent.com/4510984/125483588-8a9e6a45-bba0-40ef-b7d1-9fb63d4a0349.png)

![image](https://user-images.githubusercontent.com/4510984/125483599-8660ee42-f3da-4272-9e50-5e3930c2eaea.png)

![image](https://user-images.githubusercontent.com/4510984/125483681-9f65e131-e221-485d-9e8e-1eb7af76718b.png)

**Comment by GF-Huang** [comment]
Solved after refresh browser page.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
