### ISSUE TITLE
[Feature Request] Allow DatePickerRange to step through years to avoid 12*years clicks on long ranges

### ISSUE THREAD

**Issue by Ambro17** [plotly/plotly.py#3191]
Hello, i'm using [DatePickerRange](https://dash.plotly.com/dash-core-components/datepickerrange) over a long period of time (years).
Current experience is not optimal because one must do `12*Years_Gap` clicks to create a range across a few years.
Usually, frontend libraries like [Ant](https://ant.design/components/date-picker/) allow navigating through years besides months.
That would mean that for a range of 5 years i can get around 6 clicks instead of 12*5 = 60.
Another solution might be allowing manual input of some shape `dd/mm/YYYY` besides clicking on the calendar.

Regardless of the chosen solution, i think it would greatly improve the experience of users using a daterange to customize interactive graphs:
**Allow choosing dates by stepping through years and months to quickly find the desired date.** 

I offer my help in python implementation. I don't have much experience on javascript and if i understood correctly, improvements are added to `plotly.js` first and then backported, right?

Thanks to the whole plotly team for an awesome lib and greate documentation examples!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
