### ISSUE TITLE
display static images on nbconvert export

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#320]
https://github.com/plotly/python-api/commit/b1ec43030b19f3244af07e127c48976b88ec851b took out `_repr_png` etc methods on `iplot` because of performance.

an alternative might be to display the image in HTML, and remove it from the `DOM` once the graph is loaded. then, in `nbconvert`, only the image will be present in the `DOM`. 

A WIP is here: https://github.com/plotly/python-api/pull/183

**Comment by jonmmease** [comment]
This is actually now possible in JupyterLab when using `iplot` with the `@jupyterlab/plotly-extension`.  This extension adds a `png` representation of the plot to the mime bundle right after the plot is rendered.  This png representation is saved to the notebook where it is available to nbconvert. See

https://github.com/jupyterlab/jupyter-renderers/blob/660d1529b75849e14cbe10922ff83a24fe328e61/packages/plotly-extension/src/index.ts#L77-L91

That said, with the orca integration it would also be possible to populate this image from the Python kernel, and provide configuration options for image format and quality settings.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
