### ISSUE TITLE
Plotly Express Parallel Coordinates Plot does not correctly handle duplicate values in df index when using color

### ISSUE THREAD

**Issue by cod3licious** [plotly/plotly.py#3200]
I'm using plotly express with version 4.14.3.

I noticed the parallel coordinates plot is behaving inconsistently when the dataframe has duplicate values in the index:
<img width="711" alt="Screenshot 2021-05-22 at 19 37 41" src="https://user-images.githubusercontent.com/1093567/119236056-a0c72a80-bb35-11eb-996e-1b6f5eb64c46.png">

This is the correct plot when I don't use color:
<img width="1013" alt="Screenshot 2021-05-22 at 19 41 31" src="https://user-images.githubusercontent.com/1093567/119236072-bb999f00-bb35-11eb-8c52-f36b09c4c0a5.png">

This is the plot when coloring based on the first feature
<img width="1013" alt="Screenshot 2021-05-22 at 19 41 18" src="https://user-images.githubusercontent.com/1093567/119236082-ceac6f00-bb35-11eb-834c-9370e1a5a508.png">

**Code to reproduce the issue:**
```python
import numpy as np
import pandas as pd
import plotly.express as px

df = pd.DataFrame(np.random.randn(400, 10), columns=[f"x{i}" for i in range(10)])
df.index = 100*[0, 1, 2, 3]
# ok plot
px.parallel_coordinates(df)
# cropped plot
px.parallel_coordinates(df, color=df.columns[0])
```

**Comment by DavidWalz** [comment]
I also stumbled upon this for plotly > 4.9, whereas for plotly==4.9 I did not get the issue.  
The obvious workaround is to `df.reset_index()` for the parallel plot.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
