### ISSUE TITLE
Pie animation currently unimplemented

### ISSUE THREAD

**Issue by leonardas103** [plotly/plotly.py#3201]
Inter-frame transitions are only possible for scatter and bar plots. The current workaround to get pie chart animations in plotly is to save the figures as images and then load the images using `px.imshow`:  
```
from skimage import io
import plotly.express as px

# generate pie images
for step in steps: 
  df = get_df(step)
  fig = px.pie(df, values='x', names='y', color="y")
  fig.write_image(f"pie-{step}.png", engine="kaleido", scale=2)

# load pie images
imgs = io.ImageCollection('pie*.png').concatenate()
fig = px.imshow(imgs, animation_frame=0)
fig.show()
```
Note however this process will produce very ugly results:
![image](https://user-images.githubusercontent.com/17128994/119363429-78b30500-bcb6-11eb-8371-e34f5ec85c8a.png)
If we could pass the images as `.svg` to `px.imshow` they might look cleaner/ antialiased.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
