### ISSUE TITLE
[Feature request] Custom scales or locators

### ISSUE THREAD

**Issue by tim-tx** [plotly/plotly.py#3206]
In some bio datasets you will find weird x-scales with mixed linear and logarithmic scaling, e.g. linear between -100 and 100, and logarithmic above 100. Of course I can apply the transformation before plotting and mentally remap the x-axis ticks, but it would be great if enough of the underlying machinery for scaling were exposed so that the end-user could implement something like this.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
