### ISSUE TITLE
Animation is smooth when dragging between values, but makes erratic shapes when hitting play button

### ISSUE THREAD

**Issue by MaxGhenis** [plotly/plotly.py#3223]
See this gif:
![Screen recording 2021-06-05 12 34 15](https://user-images.githubusercontent.com/6076111/120903425-e0444b00-c5fa-11eb-8ce0-18b715f13b29.gif)

The code to produce this is in cell 18 of [this notebook](https://nbviewer.jupyter.org/github/UBICenter/libdem-ubi-analysis/blob/main/jb/analysis.ipynb). I tried to make a MWE [here](https://colab.research.google.com/drive/1H0Nu1W7VCKofVTqLl3_Sm7X1knskESdW?usp=sharing) but couldn't come up with one.

**Comment by nikhilwoodruff** [comment]
If it helps, the arrays used to generate the plot have many values (over 1,000 x-y pairs). I wonder if there's a way of forcing the animation to fix the x position of the coordinates?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
