### ISSUE TITLE
add time slider to natcdf mapping with plotly.graph_objects.layout.Slider

### ISSUE THREAD

**Issue by Homaghasemi** [plotly/plotly.py#3226]
Dear people, 

I am trying to make an interactive map from netcdf data. I could make one map for one step of time, however adding a slider to the layout is very complicated. Can anyone give me a hint, please?  I am new to plotly. 

data = Data([trace1]+traces_cc)
title = "Monthly Average hours of ligthning in 2008/ Model"
axis_style = dict(
    zeroline=False,
    showline=False,
    showgrid=True,
    ticks='',
    showticklabels=False,
)

layout = Layout(
    title=title,
    showlegend=False,
    hovermode="closest",        # highlight closest point on hover
    xaxis=dict(
        axis_style,
        range = [2, 25]
        ),
    yaxis=dict(
        axis_style,
    ),
    annotations=Annotations([
        Annotation(
            text=anno_text,
            xref='paper',
            yref='paper',
            x=0,
            y=1,
            yanchor='bottom',
            showarrow=False
        )
    ]),
    autosize=True,
    width=800,
    height=500
    #sliders = Slider(time,
     #                active = 1,
      #               label = 'time', 
       #              valmin = 1, 
        #             valmax= 12)
)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
