### ISSUE TITLE
Subplot Scaling

### ISSUE THREAD

**Issue by prolaser** [plotly/plotly.py#3236]
Hi guys

Im using plotly to create subplots (make_subplots), my problem is that these subplots scale when the number of rows differ.
For example when when (row=2,col=1) my subplots have different size with when i do (row=4,col=1). Basically the more rows I have the smaller my plots get and I dont want this to happen. I want my plots to always have the same size no matter if I add more rows and plots. So far what I tried is fig.update_layout() which also doesnt help. Im not sure if this fiture exist in plotly or not. please guide me:
**3 Rows**
![3rows](https://user-images.githubusercontent.com/38209222/121507625-17dd3980-c9e5-11eb-9264-110a3ca4df0c.png)

**4 Rows**
![4rows](https://user-images.githubusercontent.com/38209222/121507631-190e6680-c9e5-11eb-8c62-751bb9020338.png)

in this image zou can see when the number of rows increase the plots scale down in siye, I want them to always stay same size

**Comment by nicolaskruchten** [comment]
You'll need to update the height and width of your figure as you add rows and columns in order to get them to stay the same size.

**Comment by rrazaghi** [comment]
@nicolaskruchten could you provide a small reproducible example? I'm currently dealing with a similar situation.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
