### ISSUE TITLE
Treemap: plotly express  turns blank - see reproducible example

### ISSUE THREAD

**Issue by firmai** [plotly/plotly.py#3237]
Hi - please see the fast fully contained colab example
https://colab.research.google.com/drive/1lzaw1AmYeJtrcPBxcPCZPyeiACvv4U1C?usp=sharing

input:

```
%%capture
!pip install --upgrade plotly
import pandas as pd 
final = pd.read_csv("https://raw.githubusercontent.com/firmai/random-assets-two/master/test/file.csv")
final.head()
final.dtypes
import plotly.express as px
import numpy as np

typed = "In-sample"
fig = px.treemap(final, path=["Data","Acronym"], values=typed)

fig.show()
```

output:

![image](https://user-images.githubusercontent.com/26666267/121515883-920dbe00-c9e5-11eb-9c24-966072aca698.png)

**Comment by LeoWanty** [comment]
Hi !

I ran into an issue returning similar output. 

I filled null values with empty strings (using `df.fillna("")`) but Treemaps kinda don't like parents or children with empty elements. Changing this line to `df.fillna(" ")` solved my issue.

In your case @firmai , you were trying to force negative values as input in your `values=typed` argument.
Changing `fig = px.treemap(final, path=["Data","Acronym"], values=typed)` to `fig = px.treemap(final[final[typed]>0], path=["Data","Acronym"], values=typed)` do the trick.

_____________________

However those bad inputs  are silently  passed which causes empty outputs without any suggestions to correct our wrongs.

I suggest :
- [ ] Highlight in the official documentation and tutorials that blank output may be caused by wrong data specifications (and list the known issues!)
- [ ] In future versions, don't pass silently such issues with input data ! Return exceptions or message that can help solve the issue or redirect to pertinent documentation.
- [ ] In future versions, if plotly make some magic to handle most common cases (like missing values or unvalid values), it would be handsome ! :angel:

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
