### ISSUE TITLE
Question of chart Plotly

### ISSUE THREAD

**Issue by JohaMR** [plotly/plotly.py#3238]
Hi, I have a question, how do I remove the axes and background grid from a chart with plotly?

**Comment by nicolaskruchten** [comment]
This is probably a better question for our [community forum](https://community.plotly.com) :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
