### ISSUE TITLE
Line chart slider animation support

### ISSUE THREAD

**Issue by nohaapav** [plotly/plotly.py#3246]
I found few examples how to achieve slider animation support for charts with simple slider component,
however for my use-case i need line chart slider similar as following picture:

<img width="672" alt="Screen Shot 2021-06-14 at 3 13 57 PM" src="https://user-images.githubusercontent.com/4179104/121898136-5cd5d880-cd23-11eb-9b89-04b0460c5fa7.png">

Does plotly support following ?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
