### ISSUE TITLE
Unable to Erase drawings on Chart

### ISSUE THREAD

**Issue by AnandaSP** [plotly/plotly.py#3261]
After drawing on chart, unable to remove. Is there any way to remove that?

![image](https://user-images.githubusercontent.com/60298675/122684496-4946d800-d223-11eb-80d3-d03b801ed5fd.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
