### ISSUE TITLE
Why python plotly box-plot y axis is not showing appropriately?

### ISSUE THREAD

**Issue by PN1019** [plotly/plotly.py#3264]
There is an issue in Plotly Box-plot implementation I came across while doing some personal project. The Implementation Problem I  came across is related to Y-axis visual behaviour :

Y-axis is unable to handle or visualize bigger integer values. (Behaviour showing distorted figure as in this image
 ![newplot (1)](https://user-images.githubusercontent.com/16081831/122753018-42fe3d80-d2af-11eb-9e34-7984f79a6568.png)
Here is the link to a detailed discussion on [Stackoverflow](https://stackoverflow.com/questions/67300390/why-python-plotly-box-plot-y-axis-is-not-showing?noredirect=1#comment118990291_67300390):

I can provide more details on the issue if this issue is considered for evaluation.
Hoping the plotly team to look into this as soon as possible.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
