### ISSUE TITLE
Subplot scaleanchor/ratio scales wrong plot

### ISSUE THREAD

**Issue by swansk** [plotly/plotly.py#3268]
When updating the axes in a subplot with `scaleanchor = "x"` and `scaleratio = 1`, the scaling is applied to the incorrect plot. 

See example below:
```
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go

N = 100
np.random.seed(42)

fig = make_subplots(
    rows=2,
    cols=1,
    subplot_titles=("TOP", "BOTTOM_L"),
)
fig.add_traces(
    go.Scatter(
        name="scatter_1",
        x=np.random.randn(N),
        y=np.random.randn(N),
        mode="markers",
        marker=dict(size=4),
    ),
    rows=1,
    cols=1,
)
fig.add_traces(
    go.Scatter(
        name="scatter_2",
        x=np.random.randn(N),
        y=np.random.randn(N),
        mode="markers",
        marker=dict(size=4),
    ),
    rows=2,
    cols=1,
)

fig.update_xaxes(title_text="top_x", row=1)
fig.update_yaxes(title_text="top_y", row=1)
fig.update_xaxes(title_text="bot_x", row=2)
fig.update_yaxes(title_text="bot_y", row=2, scaleanchor="x", scaleratio=1)
print(fig)
fig.show()
```

The scaling is applied to the top plot, even though we specify the bottom. Output looks like:
<img width="1776" alt="image" src="https://user-images.githubusercontent.com/6597093/122957274-c7080200-d34f-11eb-9ea8-1cd09c76497f.png">

The figure is updated correctly, with the axis configuration looking like:
```
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'top_x'}},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0], 'title': {'text': 'bot_x'}},
               'yaxis': {'anchor': 'x', 'domain': [0.625, 1.0], 'title': {'text': 'top_y'}},
               'yaxis2': {'anchor': 'x2',
                          'domain': [0.0, 0.375],
                          'scaleanchor': 'x',
                          'scaleratio': 1,
                          'title': {'text': 'bot_y'}}}
```

**Comment by aleferna12** [comment]
Any updates on this issue?

**Comment by empet** [comment]
In the above code by @swansk  the line:
```
fig.update_yaxes(title_text="bot_y", row=2, scaleanchor="x", scaleratio=1)
```
is incorrect,  because in row 2 the xaxis is not 'x', but `x2`.
Hence replace it by:
```
fig.update_yaxes(title_text="bot_y", row=2, scaleanchor="x2", scaleratio=1)
```
or
```
fig.update_layout(yaxis2_scaleratio=1, yaxis2_scaleanchor='x2')
```
and get the right plot:
![scaleratio-subplot](https://user-images.githubusercontent.com/3627253/224113835-8afff975-635c-44bf-938a-81619d427258.png)


With the initial line of code the figure wasn't updated correctly:
```
'yaxis2': {'anchor': 'x2',
                          'domain': [0.0, 0.375],
                          'scaleanchor': 'x',
                          'scaleratio': 1,
                          'title': {'text': 'bot_y'}}}
```
because scaleanchor ihas been set  on  'x', but 'x' is the axis in the subplot cell from row=1.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
