### ISSUE TITLE
Scatter3D Plots Incorrectly Bin On Axis with Timestamp values

### ISSUE THREAD

**Issue by ghostop14** [plotly/plotly.py#3270]
So we've noticed some unusual behavior in the latest plotly.py (5.0.0) and plotly.js (latest 2.1.0 version) regarding scatter3d plots.  We are dealing with data where the x-axis data points are datetime objects (Pandas datetime or python datetime in plotly.py, or javascript Date in plotly.js).  When these values are plotted in a scatter3d plot, looking edge-on from the x-axis running horizontally, you can see that the data points are "binned" along the x-axis.  (There are clear gaps however the data points are contiguous).  The same outcome happens if you convert the datetimes to linux timestamps (floats).  Removing the z-axis and plotting on a standard 2D scatter does not exhibit the same behavior.

We have found a workaround that requires extra coding where the datetimes are converted to unix timestamps, then the minimum subtracted so we're left with seconds since t=0 in the time window we're analyzing.  A new set of x-axis tick labels are then laid out with an array format where the values match the seconds and the labels match the true times.  However, this adds a good bit of overhead. 

At this point, this seems like a bug in scatter3d and how it handles plotting timestamps.  Attached is a quick python example showing this behavior.  It generates time-based data then plots a scatter3d and scatter using plotly express and the time-axis spacing issue is clearly visible as you rotate the scatter3d plot.

[demo_time_bins.py.txt](https://github.com/plotly/plotly.py/files/6697299/demo_time_bins.py.txt)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
