### ISSUE TITLE
annotated_heatmaps need to be more robust to np.nan values

### ISSUE THREAD

**Issue by chiragkapoorck** [plotly/plotly.py#3271]
in computing font colours, zmid requires calulations of zmin and zmax values. They in turn use np.amin() and np.amax(). These arguments return NaN if the numpy array has any nan values. Please use np.nanmin() and nanmax() instead.

**Comment by chiragkapoorck** [comment]
Also for font colours, instead of a simple sequential criterion, it should also account for diverging colour scales. So probably white on high z-values and black on middle 50%...

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
