### ISSUE TITLE
Multi index plotting using plotly

### ISSUE THREAD

**Issue by harioyyoth** [plotly/plotly.py#3273]
Dear Team,
I have a pivot table as shown below. I need to plot this using Plotly in such a way that 'Device_ID, Temp, Supp, Freq' needs to come in X-axis, and "Noise level and Spec max' need to come to Y-axis.
May I know how to do this using plotly. 

![image](https://user-images.githubusercontent.com/70841291/123064706-25a2ae00-d42c-11eb-9965-e3f78fe44486.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
