### ISSUE TITLE
Missing buttons in modebar with Plotly 5.0.0 (documentation improvement)

### ISSUE THREAD

**Issue by JulianWgs** [plotly/plotly.py#3274]
Hello,

Spike lines and compare data on hover is missing by default in the modebar/toolbar for Plotly 5.0.0.

Originally this was a bug report, but it turned out it is feature (as you can read [here](https://github.com/plotly/plotly.py/releases/tag/v5.0.0)) 😄 

```python
import plotly.graph_objects as go

x = [0, 1, 2]
y = [0, 1, 4]
fig = go.Figure(go.Scatter(x=x, y=y))
fig
```
Plotly 4.14.3:
![full toolbar](https://user-images.githubusercontent.com/31596773/123078352-2d0d8b80-d41b-11eb-8550-7787bf9ceee2.png)

Plotly 5.0.0:
![image](https://user-images.githubusercontent.com/31596773/123078716-87a6e780-d41b-11eb-8c4e-d79a041d81bd.png)

After an overly long search I found the solution:
```python
fig.update_layout(modebar_add=[
    "v1hovermode",
    "toggleSpikelines",
])
```

So I would like to suggest to also mention `toggleSpikelines` in the release notes, because it took me an unnecessary long amount of time find the keyword for it. [Here](https://plotly.com/python/configuration-options/#removing-modebar-buttons) is also a full list of all possible mode bar buttons. A little misplaced if you ask me. In my opinion it should be placed more centrally describing the modebar. Also the documentation mentions many times examples for different mode buttons. I'd suggest to always link them to the complete list to remove duplication.

**Comment by nicolaskruchten** [comment]
Thanks for the feedback! I've updated the changelog and release notes.

**Comment by JulianWgs** [comment]
Thank you for the fast response! Feel free to close the issue (if you dont wanna tackle the documentation suggestions, just yet 😄 )

**Comment by chicolucio** [comment]
[This list of buttons](https://plotly.com/python/configuration-options/#removing-modebar-buttons) is correct? There is no `v1hovermode` in the list. I found out how to add this button reading this issue. There is a reference to `v1hovermode` [here in this link about layout](https://plotly.com/python/reference/layout/#layout-modebar-add) but maybe it would be nice to have some link to it in the configuration options page since it was removed in a recent release as @JulianWgs linked above.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by JulianWgs** [comment]
v1hovermode was still missing from that list, but it is an easy fix, so I created a PR.

**Comment by gvwilson** [comment]
see #4647
