### ISSUE TITLE
Determine the color of the 3D cones by an alternative variable

### ISSUE THREAD

**Issue by RinconFer** [plotly/plotly.py#3277]
Hello,

Thank you for amaizing package. I am using the 3D cone to represent UMAP coordinates of a single cell RNA experiment (were each cell get represented in the 3D space determined by the UMAP) and the size of the cones as an RNA velocity arrow measure which works great. However, I would like to be able to set the color of each cone depending of alternative variables, for example: expression of a gene in each cone, cell type of each cone,....

I haven't been able to unlink the color of the cones from the size of the vector delimited by the u, v, w values. Is it possible to do it at all? or it would need changes in the function?

Thank you very much.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
