### ISSUE TITLE
Feature Request: Drawing custom lines based on equations

### ISSUE THREAD

**Issue by indiana-nikel** [plotly/plotly.py#3289]
Hello,

Big fan of `plotly.express`, so much flexibility in one plotting library!

One request I have is whether it is possible to add in a feature to draw lines based on an equation (rather than the hline and vline implementations). One use case is looking at actual vs. predicted plots when assessing machine learning models. Ideally, these plots should line up on a y=x line, and it would be a wonderful feature to be able to add that (and others, y=ax2 + bx +c, etc.) to charts, similar to how you might operate a graphing calculator. 

An example implementation might be:

fig = px.scatter(df, x, y)
fig.add_line(equation="y ~ 2x + 7") #similar to patsy syntax with the ~ separating the left and right sides

I can see 3D scatter charts potentially being more complicated, but for 2D plots this would be a very helpful addition to the package.

**Comment by nicolaskruchten** [comment]
This is already mostly-doable although not with quite as nice an API as you're describing:

```python
import plotly.express as px
df = px.data.tips()
fig = px.scatter(df, x="total_bill", y="tip")

import numpy as np
x = np.linspace(df["total_bill"].min(), df["total_bill"].max())
fig.add_scatter(x=x, y=x*0.4, showlegend=False)
fig.add_scatter(x=x, y=x*x*0.005, showlegend=False)
```

![newplot](https://user-images.githubusercontent.com/203523/124683845-03814500-de9c-11eb-94f9-8dcd9d6214d6.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
