### ISSUE TITLE
Candlestick chart fails to render on Google Colab

### ISSUE THREAD

**Issue by miohtama** [plotly/plotly.py#3309]
I am rendering Plotly Candlestick charts 

*  The charts render locally on the Jupyter server and PyCharm

* The chart does not render on Google Colab

My rendering code

```python

import plotly.graph_objects as go
from plotly.offline import iplot

fig = go.Figure(data=[go.Candlestick(x=october['timestamp'],
                open=october['open'],
                high=october['high'],
                low=october['low'],
                close=october['close'])])
# Tried both methods
# fig.show()
iplot(fig)
```

Rendered locally:

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/49922/126402311-f0068edb-f6ad-4e15-8853-48e834a48cd3.png">

Rendered on Google Colab:

<img width="1978" alt="image" src="https://user-images.githubusercontent.com/49922/126402357-f97b6063-239e-4b82-a590-6eb579ab8873.png">

The notebook source: https://github.com/miohtama/capitalgram-onchain-dex-quant-data/blob/master/docs/source/examples/plotting.ipynb

The Google Colab link: https://colab.research.google.com/github/miohtama/capitalgram-onchain-dex-quant-data/blob/master/docs/source/examples/plotting.ipynb

My questions are 

* How to debug

* How to workaround if possible (happy to switch to Binder as the free notebook provider if it helps)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
