### ISSUE TITLE
Graph is plotting when i pass secondary y axis values is over primary y axis

### ISSUE THREAD

**Issue by naresh-FD** [plotly/plotly.py#3311]
We trying to create a graph with primary and as well as secondary y-axis. but we are just using the Plot component and passing all the values from backend python. when we try to render in python it works fine as below image. But when we try to implement the same with react Plot component secondary y-axis values is overlapped primary y-axis.

![image](https://user-images.githubusercontent.com/50324374/126589581-10f60a76-e73e-4d18-a57b-9cb174069b17.png)

**Comment by barrospt** [comment]
Any news?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
