### ISSUE TITLE
[Bug] Legendgrouptitle font size not correct in hovermode x-unified

### ISSUE THREAD

**Issue by stephprobst** [plotly/plotly.py#3318]
The font size of the legendgrouptitle in the x-unified hovermode is not affected by the layout.hoverlabel.font.size property:

**Setup of example chart:**

```
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=[1, 2, 3],
    y=[2, 1, 3],
    legendgroup="group",  # this can be any string, not just "group"
    legendgrouptitle_text="First Group Title",
    name="first legend group",
    mode="markers",
    marker=dict(color="Crimson", size=10)
))

fig.add_trace(go.Scatter(
    x=[1, 2, 3],
    y=[2, 2, 2],
    legendgroup="group",
    name="first legend group - average",
    mode="lines",
    line=dict(color="Crimson")
))

fig.add_trace(go.Scatter(
    x=[1, 2, 3],
    y=[4, 9, 2],
    legendgroup="group2",
    legendgrouptitle_text="Second Group Title",
    name="second legend group",
    mode="markers",
    marker=dict(color="MediumPurple", size=10)
))

fig.add_trace(go.Scatter(
    x=[1, 2, 3],
    y=[5, 5, 5],
    legendgroup="group2",
    name="second legend group - average",
    mode="lines",
    line=dict(color="MediumPurple")
))

fig.layout.hovermode='x unified'
fig.update_layout(title="Try Clicking on the Legend Items!")

```

**Issue:**

```
fig.layout.font.size = 20
fig.layout.hoverlabel.font.size = 12
fig.show()
```

![image](https://user-images.githubusercontent.com/20990315/127001745-692e6410-b447-49f4-a07e-eb1594de193a.png)

**Comment by archmoj** [comment]
The main title font size is also too small.
That is also addressed in https://github.com/plotly/plotly.js/pull/5895.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
