### ISSUE TITLE
Allow specifying a finite limit for `add_{v|h}line`

### ISSUE THREAD

**Issue by dhirschfeld** [plotly/plotly.py#3324]
e.g. change the `vline` signature to `add_vline(x, y0=None, y1=None, *args, **kwargs)` so that you can optionally specify the start or end (or both) points for the added line. If either `y0` or `y1` are `None` that would continue to mean extend to infinity in that direction i.e. it would continue to extend to the bottom/top of the axes, no matter the zoom.

The use case it to highlight the (x, y) location of specific points without having the lines extend past the point itself.

**Comment by dhirschfeld** [comment]
This would be like the ability to specify fixed/static spikelines

**Comment by majed282** [comment]
> على سبيل المثال تغيير التوقيع إلى بحيث يمكنك تحديد نقاط البداية أو النهاية (أو كليهما) للبند المضاف. إذا كان أي منهما أو أن هذا يعني الاستمرار في توسيع إلى ما لا نهاية في هذا الاتجاه أي أنها سوف تستمر في التوسع إلى أسفل / أعلى المحاور، بغض النظر عن التكبير.`vline``add_vline(x, y0=None, y1=None, *args, **kwargs)``y0``y1``None`
> 
> حالة الاستخدام لتمييز موقع (س، ص) لنقاط معينة دون أن تمتد الخطوط بعد النقطة نفسها.

**Comment by majed282** [comment]
> على سبيل المثال تغيير التوقيع إلى بحيث يمكنك تحديد نقاط البداية أو النهاية (أو كليهما) للبند المضاف. إذا كان أي منهما أو أن هذا يعني الاستمرار في توسيع إلى ما لا نهاية في هذا الاتجاه أي أنها سوف تستمر في التوسع إلى أسفل / أعلى المحاور، بغض النظر عن التكبير

> حالة الاستخدام لتمييز موقع (س، ص) لنقاط معينة دون أن تمتد الخطوط بعد النقطة نفسها.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
