### ISSUE TITLE
[Feature request] allow the use of violins in timeline plots

### ISSUE THREAD

**Issue by ClementFeltin** [plotly/plotly.py#3329]
I'm currently using timeline plots to display boxplots along a timeline (the use case is a "probabilistic" gantt chart):
![image](https://user-images.githubusercontent.com/8502782/128053391-12f486bb-ec8e-4fb7-a170-b8c7b7d96a54.png)
I would like to switch to violin plots but it does not seem to be possible at the moment.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
