### ISSUE TITLE
Incorrect go.Heatmap discrete colorscale for PDF static image export

### ISSUE THREAD

**Issue by ymerkli** [plotly/plotly.py#3333]
Hi there!

I'm using `plotly.graph_objects.Heatmap` to create heatmaps with discrete colorscales and want to export the resulting figures to `.pdf`. When displaying the figure in a Jupyter notebook, the colorscale looks as expected (i.e. discrete), where as when exported to `.pdf`, the colorscale shows a color gradient between the different discrete colors.

Reproducible example:
```
import plotly.graph_objects as go
colorscale = [
    [0.0, 'rgb(217,217,217)'], [0.25, 'rgb(217,217,217)'], [0.25, 'rgb(255,0,0)'], [0.5, 'rgb(255,0,0)'],
    [0.5, 'rgb(255,153,0)'], [0.75, 'rgb(255,153,0)'], [0.75, 'rgb(51,204,51)'], [1.0, 'rgb(51,204,51)']
]

fig = go.Figure(data=go.Heatmap(z=[[0, 0.25],[0.75, 0.5]], colorscale=colorscale))
fig.write_image('test.pdf')
fig.show()
```
Figure displayed in notebook (expected behaviour):
![expected](https://user-images.githubusercontent.com/22059822/128218288-a2f6938c-e085-4da0-a671-13ea8db6b775.png)

Figure exported to PDF:
![unexpected](https://user-images.githubusercontent.com/22059822/128218357-28f9e841-7fdc-4422-aa20-7b66b7e4c037.png)

This only happens when exporting to `.pdf`. When exporting to `.png` or `.svg`, the colorscale looks as expected. The behavior appears for both `kaleido` and `orca`.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
