### ISSUE TITLE
Scattermapbox text font family does not change

### ISSUE THREAD

**Issue by SimchaGD** [plotly/plotly.py#3335]
Not sure if bug, or I am just doing it wrong. I posted this on the community forum and stack-overflow, but nobody could help me. I suspect that it is a bug.

I want to add text to my map in a specific font. Even when I tested with basic HTML-fonts, the text in the map wouldn’t change. However, I could change the hover font. What went wrong? Or is it a bug?

```
fig = go.Figure(go.Scattermapbox(
            lat=[51.555606],
            lon=[5.090819],
            mode="markers+text",
            showlegend=False,
            text=['Test'],
            textposition='top right',
            textfont=dict(size=25, color='black', family='Courier New'),
            hoverlabel=dict(font=dict(family='Courier New', size=25)),

            marker=dict(size=20)))

fig.update_layout(mapbox=dict(zoom=11.5, center={"lat": 51.57, "lon": 5.07}, accesstoken=token))
```

Output:
![image](https://user-images.githubusercontent.com/28702544/128316120-60e9fff1-8605-45a5-a99c-878d493b810c.png)

Output figure with hover, which uses Courier New:
![image](https://user-images.githubusercontent.com/28702544/128316161-599b499f-537b-4257-b0f9-589a4fb726c5.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
