### ISSUE TITLE
[Feature Request] Modebar positioning with x,y (like Legend)

### ISSUE THREAD

**Issue by mmarras** [plotly/plotly.py#3345]
I am missing (could be that I didn't find or that it does not exist) an option for `Modebar` to define it's position in reference to the plot just like it is possible with `x` and `y` plus `xanchor`, `yanchor` in `Legend`. I think that would be helpful, having the option of `h` vs `v` is good but not sufficient.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
