### ISSUE TITLE
Keeping 3D axes static when rotating

### ISSUE THREAD

**Issue by SKJKL** [plotly/plotly.py#3350]
I've made a 3D scatter plot using the scatter_3D function and everything's working fine, I would just like a way to prevent the axes (and the whole grid) from jumping to the opposite side when you're rotating the graph. I've been looking through the documentation but I couldn't find any solution to this.

Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
