### ISSUE TITLE
I get an error while using two values only on yaxis from dataframe.

### ISSUE THREAD

**Issue by viswanaath97** [plotly/plotly.py#3354]
Hi,

So i have a code where i get the y-axis and x-axis value from data frame, i get the below error when i have only two values/dates in y-axis. The error does not occur if i have either 1 or more than 2 dates in y-axis.

Below is the screenshot of the issue.

![image](https://user-images.githubusercontent.com/46341320/130396054-b96f7d19-6e1d-436e-bfab-0ce79848a4b4.png)

The csv file of the dataframe looks like this.

![image](https://user-images.githubusercontent.com/46341320/130396116-881ab8cb-01d1-454d-8cc1-e60d3416d0ca.png)

I am using this part of code to update the plotly graph.

discrete_map = { 'None': '#7f7f7f', 'Both': '#1f77b4', 'In': '#2ca02c', 'Out': '#d62728'}
fig = px.timeline(df, x_start='Start_time', x_end='End_time', y='New_date', color='Status', color_discrete_map=discrete_map, title=t_id[:-4])
print(df['Start_time'], df['End_time'], df['New_date'])
#update x axis according to our data ( x axis with 24hours time)
fig.update_xaxes(tickformat="%H\n%M", tickformatstops=[dict(dtickrange=[3600000, 86400000], value="%H:%M")])
fig.update_yaxes(dtick='86400000')

Please do let me know if this error can be resolved, Thanks in advance!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
