### ISSUE TITLE
Can I draw a circle by plotly.graph_objects?

### ISSUE THREAD

**Issue by Lap1ace** [plotly/plotly.py#3364]
My project requires me to draw a circle in the coordinate system. I don't know whether plotly can achieve this function.
This original need to set the radius and center of the circle, expressed by a binary equation.
Ask for help!

**Comment by jwalaQ** [comment]
Do take a look at this section - https://plotly.com/python/shapes/#circles-positioned-relative-to-the-axis-data

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
