### ISSUE TITLE
hover error on https://plotly.com/python/dendrogram/ example

### ISSUE THREAD

**Issue by jsmentch** [plotly/plotly.py#3369]
As mentioned on the [forum](https://community.plotly.com/t/hover-error-in-clustermap/53037), the final heatmap with dendrogram example has an error where, when hovering, the y values are not displaying the correct informative labels.

Is there a method for making the y values displayed correctly while hovering? Thank you.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
