### ISSUE TITLE
fig.add_line similar to add_(h|v)line

### ISSUE THREAD

**Issue by janosh** [plotly/plotly.py#3370]
I often find myself needing a parity line (aka identity line, i.e. `x = y`) across the whole plot that cannot be zoomed/panned away similar to `add_(h|v)line`.

How about adding a new method `fig.add_line()` that takes an anchor point `[x0, y0] = [0, 0]` along with a `slope = 1`?

If the plot has equal `x` and `y` range, I currently use this as a workaround:

```py
import plotly.graph_objects as go

fig = go.Figure()

line_dict = dict(
    type="line", yref="paper", y0=0, y1=1, xref="paper", x0=0, x1=1, opacity=0.1
)
fig.update_layout(shapes=[line_dict])

fig.update_xaxes(range=[0, 100])
fig.update_yaxes(range=[0, 100])

fig.write_image("tmp.png")
```

![tmp](https://user-images.githubusercontent.com/30958850/131986411-ef304824-d549-4b9b-9864-06f279f99c8b.png)

**Comment by archydeberker** [comment]
Alternative syntax for plotly express: how about `trendline="equality"` as a kwarg for `px.scatter`?

```
px.scatter(
    iris_df,
    x="petal",
    y="sepal",
    title="Line is X=Y equality",
    trendline="equality",
)
```

I often need to do this to compare e.g. two ways of estimating the same quantity.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
