### ISSUE TITLE
write_html is not rendering Latex

### ISSUE THREAD

**Issue by dwerner95** [plotly/plotly.py#3373]
The following example produces two figures, one rendered in the browser using `fig.show()`displays the latex text correct. The other one using `fig.write_html` does not render latex.

```python3
import plotly.express as px
df = px.data.tips()
fig = px.histogram(df, x="total_bill")
fig.update_layout(
      yaxis=dict(
                title= r"$\Huge{\text{test}}$",
                side="left",
                )
)
fig.show()
fig.write_html("test.html")
```

**Comment by nicolaskruchten** [comment]
You'll need to use the `include_mathjax` argument to `write_html()` for this to work.

**Comment by Ipuch** [comment]
It works fine
```pythonfig.write_html(..., include_mathjax="cdn")```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
