### ISSUE TITLE
plotly.graph_objects not found during CI (works locally)

### ISSUE THREAD

**Issue by iosonofabio** [plotly/plotly.py#3377]
Dear plotly maintainers,

thank you so much for the amazing package! I'm a core developer of igraph and its Python cousin python-igraph, which is a popular network analysis library. I'm adding support for plotly into our codebase but our CI tests fail mysteriously on import:

https://github.com/igraph/python-igraph/pull/425/checks?check_run_id=3564560114#step:4:1656

The same exact command works on several of our machines so I am hoping any of you might have some insightful suggestion as of what's going wrong here. As you can see from that trace, the testing infra correctly and successfully installs plotly 5.3.1 via pip, so `import plotly` definitely goes through without throwing an exception. But then later on when `plotly.graph_objects` is called, it errors out.

I understand that `graph_objects` is an autogenerated beast which emerged from the ashes of `graph_objs` around Python 3.7 and am wondering if that might be causing the issue at hand.

Thanks in advance,
Fabio

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
