### ISSUE TITLE
[Feature request] Allow selection of colors for multiple layers in nested figures like sunburst or treemap

### ISSUE THREAD

**Issue by LeoWanty** [plotly/plotly.py#3378]
Hi!

I 'm sorry if I missed a similar issue despite my prior researchs.

I'd love to be able to choose different pallets of colors for each nested layers in sunburst graphs or treeamaps. The current version allow to customize colors for one layer only and guess colors of other layers based on it.

----------------------
What I imagine, starting from [an example in your doc](https://plotly.com/python/sunburst-charts/#using-an-explicit-mapping-for-discrete-colors)

- For discrete values, use list in `color` and `color_discrete_map` arguments :
```python 
import plotly.express as px
df = px.data.tips()

cmap_sex = {'Male':'cyan', 'Female':'magenta'}
cmap_day = {'Thurs':'white', 'Fri':'lightgrey', 'Sat':'darkgrey', 'Sun':'black'}
cmap_time = {'(?)':'red', 'Lunch':'gold', 'Dinner':'darkblue'}

fig = px.sunburst(df, path=['sex', 'day', 'time'], values='total_bill',
                  color=['sex', 'day', 'time'],
                  color_discrete_map=[cmap_sex, cmap_day, cmap_time])
fig.show()
```
- For incomplete hierarchical colors, use extending function like actual version :
```python
fig = px.sunburst(df, path=['sex', 'day', 'time'], values='total_bill',
                  color=['sex', 'time'],  # Let extending colors from "sex" column apply on "day" categories 
                  color_discrete_map=[cmap_sex, cmap_time])
fig.show()
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
