### ISSUE TITLE
px.area, adds zero values on every second tick to graph

### ISSUE THREAD

**Issue by DavoudTaghawiNejadWSP** [plotly/plotly.py#3379]
The following program should plot a random walk:

import pandas as pd
import plotly.express as px
import numpy as np

a = np.random.normal(size=50)

oil = a.cumsum() * 5 + 75
non_oil = 100 - oil
df = pd.DataFrame({"Oil": oil, "Non-Oil": non_oil})
df = df.stack()
df.index = list(zip(*df.index))[1]
df = pd.DataFrame(df).reset_index()
df.index = pd.RangeIndex(2020 - 100, 2020)
fig2 = px.area(df, line_group='index', y=0, color='index')
fig2.show()
The graph created in 4.x.x is this:

<img width="1646" alt="Screen Shot 2021-09-13 at 5 06 53 PM" src="https://user-images.githubusercontent.com/90594653/133088989-5f55b386-2728-47e2-8eff-3764e3353e66.png">

While 5.x.x produces this graph.

<img width="931" alt="Screen Shot 2021-09-13 at 5 09 32 PM" src="https://user-images.githubusercontent.com/90594653/133089375-2ec4f32b-219e-4bdd-8c82-7e87d2cfd626.png">

**Comment by andrejbo** [comment]
Why it happens? Is normal or we will have a fix for that?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
