### ISSUE TITLE
[Feature Request] Support facet_zmin and facet_zmax in px.imshow

### ISSUE THREAD

**Issue by ZeyuSun** [plotly/plotly.py#3382]
## Motivation
Multichannel images often have drastically different ranges. The current interface of `px.image` does not allow customizing `zmin` and `zmax` for each facet.

## Suggested implementation
Add arguments `facet_zmin` and `facet_zmax` that take lists of whatever input types `zmin` and `zmax` support, then
1. for `binary_string == True`, change
https://github.com/plotly/plotly.py/blob/0a833291f2b01b77cecf2a168936aa90e17acaed/packages/python/plotly/plotly/express/_imshow.py#L461-L463
to (just an idea, not tested)
```python
if animation_frame is None:
    facet_iterables = range(nslices_facet)
    facet_col_new = 0
else:
    facet_iterables = [(slice(None), i) for i in range(nslices_facet)]
    facet_col_new = 1

img_rescaled = np.stack(
    [
        rescale_intensity(
            img[s],
            in_range=(facet_zmin[i], facet_zmax[i]),  # works only when facet_zmin is a list of scalar 0..255 (each facet is a single channel image)
            out_range=np.uint8,
        )
        for i, s in enumerate(facet_iterables)
    ],
    axis=facet_col_new,
)
```
2. for `binary_string == False`, change
https://github.com/plotly/plotly.py/blob/0a833291f2b01b77cecf2a168936aa90e17acaed/packages/python/plotly/plotly/express/_imshow.py#L403-L404

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
