### ISSUE TITLE
[Feature request] pattern fill for maps

### ISSUE THREAD

**Issue by upascal** [plotly/plotly.py#3383]
I know pattern fill is implemented for bar graphs. Can a similar feature be implemented for maps?
This is mostly for b/w printing

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
