### ISSUE TITLE
Passing a list of colors to hoverlabel-->bgcolor does not work for heatmaps

### ISSUE THREAD

**Issue by ThomasSchuetz** [plotly/plotly.py#3385]
Hi,
I would like to set different background colors for the hovertext in a heatmap. I found the `hoverlabel` dictionary and its key `bgcolor`, however it seems that this feature only works for single colors, despite the documentation stating that you can pass a list or an array.

The following example successfully sets the background color of the hovertext to orange:
```
fig = go.Figure()
fig.add_trace(
    go.Heatmap(
        x=[1,2],
        y=[1]*2,
        z=[0.3, 0.6],
        hoverlabel=dict(
            bgcolor="orange"
        )
    )
)
```

However, when I change the `bgcolor` to a list, it seems to be ignored as I get the default (dark grey) hovertext background color:

```
fig = go.Figure()
fig.add_trace(
    go.Heatmap(
        x=[1,2],
        y=[1]*2,
        z=[0.3, 0.6],
        hoverlabel=dict(
            bgcolor=["orange", "green"]
        )
    )
)
```

Am I maybe missing something?

Thank you very much in advance!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
