### ISSUE TITLE
2d plane not displayed using mesh3d

### ISSUE THREAD

**Issue by hagne** [plotly/plotly.py#3389]
When trying to plot a flat surface in the x or y plane the resulting plot is empty. I am using plotly 5.3.1 in jupyterlab in a conda environment with python 3.8.
Example:
```
import plotly.graph_objects as go

fig = go.Figure(go.Mesh3d(x=[0,1,1,0],
                        y=[1,1,1,1],
                        z=[0,0,1,1],
                        opacity=0.2,
                        color='black',
                  ))
fig.show()
```
Result:
![newplot-1](https://user-images.githubusercontent.com/11184861/133653748-876182b3-4ca1-48cf-96ae-41906b51640a.png)

It works for the z plane (swapping y and z in the example above):
![newplot-2](https://user-images.githubusercontent.com/11184861/133653963-343e5301-e71c-41e8-937c-286413fd9e7d.png)

I managed to  work around this issue by playing with the vertex vectors, but I don't think this is very convenient or easy:
```
import plotly.graph_objects as go

fig = go.Figure(go.Mesh3d(x=[0,1,1,0],
                        y=[1,1,1,1],
                        z=[0,0,1,1],
                        opacity=0.2,
                        color='black',
                        i=[0, 0, 0, 1],
                        j=[1, 2, 3, 2],
                        k=[2, 3, 1, 3],
                  ))
fig.show()
```
Result:
![newplot-3](https://user-images.githubusercontent.com/11184861/133654714-a5fbe791-8d80-4123-80d3-a739213472f1.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
