### ISSUE TITLE
About scatter_matrix function in plotly.express

### ISSUE THREAD

**Issue by diligejy** [plotly/plotly.py#3390]
## Issue
I'm using scatter_matrix for iris data. However an error (of which message is that `AttributeError: module 'plotly.validators.splom' has no attribute 'DimensionValidator'`) occured.

I searched on google. However there's no page about this Error.

## Specifications
- Google colaboratory
- plotly version : 4.4.1

## Code to produce 
```{python}
import plotly.express as px
iris = px.data.iris()
iris
fig = px.scatter_matrix(iris)
fig.show()
```

## Error message
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-40-203912711277> in <module>()
      2 iris = px.data.iris()
      3 iris
----> 4 fig = px.scatter_matrix(iris)
      5 fig.show()

3 frames
/usr/local/lib/python3.7/dist-packages/_plotly_utils/importers.py in __getattr__(import_name)
     39         raise AttributeError(
     40             "module {__name__!r} has no attribute {name!r}".format(
---> 41                 name=import_name, __name__=parent_name
     42             )
     43         )

AttributeError: module 'plotly.validators.splom' has no attribute 'DimensionValidator'
```

**Comment by diligejy** [comment]
I found that the problem is the low version. 
When I used plotly version 5.3.1, The result was output normally.

Nevertheless, I would like to know if there is any other problem-solving method other than upgrading the version of the cause.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
