### ISSUE TITLE
Is it possible to use one dropdown menu to update another dropdown menu

### ISSUE THREAD

**Issue by forainychen** [plotly/plotly.py#3397]
As the question in the title, Is it possible to use one dropdown menu to update another dropdown menu?

i.e. I have two or more dropdown menu, like the example
https://plotly.com/python/dropdowns/#update-several-data-attributes

Is that a way to when making a selection in 1st menu, then the list in the 2nd menu is updated accordingly, then I can make a selection in 2nd menu to update the data?

I'm looking a way for offline mode, without dash or jupyter notebook.

Thanks.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
