### ISSUE TITLE
[Feature request] Be able to adjust the legend box width or height

### ISSUE THREAD

**Issue by WodenWang820118** [plotly/plotly.py#3400]
Hi, I've been searching around for a solution to adjust the legend box. For example, I could tweak the legend box's width and height. The figure reveals that a list of the long legends could correspond to the height or the width of the legend box. But, for now, I haven't found any solution if I want to put the legend in a specific position.
![legend](https://user-images.githubusercontent.com/48168793/135119094-d8f1fb53-a563-4d5e-b7b1-00635866cd9f.png)

What I've found:
1. If legends are a lot and by default vertical, the plot would make it slidable, but if I output the picture, some of the legends are cut off.
2. I could make the legend orientation horizontal, and it will be responsive to the plot length.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
