### ISSUE TITLE
Boxplots are transparent by default

### ISSUE THREAD

**Issue by chbk** [plotly/plotly.py#3404]
Using Plotly Express, I expected boxplots to be filled with the specified colors, not transparent colors.

This is what boxplots look like at the moment, using a default Plotly palette:

![boxplot_default](https://user-images.githubusercontent.com/7478535/135503250-fdd96f8b-d4b5-417d-8a8d-d8f1dce624d2.png)

This is what I expected:

![boxplot_expected](https://user-images.githubusercontent.com/7478535/135503244-d0ae0975-43d2-413a-acf8-df580393d38e.png)

Which is much more legible and more consistent with barplots:

![barplot](https://user-images.githubusercontent.com/7478535/135503225-c6f676aa-3275-4562-9e57-ba63a0fb0a9d.png)

I found no easy way to set the fillcolors to the actual specified colors. The colors are always more transparent by default.

**Comment by hechlera** [comment]
I know this is an old post, but since I just ran into that problem myself, here goes:

The color provided for boxplots sets the linecolor (borders), while the fillcolor defaults to the same color at half the opacity (which can be seen in the reference for box traces). I tried to find the toggle in the layout of the figure, and found this item

`fig.layout['template']['layout']['shapedefaults']`

Which is set to 0.5. You can change the opacity value but even though the new value persisted in the layout, the figure did not change.

The solution (as some stackoverflow commenters pointed out) is to set the fillcolor of the boxplot trace as an rgba with an alpha value of your choosing (1 for fully opaque). If you created the boxplots with plotly express, you can iterate through the traces, check their name for the group they represent and then set the fillcolor as described above.

`fill_colors = {'group_a':'rgba(225,190,106,0.8)',
              'group_b':'rgba(64,176,166,0.8)'}

for trace in fig.select_traces():
    
    group = trace['name']
    trace['fillcolor'] = fill_colors[group]`

That did it for me. Setting higher opacity values comes with the problem that the median line is barely visible.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
