### ISSUE TITLE
customdata/hovertemplate displays literal text with Histogram2d

### ISSUE THREAD

**Issue by Astrodude11** [plotly/plotly.py#3419]
My goal is to add custom hover data to a heat map using `px.density_heatmap`. The [documentation](https://plotly.com/python-api-reference/generated/plotly.express.density_heatmap.html) provides `hover_data` but the `hovertemplate` string does not include the data given in `hover_data`. 

Using the first heat map shown on the [Plotly 2D Histogram](https://plotly.com/python/2D-Histogram/) webpage as an example:

```
import plotly.express as px


df = px.data.tips()
fig = px.density_heatmap(df, x='total_bill', y='tip', hover_data=['size'])
print(fig.data[0].hovertemplate)
```

The output of hovertemplate is:

`total_bill=%{x}<br>tip=%{y}<br>count=%{z}<extra></extra>`

For the sake of comparison, the hovertemplate string using `px.scatter` does include `customdata`:

`total_bill=%{x}<br>tip=%{y}<br>size=%{customdata[0]}<extra></extra>`

Therefore, I tried to use `graph_objects` to explicitly define `customdata`  on `go.Histogram2d` to display the desired hover data like so:
```
import plotly.graph_objects as go
import plotly.express as px


df = px.data.tips()

fig = go.Figure(
    data=go.Histogram2d(
        x=df['total_bill'], 
        y=df['tip'],
        z=df['size'],
        histfunc='sum',
        customdata=[df['smoker']]
    )
)

fig.update_traces(
    hovertemplate='<br>'.join([
        'Bill $: %{x}',
        'Tip $: %{y}',
        'Size: %{z}',
        'Smokes: %{customdata[0]}'
    ])
)

fig.show()
```
However, as also reported by a user on the [Plotly Community Board](https://community.plotly.com/t/does-customdata-hovertemplate-not-work-with-histogram2d-with-mre-and-screenshot/56864), the literal text of `%{customdata[0]}` is displayed.

**Comment by lucasjamar** [comment]
Hi @empet, 

This makes sense if hover_data is a categorical column, but if a numeric column is provided, should the same aggregation function applied to z not also be applied to all numeric hover_data columns and be returned on hover? Otherwise, I dont see the point of having a hover_data and hover_name parameter in `px.density_heatmap`.

**Comment by nicolaskruchten** [comment]
Right now `hover_data` and `hover_name` are used in `px.density_heatmap()` (and other aggregating functions like `px.histogram()`) in marginal plots only.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by brandon-neth** [comment]
Howdy. This would be useful to me. I'd like it to be reopened if possible. I'm using version 6.3.1.
