### ISSUE TITLE
Is it possible to link a key stroke to a modebar button?

### ISSUE THREAD

**Issue by cwerner** [plotly/plotly.py#3451]
Hi and thanks for the library!

I was wondering if there is a way to define a key binding/ action that triggers a modebar button? I'm working with the image annotation code and a natural fit for the "erase active shape" button would be the `DEL` key, zoom in by the `+`, zoom out by the `-` etc.

This would make the user experience in an annotation dashboard so much nicer and annotations quicker.

Cheers,
C

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
