### ISSUE TITLE
How to control height of broken lines?

### ISSUE THREAD

**Issue by janosh** [plotly/plotly.py#3467]
How do I control the line height in titles and annotations with line breaks? I.e. how do I get the words "Simple" and "scatter" closer or further apart vertically in this example?

```py
import plotly.express as px

px.scatter(x=[0, 1, 2, 3, 4], y=[0, 1, 4, 9, 16], title="Simple<br>scatter")
```

![Screen Shot 2021-11-14 at 14 46 42](https://user-images.githubusercontent.com/30958850/141686080-216f38e4-fe19-4b7a-93d2-aef34db42d3b.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
