### ISSUE TITLE
Home button does not reset to default view with 3d plots

### ISSUE THREAD

**Issue by kurt-rhee** [plotly/plotly.py#3472]
Pressing the home button "reset camera to default" in the browser does not reset to the top down view specified by scene_camera.  The button instead resets the view to the default 1.25, 1.25, 1.25.

Here is a reproducible example.  The df data can be any x, y, z coordinate data.
 ```
           fig.add_trace(
                go.Scatter3d(
                    x=df['x'],
                    y=df['y'],
                    z=df['z'],
                    mode='markers',
                    }
                )
            )

        fig.update_layout(
            scene_aspectmode='data',
            scene_camera={
                'eye': {
                    'x': 0,
                    'y': 0,
                    'z': 3
                }
            }
        )
        if display:
            fig.show(renderer='browser')
```
![image](https://user-images.githubusercontent.com/33131958/142037245-cb67bca7-4526-4ab7-98b2-ad33a8d9f531.png)

**Comment by DavideLentini** [comment]
Hi ! Were you able to make this modification in the end ? I would like to do it too but I have the same problem as you.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
