### ISSUE TITLE
Unable to set compression level in `plotly.io.write_image`

### ISSUE THREAD

**Issue by twoletters** [plotly/plotly.py#3492]
I searched extensively for a way to set the compression level when saving charts to PNG/JPG files using function `plotly.io.write_image`. Function `plotly.express.imshow` has a parameter `binary_compression_level` that seems to fit the bill, but `plotly.io.write_image` does not. I could not figure out if this could be achieved using scopes.

This feature would be useful to control disk/cpu usage when saving large amounts of images, which is my purpose here. What say you?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
