### ISSUE TITLE
Plotly Express scatter mapbox plot saved as HTML is not rendering on iOS

### ISSUE THREAD

**Issue by spkompella** [plotly/plotly.py#3496]
I am having an issue with html maps rendering on iOS. I have saved my scattermapbox plots as .html files and hosted them for mobile access but the maps appear completely blank on iOS devices. Plots are rendering fine in a desktop browser and on Android

Plotly version: 5.3.1
iOS version: 15.0.2/15.1
Browser: Safari and Chrome

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
