### ISSUE TITLE
Allow to set set axis scaleanchor and scaleratio in template

### ISSUE THREAD

**Issue by messismore** [plotly/plotly.py#3499]
It is currently not possible to set an axis' [scaleanchor](https://plotly.com/python/reference/layout/xaxis/#layout-xaxis-scaleanchor) and [scaleratio](https://plotly.com/python/reference/layout/xaxis/#layout-xaxis-scaleratio) in a template:

```python
import plotly.io as pio
import plotly.graph_objects as go

 pio.templates["constrained_axes"] = pio.templates["plotly_white"]
 pio.templates["constrained_axes"].update( go.layout.Template(
    layout_title="constrained_axes",
    layout_xaxis=dict(
        visible = False,
    ),
    layout_yaxis=dict(
        visible = False,
        scaleanchor = 'x',  #
        scaleratio = 1      #  these are currently ignored
    )
))
```
Using the template in a figure will render axes with different scales:

```python
fig = px.line(df, 
        x="x", 
        y="y", 
        color="color", 
        template="constrained_axes")
fig.show()
```

It should render like this:
```python
fig.update_yaxes(scaleanchor = "x", scaleratio = 1)
fig.show()
```

I'm plotting online.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
