### ISSUE TITLE
Plotly install error in fresh Anaconda

### ISSUE THREAD

**Issue by pepo83** [plotly/plotly.py#3503]
Hello, I have the following problem:

Fresh installation of Anaconda3-2021.11-Windows-x86_64.

When I try to install plotly with: conda install -c plotly plotly

The following error occurs:

Downloading and Extracting Packages
plotly-5.4.0         | 6.8 MB    | ############################################################################ | 100%
tenacity-8.0.1       | 34 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File ".\Anaconda3\Lib\site-packages\plotly\io\__init__.py", line 54, in <module>
  File ".\Anaconda3\Lib\site-packages\plotly\plotly\__init__.py", line 4, in <module>
  File ".\Anaconda3\Lib\site-packages\_plotly_future_\__init__.py", line 43, in _chart_studio_error
ImportError:
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
