### ISSUE TITLE
Option for start_cell position in plotly express faceted plot

### ISSUE THREAD

**Issue by dcnadler** [plotly/plotly.py#3504]
I am using plotly express (`px.line()`) to make a figure with subplots using `facet_row` and `facet_col`. I want to add additional traces to various subplots.

However, I noticed that the row ordering is opposite of what I expect - row 1 is at the bottom. I don't see any way to change this when using plotly express (seems to be hard-coded [here](https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/express/_core.py#L2308)).

It's not just that I find it unintuitive from a matrix perspective, it's strange that it's the opposite of the `make_subplots` function's default for `start_cell` (it's default is 'top-left').

Besides what I personally might expect the default to be, it would be great to have the ability to pass the start_cell option through plotly express. Thanks!

**Comment by nicolaskruchten** [comment]
I can see why this is annoying. I don't really think we should add a `start_cell` kwarg to every single PX method, so maybe a way forward would be to add such an option to the `px.defaults` global object and then have PX reference this object when rendering. We haven't used this pattern before but we'll likely need to soon in order to avoid a kwarg explosion (more so than we already have!)

**Comment by m-ganko** [comment]
Is there any reason for px to have `start_cell="bottom-left"` for facet plots? Maybe it could be pernamently changed to `make_subplots` default?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
