### ISSUE TITLE
Bubble Scale/Marker Size Legend

### ISSUE THREAD

**Issue by knoam** [plotly/plotly.py#3505]
Is there some way to generate a legend for bubble size in plotly express? I realize you could do this by doing `color='size_col',  size='size_col'` for categorical columns, but it would be good to have bubble size as a continuous variable that can be defined separately from color variable.

Somethine like this (copied from [here](https://www.d3-graph-gallery.com/graph/bubble_legend.html))
<img width="324" alt="image" src="https://user-images.githubusercontent.com/64984232/145255006-1858a8d8-3885-41f8-bb35-4255a3a1e11d.png">

**Comment by nicolaskruchten** [comment]
There's no feature for this at the moment, and it would likely have to be implemented in Plotly.js first before being usable in Plotly.py/Plotly Express. See the following related issue:
- https://github.com/plotly/plotly.js/issues/5099

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by cbadams2** [comment]
I would advocate for this to be reopened, as the issue remains open in Plotly.js (https://github.com/plotly/plotly.js/issues/5099). Given that several of the scatter functions in Plotly take size (and color) as arguments to determine the visual appearance of scatter points, it seems logical to keep the request for a legend to explain the visual appearance open (and abreast of the progress in Plotly.js).
