### ISSUE TITLE
Why Does Hist Produce Such Large Image Files?

### ISSUE THREAD

**Issue by knoam** [plotly/plotly.py#3512]
Thank you for this wonderful library. I have a question about plotly express hist function: why does it keep so much data when binning a large dataset? For example, see the following code:

```python
import pandas as pd
import numpy as np
pd.options.plotting.backend = 'plotly'

for size in 10**np.array([1,2,3,4,5,6,7]):
    fig = pd.Series(np.random.random(size)).hist()
    fig.write_html(f'tmp/test_{size}.html')
```
The last file is 196MB large. When it's embedded in a Jupyter notebook, the notebook becomes unresponsive.

As workarounds, one could use pd.value_counts() first (if not too many individual values) or np.histogram, but those slow down the workflow. Since the figure is summarizing counts in each bin, why does the resulting figure/file need to be so large?

Thanks!

**Comment by knoam** [comment]
Is there a reason for Plotly.js to keep the individual values? Would it make more sense to always have it accept pre-computed bin values?

**Comment by nicolaskruchten** [comment]
There's no great reason for this other than that these libraries evolved in a particular order and we've made commitments not to make breaking changes so it's hard for us to quickly get to what, with the benefit of a few years of hindsight, would be a better design :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by wallykop** [comment]
Hi, @gvwilson! 
This issue is still a concern. I experienced this bug using plotly.py version 5.20.0
