### ISSUE TITLE
[Feature] Apply histfunc to marginal histogram for 2d histogram and 2d contour

### ISSUE THREAD

**Issue by lucasjamar** [plotly/plotly.py#3521]
Python: 3.8
Plotly: 5.4.0

For 2d histograms and contour plots, plotly always applies count for the marginal plots regardless  of the z value and histfunc provided.
It would be awesome if z and the histfunc were provided to the marginal histograms. Example code:

Thanks for plotly!
```
import plotly.express as px
df = px.data.tips()

fig = px.density_heatmap(df, x="size", y="tip", z="total_bill", histfunc="sum", marginal_x="histogram", marginal_y="histogram")
```
![image](https://user-images.githubusercontent.com/39372418/146562209-27ff07c0-e686-4ca1-96b6-ed2aa77f9a3f.png)

**Comment by pcsee** [comment]
Any update on this? It would be real great if sum feature is available

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
