### ISSUE TITLE
graph_objects: Text on Heatmap not showing up

### ISSUE THREAD

**Issue by aaronsl-hku** [plotly/plotly.py#3527]
Long story short: Using plotly 5.5.0, I tried to run the exact code from the [tutorial](https://plotly.com/python/heatmaps/#text-on-heatmap-points) and the text does not show up (unlike what is shown in the tutorial).

[https://plotly.com/python/heatmaps/#text-on-heatmap-points](https://plotly.com/python/heatmaps/#text-on-heatmap-points)

My output
![image](https://user-images.githubusercontent.com/74041173/147208693-992335e1-d44e-4fef-a6af-2a6de2bcf8eb.png)

**Comment by nicolaskruchten** [comment]
Can you tell me a bit about the environment you're running in? Jupyter Notebook? Jupyter Lab? Colab or something hosted like that? Which version of the notebook system?

I ask because in some environments eg Jupyter Lab 2.x, you must manually install an updated extension for new features to work, every time you upgrade.

**Comment by aaronsl-hku** [comment]
> Can you tell me a bit about the environment you're running in? Jupyter Notebook? Jupyter Lab? Colab or something hosted like that? Which version of the notebook system?
> 
> I ask because in some environments eg Jupyter Lab 2.x, you must manually install an updated extension for new features to work, every time you upgrade.

Hello Nicolas, I am on Jupyter Lab 3.0.16.

**Comment by mattppal** [comment]
I'm experiencing the same issue. Additionally, when I try to use `texttemplate` per [the documentation](https://plotly.github.io/plotly.py-docs/generated/plotly.graph_objects.Heatmap.html), I get the following error:

`ValueError: Invalid property specified for object of type plotly.graph_objs.Heatmap: 'texttemplate'`

**Comment by samrshook** [comment]
I was having the same issue where no annotation appeared while making a px.imshow() heatmap in VS Code Jupyter Notebook. 
Spent a lot of time troubleshooting and thinking I was crazy.
When I switched over to a Kaggle notebook, everything was working perfectly fine with the same code. 
All I can recommend for anyone experiencing the same thing is to switch up your environment

**Comment by nicolaskruchten** [comment]
Remember to upgrade Plotly to the latest version if you're seeing some behaviour that works in the docs and not in your setup. The current latest version is 5.6 and the troubleshooting guide is here: https://plotly.com/python/troubleshooting/

**Comment by mattppal** [comment]
I did try updating plotly to 5.6. The issue persists.

**Comment by jcarusone1650** [comment]
Seeing the same thing implemented the same way as @mattppal on 5.5 and 5.6

**Comment by jcarusone1650** [comment]
Heard from dash support on this one @mattppal and their solution does work.
 
I looked into this and it looks like, because this is a relatively new feature, it hasn't been implemented into Dash yet. However, you can override the version of Plotly that Dash installs by placing the most up-to-date version of Plotly.js in your assets folder. Simply cd into your assets folder and curl https://cdn.plot.ly/plotly-2.10.0.js -o plotly-2.10.0.js to get the most up-to-date version.

**Comment by mattppal** [comment]
@jcarusone1650 Thanks for the update!

**Comment by admivsn** [comment]
I am also still having this issue

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
