### ISSUE TITLE
how to use Trisurf Plots in Python in javascript app

### ISSUE THREAD

**Issue by tahere-yaghubi** [plotly/plotly.py#3530]
i want to use Trisurf Plots in Python in javascript app.

**Comment by empet** [comment]
If you are referring to the function `ff.create_trisurf()`, illustrated  in this tutorial 
[https://plotly.com/python/trisurf/](https://plotly.com/python/trisurf/),  then it is not recommended  to search for a Javascript equivalent, because it is now obsolete. 
A trisurf can be defined as a mesh3d [https://plotly.com/javascript/3d-mesh/](https://plotly.com/javascript/3d-mesh/),
but previously you must triangulate the surface.  With Python, we are using `scipy.spatial.Delaunay` for triangulation, as in this notebook [https://chart-studio.plotly.com/~empet/15522](https://chart-studio.plotly.com/~empet/15522). 
A github search for `Delaunay triangulation` returns 97 Javascript repos destinated to this task:
[https://github.com/search?l=JavaScript&q=Delaunay+triangulation&type=Repositories](https://github.com/search?l=JavaScript&q=Delaunay+triangulation&type=Repositories)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
