### ISSUE TITLE
Chart-Studio not updating existing charts as of DEC 23

### ISSUE THREAD

**Issue by wyczolko** [plotly/plotly.py#3532]
chart_studio.plotly for python not allowing update of existing chart.
I experienced this same problem in the past, oddly enough around DEC 2020, and it was resolved but I have just started to experience this message again :

-PlotlyRequestError: Sorry, a file named ‘Cc1IVOLRVOLAnimation1.html’ already exists-

An example call of the use case:
py.plot(cf.subplots(list(figlst.values()),shape=(math.ceil((len(figlst.keys()))/3),3),subplot_titles=list(figlst.keys())),filename=‘IndPerf’+str(i)+’_.html’)
I run this every day with no problem and it just started to bug out and won’t allow me to update any of my charts. I would greatly appreciate someone looking into the issue for resolution.

**Comment by empet** [comment]
Chart Studio is back to normal.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
