### ISSUE TITLE
Option to only show axis labels when a gridline is present

### ISSUE THREAD

**Issue by grantackerman1** [plotly/plotly.py#3540]
It would be great if you had an option to only show axis labels when a gridline is present. When I get rid of background color, I'm running into an issue where a y-axis label is showing but there isn't an associated gridline, presumably because the top of the plot is at $2.60 exactly. My current workaround is to manually adjust the yaxis slightly. However, I'm trying to programmatically generate a lot of charts like this, and it isn't ideal to need to manually check each graph for this issue. Thanks!

<img width="1022" alt="Screen Shot 2022-01-06 at 1 09 25 PM" src="https://user-images.githubusercontent.com/37025199/148453139-00d64a69-7024-4fcb-b66f-5a3dd36c5b06.png">

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
