### ISSUE TITLE
Misbehaviour using plotly with ipywidgets output widget.

### ISSUE THREAD

**Issue by cmartinotti** [plotly/plotly.py#3541]
I'm using JupyterNotebook to create little applications through Ipywidgets. 
When running the code : 
```
##CELL1##
import plotly.express as px
import pandas as pd
import ipywidgets as widgets

out=widgets.Output()
dfa=pd.DataFrame({'x':[1,2,3],'y':[1,2,3]})


with out:
    out.clear_output(wait=True)
    print('ciao')
    fig=px.scatter(dfa,x='x',y='y', width=800, height=400 )
    fig.show()

out
```
I expect the output widget to capture the fig.show() output, but I instead get the print output followed by an empty area. 
The weirdest thing is that I used similar code multiple times in the past to craft interactive applications and they are actually still working.  The weirderst thing is that if I run CELL 1 i get an empty output, but then if I run CELL2:
```
#CELL 2 
with out:
    out.clear_output(wait=True)
    print('ciao')
    fig=px.scatter(dfa,x='x',y='y', width=800, height=400 )
    fig.show()

out
```
The output of CELL2 is still empty, but the output from CELL1 updates to what should have been the output of CELL2.

Furthermore this seems to be a problem that affects different users differently, in fact running CELL1 I have been already told that:
a) it works on JupyterLab but not on JupyterNotebook (for me it works in neither)
b) it can be solved adding     `fig.show(renderer='notebook')` (doesn't work for me either)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
