### ISSUE TITLE
Smith charts need real and imaginary axis inversion

### ISSUE THREAD

**Issue by fdion** [plotly/plotly.py#3544]
# Current

Smith charts (https://plotly.com/python/smith-charts/) allows one to plot z (impedance chart) from real and imaginary numbers.

This covers only one of 3 common scenarios (impedance, admittance, immittance).

# Proposal

Smith charts usually are drawn for z (impedance chart), y (admittance chart) or both z and y (immittance chart). The admittance is an impedance chart rotated 180 degrees, while immittance is a combination of both charts in one.

With a way to reverse both real and imaginary axis on smith charts or to rotate by 180 degrees, it should be possible to properly make all 3 chart types.

**Comment by nicolaskruchten** [comment]
This is certainly a good idea, and would need to be implemented in Plotly.js. No one from the Plotly team is likely to work on this in the near future, so the most likely way this gets done is via a community contribution. Smith charts were originally introduced in this PR: https://github.com/plotly/plotly.js/pull/5956

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
