### ISSUE TITLE
Expose event data serialization functions in plotly.js

### ISSUE THREAD

**Issue by rmorshea** [plotly/plotly.py#3550]
I have a need to serialize the events which plotly emits. I noticed that the Jupyter widget for Plotly already does [exactly this](https://github.com/plotly/plotly.py/blob/cfad7862594b35965c0e000813bd7805e8494a5b/packages/javascript/jupyterlab-plotly/src/Figure.ts#L1295-L1300). It would be great if these functions could be exported by `plotly.js` since they seem generally useful.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
