### ISSUE TITLE
Plotly graph in jupyterlab notebook after exporting to html not interactive

### ISSUE THREAD

**Issue by Zhekun-Xiong** [plotly/plotly.py#3552]
Hi,

I have plotly interactive graphs on a jupyterlab notebook, it works fine on jupyterlab. But when I tried to export the notebook to html (File -> Export Notebook As -> Export Notebook to html), the html file opened has the graph but it's not interactive anymore.

Below is the code snippet I have in the notebook

```
import plotly.io as pio
pio.renderers.default = "jupyterlab"

import plotly.express as px

fig =px.scatter(x=range(10), y=range(10))
fig.show("jupyterlab")
```

And when I opened the Chrome develop tool, it shows below
![image](https://user-images.githubusercontent.com/54915167/149633681-ea2c6b40-674b-42d3-abbb-62cf590cbbfa.png)

Do you know if any way to enable that the plotly graph shown interactively in the exported jupyterlab notebook html file? Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
