### ISSUE TITLE
jupyter plotly javascript error happen.

### ISSUE THREAD

**Issue by harimax** [plotly/plotly.py#3553]
I'm japanese univercity student.

suddenly plotly can't show graphs.
error code"Javascript Error: Cannot set properties of null (setting '0')"
But strangely, 

`import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig.show()  ` 

this code can show graph. 
on the other hand,

`import plotly.graph_objects as go

import pandas as pd

z_data = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/api_docs/mt_bruno_elevation.csv')

fig = go.Figure(data=[go.Surface(z=z_data.values)])

fig.update_layout(title='Mt Bruno Elevation', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()`

this code can't show  graph.
I can't how to solve this error!

Development environment
windows  10 
jupyter lab   3.2.1
plotly           5.5.0
ipywidgets   7.6.5

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
