### ISSUE TITLE
Front and back dots overlap when rotating

### ISSUE THREAD

**Issue by brianpenghe** [plotly/plotly.py#3556]
I've been using px.scatter_3d to generate 3D plots.
One thing I realized is that the dots supposed to be in the front are not always so. When rotating, which dots block the vision of which dots are dependent on pre-decided front-back relationships but not 3D coordinates. Is that true?

Is there a way to show a real 3D visualization of the plots where dots are farther away from us are hidden behind nearer dots in the way? 

I've attached the link to my saved 3D plot if that makes it clearer.
https://github.com/chanzuckerberg/cellxgene/files/7850192/220111FetalLung_3D_UMAP.html.zip

And this issue is related to this one https://github.com/plotly/plotly.js/issues/1267

Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
