### ISSUE TITLE
Merging templates with annotations is counterintuitive

### ISSUE THREAD

**Issue by netgull** [plotly/plotly.py#3570]
Current behaviour: Merging two templates with one annotation each merges the annotations into one in the final template.
The two annotations have different names.

Expected behaviour from documents (possibly wrongly): 
- Templates can be used to add default annotations to figures.
- Templates can be combined arbitrarily

From that I would expect annotations of merged templates to append as new items in the layout.annotations list of the final template - particularly if they have different names.
I appreciate that complicates the merging code and opens up a lot of subcases, so just bringing it up for consideration.

Code strub reproducing the above:
```
import plotly.io as pio
import plotly.graph_objects as go
from pprint import pprint

pio.templates['a'] = go.layout.Template()
pio.templates['a'].layout.annotations = [
    go.layout.Annotation(name="text_boxa",
                         x=0, y=0,
                         bordercolor='black', bgcolor='white',
                         )]
pio.templates['b'] = go.layout.Template()
pio.templates['b'].layout.annotations = [
    go.layout.Annotation(name="draft_wm_b", text="DRAFT_B",
                         textangle=-30, opacity=0.1,
                         x=1, y=1
                         )]

c = pio.templates.merge_templates(pio.templates['a'], pio.templates['b'])
pprint(c)
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
