### ISSUE TITLE
Candlestick increasing / decreasing color issue

### ISSUE THREAD

**Issue by wargx** [plotly/plotly.py#3571]
Hello,

First of all, thank you for making such awesome library!

Sometimes increasing / decreasing color of candles is wrong.
Here is an example when all OHLC values are lower and consistent between two dates but candle is green and even 
marker for close column shows "up":

![candlestick_error_1](https://user-images.githubusercontent.com/10848059/151357158-267d8b1a-14df-40d5-8742-0402a91f383c.png)
![candlestick_error_2](https://user-images.githubusercontent.com/10848059/151357160-e87968d3-7764-49f2-8eec-cd62bcf490ec.png)

To eliminate possible problems caused by gaps in data tried to draw for just those few days, but got the same result:

![candlestick_error_3](https://user-images.githubusercontent.com/10848059/151357162-42c52dfb-3cc3-407a-a8cb-62d786e33f37.png)
![candlestick_error_4](https://user-images.githubusercontent.com/10848059/151357164-96471470-4aab-4ddf-9515-d6cf40f62ba2.png)

Parameters for chart are basic minimum:

```python
go.Candlestick(  
    x=data[columns["date"]], open=data[columns["open"]],  
    high=data[columns["high"]], low=data[columns["low"]],  
    close=data[columns["close"]], name="OHLC"  
)  
```

which is added in `make_subplots` figure with 1x1 grid and no parameters for testing purposes.

data used: [dji.csv](https://github.com/plotly/plotly.py/files/7950406/dji.csv)

**Comment by lucasjamar** [comment]
Hi,

There is nothing wrong with your plots. Candlesticks are green when Close > Open and red inversely.

https://en.wikipedia.org/wiki/File:Candlestick_chart_scheme_03-en.svg

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
