### ISSUE TITLE
In Sankey Diagram, node property color and width does not work with array input.

### ISSUE THREAD

**Issue by ylee197** [plotly/plotly.py#3574]
From the library, 
The node property 'color' and 'width' in line can have array input. 
However, it seems like not working. 
Is there any way to apply different node line width and color to the each node?

Thanks.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
