### ISSUE TITLE
Plot's saved image is resampled and details are lost.

### ISSUE THREAD

**Issue by Nemecsek** [plotly/plotly.py#3603]
I produce a histogram plot to show how some power values exceed a threshold.
This is what I see onscreen  (snapshot with Spectacle in Ubuntu):
![screen_snapshot](https://user-images.githubusercontent.com/25978536/155519957-b704c06c-a019-4cb3-b6e8-57e2fcaf32e4.png)
As you can see, on the right of the red line there are some outliers.

Saving the image by pressing the Camera  icon without changing any parameter, these details are lost:
![plotly_save](https://user-images.githubusercontent.com/25978536/155520093-3f421ae3-84c5-4d30-bc9b-420003e03d3a.png)

I tried to save the image with `pio` instead:
```python
import plotly.io as pio  # uses kaleido
...
pio.write_image(fig, 'filename.png', width=2000, height=750) 
```
and at high resolution the details are again missing:
![2000pixel](https://user-images.githubusercontent.com/25978536/155520628-02d8b08f-3b35-44b2-9dc5-81de6a5391d2.png)

At a lower resolution (width=1000px, height=375), they are shown:
![1000pixel](https://user-images.githubusercontent.com/25978536/155520757-e43b6765-7026-4f7c-b286-93563d8cfca6.png)

I understand that it is a problem with bitmap resampling, but results should be consistent and possibly based on what it is seen onscreen. A customer of mine complained that he couldn't see the outliers in a couple of plots out of a dozen, while onscreen I could see them all.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
