### ISSUE TITLE
px.density_mapbox does not show the data point if z value is "1"

### ISSUE THREAD

**Issue by RunQi-Han** [plotly/plotly.py#3604]
While using `px.density_mapbox` to show heatmap, if z value is '1', this data point will not show up on the map.

For example, the sample code below should show three data points:
```
import pandas as pd
import plotly.express as px

data = {'Latitude': [54, 52,51], 'Longitude': [-114, -106,-97],'Color':[1,2,3]}
df = pd.DataFrame(data=data)

fig = px.density_mapbox(df, lat='Latitude', lon='Longitude', z='Color', radius=30,
                        center=dict(lat=52, lon=-97), zoom=2.5,
                        mapbox_style="stamen-terrain")
fig.show()
```
The result is as below:
  - the point(54, -114) with z =1 (color) does not show up on the chart
<img width="916" alt="image" src="https://user-images.githubusercontent.com/77292603/155581878-8642e1b1-5397-4ff1-84d7-56d255acffe6.png">

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
