### ISSUE TITLE
Traces on px.histogram with the same value in the list produce square blobs instead of one bar

### ISSUE THREAD

**Issue by jayceslesar** [plotly/plotly.py#3608]
`px.histogram` calls with values of only one value produce plots with huge square traces instead of one bar.

```py
import plotly.express as px


diffs = [0.0100 for _ in range(10000)]

fig = px.histogram(diffs)
fig.update_layout(title='test', title_x=0.5, font_size=10)
fig.update_layout(showlegend=False)
fig.update_xaxes(title='value', range=[0, .1], tick0=0, dtick=0.01)
fig.show()
```
Produces
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/47452474/155997257-d5cab031-8959-4e71-b7ac-654806db2a93.png">

Adding a dummy value to the diffs like `diffs = [0.0100 for _ in range(10000)] + [0.011]`. This is kind of a solution but is more of a bandaid.
produces
<img width="1758" alt="image" src="https://user-images.githubusercontent.com/47452474/155997569-01dfb553-924d-4659-a73b-ea3a3f459bfb.png">

**Comment by alexcjohnson** [comment]
In fact what's being shown here *is* one bar, but because we have no information about the width or precision of the distribution when there's only one value, the bin size we fall back on is 1 - far larger than the axis range you set, but there would be all sorts of issues if we tried to use the axis range as part of guessing the bin size.

To recover the bin size you want, specify it explicitly:
```py
fig.update_traces(xbins=dict(size=0.001))
```
