### ISSUE TITLE
go.Contour() allow list as contour levels

### ISSUE THREAD

**Issue by janosh** [plotly/plotly.py#3610]
The [Customizing Size and Range of a Contour Plot's Contours](https://plotly.com/python/contour-plots/#customizing-size-and-range-of-a-contour-plots-contours) example shows how to set a `start`, `end` and `size` to determine at which z-values contour lines are drawn. It would be much more flexible if the `contours` kwarg accepted a list of z values as a lot of data has power or exponential relationships where equidistant contour lines don't make much sense. This is also how `matplotlib` does it (see the `levels` kwarg of [`plt.contour()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.contour.html)).

```py
import plotly.graph_objects as go

fig = go.Figure(data =
    go.Contour(
        z=[[10, 10.625, 12.5, 15.625, 20],
           [5.625, 6.25, 8.125, 11.25, 15.625],
           [2.5, 3.125, 5., 8.125, 12.5],
           [0.625, 1.25, 3.125, 6.25, 10.625],
           [0, 0.625, 2.5, 5.625, 10]],
        colorscale='Hot',
        contours=dict(
            start=0,
            end=8,
            size=2,
        ),
        # contours=[1, 2, 5, 10], # not supported but would be great to have
    ))

fig.show()
```

![contour](https://user-images.githubusercontent.com/30958850/156226441-db556638-5e73-4ab3-9aaf-bed355d6fce3.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
