### ISSUE TITLE
Histogram in scatterplot interferes with setting marker size

### ISSUE THREAD

**Issue by tlw1876** [plotly/plotly.py#3614]
Pandas launch of a plotly plot shown below fails to set the marker size if I specify a margin_y histogram.

fig = df.plot.scatter(x=xAxis, y=testId,
                                  color=df.pf_stat,
                                  color_discrete_map={
                                      "P":"black", 
                                      "FAIL":"red", 
                                      "c":"blue", 
                                      "a":"goldenrod"},
                                  symbol=df.computer_name,
                                  hover_data = hover_data,
                                  title = title,
                                  marginal_y = "histogram",
                                  labels = {
                                      testId:testGroupAndName[1]
                                  })

fig.update_traces(marker={"size":self.markerSize}) # this fails if I define the margin_y above.  Otherwise it works

Failure message: builtins.ValueError: Invalid property specified for object of type plotly.graph_objs.histogram.Marker: 'size'

It appears that it's attempting to set a marker size on the histogram and not on the main graph itself

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
