### ISSUE TITLE
Mesh3d alphahull is broken

### ISSUE THREAD

**Issue by cstenkamp** [plotly/plotly.py#3615]
In version 4.14.3, `alphahull` algorithm for `Mesh3d` seems broken - the examples at https://plotly.com/python/3d-mesh/ also don't render.

Minimal example (from the docs):
```
import plotly.graph_objects as go
import numpy as np

pts = np.loadtxt(np.DataSource().open('https://raw.githubusercontent.com/plotly/datasets/master/mesh_dataset.txt'))
x, y, z = pts.T

fig = go.Figure(data=[go.Mesh3d(x=x, y=y, z=z,
                   alphahull=5,
                   opacity=0.4,
                   color='cyan')])
fig.show()
```
See also https://stackoverflow.com/q/70825818/5122790

**Comment by archmoj** [comment]
Thanks for the report.
This is now addressed at `plotly.js` level:  https://github.com/plotly/plotly.js/releases/tag/v2.10.1 so the fix would be available in the next `plotly.py` release.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
