### ISSUE TITLE
[Feature Request] Add "auto" option to rangebreaks

### ISSUE THREAD

**Issue by YasserHassan** [plotly/plotly.py#3621]
It'd be much better to be able to automatically hide the missing dates/times from the chart instead of letting the developer identify and provide that data via `rangebreaks`. Letting the chart identify the generated dates/times that do not exist in the provided data not only could save development time but would also be more reliable. That would make the chart much easier to use for applications like financial charts where hiding non-trading dates/times is the norm and there are irregular off days/times that may change from year to year or market to market especially with short trading days where `rangebreaks` patterns would not do the job.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
