### ISSUE TITLE
[BUG] add_hline and add_vrect rendering incorrectly

### ISSUE THREAD

**Issue by BlkPingu** [plotly/plotly.py#3623]
Python 3.9
Plotly 5.6.0

[The tutorial on `add_hline` and `add_vrect`](https://plotly.com/python/horizontal-vertical-shapes/) is providing code snippets.

```
import plotly.express as px

df = px.data.iris()
fig = px.scatter(df, x="petal_length", y="petal_width")
fig.add_hline(y=0.9)
fig.add_vrect(x0=0.9, x1=2)
fig.show()
```

Is supposed to produce a figure like this:
![newplot](https://user-images.githubusercontent.com/28692167/157447927-f8374f4f-39dd-495b-8a27-ed3091a06950.png)

Instead it's producing 
<img width="1323" alt="Screen Shot 2022-03-09 at 14 01 16" src="https://user-images.githubusercontent.com/28692167/157447961-79f92330-06b8-4448-9d63-2858deb1df8d.png">

There are issues on Stackoverflow about this reporting the [same issue months ago](https://stackoverflow.com/questions/65846866/plotly-how-to-add-vertical-line-to-plotly-plot
).

**Comment by takoika** [comment]
I can not reproduce the problem with Python 3.9 and Plotly 5.6.0. The problem may be already fixed at newer version. Can you try with newer version?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
