### ISSUE TITLE
No vertical orientation option for bullet shaped Indicator gauge

### ISSUE THREAD

**Issue by kimvanwyk** [plotly/plotly.py#3633]
The deprecated *create_bullet* method of the **figure_factory** module accepts an *orientation* argument to produce vertically oriented bullet graphs, as indicated [here](https://plotly.com/python/v3/bullet-charts/).

The recommended way to make a bullet chart in v4 is to use the *[Indicator](https://plotly.com/python/bullet-charts/)* class from the **graph_objects** module with a *shape* argument of "bullet". The *Indicator* class doesn't however seem to include a similar orientation argument or option and appears to only do horizontally oriented bullet charts. 

It's very possible I just can't find it in the docs - but if it's no longer an option this may be possibly be a bug.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
