### ISSUE TITLE
[Feature Request] Allow to determine automatically ranges when axis min or max is manually set. 

### ISSUE THREAD

**Issue by ievgennaida** [plotly/plotly.py#3634]
Range for the x/y axis can be defined by the property 'range'.

`
fig.update_yaxes(range=[min, max])
`

**I would like to pass only max or min and other value should be determined automatically.**
Ex: 
range =  [None, 100]
or 
range =  [10, None]

**Use case:** 
Users can specify min or max by setting; ne value. It's fine when another is just calculated. 
**Current behaviour:**
Range is ignored when one of the numbers is None or NaN

**Comment by johnnybarrels** [comment]
+1 for this, would be immensely useful!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by tjnd89** [comment]
@gvwilson This looks like it was added in version 5.17 as part of the `autorangeoptions`.
