### ISSUE TITLE
Margin pad color problem

### ISSUE THREAD

**Issue by Adam-Antios** [plotly/plotly.py#3640]
When I embed a Plotly figure into Streamlit that includes a value for `margin_pad`  greater than 0 then the padding can be rendered with a different color.

More specifically, in the case of Streamlit, then when I use the Plotly Dark them, and the Streamlit app also uses its dark theme then a grey area is rendered around the figure. The same happens when I use the Plotly White (or ggplot2 for that matter) and the Streamlit light theme respectively. Both cases can be seen in the following images.

When using dark themes, then If I manually set the following properties

```
paper_bgcolor='#000000',
plot_bgcolor='#000000',
```

and thus use specific background colors, then the problem is solved but I don't understand why it exists in the first place when Plotly figures are produced in Streamlit.

The fact that this issue arises under specific circumstances makes me think that it is a bug. Is that so?

Upon further investigation I think this might be related to this [thread](https://discuss.streamlit.io/t/plotly-templates-dont-work-properly/17593).

![Screenshot 2022-03-23 181448](https://user-images.githubusercontent.com/17729838/159746285-466ef46f-8703-434a-95c6-885a0ea8c205.png)

![Screenshot from 2022-03-26 21-33-57](https://user-images.githubusercontent.com/17729838/160254537-47b58dd8-165d-42ca-bc5a-ccdd5cb191fe.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
