### ISSUE TITLE
[Feature Request] Routing Tables for Plotly

### ISSUE THREAD

**Issue by Sulstice** [plotly/plotly.py#3644]
Hello,

So recently to explain my software architecture I have been using the visualization of routing tables. 

https://docs.luos.io/docs/luos-technology/services/routing-table

Check out this example from luos. Could do this be a feature in plotly perhaps or is there a way to do this do you think?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
