### ISSUE TITLE
[Feature Request] Dynamic marker_color groups 

### ISSUE THREAD

**Issue by matanper** [plotly/plotly.py#3650]
I'm creating plots that have a number of traces that I want to link together with the same color. 
I'm saving those plots and loading them in a number of systems that might have different themes, therefore I don't want to manually specify the color of each trace, I want to just "group" a few traces as having the same color, and let the template of each system to determine the colors.

[Here I asked about it in the forum with code to reproduce](https://community.plotly.com/t/apply-color-groups-for-multiple-traces/59950)

The best solution for me would be instead of defining "marker_color" define a "marker_color_index" which will later on be converted to the actual color when the plot is loaded where it is displayed.

![image](https://user-images.githubusercontent.com/9868530/161012599-f978688d-d7e5-4c3c-a383-492f2333cd17.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
