### ISSUE TITLE
3D Subplots in MATLAB bug?

### ISSUE THREAD

**Issue by emilyoross** [plotly/plotly.py#3671]
I encountered a problem creating 3D subplots using MATLAB and when I went to check the example I saw the same problem is actually happening on the example on the website at the bottom of this page: https://plotly.com/matlab/3d-subplots/

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
