### ISSUE TITLE
Feature Request : Functionality to hide empty leaves in tree map.

### ISSUE THREAD

**Issue by kambliameya** [plotly/plotly.py#3680]
Thanks for your interest in Plotly.py!

Before opening an issue, please search for existing and closed issues :)

**Please** accompany bug reports with a reproducible example. Please use the [latest version](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md) of plotly.py in your report unless not applicable.

Note that GitHub Issues are meant to be used for bug reports and feature requests only. Implementation or usage questions should be asked on [community.plotly.com](https://community.plotly.com/c/graphing-libraries/python/10) or on Stack Overflow (tagged [`plotly`](https://stackoverflow.com/questions/tagged/plotly)).

**Comment by kambliameya** [comment]
Kindly add a functionality to hide empty leaves in tree map.
For example : 
I have 5 categories with different depths belonging to 1 single product , i would ideally want to limit the drilling of tree map based on max level of that particular catergory. For example CATEGORY A has just 3 LEVELS vs CATEGORY D has 8 levels, so ideally i would want to limit the drillng of treemap for Catergory A limited to 3 levels instead of 8 with 5 blank levels (HIDE EMPTY LEAVES).

Is there any way to achieve this, or any support that i can expect in the future

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
