### ISSUE TITLE
DropDown to filter both Table and Scatter subplots

### ISSUE THREAD

**Issue by Metatr0n** [plotly/plotly.py#3684]
Hi!

First of all, thank you so much for Plotly!
It's amazing =)

My question is how could i create dropdown to filter both Table and Scatter subplot (like here [https://plotly.com/python/table-subplots/](url)) via "Cost per trans-USD" for example?

Code for dropdown to filter Table i found here: [https://stackoverflow.com/questions/69568250/interactive-filtering-data-table-in-plotly-by-using-a-dropdown/71930988#71930988](url). 

Thank you for your answers!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
