### ISSUE TITLE
Plot export with Static Background Image on Safari

### ISSUE THREAD

**Issue by xdev-x** [plotly/plotly.py#3685]
Hi,

First, thanks for Plotly/Dash framework, very nice and useful.

I found a bug with Plotly on Safari (tested with Chrome, it works correctly).

To reproduce the bug, go to [https://plotly.com/python/images/](https://plotly.com/python/images/#add-a-background-image) and use the modbar button to export the plot to a file. 

You will get the plot without the background image.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
