### ISSUE TITLE
Image data lazy loading support for plotly imshow output

### ISSUE THREAD

**Issue by jnissin** [plotly/plotly.py#3692]
We are working on a project involving multiple high resolution images and visualizing them using [plotly imshow](https://plotly.com/python/imshow/). We are very pleased with the automatic pan and zoom functionality that the function provides. However, the notebooks and possible HTML exported versions of the notebook, are very large due to the embedded image data in the output cells of the notebooks. When working with images that can be tens or hundreds of megabytes in size the notebooks and their HTML exports are starting to be impractical to share.

What I would like to know is whether it would be possible to somehow use the plotly imshow function so that the function lazy loads the images from a URL endpoint instead of embedding the encoded image data in the HTML? Essentially this would mean that the URL for the image data is stored in the output cell and the JavaScript library loads the image data from the URL each time the notebook (page) is loaded. This would be especially useful for us since we are using the HTML exports of the Jupyter notebooks to share analyzed information with non-technical people in our project.

Also, any ideas as to how to possibly wrap the plotly imshow function in Jupyter context to achieve this sort of functionality would be much appreciated 🙏 .

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
