### ISSUE TITLE
Zooming does not Work properly in px.scatter_geo() when projection="orthographic")

### ISSUE THREAD

**Issue by Nobody-loses-like-trump** [plotly/plotly.py#3698]
when you make an "orthographic" projection in px.scatter_geo() E.G.
```
df = px.data.gapminder().query("year == 2007")
px.scatter_geo(df, locations="iso_alpha",
               color="continent",
               hover_name="country",
               size="pop",
               projection="orthographic")
```
If you are zooming **IN**, then you start zooming **OUT** in the 1st scroll you will still zoom **IN**

and the same thing when zooming **OUT**, then you start zooming **IN** in the 1st scroll you will still zoom **OUT**

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
