### ISSUE TITLE
MacOS Monterey: fig.show stuck with browser/default renderer 

### ISSUE THREAD

**Issue by klieret** [plotly/plotly.py#3699]
I'm on MacOS Monterey. If I set (in an ipython shell or python script) 

```python3
import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Bar(y=[2, 1, 3])],
    layout_title_text="A Figure Displayed with fig.show()"
)
# works fine
```

Now if I type

```python3
fig.show()
```

nothing happens (the command does not terminate). Similar behavior for `fig.show("browser")` (which should be identical, because I checked that the default is set to `browser`).

However, `fig.show("firefox")` works as expected.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
