### ISSUE TITLE
box plot not formatting correctly tickformat for timedelta

### ISSUE THREAD

**Issue by riodda** [plotly/plotly.py#3729]
Hi, i'm doing a box plot were the Y axis is a timedelta value (laptime of a car).
with the following code:
```
Title = "Portimao DTM Speedtrap"
event['CAR_NUMBER'] = event['NUMBER'].map(str)
fig = px.box(event, x='TOD_MIN', y="LAP_TIME", color = "MANUFACTURER", points="all",template="simple_white", title=Title)
fig.update_xaxes(showgrid=True, tickformat = '%M:%S.%2f',ticklen = 8,showline=True, linewidth=2, linecolor='black', mirror=True)
fig.update_yaxes(showgrid=True, showline=True, linewidth=2, linecolor='black', mirror=True)
fig.show()
```
Were LAP_TIME is a time delta column.

as you can see the LAP_TIME is shown as 108B 107B etc, while the tickformat should be formatting as 1:48.000.
Removing ticklen don't affect the display.

![image](https://user-images.githubusercontent.com/13453063/168107887-4f5dbb3c-9a49-4df7-8890-048eb5099838.png)

**Comment by riodda** [comment]
> 

thanks for your prompt response, i will convert into seconds then. 
Would be cool to have the same support to time delta as is for datetime axes.
Cheers.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
