### ISSUE TITLE
Provide ability to define custom widths for parcats dimensions

### ISSUE THREAD

**Issue by sudeepag** [plotly/plotly.py#3730]
By default, all dimensions in a parcats trace are spread out equally within the figure. However, there may be instances where using different widths for each dimension would be useful. For example, if some dimensions are more important than others, I'd like to devote more of the space on my chart to those dimensions.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
