### ISSUE TITLE
[Enhancement Request] : Dropdown for figures created using Plotly Express 

### ISSUE THREAD

**Issue by rajneesh407** [plotly/plotly.py#3737]
I have recently started using Plotly Express and wanted to create a dropdown button for one of my plot.  

It is really simple to use dropdowns in Plotly Go : [https://plotly.com/python/dropdowns/]  although, I am not able to find similar functionality in Plotly Express, and neither there is any request for enhancement on your issues page.  

Are you planning to build dropdown capability for Express anytime soon ?

Thanks

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
