### ISSUE TITLE
px.imshow throws Attribute error but only when debugging

### ISSUE THREAD

**Issue by mdopy** [plotly/plotly.py#3740]
px.imshows throws the following error:
*AttributeError: 'NoneType' object has no attribute 'layout'*
but only when debugging in spyder with Strg+F10.
Debugging and executing the plot line with F9 is working and running the whole script is also working.
Im using Winpython with Python 3.9.10
- numpy v1.21.6
- plotly v5.8.0
- spyder v5.2.2

Here is a minimal code example:
```

import plotly.express as px
import numpy as np

r = np.zeros([400, 800])
b = np.ones([400,800])
g = np.ones([400,800])

imgsorig = np.stack([r,100*g,200*b], axis = 2)

px.imshow(imgsorig.astype('uint8')).show()
```

**Comment by barakush84** [comment]
Same issue for me.
Any solution?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
