### ISSUE TITLE
[Feature Request] Add tooltip capabilities to main plot titles and axes titles

### ISSUE THREAD

**Issue by Dekermanjian** [plotly/plotly.py#3766]
Hello Plotly community, thank you for all you have done and are currently doing. I would like to request a feature to include tooltips on a plots main title and axes. I think it would be very helpful to be able to include an explanation of what the plot represents in the tooltip.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
