### ISSUE TITLE
The left boundary of the first histogram bin doesn't start with min value

### ISSUE THREAD

**Issue by PlatonB** [plotly/plotly.py#3771]
Let's build a histogram over the toy data series `1, 3, 1, 2, 1, 2`. It would be logical to start the first bin at value 1, but Plotly starts at 0.5:
![histogram_plotly](https://user-images.githubusercontent.com/25541767/173080808-3b6a95c9-0109-465f-b336-7fbef90e9e16.png)

Microsoft Excel and Google Sheets, as expected, start X with value 1:
![histogtam_excel_online](https://user-images.githubusercontent.com/25541767/173081496-60776459-0ba5-4b4a-b1b3-968020877af1.png)
![histogram_google_docs](https://user-images.githubusercontent.com/25541767/173081513-b3b27c57-5a2b-4bac-afdd-32bc0e041518.png)

**Comment by alexcjohnson** [comment]
We've had lots of discussions about this auto-binning algorithm - and you're certainly welcome to shift the bins to start where you like with eg `fig.update_traces(xbins=dict(start=1, end=4, size=1))`

In short, the rationale for us to shit the bins over is that this way it's immediately obvious which bin each integer value goes into.

The way Excel does it you need to look carefully at the labels to see where you have open vs closed ends to the intervals (kudos to them for being very explicit about these bins, and the fact that the first one is `[]` whereas subsequent bins are `(]`, but this makes the axis pretty hard to read and you wouldn't be able to add other non-binned data on top of it).

The way Google does it you don't even get that - the label `2,00` is exactly at the boundary between two bins, so which bin gets the 2s? You just have to know that they go in the bin from 2 to 3, ie it's really `[2, 3)`, but this is stated nowhere (and notice that we can infer all the bins are `[)` because we know the distribution, but this is different from the choice Excel made).

**Comment by PlatonB** [comment]
If the minimum value is in the middle of the first bin, it is not clear to someone who didn't work with the underlying data, that there are no values defining the space between the left boundary and the middle of the first bin. I think this might explain the default behavior of office editors.

**Comment by alexcjohnson** [comment]
Perhaps - all of these choices come with tradeoffs for sure. I suspect if you play with different data sets with larger or non-integer values, none of these algorithms will reliably indicate where the minimum is. Certainly neither of the examples you gave show where the _maximum_ is. If that's a key bit of information for your use case, a histogram isn't really the right choice, at least not by itself. A box plot may be more appropriate, for example - and with px you can add one above the histogram using `marginal='box'`
