### ISSUE TITLE
[Request] Add support for new mapbox cooperativeGestures option

### ISSUE THREAD

**Issue by jnsebgosselin** [plotly/plotly.py#3784]
`mapbox-gl 2.6.0` (released on Nov 08, 2021) added a new option for “cooperative gestures” - when enabled, touch panning requires two fingers and scroll zooming requires ctrl to be pressed while scrolling:

https://github.com/mapbox/mapbox-gl-js/releases/tag/v2.6.0
https://docs.mapbox.com/mapbox-gl-js/example/cooperative-gestures/
https://github.com/mapbox/mapbox-gl-js/issues/2618

Is it a feature that could be made available in `plotly.py`?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
