### ISSUE TITLE
[Feature request] gradient for plot background

### ISSUE THREAD

**Issue by shubhamgupta568** [plotly/plotly.py#3789]
Hi Everyone,

Can we please add a feature to fill plot background with Gradient ?

<img width="432" alt="Screenshot 2022-06-23 115018" src="https://user-images.githubusercontent.com/46197367/175229165-91420fb1-d909-4b24-bfc1-0ee0827afba1.png">

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
