### ISSUE TITLE
Subplots domains

### ISSUE THREAD

**Issue by rrazaghi** [plotly/plotly.py#3800]
I'm currently wondering if this is a bug or an expected behavior:
https://community.plotly.com/t/subplot-individual-height/65599

I'm trying to have the first few rows heights fixed across different plots, but the last row changes the overall plot height while keeping the other rows the same

This happens even when not having title and vertical spacing

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
