### ISSUE TITLE
Discord server?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [plotly/plotly.py#3808]
Hello, folks.

`plotly.py` seems to be great and *very* popular project. To the extent that we from [Plotly.NET](https://github.com/plotly/Plotly.NET) often get questions in our chat about `plotly.py` :laughing: 

So what I'm suggesting is... why don't we make a discord server for `plotly.py`? Discord is a popular platform for community chats (e. g. a 200k member python server, 30k+ C# server, as well as many many more). It would make communications much easier.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
