### ISSUE TITLE
How to override box chart hover template, trace name is repeating in each property on hover.

### ISSUE THREAD

**Issue by patilabhay679** [plotly/plotly.py#3836]
```
import plotly.graph_objects as go
from plotly.data import iris

# Load the dataset
df = iris()

fig = go.Figure()

fig.add_box(x =df['sepal_length'],name='sepal_length')
fig.add_box(x =df['sepal_width'],name='sepal_width')
fig.add_box(x=df['petal_length'],name='petal_length')
fig.add_box(x=df['petal_width'],name='petal_width')

fig.update_layout(template ='gridon')
fig.show()
```

![image](https://user-images.githubusercontent.com/72353341/183399394-74ece878-ab21-440b-b807-9e31c4e71588.png)

How to Remove the Trace name i.e. "petal width", from hover of each property of box plot? having legend intact.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
