### ISSUE TITLE
sankey - connected path

### ISSUE THREAD

**Issue by shresth21** [plotly/plotly.py#3847]
hi

in sankey diagram, i can only see connection to 1 prior and one next node, when a node is selected.
i want to highlight all connected path for the node - from start to end.

Could you please suggest me a way to do it. Hovermode doesn't give this option

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
