### ISSUE TITLE
Vertical Plane doesn't plot on Mesh3d

### ISSUE THREAD

**Issue by jgomez94** [plotly/plotly.py#3851]
When running this code, the add mesh figure is not added to the 3d graph,

import plotly.graph_objects as go

fig = go.Figure(data=[
    go.Mesh3d(
        x=[-77, -77,  193, 193, 403,  403, 508,  508, 741,  741],
        y=[-40,  40, -115, 115, -122, 122, -122, 122, -122, 122],
        z=[200, 200,  200, 200,  200, 200,  200, 200,  200, 200],
    )
])

fig.add_mesh3d(
        x=[-77, -77, 193, 193, 403, 403, 508, 508, 741,  741],
        y=[  0,   0,   0,   0,   0,   0,   0,   0,   0,    0],
        z=[100, 150, 200, 150, 100, 150, 200, 150,  100, 150],
    )

fig.show()

However, if I replace the second y array to the following, it does plot it. 
y=[  0,   0,   0,   0,  50,   0,   0,   0,   0,    0],

Am I doing something wrong or is this a limitation?

**Comment by empet** [comment]
To get the second plane, you must set the delaunayaxis="y". 
```
fig.add_mesh3d(
x=[-77, -77, 193, 193, 403, 403, 508, 508, 741, 741],
y=[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
z=[100, 150, 200, 150, 100, 150, 200, 150, 100, 150],
delaunayaxis="y"
)
```
The `go.Mesh3d.delaunayaxis` gives the direction of the normal to a plane, which is perpendicular to one of the three axes.
The default value is `delaunayaxis="z"`, i.e. the normal to the plane is the vector `k=(0,0,1)`. That's why the first plane was plotted, but not the second one

**Comment by jgomez94** [comment]
Just implemented it into the actual code and works great.

Thanks!
