### ISSUE TITLE
ModuleNotFoundError: No module named 'plotly.express'

### ISSUE THREAD

**Issue by HamzaAJEDDIG** [plotly/plotly.py#3852]
Thanks for your interest in Plotly.py!

Before opening an issue, please search for existing and closed issues :)

**Please** accompany bug reports with a reproducible example. Please use the [latest version](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md) of plotly.py in your report unless not applicable.

Note that GitHub Issues are meant to be used for bug reports and feature requests only. Implementation or usage questions should be asked on [community.plotly.com](https://community.plotly.com/c/graphing-libraries/python/10) or on Stack Overflow (tagged [`plotly`](https://stackoverflow.com/questions/tagged/plotly)).

**Comment by alexcjohnson** [comment]
@HamzaAJEDDIG can you provide details? Sometimes errors like this happen because you have a file named `plotly.py` that just needs to be renamed.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
