### ISSUE TITLE
Feature Request: Horizon Charts

### ISSUE THREAD

**Issue by AhmedThahir** [plotly/plotly.py#3857]
Hiii
I would like to request a plotly express function for creating horizon charts. 

[Horizon Chart Explanation](https://www.r-bloggers.com/2022/03/what-is-a-horizon-chart/#:~:text=A%20horizon%20chart%20is%20a,and%20similar%20to%20a%20heatmap%E2%80%A6)

Also, is there a way to do this using Plotly Graph Objects?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
