### ISSUE TITLE
Importing plotly.tools changes warnings.formatwarning as a side effect

### ISSUE THREAD

**Issue by SlaushVunter** [plotly/plotly.py#3872]
Importing plotly.tools changes warnings.formatwarning as a side effect. Is this necessary? If not, it would be better to only do this when requested explicitely.

Example:
```
import warnings
print(warnings.formatwarning)
import plotly.tools
print(warnings.formatwarning)
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
