### ISSUE TITLE
Using Additional Symbols in Plotly 3D

### ISSUE THREAD

**Issue by rkerr31** [plotly/plotly.py#3877]
Hello, 

I have a task to complete that requires seven distinct, solid symbols for a 3d scatter figure (go.Scatter3d), and from what I can gather from other threads there are only eight symbols available total, many of which are not solid, meaning I can't make the use of opacity meaningful, which is very important for what I'm trying to do. 

These are the symbols my console is telling me are valid: ['circle', 'circle-open', 'cross', 'diamond',
            'diamond-open', 'square', 'square-open', 'x']

How do I add more symbols, or is this even possible? Unfortunately this is a pretty hard requirement for me, diversity of symbols in plotting is pretty much non-negotiable for making plots colorblind-friendly

Thanks for your help!

**Comment by AaronStiff** [comment]
Hi @rkerr31. This is certainly possible! See here for more information/examples: https://plotly.com/python/marker-style/#custom-marker-symbols

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
