### ISSUE TITLE
`FigureWidget` show wrong data

### ISSUE THREAD

**Issue by wang0618** [plotly/plotly.py#3878]
When I use a scatter polar Figure object to construct a FigureWidget, I find the FigureWidget display wrong data.

```python
import plotly.express as px
import plotly.graph_objects as go

r = [71.7011, 7.0021, 2.7335, 24.0294, 69.2684]
theta = [29.7066, 91.0809, 43.1147, 182.1037, 312.1727]

fig = px.scatter_polar(r=r, theta=theta, height=300)
fig

fig_widget = go.FigureWidget(fig)
fig_widget
```

![image](https://user-images.githubusercontent.com/8682073/188398277-3d79a4d0-a64a-48f3-951a-06fca37d7362.png)

**Comment by wang0618** [comment]
It seems the theta data is wrong in figurewidget:

![image](https://user-images.githubusercontent.com/8682073/188399010-d6e3a7e6-12b9-469b-9bf1-4136ac516d12.png)

But the figure attributes of FigureWidget is correct:

![image](https://user-images.githubusercontent.com/8682073/188399308-faaea298-4958-4968-b49a-77857fc687db.png)

**Comment by empet** [comment]
I get the same plot and displayed values on hover, for both figures, with the same Plotly version.

**Comment by AaronStiff** [comment]
Hi @wang0618. This seems to be working for me on recent versions of `plotly.py` and `plotly.js` (5.13.1, 2.18.2). Could you confirm?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
