### ISSUE TITLE
Allow browser tab title to be set

### ISSUE THREAD

**Issue by Dr-Irv** [plotly/plotly.py#3896]
By default, if running a python script and doing `fig.show()`, there is no way to control the title of the browser window/tab.

Ideally, you'd be able to inject a `<title>MYTITLE</title>` into the generated HTML via some parameter.

I found a way to hack it and posted an answer in StackOverflow here:
https://stackoverflow.com/a/73807264/1970354

But it would be nice if this was generalized and supported directly by plotly.

**Comment by dougmellon** [comment]
Does the following not support our needs?

`app = dash.Dash(__name__, title='My Browser Tab Title')`

**Comment by Dr-Irv** [comment]
> Does the following not support our needs?
> 
> `app = dash.Dash(__name__, title='My Browser Tab Title')`

Maybe so, but then I have to create a `Dash` application.  Using `fig.show()` is a lot simpler!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
