### ISSUE TITLE
v.2.3.0 JSON format converter

### ISSUE THREAD

**Issue by oguzgurerk** [plotly/plotly.py#3915]
I am looking at some code examples from https://moderndata.plotly.com/elections-analysis-in-r-python-and-ggplot2-9-charts-from-4-countries/
The code is very old (from 6 years ago) and the json API has changed considerably over the years. Could you please add a converter for reading old json files?

Thank you

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
