### ISSUE TITLE
Sunburst chart label position/CSS via python

### ISSUE THREAD

**Issue by rlewkowicz** [plotly/plotly.py#3928]
This is a feature request for either custom css via python or custom label position via arguments for sunburst charts

There's a number of posts across different forums and the solutions all betray the general ease of use via plotly, and in general are sub optimal. As the slices get too small, the data becomes unreadable. The pie chart has the ability to put labels outside the chart, but sunburst has no such option. An easy breakfix would be some sort of universal option to inject css options. I could then just offset the values outside the circle, and then make lines using css. 

If you could take the css route, you add some powerful options across the board.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
