### ISSUE TITLE
Workflow for displaying multiple small graphs in notebook with expansion/details on click

### ISSUE THREAD

**Issue by cailiang9** [plotly/plotly.py#393]
For example: assume each row can show 3 figures (maybe we can also adjust the number for very big displays), the output could be like:

fig0 fig1 fig2
fig3 fig4 fig5
fig6 ...

when we click a figure, it can expand to 100% in width.

This is very important for dense experiment work, such as CNN (Deep learning). We can plot neuron weights for many neurons (a heatmap for each neuron) easily. And we don't lose global views.

We don't use subplot because it needs to determine the numbers first and we need to hold the handle of a panel. (We don't like too much intrusive code in the framework for assist purpose)

Do you think it can be integrated?

**Comment by ryscet** [comment]
Would also very much appreciate this feature

**Comment by jonmmease** [comment]
Perhaps this could be done as a `FigureWidget` based extension of the WIP sparklines figure factory https://github.com/plotly/plotly.py/pull/888

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
