### ISSUE TITLE
Plotly Express facet wrap has inverted row numbering

### ISSUE THREAD

**Issue by kvanderwijst** [plotly/plotly.py#3943]
When creating a Plotly Express figure with `facet_col_wrap` parameter, the row order is inverted compared to a normal subplots figure. Row 1 is then the bottom row, row 2 the one before the last row, etc.

Using the gapminder example:
```
import plotly.express as px

df = px.data.gapminder()
fig = px.scatter(df, x='gdpPercap', y='lifeExp', color='continent', size='pop',
                facet_col='year', facet_col_wrap=4)

fig.update_traces(row=1, marker_color="red")

fig.show()
```

This highlights the bottom row:
![image](https://user-images.githubusercontent.com/863938/198620177-6ada4155-f0f8-4201-9089-22f719a02758.png)

**Comment by nicolaskruchten** [comment]
Yes, this is an unfortunate case of us using different defaults in different parts of the code... see my answers in https://github.com/plotly/plotly.py/issues/3908

**Comment by ned2** [comment]
Heya @nicolaskruchten, it would be great to get this nuance documented somewhere more prominent. I read closely through both [Facet and Trellis Plots in Python](https://plotly.com/python/facet-plots/) and [Creating and Updating Figures in Python](https://plotly.com/python/creating-and-updating-figures/) closely hoping to find some clue how the indexing for faceted plots produced from Plotly Express works, and why they were reversed from what I expected. It was only after a bunch of googling that I found this issue, which explained what's going on.

Just a small section/note explaining how the row/col indexes are derived in either/both of those pages would be really helpful.

**Comment by alexcjohnson** [comment]
@ned2 since you have a clear idea now what's missing from the docs, would you be up for adding such a note to those pages? They both have "Suggest an edit to this page" links which take you to an editor in the appropriate markdown files. Then @LiamConnors can review and deploy.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
