### ISSUE TITLE
Hang for several minutes when daily limit reached on 429 error

### ISSUE THREAD

**Issue by pniaps** [plotly/plotly.py#3949]
Hi.
My code is hanging for 3-10 minutos because of the next error.
The problem is because we have reached the daily limit, but in my opinion this error should not retry the request. It's my job to handle it.

**chart_studio.exceptions.PlotlyRequestError: Hi there, you've reached the threshold of 100 combined image exports and chart saves per 24h period. If you need to raise your daily limit, please consider upgrading to a paid plan**

This error was introduced on https://github.com/plotly/plotly.py/pull/1307

At the moment I can't get a paid plan until the boss decide it, so i've to live with that.

Maybe this should be configurable.

Many thanks.

**Comment by AaronStiff** [comment]
Perhaps a potential workaround for now would be to include a try-except block that catches that particular error and stops the program?

**Comment by pniaps** [comment]
The problem is that no retry should be done on first 429 error, because if i've reached the daily limit will fail again.

Perhaps should be better to allow disabling retrying on 429 code with a variable or something like this

```
chart_studio.tools.disableRetryWhenThrottled()
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
