### ISSUE TITLE
Pandas backend color scatter not working

### ISSUE THREAD

**Issue by astrowonk** [plotly/plotly.py#3956]
Plotly 5.11
Pandas 1.5.1

Easy reproduction here:

```
import plotly.express as px
df = px.data.iris()
px.scatter(df, x="sepal_width", y="sepal_length", color="species")
df.plot.scatter(x="sepal_width", y="sepal_length", color="species")
```

<img width="953" alt="Screenshot 2022-11-16 at 7 44 47 AM" src="https://user-images.githubusercontent.com/13702392/202183992-99269969-4597-4862-9866-82fe79048985.png">

**Comment by nicolaskruchten** [comment]
Hmm there's something strange going on here because it works for me, and the output above seems inconsistent with what I would expect to see. Normally you should only see a single figure output (the last one) unless you call `.show()` on each of them.

Here's what I see:

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/203523/202204813-c4fc4d92-b66d-4ddf-9b27-5530b39b3f4a.png">

**Comment by astrowonk** [comment]
@nicolaskruchten  That is simply because I have it set up to show all output, so I get both figures (or both of anything, when multiple lines have variables in them)


```
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
```

What version of plotly/pandas are you using?

**Comment by nicolaskruchten** [comment]
OK. It works for Pandas 1.2 but not 1.5. Someone'll have to dig into what the new version of Pandas is doing differently... The relevant code in our repo is here, for reference: https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/__init__.py#L99

**Comment by astrowonk** [comment]
[Pandas turned `color` into an alias for 'c' ](https://github.com/pandas-dev/pandas/blob/e3b0d4d74b1311f6a40ce1ae13c42cc7619178ab/pandas/plotting/_core.py#L1651) which then removes `color` from the kwarg list becaues they pop it out, and then plotly doesn't have the argument.

I opened pandas-dev/pandas#49732

**Comment by nicolaskruchten** [comment]
Nice work, thanks very much 🙏

**Comment by AaronStiff** [comment]
@nicolaskruchten That pandas change was successfully reverted in pandas-dev/pandas#49836, but the code example @astrowonk gave is still returning an error:

```
ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not ['species']
```

I think it's because `pandas` can't map an array of categories to colours (mentioned here: https://github.com/pandas-dev/pandas/issues/16485#issuecomment-1258727343). Is that correct?
