### ISSUE TITLE
Unable to use because of chart_studio error

### ISSUE THREAD

**Issue by toncho11** [plotly/plotly.py#3963]
Why do I get this error after installation with `pip install plotly==5.11.0`

Code:

```
import plotly.plotly as py
from plotly import tools
from plotly.graph_objs import Layout, YAxis, Scatter, Annotation, Annotations, Data, Figure, Marker, Font
```

Error:

```
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.
```

**Comment by nicolaskruchten** [comment]
The message is correct: the old `plotly.plotly` module is deprecated and was moved a few years ago into its own `chart_studio` package. This module is not required to simply make and view graphs, but rather to upload them to Plotly's hosted Chart Studio platform. We broke it out of the main library because many users were concerned about accidentally uploading their data to the cloud.

**Comment by toncho11** [comment]
I see. 
I was using an old example. 
One must use `fig.show()` instead of `py.iplot()` and in this case there is no need for `import plotly.plotly as py`

**Comment by toncho11** [comment]
Maybe this can be added to the wiki in Troubleshooting.
