### ISSUE TITLE
Generating plots in vscode should generate the same mime types as in Jupyter

### ISSUE THREAD

**Issue by DonJayamanne** [plotly/plotly.py#3977]
When running the above code in a notebook in Jupyter Notebook and VS Code we get different outputs
* In vscode only the `application/vnd.plotly.v1+json` output is generated
* Where as in jupyter notebooks we get the above as well as `text/html`
I.e. in vscode there's just one mime type and in jupyter notebook we get two mime types.

Both render perfectly well in the Notebook UI.
However the notebook is exported to HTML using nbconver, the HTML generated in vscode will not display the plots.
This is because the text/html mime type is missing from the output

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by jeffreybliang** [comment]
This is still an issue I believe. I most recently used Plotly 6.0.1 and had to use the hack mentioned in the [thread mentioned](https://github.com/plotly/plotly.py/issues/3977#:~:text=Plots%20not%20shown%20in%20HTML%20export%20for%20default%20Plotly%20renderer%20microsoft/vscode%2Djupyter%236999)
