### ISSUE TITLE
graph_objects.Mesh3d broken when `x` and `y` is identical, or something else?

### ISSUE THREAD

**Issue by kaimo455** [plotly/plotly.py#3988]
Broken codes, where are several scenarios:

#### Scenario 1: `x` and `y` are identical
```python
x = np.random.randn(100)
y = x.copy()
z = np.random.randn(100)
fig = go.Figure(data=[go.Mesh3d(x=x, y=y, z=z, opacity=0.50)])
fig.show()
````
![image](https://user-images.githubusercontent.com/23258141/208300636-a6e1f7d6-38f8-4180-9ca8-e5cf65a4e8b5.png)

#### Scenario 2: `x` and `y` are created by `np.linspace`
```python
import plotly.graph_objects as go
import numpy as np
x = np.linspace(-10, 10, 100)
y = np.linspace(-6, 12, 100) 
z = np.random.randn(100)
fig = go.Figure(data=[go.Mesh3d(x=x, y=y, z=z, opacity=0.50)])
fig.show()
````
![image](https://user-images.githubusercontent.com/23258141/208300550-263e2921-61e6-45c2-b6ad-7965ac55c38b.png)

#### The worked codes
```python
import plotly.graph_objects as go
import numpy as np
x = np.random.randn(100)
y = np.random.randn(100)
z = np.random.randn(100)
fig = go.Figure(data=[go.Mesh3d(x=x, y=y, z=z, opacity=0.50)])
fig.show()
```
![image](https://user-images.githubusercontent.com/23258141/208300678-117d2925-f096-4376-9767-78352d52a42b.png)

**Comment by alexcjohnson** [comment]
When you don't provide index arrays i, j, k we need to infer how to connect these (x,y,z) points with triangles. The default is Delaunay triangulation looking along the z axis (ie ignoring the z data and just using the data in the xy plane). And when x==y all of the resulting triangles are degenerate (they're just lines) - so it's not surprising the algorithm doesn't know what to do with this. You can get a visible result if you add `delaunayaxis='x'` (or `'y'`), though still the first render shows nothing because the default projection is looking edge-on at the infinitely-thin slice, but if you rotate you'll see it
<img width="370" alt="Screenshot 2022-12-19 at 10 30 27" src="https://user-images.githubusercontent.com/2678795/208461436-7099a64a-78dc-4909-b0e3-e791ee16771b.png">

**Comment by kaimo455** [comment]
wow, that's cool!
Thank you for your detailed response!
