### ISSUE TITLE
go.Heatmap is missing rows for large data / lower output resultion than input

### ISSUE THREAD

**Issue by TRuikes** [plotly/plotly.py#3990]
I'm trying to visualize `sorted_map` (266 x 104 np.ndarray),  using go.Heatmap, but in the output it seems to plot only a few rows. The full output should be as with matplotlib (2nd, bottom plot). Can I somehow tell the function to visualize the full array? I have this issue with both the export to image and to vector file (.svg). (heatmapgl does plot the correct output, but is deprecated?)
```
        fig.add_heatmap(
            x=map_x,
            y=map_y,
            z=sorted_map,
            colorscale='Turbo',
            showscale=False,
            # zmin=0,
            # zmax=0.95,
            **pos,
        )


# export with
        write_image(
            fig=fig,
            file=file,
            format=f,
            scale=1 if f != 'png' else 10,  # not used when exporting to svg
            engine='kaleido',
            # width=300,
            #)
```

![fig_3_main](https://user-images.githubusercontent.com/29676016/208704166-d4e28c22-2108-4750-80cc-a4dde5acf293.png)
![tmp](https://user-images.githubusercontent.com/29676016/208704075-0ed93cc1-038f-4e8f-9625-2e6eb9046408.png)

**Comment by AaronStiff** [comment]
Hi @TRuikes. This seems like a scaling issue, as the exported plot's y-axis indicates all the data is being plotted. It would appear `write_image` just isn't scaling the image like `matplotlib`. Does the output of `fig.show` look correct, i.e. without exporting?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
