### ISSUE TITLE
Allow setting `fig.show()`/`fig.write_html` `config` options globally

### ISSUE THREAD

**Issue by janosh** [plotly/plotly.py#4000]
I find myself having to repeat this config every time I write a plot to HTML:

```py
fig.write_html(
    "plot.html",
    include_plotlyjs=False,
    full_html=False,
    config=dict(showTips=False, displayModeBar=False, scrollZoom=True),
)
```

Would be great if this could be set once globally, for example in a template. Something like this added to my custom template (currently unsupported):

```diff
global_layout = dict(
    margin=dict(l=30, r=20, t=60, b=20),
    paper_bgcolor="rgba(0,0,0,0)",
)
+ global_config = dict(
+     showTips=False, displayModeBar=False, scrollZoom=True)
+ )
- pio.templates["global"] = dict(layout=global_layout)
+ pio.templates["global"] = dict(layout=global_layout, config=global_config)
pio.templates.default = "global"
```

Related StackOverflow post: https://stackoverflow.com/q/63936983

**Comment by grisaitis** [comment]
I would love this as well.

Something like this would be great:

```python
plotly_renderer = pio.renderers["plotly_mimetype"]
plotly_renderer.config["displayModeBar"] = False
```

Certain renderers support modifying defaults in this way, e.g. `pio.renderers["png"].scale = 2`. Not sure how it's implemented, though.

**Comment by nicolaskruchten** [comment]
I'd certainly consider merging a PR for this if someone wanted to submit one!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
