### ISSUE TITLE
Add ability to add map to px.imshow

### ISSUE THREAD

**Issue by mdavid800** [plotly/plotly.py#4002]
One major element missing from plotly at present is the ability to display an image or gridded dataset on a background tile map. 

For example, one of the  example code snippets in  https://plotly.com/python/heatmaps/
displays air temp but there is no way to show this on a map easily and retain the tooltip. 

Would it be possible to have a px.imshow_geo ?

Please

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
