### ISSUE TITLE
Bug using the underscore notation for annotation attributes, coupled with buttons

### ISSUE THREAD

**Issue by sde-cdsp** [plotly/plotly.py#4007]
Hi, I just had trouble with the following example:

```
fig.update_layout(
            updatemenus=[
                dict(
                    type="buttons",
                    buttons=[
                        dict(
                            label="All",
                            method="update",
                            args=[
                                {"visible": [True] * 9},  # show all traces
                                {
                                    "annotations": [inner_annotation]
                                },
                            ],
                        ),
                    ],
                )
            ]
        )
```
Everything works fine on the figure load, however, clicking on the button would change the font_size of my annotation back to default, whereas I set it on 16.
```
inner_annotation = dict(
            ...
           font_size=16,
        )
```

After some tests I figured out changing the syntax to 
```
inner_annotation = dict(
            ...
           font={"size": 16},
        )
```
resolved the issue.

**Comment by AaronStiff** [comment]
As far as I can tell, setting `font` to a dictionary with keys such as `size` is the documented method: https://plotly.com/python/reference/layout/annotations/#layout-annotations-items-annotation-font

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
