### ISSUE TITLE
more helpful error message when you set an invalid config or credentials key

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#404]
![image](https://cloud.githubusercontent.com/assets/1280389/13064117/e1c4dabe-d41d-11e5-8349-db0b06567b32.png)

we just say "is invalid" but it'd be nice to know which ones _were_ valid

**Comment by yankev** [comment]
Made a slight change here: [https://github.com/plotly/plotly.py/pull/407](url)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
