### ISSUE TITLE
color_discrete_map not respected for single column charts

### ISSUE THREAD

**Issue by ilfrich** [plotly/plotly.py#4051]
I have the following data frame and bar plot:

```
df = pandas.DataFrame({"x": [1, 2, 3, 4, 5], "y": [4, 4, 3, 4, 10]})
fig = plotly.express.bar(df, x="x", y="y", color_discrete_map={"y": "#ff9900"})
```

But the `color_discrete_map` is ignored for the column `"y"`. It is only used when I pass `y=["y"]` as a `list`, which seems unnecessary. I do not want to have to introduce some additional column to my `DataFrame` in order to adjust the colour either. And as far as I can tell, there's no other parameter that allows me to directly set the colour of that bar figure directly in the `.bar(..)` call.

The workaround with `update_traces(marker=..)` after creating the figure does not look very clean either.

I see 2 possible solutions:
- add a new `color=` parameter to the `.bar(..)` function (and others) that is used when there's only a single `y` series passed or
- respect the `color_discrete_map` and look-up the colour using the `y` parameter, if it is a string from the provided map (preferred).

I'm using `plotly==5.13.0`

**Comment by nicolaskruchten** [comment]
The [`color_discrete_map` parameter serves to map colors to *values* of the column that is mapped to `color`](https://plotly.com/python/discrete-color/), like this:

```python
import pandas
import plotly.express
df = pandas.DataFrame({"x": [1, 2, 3, 4, 5], "y": [4, 4, 3, 4, 10], "z": ["a","a","b","b","c"]})
plotly.express.bar(df, x="x", y="y", color="z",
                         color_discrete_map={"a": "red", "b":"blue", "c":"green"})
```

![newplot](https://user-images.githubusercontent.com/203523/216638027-78552f84-f069-41ad-92cd-6ea9760a2dcd.png)

In your case, there is nothing mapped to `color` and there are no values of `"y"`. If you use `y=["y"]` then this triggers and automatic ["wide-form" mode](https://plotly.com/python/wide-form/) in which case the data frame is melted and remapped internally and the plot is roughly the equivalent of this:

```python
import pandas
import plotly.express
df = pandas.DataFrame({"x": [1, 2, 3, 4, 5], "y": [4, 4, 3, 4, 10]})
melted = df.melt(id_vars="x")
plotly.express.bar(melted, x="x", y="value", color="variable", color_discrete_map={"y": "#ff9900"})
```

This is so that when you have one column per set of bars, you can control the color of each column.

If all you want to do is force all the color the bars, you can set `color_discrete_map="identity"` like this:

```python
import pandas
import plotly.express as px
df = pandas.DataFrame({"x": [1, 2, 3, 4, 5], "y": [4, 4, 3, 4, 10]})
px.bar(df, x="x", y="y", color=px.Constant("#ff9900"), color_discrete_map="identity")
```

Hope this helps!

**Comment by ilfrich** [comment]
Thanks @nicolaskruchten 

The `color_discrete_map="identity"` solution works and is what I was looking for. I guess then the main problem is that throughout the entire documentation the value-based colouration is dominating every example and the simple case of "I just want the bars of a single series to be orange" is not really covered anywhere and would mean I have to do the `.melt` step myself (an operation I wasn't even aware exists and may be hard for newbies to grasp) or simply introduce a dummy column in my `DataFrame` with a constant value that I then map to the colour.

I think this is a bit of a UX issue. But that's obviously a subjective assessment. Please feel free to close the ticket, if you think this case is sufficiently documented / easy enough to work-around. Just spotted an example of the "identity" solution [in this documentation](https://plotly.com/python/discrete-color/). Must have overlooked it as it is wedged in between the value-based colouring.

**Comment by nicolaskruchten** [comment]
Thanks for your feedback! I'll see what I can do to improve the docs.
