### ISSUE TITLE
 Plotly express bar: slow to setup with animations and/or color 

### ISSUE THREAD

**Issue by hrani** [plotly/plotly.py#4071]
https://github.com/plotly/plotly.py/issues/2400
I am facing almost the similar problem, according to issue 2400 it has been address and increased the speed of loading.
[tohistogram.txt](https://github.com/plotly/plotly.py/files/10787467/tohistogram.txt)
import plotly.express as px
import pandas as pd
df=pd.read_csv('tohistogram.csv')
fig_bar = px.bar(df,x='Name',y='Value',animation_frame='Time',color='Name',facet_row='Type') (4.8s to load)
fig_bar = px.histogram(df,x='Name',y='Value',animation_frame='Time',color='Name',facet_row='Type') (5.1s to load)
fig_bar = px.bar(df,x='Name',y='Value',animation_frame='Time',facet_row='Type') (1.48s to load)
fig_bar = px.histogram(df,x='Name',y='Value',animation_frame='Time',facet_row='Type') (1.51s to load)
fig_bar.show()
With color the plotting takes 4.8sec and without color it takes 1.47s,
 I have around 9 data point and each data point have 255 entry (Which is starting point, number of data points and entry gets bigger)
Is this reasonable time what I am facing or am I doing something wrong here?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
