### ISSUE TITLE
How to remove x-axis if not has all colors

### ISSUE THREAD

**Issue by mvrpl** [plotly/plotly.py#4081]
## How to remove x-axis if not has all colors ?

I need to remove the X axes with values (Supermercado Pinheiro, Pague Menos, Hiper Select and Top da Ilha Supermercados).

![Example](https://iili.io/HMYbk2R.png)

**Comment by AaronStiff** [comment]
Hi @mvrpl. I think maybe you could accomplish this by manually specifying which values you want ticks for using a combination of `ticktext` and `tickvals`.

An example: https://plotly.com/python/axes/#enumerated-ticks-with-tickvals-and-ticktext

In the docs: https://plotly.com/python/reference/bar/#bar-marker-colorbar-ticktext
and https://plotly.com/python/reference/bar/#bar-marker-colorbar-tickvals

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
