### ISSUE TITLE
'color' argument in px.bar resorts bars

### ISSUE THREAD

**Issue by fedderw** [plotly/plotly.py#4082]
Why dpes the color argument resort the order of the bars? 

I want to see the B bar turn red here. That's it.
![image](https://user-images.githubusercontent.com/16396180/221300160-59fe6be3-5059-463f-9d76-4c7361437f58.png)

Instead, it resorts the bars, but I did not pass any arguments to do so.
![image](https://user-images.githubusercontent.com/16396180/221300298-762cca08-fdae-4e16-b8ff-1b00384075c1.png)

```
import plotly.express as px
import pandas as pd

# Create sample data
df = pd.DataFrame({'alternative': ['A', 'B', 'C'], 
                   'locally_preferred_alternative': [True, False, True], 
                   'minutes_saved': [20, 10, 15]})

# Create plot
fig = px.bar(
    df.sort_values("minutes_saved", ascending=True),
    x="minutes_saved",
    y="alternative",
    orientation="h",
    title="Minutes Saved",
    color='locally_preferred_alternative',
)
fig.update_layout(
    xaxis=dict(
        title="Minutes Saved",
        tickformat=",d",\
        
    ),
    yaxis=dict(
        title="Alternative",
    ),
    # Remove the legend
    showlegend=False,
)
fig.show()
```

Can this behavior be changed? If not, what is the workaround?

**Comment by AaronStiff** [comment]
Hi @fedderw. What version of `plotly.py` and `plotly.js` are you on? I'm getting a different result than yours with the most recent versions:

![image](https://user-images.githubusercontent.com/69512633/221325768-ba6f72b7-b7bd-44c1-b6ca-cf4e62f1d9b8.png)

**Comment by fedderw** [comment]
> Hi @fedderw. What version of `plotly.py` and `plotly.js` are you on? I'm getting a different result than yours with the most recent versions:
> 
> ![image](https://user-images.githubusercontent.com/69512633/221325768-ba6f72b7-b7bd-44c1-b6ca-cf4e62f1d9b8.png)

I'm using version 5.13.1

**Comment by basovam** [comment]
> Why dpes the color argument resort the order of the bars?
> 
> I want to see the B bar turn red here. That's it. ![image](https://user-images.githubusercontent.com/16396180/221300160-59fe6be3-5059-463f-9d76-4c7361437f58.png)
> 
> Instead, it resorts the bars, but I did not pass any arguments to do so. ![image](https://user-images.githubusercontent.com/16396180/221300298-762cca08-fdae-4e16-b8ff-1b00384075c1.png)
> 
> ```
> import plotly.express as px
> import pandas as pd
> 
> # Create sample data
> df = pd.DataFrame({'alternative': ['A', 'B', 'C'], 
>                    'locally_preferred_alternative': [True, False, True], 
>                    'minutes_saved': [20, 10, 15]})
> 
> # Create plot
> fig = px.bar(
>     df.sort_values("minutes_saved", ascending=True),
>     x="minutes_saved",
>     y="alternative",
>     orientation="h",
>     title="Minutes Saved",
>     color='locally_preferred_alternative',
> )
> fig.update_layout(
>     xaxis=dict(
>         title="Minutes Saved",
>         tickformat=",d",\
>         
>     ),
>     yaxis=dict(
>         title="Alternative",
>     ),
>     # Remove the legend
>     showlegend=False,
> )
> fig.show()
> ```
> 
> Can this behavior be changed? If not, what is the workaround?

In 7 you proabably mean `'minutes_saved': [20, 15, 10]`, not the `'minutes_saved': [20, 10, 15]`.

If you want this behavior:
![newplot](https://user-images.githubusercontent.com/58362636/224962465-d8adda34-17d9-4305-8e4c-263e9bff3d1e.png)

you can use plotly.graph_objects instead of plotly.express:

```
import plotly.graph_objects as go
import pandas as pd

df = pd.DataFrame({'alternative': ['A', 'B', 'C'], 
                   'locally_preferred_alternative': [True, False, True],
                   'minutes_saved': [20, 15, 10]}).sort_values("minutes_saved", ascending=True)

colors = df['locally_preferred_alternative'].apply(lambda x: '#636EFA' if x else '#EF553B')

fig = go.Figure(data=[go.Bar(
    x=df['minutes_saved'],
    y=df['alternative'],
    marker_color=colors,
    orientation="h",
)])

fig.update_layout(
    xaxis=dict(
        title="Minutes Saved",
        tickformat=",d",\
        
    ),
    yaxis=dict(
        title="Alternative",
    ),
    # Remove the legend
    showlegend=False,
)

fig.show()
```

**Comment by nicolaskruchten** [comment]
The answer as to "why" is because when you color by the boolean, internally your data frame is split on the boolean and the traces are added in order, so the trace with `color=False` is added separately from the `color=True` trace. The workaround for now is to force `category_orders={"alternative": ["A","B","C"]}`

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
