### ISSUE TITLE
set different color using for_each_trace in plotly express bar chart

### ISSUE THREAD

**Issue by hrani** [plotly/plotly.py#4087]
To increase the performance of loading time in the plotly.express.bar graph, (https://github.com/plotly/plotly.py/issues/4071) where limiting factor was the color which was slowing down.
Found suggestion stackover "[set color different in plotly express based on conditions] made some modifcation
[tohistogram.csv](https://github.com/plotly/plotly.py/files/10860530/tohistogram.csv)

```
import pandas as pd
import plotly.express as px

colors = ("lightblue","lightgreen","lightslategrey","firebrick","plum","dodgerblue")
df=pd.read_csv('tohistogram.csv')
fig_bar = px.bar(	df,	x ="Name",y ="Ratio",text=[f"{row:.2}uM" for row in df['Value']], animation_frame='Time',hover_name ="Name",facet_row="Type",color_discrete_sequence=["blue"],height=400)
fig_bar.update_xaxes(matches=None)
fig_bar.for_each_xaxis(lambda xaxis: xaxis.update(showticklabels=True))
fig_bar.for_each_trace(lambda t: t.update({"marker": {"color": [colors[i] for i, _ in enumerate(t.x)]}}))

print(fig_bar.data)
fig_bar.show()

```
plot display as per the color index, but when I animation, default color (blue) takes back. How to fix this

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
