### ISSUE TITLE
color_bar for each facet_col

### ISSUE THREAD

**Issue by SujeetO** [plotly/plotly.py#4098]
As far as I know, currently there is not a very elegant way of getting colorbar for each facet_col or facet_row independently.
There are some solutions suggested for this in Plotly community ( https://community.plotly.com/t/colorbar-for-each-facet-col/73456 ), but I feel it requires lot of coding.

I think, we need to provide simple interface to achieve the same. Something like this:

`
fig = px.scatter(
    df, x=df.index, 
    y='total_bill', 
    facet_col='sex', 
    color='total_bill',
    facet_col_spacing=0.2,
    ****split_facet_col_colorbar**=1**

)`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
