### ISSUE TITLE
FigureWidget modifies the position of Title

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [plotly/plotly.py#4111]
Dear Plotly,

I have encountered the issue that when using FigureWidget  ans subplot while keeping shared_yaxis=True, the title of a second subplot is changed to the left side. 

This is a make_subplot object 

![Screenshot 2023-03-16 at 15 50 45](https://user-images.githubusercontent.com/34098967/225655953-04b4a935-8683-4c4f-8881-071ed4b1bd06.png)
And this is what occurs when the Figure object is pass to FigureWidget

![Screenshot 2023-03-16 at 15 51 13](https://user-images.githubusercontent.com/34098967/225656141-3b58cfe4-2f23-486d-a91b-a9aa71760b19.png)

Is there any solution to keep shared_yaxis=True and get the title of the second subplot on the right side [YAxis side option was used to generate the first figure)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
