### ISSUE TITLE
[Feature Requested]: Sunburst sort option to be optionally set individually by "onion layer"

### ISSUE THREAD

**Issue by Skrattoune** [plotly/plotly.py#4115]
Hi, I've been looking everywhere on the web, and it appears that sorting for Sunburst charts can be set either `True `or `False`
(cf plotly/plotly.js#4823 and plotly/plotly.js#5164)

Would it be possible to add the possibility to set it independantly for the different "onion layers"
as it is the case for many parameters?

something like `sort=[True, False, False]` (which would be the thing specifically needed in my case )

Thanks in advance 👍

**Comment by nicolaskruchten** [comment]
OK. Here is where Plotly Express converts between the input data frame and the structure which go.Sunburst requires. Any changes to how things are sorted would need to be made here. https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/express/_core.py#L1543

**Comment by janosh** [comment]
To be clear, right now there's no sorting option in the python wrapper at all? Neither by "onion layer" nor for the plot as a whole?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
