### ISSUE TITLE
Custom mapbox source doesn't load in a scatter mapbox figure

### ISSUE THREAD

**Issue by montmejat** [plotly/plotly.py#4137]
I'm trying to use a custom source with:
```python
fig = px.scatter_mapbox(...)
fig.update_layout(
    mapbox_style="white-bg",
    mapbox_layers=[{
        "below": 'traces',
        "sourcetype": "raster",
        "sourceattribution": "...",
        "source": [
            "https://[...]/{z}/{x}/{y}.png"
        ]
    }]
)
````

But I get the following error in the console when loading the map:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://[...]/19/267018/185328.png. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200
```

By the way, the link works just fine. Any ideas? :smile:

**Comment by nicolaskruchten** [comment]
For this to work, the *server* must provide the appropriate headers: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by aurelien-m** [comment]
Thanks for the info, I'm not very familiar with CORS. My tiles are actually on an AWS public bucket, and I needed to add this in the CORS section in the permissions tab:

```json
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```

By any chance, @nicolaskruchten, do you know what I can add in `AllowOrigins` to add an extra filter? Using `*` in `AllowedOrigins` works fine but just adding my public IP doesn't work. I'd just like to avoid allowing all origins if that's possible

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
