### ISSUE TITLE
Area charts: area() got an unexpected keyword argument 'stackgaps'

### ISSUE THREAD

**Issue by Skrattoune** [plotly/plotly.py#4141]
Hi, I have issues with different area charts which I'm using to monitor the presence of different types of events.

My data in my area charts are going all over the place because values seem by default to be interpolated for the traces which have no data at one "location" (for a given month, in my case)
![image](https://user-images.githubusercontent.com/56255427/229380155-dc10ab04-e6f3-4430-84ae-9a47fb6403df.png)
![image](https://user-images.githubusercontent.com/56255427/229380221-407a7170-78c3-48a6-8efc-8961096c03dd.png)
in this examples, each time there is no data, the curves should go back to zero 
Instead, the area extends for each trace to the next point where there is some data.

I would like to insert a zero at locations at which other traces in this group have data but this one does not

from https://github.com/plotly/plotly.js/issues/1217
and from https://plotly.com/python/reference/scatter/#scatter-line

I understood that I should use `stackgaps="infer zero"` to avoid have my data in my area chart going all over the place because values are by default interpolated for the traces which have no data at one "location" (for a given month, in my case)

I'm declaring my chart as a plotly express area chart.
It seems that under the hood, it a a scatter plot, and it links to the reference for scatter plots.

So I don't really undertand why my `stackgaps` parameter is not recognized, either in the `fig = px.area` definition or in the `fig.update_traces(stackgaps="infer zero",)`

Is that a bug? What am I doing wrong?

**Comment by nicolaskruchten** [comment]
Can you please share some sample code/representative data so I can see what's going on?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
