### ISSUE TITLE
Problem following How to Contribute on M1 Mac (node.js)

### ISSUE THREAD

**Issue by stephenpardy** [plotly/plotly.py#4146]
Similar to #4072

I am trying to install plotly from source on an M1 Mac. There are a few issues:

1. Installing `geopandas` fails due to issues with the `fiona` dependency on M1. This is resolved by following the geopandas guide here: https://github.com/geopandas/geopandas/issues/1816 (using homebrew to install `gdal`).
2. Installing npm dependencies (unresolved).

I have tried with and without the conda environment file provided - both give the same result. 
```
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      /private/var/folders/64/1qk4dnjs5x7302nlk1hvx3_80000gq/T/pip-build-env-kj14agus/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /private/var/folders/64/1qk4dnjs5x7302nlk1hvx3_80000gq/T/pip-build-env-kj14agus/overlay/lib/python3.10/site-packages/setuptools/dist.py:328: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running egg_info
      running jsdeps
      9.5.0
      9.5.0
      Installing build dependencies with npm.  This may take a while...
      npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
      npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
      npm ERR! request to https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz failed, reason: self-signed certificate in certificate chain
      
      npm ERR! A complete log of this run can be found in:
      npm ERR!     /Users/<USER>/.npm/_logs/2023-04-04T19_19_02_443Z-debug-0.log
      rebuilding js and css failed
      missing files: ['/Users/<USER>/OSS/plotly.py/packages/python/plotly/jupyterlab_plotly/nbextension/index.js', '/Users/<USER>/OSS/plotly.py/packages/python/plotly/jupyterlab_plotly/labextension/package.json']
  ...
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
