### ISSUE TITLE
Secondary y issues when dump and load a Figure with Subpplots

### ISSUE THREAD

**Issue by barrospt** [plotly/plotly.py#4159]
In my webapp I'm trying to pass a chart for a fetch js function that allows you to download a report with that same chart.

The problem is that when in the other route I load the json object and try to assemble the chart, the secondary axes stop working correctly. I no longer see the title and axis ticks.

Briefly, what I do is the following:

```
chart.show()

# Dump and load:
plotly.io.from_json(plotly.io.to_json(chart)).show()

```

Before Load
https://i.imgur.com/XyA20H3.png

After Load
https://i.imgur.com/PP7IK1C.png

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
