### ISSUE TITLE
Feature request: option to pass custom functions to trendline parameter in px.scatter

### ISSUE THREAD

**Issue by Servot** [plotly/plotly.py#4168]
Currently px.scatter only accepts strings as arguments for the trendline parameter.
These strings are references to functions implemented in px.trendline_functions.

It would be nice to be able to pass custom trendline functions as arguments (e.g. using weighted least squares instead of OLS).
The only precondition for the custom functions would be that they except the same unnamed arguments and return the same type of values as the ones implemented in px.trendline_functions

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
