### ISSUE TITLE
Shading disappears in the intersection of two shapes in Plotly (sometimes, but not always)

### ISSUE THREAD

**Issue by ghproek** [plotly/plotly.py#4174]
Here are two snippets which look similar, but behave differently.  In each case we generate two overlapping triangles.  However the shading in the overlapped region disappears in one case and not the other.

```python
import plotly.graph_objects as go

x = [0, 0, 1, 0, None, 0, 1, 1, 0, None ]
y = [0, 1, 0, 0, None, 0, 0, 1, 0, None ]
trace = go.Scatter(x=x, y=y, fill="toself")
fig = go.Figure(data=[trace])
fig.update_layout(title="two right triangles with vanishing intersection")
fig.show()
```

```python
import plotly.graph_objects as go

x = [0, 1, 2, 0, None, 1, 2, 3, 0, None ]
y = [0, 1, 0, 0, None, 0, 1, 0, 0, None ]
trace = go.Scatter(x=x, y=y, fill="toself")
fig = go.Figure([trace])
fig.update_layout(title="two isoceles triangles with non-vanishing intersection")
fig.show()
```
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/116531679/234151219-cec0b144-92e9-4278-b6d7-f8f176516fed.png">
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/116531679/234185142-64e4d6c6-f3dc-4c24-b29d-a134a5e4c7ac.png">

### Questions

What's the difference between these two examples and how can I make plots that avoid the disappearing intersection behavior?

### System details

- Plotly version: 5.14.1
- Python version: Python 3.9.16

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
