### ISSUE TITLE
px.line_polar line width

### ISSUE THREAD

**Issue by ziyanwu10** [plotly/plotly.py#4178]
Hi, I am using px.line_polar to make my radar plots. Since I like to make my plot large, I feel it would be nice if there is an option that I can change the line width to make lines thicker.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
