### ISSUE TITLE
Objects fail if they're not JSON-able

### ISSUE THREAD

**Issue by MaximilianR** [plotly/plotly.py#418]
An object such as a pandas Period, which isn't JSON-able according to [this list](https://github.com/plotly/plotly.py/blob/master/plotly/utils.py#L204), will fail at the moment, when it's very reasonable to show their `str()` output.

I think this (done properly, without the monkey patch) should be enough to solve it:

``` python
# continued from above

        encoding_methods = (
            self.encode_as_plotly,
            self.encode_as_sage,
            self.encode_as_numpy,
            self.encode_as_pandas,
            self.encode_as_datetime,
            self.encode_as_date,
            self.encode_as_list,  # because some values have `tolist` do last.
            self.encode_as_str,  # all else fails - call str() on it
        )
        for encoding_method in encoding_methods:
            try:
                return encoding_method(obj)
            except NotEncodable:
                pass
        return json.JSONEncoder.default(self, obj)

    def encode_as_str(obj):
        """ all else fails - call str() on it """
        return str(obj)

    from plotly.utils import PlotlyJSONEncoder

    PlotlyJSONEncoder.default = default
    PlotlyJSONEncoder.encode_as_str = staticmethod(encode_as_str)
```

solved downstream here: https://github.com/santosjorge/cufflinks/issues/35

**Comment by chriddyp** [comment]
this seems reasonable to me. @theengineear @cldougl @yankev - thoughts?

**Comment by theengineear** [comment]
Yeah, seems reasonable. I'm a little worried that it will cause silent failures though. I guess I'd favor making it easier for users though... cool :+1:

**Comment by chriddyp** [comment]
>  I'm a little worried that it will cause silent failures though

Yeah, on second thought I'm with you @theengineear . If you make a silly typo like `x=np.random.randn` instead of `x=np.random.randn(4)` then we'll serialize that object as a string like `x='<built-in method randn of mtrand.RandomState object at 0x103e960d0>'` and try to plot it. the plot won't load, and the user will have no idea why and no easy way to debug.

I've definitely made these types of typos before and been happy that plotly hit me with an exception early and hard.

**Comment by theengineear** [comment]
Closing this as I think it's safer as-is.
