### ISSUE TITLE
slider page extension

### ISSUE THREAD

**Issue by maavvi** [plotly/plotly.py#4180]
According to a wishlist of examples, slider page (https://plot.ly/python/sliders/) needs to be updated. I'll add an example using the update method and an example using relayout.

**Comment by empet** [comment]
@akaalena On ploly forum you can find  such examples, as well as in this notebook: [https://chart-studio.plotly.com/~empet/15605/update-method-called-within-an-update/#/], to see what is important to illustrate in your example to be posted as slider demo.

**Comment by akaalena** [comment]
@empet , thank you for that suggestion. I have updated the examples. Hopefully, they consider now what you meant.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
