### ISSUE TITLE
how to add tms tiles in plotly

### ISSUE THREAD

**Issue by tudoulei** [plotly/plotly.py#4197]
Plotly does not have the parameter 'scheme'

fig.update_layout(
    mapbox_style="white-bg",
    mapbox_layers=[
{
            "below": 'traces',
            "sourcetype": "raster",
            "sourceattribution": "",
            # "scheme": "tms",
            "source": [
                url
            ]
        },

**Comment by makmegs** [comment]
This has been highlighted before at #1610

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
