### ISSUE TITLE
Plot traces disappear when using "hover_data"

### ISSUE THREAD

**Issue by Predator83** [plotly/plotly.py#4199]
when using plotly express to plot a scatter or area graph, in certain situations traces disappear when using the "hover_data" option. 

Here is a minimal example: 

```
import pandas as pd
import plotly.express as px

df = pd.DataFrame({"A": [0,1,2], "B":[0,1,2], "C": [1,2,3]})
px.scatter(df, x="A", y=["B", "C"], hover_data=["B","C"])
```

the bug results in traces, that are listed in hover_data, disappearing from the graph. For the example above, no traces remain to be displayed in the graph. If "hover_data=["B"] then only trace "C" remains in the graph. 

 This bug does not occur, when for y not a list but only single value is handed over. However, this in not very practical as you can only display one "y" trace in the graph.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
