### ISSUE TITLE
Hide/show annotation text with button

### ISSUE THREAD

**Issue by kunalgoyal9** [plotly/plotly.py#4201]
Hi,

I have below code that write text on ploty.

	annotation = go.layout.Annotation(
    x=-0.047,
    y=1.025,
    xref="paper",
    yref="paper",
    xanchor="left",
    yanchor="top",
    bordercolor="black",
    borderwidth=1,
    borderpad=4,
    text="id: {person['id']}<br>"
    + "user_id: {person['user_id']}<br>"
    + "test_id: {person['test_id']}<br>"
    + "exam_id: {person['exam_id']}",
    visible=True,  # Initially visible
	)

Now I want a way to toggle this text using button. How can I do this?

I tried below script but it doesn't work. link: https://gist.github.com/kunalgoyal9/7b6ad19d11dccec19870e5aac2dfb8a5

**Comment by empet** [comment]
You must call the method `relayout`, because you are updating an attribute of `go.Layout.annotations`. The list buttons should contain two dicts: one  that makes the text visible and another, that hide it:
```
import plotly.graph_objects as go
fig = go.Figure()
annotation = dict(
    x=-0.047,
    y=1.01,
    xref="paper",
    yref="paper",
    xanchor="left",
    yanchor="bottom",
    bordercolor="black",
    borderwidth=1,
    borderpad=4,
    showarrow=False,
    text="id: {person['id']}<br>"
    + "user_id: {person['user_id']}<br>"
    + "test_id: {person['test_id']}<br>"
    + "exam_id: {person['exam_id']}",
    visible=True) 
fig.update_layout(annotations=[annotation],
                  updatemenus=[
                      dict(buttons=[dict(label="Show",
                                         method="relayout",
                                         args=[{"annotations[0].visible": True}]),
                                    dict(label="Hide",
                                         method="relayout",
                                         args=[{"annotations[0].visible": False}])
                                   ],                 
        showactive=True,
        x=1,
        xanchor='left',
        y=1.0,
        yanchor='top')])
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
