### ISSUE TITLE
Adding scale to a map 

### ISSUE THREAD

**Issue by melanopsis** [plotly/plotly.py#4208]
Hi,  I can't seem to find a way to add scale to a map (neither via built-in methods nor mapbox). Would it be possible to have some sort of a `map_scale` option that would enable the scale as seen here https://docs.mapbox.com/mapbox.js/example/v1.0.0/scale-control/  -  https://docs.mapbox.com/mapbox-gl-js/api/markers/#scalecontrol?

Thank you.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
