### ISSUE TITLE
Could you add a function to extract values of go.Box?

### ISSUE THREAD

**Issue by Crispy13** [plotly/plotly.py#4209]
I need to extract some values of go.Box. (e.g. median, q1, q3, upper and lower fences)

When using matplotlib.pyplot, I can extract them like:
```
B = plt.boxplot(data)
[item.get_ydata() for item in B[‘whiskers’]]
```

Could you add a function or something to extract values of go.Box?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
