### ISSUE TITLE
Allow applying patterns to single values

### ISSUE THREAD

**Issue by ernestask** [plotly/plotly.py#4229]
Context: plotly.express.timeline

Looking at (and neighboring lines which perform analogous checks) https://github.com/plotly/plotly.py/blob/216fca2a7ed14d2e58f5423557b6e731e2a0f575/packages/python/plotly/plotly/express/_core.py#L973, there is no way to set `pattern_shape_sequence` to `['']` and set patterns for individual values within `pattern_shape_map`. All I want is to make one specific thing stand out without changing its color.

…unless there is another way to achieve that that I’d missed.

**Comment by ernestask** [comment]
Ah, yes:

```python3
fig.for_each_trace(lambda trace: trace.update(marker_pattern_shape="foo") if trace.name == "bar" else ())
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
