### ISSUE TITLE
plotly used with nginx is not allowing to show second fig 

### ISSUE THREAD

**Issue by Sandy4321** [plotly/plotly.py#4265]
plotly used with nginx is not allowing to show second fig 
only first fig shown and then second plot block code running  

![image](https://github.com/plotly/plotly.py/assets/11426119/a301d714-6257-4ce4-8541-1dd2a3e0b73a)

import plotly.express as px
import pandas as pd
#config = {'responsive': False}
# Create dataset
data = {
   'year':[2015,2016,2017,2018,2019],
   'lifeexp':[75,74,72,70,69],
   'state':['kerala','punjab','karnataka','andhra','odisha'],
   'ratio':[-74,73.9,-71.5,6.98,69]
}
# Create dataframe
df = pd.DataFrame(data)
# Create Line plot
fig = px.line(df, x=df['year'], y=df['lifeexp'])
# Add Scatter plot
fig.add_scatter(x=df['year'], y=df['ratio'])
# Display the plot
print('b1')
fig.show() #block = False) #,config=config)
print('b2')
#del fig 
#new fig 
fig2 = px.line(df, x=df['year'], y=df['ratio'])
fig2.update_traces(line_color='#cf0af0', line_width=5)
# Add Scatter plot
#fig.add_scatter(x=df['year'], y=df['ratio'])

# Display the plot
print('b3')
fig2.show() #block = False) #, config=config)
print('b4')
q=0

**Comment by Sandy4321** [comment]
it is about visual code  code running on ec2 instance aws

**Comment by Sandy4321** [comment]
set up done according to
How to run an instance of Visual Studio Code over your network with AWS EC2
https://aws.plainenglish.io/how-to-run-an-instance-of-visual-studio-code-over-your-network-with-aws-ec2-d9fc6034c091

**Comment by Sandy4321** [comment]
but
"Be sure to replace you@example.com with your actual email and yourdomain.com with your actual domain name."

set up done without using domain but from local computer browser

IMPORTANT 
WHEN EXECURING PYTHON CODE LINE BY LINE IN DEBUG MODE
ALL RUNS CORRECTLY - SECOND FIG IS SHOWN AND CODE EXECUTOIN IS NOT BLOCKED BY LINE fig2.show() !!!

**Comment by Sandy4321** [comment]
just opened ip in chrome
![image](https://github.com/plotly/plotly.py/assets/11426119/4daf9e73-b762-4781-9ab6-c541187e5ce3)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
