### ISSUE TITLE
Plotly Express cannot process wide-form data with columns of different type.

### ISSUE THREAD

**Issue by subsurfaceiodev** [plotly/plotly.py#4266]
Hi! When running the following code:

```
df = pd.DataFrame({'numeric': [1, 2], 'string': ['A', 'B']})
fig = px.scatter(df, x=df.columns, facet_col='variable')
fig.show()
```

We get the following error:
`ValueError: Plotly Express cannot process wide-form data with columns of different type.`

Expected output is:
![image](https://github.com/plotly/plotly.js/assets/109676812/400bc8e0-ae6b-4d8d-ac26-e3a593cf667d)

We understand the need for prevention of data type mixing for other type of plots, but for scatter or line plots use cases like expected output can be very common. Commenting the following code:

```
elif dtype != v_dtype:
    raise ValueError(
        "Plotly Express cannot process wide-form data with columns of different type."
    )
```

In plotly/express/_core.py gives us expected output.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
