### ISSUE TITLE
Static Image Export in Python Not Working

### ISSUE THREAD

**Issue by tadavoila** [plotly/plotly.py#4296]
I was following the [documentation](https://plotly.com/python/static-image-export/), but the code provided does not seem to let me save my Plotly graphs as static images.

I have already tried restarting the Kernel and rerunning cells. I am on a Windows 11 computer. This problem applies for any plotly chart I create.

I also tried the following things:
a)
In my Jupyter Notebook, I ran
`!pip install kaleido`
`fig.write_image("images/fig1.png")`

I also ran `import kaleido` once before `fig.write_image("images/fig1.png")` just in case that was what was needed.

Both times, I got the following error when trying to write the image.: 

ValueError: 
The kaleido executable is required by the kaleido Python library, but it was not included
in the Python package and it could not be found on the system PATH.

Searched for included kaleido executable at:
    C:\Users\yeahs\AppData\Roaming\Python\Python39\site-packages\kaleido\executable\kaleido 

Searched for executable 'kaleido' on the following system PATH:
    C:\ProgramData\Anaconda3
    C:\ProgramData\Anaconda3\Library\mingw-w64\bin
    C:\ProgramData\Anaconda3\Library\usr\bin
    C:\ProgramData\Anaconda3\Library\bin
    C:\ProgramData\Anaconda3\Scripts
    C:\ProgramData\Anaconda3\bin
    C:\ProgramData\Anaconda3\condabin
    C:\ProgramData\Anaconda3
    C:\ProgramData\Anaconda3\Library\mingw-w64\bin
    C:\ProgramData\Anaconda3\Library\usr\bin
    C:\ProgramData\Anaconda3\Library\bin
    C:\ProgramData\Anaconda3\Scripts
    C:\Python311\Scripts
    C:\Python311
    C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin
    C:\WINDOWS\system32
    C:\WINDOWS
    C:\WINDOWS\System32\Wbem
    C:\WINDOWS\System32\WindowsPowerShell\v1.0
    C:\WINDOWS\System32\OpenSSH
    C:\Program Files\dotnet
    C:\Program Files\eSpeak NG
    C:\Program Files\nodejs
    C:\ProgramData\chocolatey\bin
    C:\Users\yeahs\AppData\Local\Microsoft\WindowsApps
    .
    C:\Users\yeahs\AppData\Local\Programs\Microsoft VS Code\bin
    C:\Users\yeahs\.dotnet\tools
    C:\Users\yeahs\AppData\Roaming\npm. 

b) 
I ran `pip install -U kaleido` in my administrator command prompt before running the code from (a) in Jupyter Notebook. I still got the same error message as in (a)

c) 
Per this [Stack Overflow page](https://stackoverflow.com/questions/70997997/not-able-to-save-plotly-plots-using-to-image-or-write-image/71621135#71621135), I ran `pip install -U kaleido==0.1.0post1` and `!pip install kaleido==0.1.0post1` in both my administrator command prompt and my Jupyter Notebook respectively before running the code from (a), but I still got the same error message as in (a).

Please let me know if there is any way to solve this! Thank you!

**Comment by ElangoSubramani** [comment]
<img width="947" alt="image" src="https://github.com/plotly/plotly.py/assets/122277416/c64f00b0-e1f3-4d36-b0fc-562f2d8a5ab0">
<img width="885" alt="image" src="https://github.com/plotly/plotly.py/assets/122277416/c099f39a-43c7-4f32-919a-c45665f706e8">
<img width="496" alt="image" src="https://github.com/plotly/plotly.py/assets/122277416/abab53a6-7c4e-4d7b-9b09-ac4ddd3a20af">
I followed the same documentation, It is working kinkdy check it out the screenshots

**Comment by ElangoSubramani** [comment]
I also faced some issues:
while installing kaleido you have to deactivate virtual environment and should not run using F5 or IDE, Run in Terminal, Python3 appname.py
You can check the python library by "pip list"

**Comment by ElangoSubramani** [comment]
As you mentioned this issue:
ValueError:
The kaleido executable is required by the kaleido Python library, but it was not included
in the Python package and it could not be found on the system PATH.

This raises because your IDE using some kind of virtual environment For eg: base,flask or your ouwn in Anaconda IDE
Try to install library manually in python3 or use base env by conda activate base and run using the command i mentioned above. 
Hope this solves your issue!!
Thank you

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
