### ISSUE TITLE
Treemap adjust heat map color scale to selected scope

### ISSUE THREAD

**Issue by dask-user** [plotly/plotly.py#4314]
Is it possible to adjust the heat map color scale to the scope of the selected branch. For example say we have a heat map of low=blue, high=red. Currently when you click into a new scope the colors respect the global low/high values and so boxes remain the same color no matter what scope you’re in. What I’m looking for is for the colors to dynamically adjust such that in the new scope the new lowest values are blue and new highest values are red.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
