### ISSUE TITLE
conflict with vscode jupyternote book syntax highlight

### ISSUE THREAD

**Issue by yongqiang-zhao** [plotly/plotly.py#4316]
Thanks for your interest in Plotly.py!

Before opening an issue, please search for existing and closed issues :)

**Please** accompany bug reports with a reproducible example. Please use the [latest version](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md) of plotly.py in your report unless not applicable.

Note that GitHub Issues are meant to be used for bug reports and feature requests only. Implementation or usage questions should be asked on [community.plotly.com](https://community.plotly.com/c/graphing-libraries/python/10) or on Stack Overflow (tagged [`plotly`](https://stackoverflow.com/questions/tagged/plotly)).
Recently my vscode jupyternote book syntax highlight is completely broken. And I found that if I comment all plotly packages and corresponding code, the highlight is working again. My vscode is 1.81.1 and my OS is Windows_NT x64 10.0.22621, my plotly is 5.15.0

**Comment by alexcjohnson** [comment]
Thanks @yongqiang-zhao - are you able to share some screenshots of working / non-working highlighting?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
