### ISSUE TITLE
Impossible to show px.scatter and  px.bar in X values descending order 

### ISSUE THREAD

**Issue by fede72bari** [plotly/plotly.py#4323]
I am using Plotly Express. I tried everything on Jupiter notebook to show some data in X descending order; the dataset was previously sorted by descending values of the feature used as X axe. The values of X axe are numbers. Here are my attempts and the results

**First attempt: not specific definition in the parameters of px, just passed a correctly ordered DataFrame**

```
analysis_df = analysis_df.sort_values(by=['int_first_min_DTE'], ascending=[False])

# Crea il grafico di dispersione con Plotly Express
fig = px.scatter(analysis_df, x='int_first_min_DTE', y='min_max_rel_delta', 
                 title='Distribuzione dei profitti relativi min_max_rel_delta vs int_first_min_DTE')

# Mostra il grafico
fig.show() 
```

**Second attempt: update_xaxes(categoryorder='category ascending')**
```
analysis_df = analysis_df.sort_values(by=['int_first_min_DTE'], ascending=[False])

# Crea il grafico di dispersione con Plotly Express
fig = px.scatter(analysis_df, x='int_first_min_DTE', y='min_max_rel_delta', 
                 title='Distribuzione dei profitti relativi min_max_rel_delta vs int_first_min_DTE')

# Mostra il grafico
fig.update_xaxes(categoryorder='category ascending')

fig.show() 
```

**Third attempt: creation of a descending ordered array for categoryarray**
```
analysis_df = analysis_df.sort_values(by=['int_first_min_DTE'], ascending=[False])
# print(analysis_df)
# Crea il grafico di dispersione con Plotly Express
fig = px.scatter(analysis_df, x='int_first_min_DTE', y='min_max_rel_delta', 
                 title='Distribuzione dei profitti relativi min_max_rel_delta vs int_first_min_DTE')
x_label_order_array = analysis_df['int_first_min_DTE'].unique()
print(x_label_order_array)
# Mostra il grafico
fig.update_xaxes(categoryorder='array', categoryarray = x_label_order_array)

fig.show() 
```

in this attempt, the x_label_order_array values are as follows

```
[43 42 39 36 35 32 31 30 29 28 26 25 24 23 22 21 18 17 16 15 14 11 10  9
  8  7  5  4  3  2  1  0]
```

So it is in the correct descending order. 

In all these cases what I get is 

![newplot (12)](https://github.com/plotly/plotly.py/assets/46624075/f7d16efa-0c8e-4a14-af01-106923fa1c74)

As you can see the X axe is sorted by ascending values. Same using px.bar. Am I wronging something?

**Comment by alexcjohnson** [comment]
Is your goal to keep the x axis numeric, just reverse it? If so `fig.update_xaxes(autorange='reversed')` is what you want. If instead you want a category axis, which would remove the extra whitespace at values that have no data because it would treat each unique number as a category rather than part of a linear scale, you can `fig.update_xaxes(type='category')` and then all the ordering above will have an effect.

**Comment by fede72bari** [comment]
Thank you @alexcjohnson, my goal is not to skip the missing data that generate white spaces in the chart (even if I have this problem with showing candlesticks yet, but it is another issue and I will try your last suggestion); rather than this, my goal is to show the data in descending int_first_min_DTE order or keep the int_first_min_DTE as it is in the provided DataFrame that in this specific case has been previously sorted in descending order. Or indeed respect the order provided by (categoryorder='array', categoryarray = x_label_order_array). I have tried your suggestion on using fig.update_xaxes(autorange='reversed') and ... it works!!! Still, I have not understood why the others are not working; could it be possible because I have to disable the autorange function? Thanks.

**Comment by alexcjohnson** [comment]
Great! All the `category*` attributes only apply to category axes, not numeric, so they are ignored unless you explicitly use `type='category'`

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
