### ISSUE TITLE
Cannot get shown 3 trendlines as the 3 colors of the scatter chart

### ISSUE THREAD

**Issue by fede72bari** [plotly/plotly.py#4325]
I used the following code

```
# Filtra e seleziona solo le colonne necessarie
filtered_data = filtered_buy_call[filtered_buy_call['is_min_call'] == 1][['int_DTE', 'C_DELTA', 'C_ASK']]
filtered_data = filtered_data[((filtered_data['int_DTE'] == 1) | (filtered_data['int_DTE'] == 12) | (filtered_data['int_DTE'] == 14)) & (filtered_data['C_ASK'] <= 0.5)] #  & (filtered_data['C_ASK'] <= 0.5)
# Crea il grafico scatter con Plotly Express
fig = px.scatter(filtered_data, 
                 x='C_ASK', 
                 y='C_DELTA', 
                 color='int_DTE', 
                 trendline = 'lowess',
                 title='Distribuzione dei Valori di Delta per ogni Valore della Call con is_min_call == 1',
                 labels={'C_ASK': 'Prezzo della Call', 'C_DELTA': 'Valore di Delta', 'int_DTE': 'int_DTE'})


# Mostra il grafico
fig.show()
```

The scatter chart is drown properly, but just one trendline is shown. Am I wronging something? Here is the result:

![newplot (13)](https://github.com/plotly/plotly.py/assets/46624075/1d5422dd-8539-433e-a791-5a06daf37ed4)

**Comment by alexcjohnson** [comment]
Hi @fede72bari - how-to questions are better suited to https://community.plotly.com/, so we can keep GitHub for bugs and feature requests. Thanks!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
