### ISSUE TITLE
Would a simple px.pictogram function that takes bar chart input and outputs scatter or heatmap be useful?

### ISSUE THREAD

**Issue by rl-utility-man** [plotly/plotly.py#4326]
Hello,

I recently needed to visualize the number of students enrolled in specific colleges, which is a distribution where values around 1,000 are common, the median is ~10,000 and a few schools enroll ~60,000 students.  A conventional bar chart would make the important difference between say 1,000 and 3,000 students almost invisible.  I was considering a pictogram that would show e.g. one person icon for each 1,000 students in rows of up to say 15-20 icons with the largest campuses wrapping onto additional lines.  It's easy to imagine wanting to make this a stacked bar chart with e.g. icons in different colors for men and women; or for undergraduate and graduate students.  This is essentially an exercise in taking barchart style options and producing scatterplot or heatmap output.

There are posts on how to build your own solutions to this problem e.g. here:
https://blog.matteoferla.com/2019/10/pictograms-with-plotly-and-fontawesome.html
https://community.plotly.com/t/waffle-chart-in-plotly-dash/51431

The basics seem like a straightforward Python exercise, but some nice-to-have features, like being able to hide arbitrary segments of a stacked bar chart and then have the remaining segments shift left are far harder and likely require adding to the JavaScript.  Would wrapping the two basic examples in a friendly call be of interest?  Is it already on your roadmap?  Thanks!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
