### ISSUE TITLE
Interpolation method for 'Surface'

### ISSUE THREAD

**Issue by JintaoLee-Roger** [plotly/plotly.py#4332]
Hi!

I have some problems about `Surface`.

My surfaces are three slices of a 3D volume, which only contains [0, 1, 2, 3, 4] five values, and each value means one class.

However, after plotting the slices, I notice that an anomalous line appears at the boundary between two classes (values). I believe this might be related to the interpolation method. Is there a way to set the interpolation method to 'nearest' in order to avoid the presence of other values, similar to the `interpolation='nearest'` parameter in `plt.imshow()`?

![image](https://github.com/plotly/plotly.py/assets/38800137/5228645b-b522-4dac-939f-2bef017e0fd4)

Thanks!

**Comment by sOnU1002** [comment]
import plotly.graph_objs as go
import numpy as np

Z = np.array([[0, 0, 1, 1],
              [0, 2, 2, 1],
              [3, 3, 2, 1],
              [3, 4, 4, 4]])

go.Figure([go.Surface(z=Z)]).show()

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
