### ISSUE TITLE
Table component, filling cells with <a href> elements - makes cell height grow.

### ISSUE THREAD

**Issue by Marcin-Narzynski** [plotly/plotly.py#4333]
Plotly Python version 5.15.0.
I create a Table element. Next I fill cells with strings. Table is created as expected. I can set height of rows. 
Now, lets fill some cells with strings in format of html "a" component ("`<a href...>...`"). This time rows of cells grow. Height set by parameter does not shrink them. It looks like a bug.

**Comment by tomczykart** [comment]
Hi, I am trying to recreate this bug. Did you somehow put html a href into plotly go.Table object or used dash app?

**Comment by Marcin-Narzynski** [comment]
I've just created a function returning a string:
`def create_href(text: str, link: str):
    result = f'<a href="{link}"><b>{text}</b></a>'
    return result`
This string is just passed to cells.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
