### ISSUE TITLE
[REQUEST] A simple renderer that starts an http server and prints the URL to stdout?

### ISSUE THREAD

**Issue by carschandler** [plotly/plotly.py#4338]
It would be awesome to have a renderer that works just like `browser`, but prints the URL to `stdout` instead of attempting to open it with a browser. I like to work in a Jupyter Notebook that I start inside WSL, and then open it in my native Windows browser by simply clicking the URL that it prints to stdout. I'd like to be able to do the same with plotly figures. I've developed a workaround by registering a new "browser" class in the `webbrowser` module, which plotly's `fig.show(renderer='browser')` uses under the hood:

```python
import webbrowser

class PrintUrl:
    def open(self, url, *args, **kwargs):
        print(url)

webbrowser.register('print', PrintUrl)
```

Now I can call `fig.show(renderer='browser', using='print')` to get the desired result.

It would just be nice to skip this additional step and have a `renderer='print_http_url'` option or something.

**Comment by sOnU1002** [comment]
import plotly.io as pio

class PrintUrlRenderer:
    def __call__(self, fig_dict, **kwargs):
        print(fig_dict["url"])

pio.renderers.default = PrintUrlRenderer()

import plotly.express as px
fig = px.scatter(x=[1, 2, 3], y=[4, 5, 6])
pio.show(fig)

**Comment by carschandler** [comment]
@sOnU1002 that's also great; thank you!

Turns out the best solution for me is to just properly set my `BROWSER` environment variable to the native Windows executable through `/mnt/c/path/to/brave.exe` and then `fig.show(renderer='browser')` works as intended! I do still think that there could be use for a default renderer that starts the server and prints the URL, though, similar to how you can start `jupyter notebook --no-browser` and all the information about the server is printed for you.

**Comment by sOnU1002** [comment]
import webbrowser

# Replace this URL with the actual URL you want to open
url_to_open = "https://www.example.com"

# Open the URL in the default web browser
webbrowser.open(url_to_open)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
