### ISSUE TITLE
Feature Request: Plotly Express ability to change the icon in the legend

### ISSUE THREAD

**Issue by e-wallace** [plotly/plotly.py#4342]
> Unfortunately this is not possible via plotly currently. Plotly's legend symbols are 1-1 with their marker counterparts such that the user can essentially only change the legend via the markers characteristics. I.e. Making the bar graph purple will make the legend symbol purple, but you can't directly change the legend to purple without changing the bar graph to be purple. [source](https://stackoverflow.com/questions/66456467/custom-markers-in-plotly-dash-legend
)

When creating a bar graph like so:

```
import plotly.express as px
df = px.data.tips()
fig = px.histogram(df, x="sex", y="total_bill",
             color='smoker', barmode='group',
             height=400)
fig.show()
```
It creates a legend that reflects the graph style. 
<img width="800" alt="Screen Shot 2023-08-28 at 4 59 45 PM" src="https://github.com/plotly/plotly.py/assets/44043492/a2ed04d6-077a-4f9b-b148-eb915be373e3">

There's no property that allows you to change or customize the icon used in the legend. 

The request is to create a property in plotly express that allows you to choose the legend marker. Default could be the current case, which is to match the graph. Other options could be line, square or circle. 

This FR came from an enterprise client and in my research I found it was echoed by the community as well
https://stackoverflow.com/questions/66814448/plotly-how-to-change-legend-item-shape-from-line-to-box-or-circle-in-a-line-cha
https://stackoverflow.com/questions/66456467/custom-markers-in-plotly-dash-legend

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
