### ISSUE TITLE
Feature request: Explicit control over leader lines of labels in px.pie 

### ISSUE THREAD

**Issue by Madrigallo** [plotly/plotly.py#4345]
Hello, this is my first post here so I'm sorry if there's something I'm not aware of.
I would like to request a feature for better control over leader lines of labels outside pie charts.
For example:
```
import pandas as pd
import plotly.express as px
df = pd.DataFrame([["C", "H", "N", "S", "O"],[0.47514, 0.06385, 0.12931, 0.00794, 0.32376]])
df = df.transpose()
df.columns=["element", "value"]

fig = px.pie(df, values="value", names="element")
fig = fig.update_traces(textposition='auto', textinfo='percent+label', showlegend=False)
fig = fig.update_layout(uniformtext_minsize=20, uniformtext_mode="show")
fig
```

Produces 
![image](https://github.com/plotly/plotly.py/assets/143700379/d719929b-90da-4ef6-a439-2767d4ae480a)

I would like to be able to either force leader lines for all outside labels, or be able to switch them off. As you see, the part "S" has no leader line even though one would expect one there.
Thanks!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
