### ISSUE TITLE
Feature: reference a rangeselector button range with update_xaxes instead of having to define the values manually

### ISSUE THREAD

**Issue by celia-lm** [plotly/plotly.py#4346]
Reference/MRE: https://plotly.com/python/range-slider/#basic-range-slider-and-range-selectors

By default, when rangeslider + rangeselector are defined for a figure, the default range is `"all"`; it doesn't matter if the `"all"` button is not defined or if other buttons are defined after the `"all"` rangeselector button. It's possible to set the range of other button manually, but the developer needs to calculate explicitly the limits of the range.

That is, the developer needs to include the Python code that would be equivalent to this: https://github.com/plotly/plotly.js/blob/a5577d994ea06785be100f9e7decff3e6cd8ab1f/src/components/rangeselector/get_update_object.js#L4

For example, for the YTD button, the developer would need to include something this code:
```
fig.update_xaxes(
    range=[
        # take the last element of the X axis (highest date) and calculate the first day of that year to calculate xmin
        str(datetime.strptime(fig['data'][0]['x'][-1], "%Y-%m-%d").date().replace(month=1, day=1)),
        # take the last element of the X axis as xmax
        fig['data'][0]['x'][-1]
        ]
)
```

It's be great to have an option like this:
```
fig.update_xaxes(range=rangeselector['YTD'])
```

Related: https://github.com/plotly/plotly.py/issues/828

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
