### ISSUE TITLE
Can add real-time update function?

### ISSUE THREAD

**Issue by CyberFork** [plotly/plotly.py#4362]
I tried to update the chart in real-time, but it did not work as expected. Of course, I could not find any reference to real-time updating in the documentation.

`import plotly.graph_objects as go
import numpy as np
from datetime import datetime
import time

fig = go.Figure(go.Scatter(x=[], y=[]))
fig.show()
np.random.seed(1) 

# real time update
for i in range(30):
    x = datetime.now().strftime("%H:%M:%S.%f")
    y = np.random.randn(1)
    fig.add_trace(go.Scatter(x=[x], y=[y]))
    fig.update_layout(title = f'Real Time Data: {i}')
    fig.update_xaxes(title='Time')
    fig.update_yaxes(title='Value')
    fig.update_traces(mode='lines+markers')

    print(i)
    time.sleep(1)`

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
