### ISSUE TITLE
Feature requests: add optional CSS attributes to HTML renderers

### ISSUE THREAD

**Issue by jeertmans** [plotly/plotly.py#4369]
Hello,

Currently, using the HTML renderers like `IFrameRenderer` wraps the output inside an `<iframe>...<iframe>`, with a fix set of attributes.

I manage to override the default behavior by subclassing `IFrameRenderer` and implementing my own`to_mimebundle`.

However, I think this would nice to be able to have options like `**attrs` or `style` to specify custom attributed.

E.g., `IFrameRenderer(id="123")` would render `<iframe id="123">...<iframe>`.

What do you think?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
