### ISSUE TITLE
Add functionality to handle large data or download contours for Histogram2dContour

### ISSUE THREAD

**Issue by NursultanBS** [plotly/plotly.py#4378]
I'm using plotly.graph_objects.Histogram2dContour with large data (up to 5 million points) and when I save the plot in html file, I get a huge file sizes (250+ mB), because all of the points are getting saved even though they are not needed for the plot itself. Is it possible to add a functionality to avoid saving all data points for this plot and do the computation of contours beforehand?

Or if this is not possible, could you add functionality to download the contour information and ability to plot this contours without saving all points?

Thank you!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
