### ISSUE TITLE
UpdateMenu breaks px.Bar figure when Color Argument Specified

### ISSUE THREAD

**Issue by ehardgrave** [plotly/plotly.py#4386]
Hello All,

I'm trying to plot a bar chart and separate the values of each bar by the value in a separate column. I also want to add a dropdown / button array using updatemenu which allows me to update how the data is filtered.

This code works acceptably:
```
import numpy
import plotly.express as px
df = px.data.gapminder()
dfstart = df[df['year'] == 1967]
bar = px.bar(
                        x = dfstart["continent"],
                        text= dfstart["country"],
                        y= dfstart["pop"]
                        )
df67 = df[df['year'] == 1967]
df72 = df[df['year'] == 1972]
yearbuttons = [
    {'label': "67", 'method': 'update',
     'args': 
     [{'x': [df67['continent']], 
       'y': [df67['pop']], 
       'text': [df67['country']]
       },{'title': 'Top 5'}]},
    {'label': "72", 'method': 'update',
     'args': 
     [{'x': [df72['continent']], 
       'y': [df72['pop']], 
       'text': [df72['country']]
       },{'title': '72'}]}
    ] 
bar.update_layout(
    updatemenus=[
        dict(
            type = "dropdown",
            direction = "down",
            buttons=yearbuttons,
            x=1,
            xanchor="left",
            y=1.3,
            yanchor="top",
            active = 0
        )
    ]
)
bar.show()
```

However, if I would like to separate the value of each bar by color, and replace 'text' with 'color' in the above example, then the data breaks as soon as I click a button and the data blows up. It seems like the color argument is still pointing at the original graph and plotting all colour values in the original graph against all values in the updated graph.
I posted on the forum in case there was an answer there and didn't get far: [See Forum Post](https://community.plotly.com/t/use-updatemenu-buttons-to-filter-data-for-a-given-value-in-a-column-of-the-underlying-dataframe/79247/8)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
