### ISSUE TITLE
Way of handling all None/NaN vector for marker_color in go.Scatter

### ISSUE THREAD

**Issue by bonfire27** [plotly/plotly.py#4394]
If I do a go.Scatter with an all NaN vector on the markers color attribute the code raises an error:

```
import plotly.graph_objects as go
fig=go.Figure(
  data=[
    go.Scatter(
      x=[1,2,3,4],
      y=[2,4,5,7],
      marker_color=[None,None,None,None],
      )
  ]
  )
fig.show()
```

> ValueError: 
>     Invalid element(s) received for the 'color' property of scatter.marker
>         Invalid elements include: [None, None, None, None]

I think it would be better to default it to the NaN color instead

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
