### ISSUE TITLE
plotly express showing Unicode characters with to_json()

### ISSUE THREAD

**Issue by AbdealiLoKo** [plotly/plotly.py#4395]
I took some code from the plotly examples on the website and ran it in a notebook.
```py
import plotly.express as px
df = px.data.tips()
fig = px.histogram(df, x="total_bill")
fig.show()
(fig.to_json())[:150]
```

The hover text in the image that shows up in notebook is fine - but when I export the JSON an use it on my website there are unicode characters present in the JSON:
```
'{"data":[{"alignmentgroup":"True","bingroup":"x","hovertemplate":"total_bill=%{x}\\u003cbr\\u003ecount=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","le'

```

![image](https://github.com/plotly/plotly.py/assets/2200743/f5e53436-ec3d-48ed-ab03-a4d19de1d575)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
