### ISSUE TITLE
Warn about `write_image` hanging with latest Kaleido 

### ISSUE THREAD

**Issue by OverLordGoldDragon** [plotly/plotly.py#4401]
https://github.com/plotly/Kaleido/issues/134

Unfixed problem, had to spend time debugging. A warning should be thrown, and it'd help to suggest the commonly-working fix of downgrading to `kaleido==0.1.0.post1` (`0.1.0` via `-conda-forge` also worked for me).

**Comment by eeintech** [comment]
Thanks for the tip, I ran into the same issue.

**Comment by MAhbab** [comment]
> [plotly/Kaleido#134](https://github.com/plotly/Kaleido/issues/134)
> 
> Unfixed problem, had to spend time debugging. A warning should be thrown, and it'd help to suggest the commonly-working fix of downgrading to `kaleido==0.1.0.post1` (`0.1.0` via `-conda-forge` also worked for me).

Thank you for this! Worked like a charm on Windows.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by kendavidn** [comment]
Still seems to be an issue for the current kaleido

**Comment by gvwilson** [comment]
hi @kendavidn - we have an early release candidate of a re-architected kaleido that seems to solve some of these problems - if you're willing to give it a try, please mail me (greg.wilson@plot.ly) and I'll point you at it. thanks - Greg
