### ISSUE TITLE
Feature suggestion: plotly_express.heatmap (with animate_frame)

### ISSUE THREAD

**Issue by bonfire27** [plotly/plotly.py#4407]
I can do a sort of anmimated heatmap with plotly express by using the colors in plotly_express.scatter:
 fig = px.scatter(
        df.reset_index(),
        x="index0",
        y="index1",
        animation_frame="index2",
        color="values",
    )
But if I want to do a proper heatmap the function density_heatmap sums the values and the function imshow doesn't allow input in the same format as px.scatter.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
