### ISSUE TITLE
Output of dcc.Graph (px.imshow) to tiff

### ISSUE THREAD

**Issue by matt-sd-watson** [plotly/plotly.py#4408]
I have an application that uses `dcc.Graph` and `px.imshow` to display multiplexed images that originally came from tiff. I would like to be able to export the image canvas with character annotations (written labels and shapes) to a tiff file format, but I see that it is not supported by `fig.write_image`. 

It would be nice to have the ability to have tiff files be supported by fig.write_image, possible using support through [tifffile](https://github.com/cgohlke/tifffile)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
