### ISSUE TITLE
Problem with Go Pie Chart, and Interested in contributing to the community for the pie chart

### ISSUE THREAD

**Issue by yyhtbs-yye** [plotly/plotly.py#4420]
I am using plotly go. The key problem for me is the legend of go.Pie is automatically generated from labels. and it is not possible to add legendgroup for each sector as far as I know. It will not allow us to sync legend with other charts (unless using dash for sync). 

It might be better to enable sector by sector adding to the pie chart just like bar charts. 

The function should be logically simple to implement as it is the same as lazy rendering as stack bar chart. 

I wonder if the community would like to provide the function in the near future or I would happy to contributing to the feature. 

However, I do not really understand the structure of the repo (I can see the graph_obj.Pie there, but inside is not clear to me). If there are any guideline for the repo, that would be great. 

--------------------------------------------------------------------------------------------------------------------------------

**Please** accompany bug reports with a reproducible example. Please use the [latest version](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md) of plotly.py in your report unless not applicable.

Note that GitHub Issues are meant to be used for bug reports and feature requests only. Implementation or usage questions should be asked on [community.plotly.com](https://community.plotly.com/c/graphing-libraries/python/10) or on Stack Overflow (tagged [`plotly`](https://stackoverflow.com/questions/tagged/plotly)).

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
