### ISSUE TITLE
how to change colors with css variables?

### ISSUE THREAD

**Issue by terlan4** [plotly/plotly.py#4444]
Hi, I would like to be able to change colors with css variables so that when other parts of my React code changes that css variable dynamically, it should reflect the change inside of plotly frame as well. (It's jupyterlab app, so some widgets are React and some are python plotly) How can I achieve something like this? Thanks

```py
# for example it would be great if the following code would work
fig.add_annotation(
    bgcolor="var(--custom-color-var-that-dynamically-changes)",
)
```

**Comment by Coding-with-Adam** [comment]
hi @terlan4 
This is a good question to ask on the [Plotly forum](https://community.plotly.com/) first. If you don't get an answer there, please let me know.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
