### ISSUE TITLE
Heatmap using `px.imshow` stops rendering fully after seemingly arbitrary number of elements from a pandas dataframe

### ISSUE THREAD

**Issue by matt-sd-watson** [plotly/plotly.py#4484]
I have a heatmap based on `px.imshow` in my dash application that renders a dataframe of expression values. Currently, the visualization works fine if the number of dataframe rows is 65000 or less:

![Screenshot from 2024-01-17 15-08-39](https://github.com/plotly/plotly.py/assets/40243147/1d4f4d26-89bb-452d-aa27-e378970dbef4)

However, as soon as I increase the number of dataframe rows ever so slightly to 66000, the heatmap no longer actually shows the values and just returns a partially blank graph:

![Screenshot from 2024-01-17 15-06-16](https://github.com/plotly/plotly.py/assets/40243147/097dbf1b-a0fa-4610-b088-f487f93096fb)

Additional implementation details:

- this applies for data import as well as changing the number of data frame rows in the application interactively using a callback

The heatmap is rendered in a `dcc.Graph` component that itself is contained in a `dbc.Col` of width 6 with the following parameters:

```
dcc.Graph(id="quantification-heatmap-full",
                                    figure={'layout': dict(xaxis_showgrid=False, autosize=False,
                                    yaxis_showgrid=False, xaxis=XAxis(showticklabels=False),
                                    yaxis=YAxis(showticklabels=False), margin=dict(l=5, r=5, b=15,
                                    t=20, pad=0))}, responsive=False),
```

**Comment by Coding-with-Adam** [comment]
Thanks for reporting this issue, @matt-sd-watson 
Do you mind sharing with us MRE so we can reproduce this error locally?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
