### ISSUE TITLE
 Add Support for fill Hatching /Patterns styles in Plotly Boxplots [ Enhancement Request ]

### ISSUE THREAD

**Issue by Isurusachitha** [plotly/plotly.py#4503]
**Issue Description
![Screenshot 2024-01-31 110419](https://github.com/plotly/plotly.py/assets/22257977/504c7d62-dd84-4f51-98e1-85a12dd6f66f)
:**

The current implementation of Plotly includes support for fill patterns (hatching or texture) in various chart types such as Bar charts, Histograms, Polar Bars, Area charts, and Pie charts. However, **this crucial feature is notably absent in Plotly Boxplots.**

**Request:**

Considering the widespread use of Boxplots in scientific data visualization, especially in grouped boxplots, the addition of fill patterns to Plotly Boxplots would significantly enhance the interactive and informative aspects of plots. This feature is essential for various reasons:

Accessibility: Introducing fill patterns allows for double-encoding variables, making visualizations more accessible to users with visual impairments. This improvement goes beyond the use of color alone.

Additional Variable Encoding: The inclusion of fill patterns provides the ability to encode an additional variable, offering more comprehensive insights and analysis possibilities.

Print-Friendly Charts: The option to use fill patterns in Boxplots makes charts more printer-friendly, especially in black and white, catering to situations where color might not be distinguishable.

By addressing this enhancement request, Plotly can further enhance its capabilities and cater to a wider range of users with diverse visualization needs.

**Comment by Coding-with-Adam** [comment]
Thank you for the suggestion, @Isurusachitha . 
Is this something you would like to try to build and create a pull request for?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
