### ISSUE TITLE
Can we add customdata to the px.density_heatmap?

### ISSUE THREAD

**Issue by muntakim1** [plotly/plotly.py#4508]
Instead of showing z value we wanna show a different value in text_auto from the dataframe by passing a column as customdata.
Please add this feature!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
