### ISSUE TITLE
question to subplots and legends

### ISSUE THREAD

**Issue by geraldstanje** [plotly/plotly.py#4602]
Hi,

this is a question to subplot with multiple legends.

i currently have a subplot with a single legend - but its hard to see that the legend is for 2 plots...

how can i have 2 legends in this subplot?
i want to have:
- legend 1 at the same level as plot 1 (for qps bars)
- legend 2 at the same level as plot 2 (for latency bars)
how to achieve that?

Here the plot:
![image](https://github.com/plotly/plotly.py/assets/6293104/0daf536d-c3e4-44cf-ac42-8ac957dfcc86)

Thanks

**Comment by Coding-with-Adam** [comment]
hi @geraldstanje 
I'm not sure that's possible. But you'll get much more help if you post this question on the [Plotly forum](https://community.plotly.com/), because more community members are on that platform. Can you please ask your question there. If you don't get an answer on the forum, or if there is a way to separate the vertical positioning of the legends, we can re-open this issue.
