### ISSUE TITLE
`Download plot as png` from `dcc.Graph` sometimes shows a blank PNG with annotations

### ISSUE THREAD

**Issue by matt-sd-watson** [plotly/plotly.py#4604]
Our application uses a `dcc.Graph` with `px.imshow` to render a user-edited image with annotations. 

Certain users have reported the following image errors when using the `Download plot as png`, where the underlying image is grayed out with the default grid lines provided, but the text annotations are still retained: 

![324509122-a7923dd6-c7da-4ddc-ae4e-b415d163b814](https://github.com/plotly/plotly.py/assets/40243147/3abe580d-366b-47bc-af61-9a6cba5052e3)

This issue is difficult to replicate because it occurs only for certain users, and not for others who have similar OS and browser setups.

**Comment by Coding-with-Adam** [comment]
Hi @matt-sd-watson 
I'll try to replicate on my end using different browsers. Do you mind sharing sample code?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
