### ISSUE TITLE
How to smooth 3D surface plot

### ISSUE THREAD

**Issue by btayhan** [plotly/plotly.py#4633]
I have a 3D surface plot like this:

![image](https://github.com/plotly/plotly.py/assets/144340455/567b26e0-e501-42ff-b108-ef67af0391dd)

I am not sure how to smooth this plot, I searched but could not find any information.

**Comment by empet** [comment]
If you know the surface height, z, at n scattered points of coordinates (x, y),
then you can get the surface height at the points of a regular meshgrid, using 
`griddata`, method="cubic",  from `scipy.interpolate`: 
[https://docs.scipy.org/doc/scipy/tutorial/interpolate/ND_unstructured.html](https://docs.scipy.org/doc/scipy/tutorial/interpolate/ND_unstructured.html)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
