### ISSUE TITLE
Subtitle does not render following example from docs

### ISSUE THREAD

**Issue by hannahker** [plotly/plotly.py#4715]
Following this example from the [docs](https://plotly.com/python/figure-labels/#adding-a-plot-subtitle), I'm not able to get a subtitle to render: 

```python
import plotly.graph_objects as go
from plotly import data

df = data.gapminder().query("continent == 'Europe' and (year == 1952 or year == 2002)")

df_pivot = df.pivot(index="country", columns="year", values="lifeExp")

fig = go.Figure(
    [
        go.Bar(
            x=df_pivot.index, y=df_pivot[1952], name="1952", marker_color="IndianRed"
        ),
        go.Bar(
            x=df_pivot.index, y=df_pivot[2002], name="2002", marker_color="LightSalmon"
        ),
    ],
    layout=dict(
        title=dict(
            text="Life Expectancy",
            subtitle=dict(
                text="Life expectancy by European country in 1952 and in 2002",
                font=dict(color="gray", size=13),
            ),
        )
    ),
)


fig.show()
```

This code outputs: 

![Screenshot 2024-08-13 at 1 50 04 PM](https://github.com/user-attachments/assets/8b08910a-3341-442d-b882-226ab134d89a)

I have validated that I have installed `plotly==5.23.0`.

**Comment by rusiano** [comment]
+1

**Comment by ndrezn** [comment]
Are both/either of you using VSCode notebooks and experiencing this issue? My guess is yes...

If you are using VSCode notebooks to generate your chart, you'll need to manually specify the notebook renderer because the builtin Plotly.js for VSCode notebooks is too old. See: https://github.com/microsoft/vscode-notebook-renderers/pull/199

The workaround is to add:
```python
import plotly.io as pio
pio.renderers.default = "notebook_connected"
```

To your notebook.

Rather than validating the version of the Python package, can you check the version of Plotly.js in use by hovering over the Plotly icon in the modebar? Subtitles were added in `v2.34.0`, so this should be `>2.34.0`.

![Image](https://github.com/user-attachments/assets/091e4bd8-d9bb-4413-8bfb-aa578433efb6)

**Comment by ndrezn** [comment]
I am going to close in favour of #4827 but feel free to re-open if my diagnosis above is incorrect.
