### ISSUE TITLE
Some charts rendering differently on master branch vs Plotly.py 5.24.1

### ISSUE THREAD

**Issue by LiamConnors** [plotly/plotly.py#4863]
There are a few charts that show differently with what's on master branch vs the latest release of Plotly.py:

**1. Histogram with px**
```
import plotly.express as px
tips = px.data.tips()
fig = px.histogram(
    tips, x="total_bill", y="tip", color="sex", marginal="rug", hover_data=tips.columns
)
fig.show()
```

5.24.1:

![Image](https://github.com/user-attachments/assets/17fb38ea-e9e5-42be-8c4e-c33d4c29f86c)

Master branch:

![Image](https://github.com/user-attachments/assets/9417ef76-67ff-4562-a16d-e7bc08cd3872)

**2. Timeline with px**

```
import pandas as pd
import plotly.express as px
df = pd.DataFrame(
    [
        dict(Task="Job A", Start="2009-01-01", Finish="2009-02-28"),
        dict(Task="Job B", Start="2009-03-05", Finish="2009-04-15"),
        dict(Task="Job C", Start="2009-02-20", Finish="2009-05-30"),
    ]
)
fig = px.timeline(df, x_start="Start", x_end="Finish", y="Task", color="Task")
fig.show()
```

5.24.1:

![Image](https://github.com/user-attachments/assets/c9e730fe-763e-4b66-ac86-04e12f2266be)

Master branch:

![Image](https://github.com/user-attachments/assets/5c4f8ce8-de81-4746-9280-9a3b9d3f1c14)

**3. Scatter with px**

```
iris = px.data.iris()
fig = px.scatter(
    iris,
    x="sepal_width",
    y="sepal_length",
    color="species",
    marginal_y="rug",
    marginal_x="histogram",
)
fig.show()
```

5.24.1:

![Image](https://github.com/user-attachments/assets/e311c946-744c-4ef1-99b9-b0a27d656867)

Master branch:

![Image](https://github.com/user-attachments/assets/170b3253-bc25-47f2-9375-f48089f69150)

**Comment by emilykl** [comment]
OK, I've confirmed that at least the histogram case is indeed a result of https://github.com/plotly/plotly.js/pull/7009/.

Before that PR, with `barmode: 'relative'`, the `offsetgroup` property of traces was ignored. That PR introduced a change where `offsetgroup` is applied in relative barmode (and bars with the same category-axis value _and_ offsetgroup are stacked), which has the effect that if two traces have different `offsetgroup` values, they appear as grouped bars even if `barmode` is set to `relative` or `stacked`.

This caused the change in behavior we are seeing for histograms, since `px` assigns an `offsetgroup` to each trace when creating the figure object.

Maybe the fix is as simple as removing `offsetgroup` from the traces in the generated figure object -- I'm not sure whether there's a reason for it to be there; still investigating.
