### ISSUE TITLE
Add `scattermap` and `map` to plotly.py templates similar to `scattermapbox` and `mapbox`

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.py#4879]
In order for `scattermap` and `map` behave similar to `scattermapbox` and `mapbox`, we should add `scattermap` and `map` to the templates inside `packages/python/plotly/plotly/package_data/templates/`.

**Comment by archmoj** [comment]
cc: @gvwilson @ndrezn

**Comment by archmoj** [comment]
Are there similar defaults in ddk that should be updated?

**Comment by archmoj** [comment]
@LiamConnors Are these templates auto generated?

**Comment by archmoj** [comment]
We should add `map` alternatives e.g. [here](https://github.com/plotly/plotly.py/blob/5898816e594a38270843d022d5b1e977dd498d0d/packages/python/plotly/templategen/definitions.py#L143) and in other places similar to `mapbox`.

**Comment by gvwilson** [comment]
but where is `templategen` called and by whom? I can't find anything in either plotly.js or plotly.py that invokes it.

**Comment by gvwilson** [comment]
Progress of a sort. Please note that I'm working off the master branch, which may not have the most up-to-date files.
1. Modified packages/python/plotly/templategen/utils/__init__.py to change template.data.heatmapgl[0] to template.data.heatmap[0]. (Step 3 fails without this change.)
2. Moved the interesting bits of packages/python/plotly/templategen/__init__.py to packages/python/plotly/templategen/__main__.py so that we can run python -m templategen from the packages/python/plotly/templategen directory.
3. Ran that command, which generated new versions of these six files:
    - plotly/package_data/templates/ggplot2.json
    - plotly/package_data/templates/plotly.json
    - plotly/package_data/templates/plotly_dark.json
    - plotly/package_data/templates/plotly_white.json
    - plotly/package_data/templates/seaborn.json
    - plotly/package_data/templates/simple_white.json
4. Note that this command did not generate new versions of gridon.json, presentation.json, xgridoff.json, or ygridoff.json - I don't know why.
I'm attaching pretty-printed versions of the old and new versions of plotly.json. The only difference is that the new version has an entry for scattermap as well as scattermapbox, while the old version only had scattermapbox.[new-plotly-indented.json](https://github.com/user-attachments/files/17758108/new-plotly-indented.json)
[old-plotly-indented.json](https://github.com/user-attachments/files/17758109/old-plotly-indented.json)

**Comment by archmoj** [comment]
Thanks @gvwilson That's a good progress to help continue automation of this process.
Are you going to open a pull request?
If so on `master` please `git pull` switch to have the latest files.
Then please switch to a new branch other than master and and rerun the script and commit the changes.
You may consider skipping the pretty-print step in your PR specially if that helps the diffs to be clearer.

**Comment by gvwilson** [comment]
I've created a new branch off `master` with my changes called `add-new-traces-to-templategen` - @archmoj please take it from here.
