### ISSUE TITLE
Odd colormaps generated from a list of colors, in tools.py

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#507]
The method of defining a Plotly colorscale from a list of  colors  appears to change from one Plotly version to another, and moreover  in 1.12.0 the resulted colormap is really strange.

In this notebook: http://nbviewer.jupyter.org/gist/empet/f2cd8f4fa7c5cbb12a985d208bbcab67
I illustrate two different coloring of a trisurf generated with the same code, running first Plotly 1.11.0, and later  1.12.0.

The colormap used in the above notebook is defined by a list of three colors. These three colors are the first, mid and the last color in a list of 11  colors I used for defining the Plotly colorscale for the initial plot of this surface (with my own code, not  calling `FF.create_tisurf`):   https://plot.ly/~empet/13810/isosurface/

Comparing to the last plot, the two displayed in the notebook are too dark in the upper part of the surface.

**Comment by Kully** [comment]
@empet 

The `FF.create_trisurf` indeed _does_ function differently between different versions of Plotly. In plotly 1.12.0, the plot looks weird because it is actually using all three colors provided in the colorscale. It's assigning the last color to the highest z values of the triangle vertices, and happens to be a blue color.

In 1.11.0, the `trisurf` code will only take the first two colors in a list of colorscale to use for the color interpolation.

I hope this helps. Let me know if you have other questions.

**Comment by empet** [comment]
@Kully I cannot understand why when
the three colors  (in my code) are  cmap(0.0), cmap(0.5), and cmap(1.0), where `cmap=cmocean.cm.waveheight`,  and cmap(1.0) is the lighter color, the plot with 1.12.0 is so dark in the region plotted with colors close to cmap(1.0).  I address these questions not for me, because I usually don't use `FF.create_trisurf`, but for suggesting that the method to create a colormap from a list  is not the best one.
