### ISSUE TITLE
matplotlylib - change ticks=='inside' default to track

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#51]
from https://github.com/plotly/python-api/issues/46

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
