### ISSUE TITLE
colorbar is not working

### ISSUE THREAD

**Issue by orena1** [plotly/plotly.py#552]
This simple example is not working:

``` python
import matplotlib.pyplot as plt
import plotly.plotly as py
py.sign_in(?,?)
plt.ion()
fig = plt.figure()
cm = plt.cm.get_cmap('RdYlBu')
xy = range(20)
z = xy
sc = plt.scatter(xy, xy, c=z, vmin=0, vmax=20, s=35, cmap=cm)
plt.colorbar(sc)
plt.show()

plot_urlfig1 = py.plot_mpl(fig)
print plot_urlfig1
```

I get this 

> Dang! That path collection is out of this world. I totally don't know what to do with it yet! Plotly can only import path collections linked to 'data' coordinates

![image](https://cloud.githubusercontent.com/assets/8983713/17836432/89d88a8c-679b-11e6-94fb-f60619783a6b.png)

and the colorbar is missing

Thanks.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
