### ISSUE TITLE
Hoverinfo text doesn't display well with more than 6 subplots

### ISSUE THREAD

**Issue by PhML** [plotly/plotly.py#568]
I work in a jupyter notebook with plotly.offline (v'1.12.8').

In the following snippet, when I set `number_of_subplot` to `7` the hoverinfo text is only displayed for the four first values. 

``` python
from plotly import tools
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode

init_notebook_mode(connected=True)

number_of_subplots = 6

x = list(range(10))
y = list(range(10))
txt = ['txt'] * 10
fig = tools.make_subplots(number_of_subplots, 1)
trace = go.Scatter(x=x, y=y)
trace['text'] = txt
fig.append_trace(trace, 1, 1)
iplot(fig)
```

**Comment by cldougl** [comment]
Hi there,
This is because with that number of subplots your subplots are starting to overlap.
You have the option of increasing the height of your plot (recommended for): 
```
from plotly import tools
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode

init_notebook_mode(connected=True)

number_of_subplots = 8

x = list(range(10))
y = list(range(10))
txt = ['txt'] * 10
fig = tools.make_subplots(number_of_subplots, 1)
trace = go.Scatter(x=x, y=y)
trace['text'] = txt
fig.append_trace(trace, 2, 1)
fig.layout.height=1000
iplot(fig)
```
You also have the option of trying to set up the subplots by defining the axes domains as done in the examples [here](https://plot.ly/python/subplots/#simple-subplot) and [here](https://plot.ly/python/subplots/#multiple-subplots). This may help prevent overlap.

**Comment by PhML** [comment]
Increasing the height of my plot is fine. Thank you.

Would it be a sane behaviour if a warning was raised when subplots overlaps ? I think if such a warning had pop up, I would have found the solution myself. But here I had no clue.
