### ISSUE TITLE
Feature Request:  Table Feature Factory

### ISSUE THREAD

**Issue by keithjjones** [plotly/plotly.py#595]
Please think about adding the ability to get a table data back so you don't have to have it as a figure already.  Being able to add a table simply with the subplots facility would be much easier than the methods outlined in the documentation.  I couldn't find how to plot a pre-generated figure as a sub plot.  If the ability is there, I could not find it in the documentation.

**Comment by keithjjones** [comment]
For example, using the documentation won't plot a pie graph on top of a table.

**Comment by cldougl** [comment]
Hi there, unfortunately the table is part of our figure factory wrapper (the entire figure will be returned as these wrapper create the given chart with `data` and `layout` attributes.) This is necessary for this wrapper because the text is added with plotly annotations which are part of the layout object (not the data).
I'm going to close this issue because the request will not be possible with this given in this repo BUT we would like to add tables to our core graphing library [plotly.js](https://github.com/plotly/plotly.js), to make them a more customizable feature. You can follow [this issue](https://github.com/plotly/plotly.js/issues/991) for updates on that.

Additionally, it is possible to plot a table and piechart subplot: I've added an example here: https://plot.ly/python/table/#tables-with-graphs for more information about pie-chart subplots see: https://plot.ly/python/pie-charts/
