### ISSUE TITLE
Frames api interface

### ISSUE THREAD

**Issue by mdtusz** [plotly/plotly.py#633]
For creating plots with frames, it would be ideal if we can have an interface that matches closely to the plotly.js interface - something like

```py
py.plot(data=data, layout=layout, frames=frames)
```

would be awesome, and let plotly.py handle the internals of creating the references to grid data (e.g. `xsrc` and `ysrc` values).

**Comment by cldougl** [comment]
+1 plotly.js *and* the [`offline.plot()` syntax](https://plot.ly/python/animations/#moving-point-on-a-curve)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
