### ISSUE TITLE
Improve tests for Violin plots in FF

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.py#671]
The current test coverage in unreleased version: https://1894-14579099-gh.circle-artifacts.com/0/tmp/circle-artifacts.mLgBx3K/coverage-reports/py27-optional/plotly_figure_factory__violin_py.html at 62%

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
