### ISSUE TITLE
Feature request | Polar coordinates toggle between radians and degree

### ISSUE THREAD

**Issue by jolespin** [plotly/plotly.py#672]
I'm trying to port some of my `matplotlib` polar projection graphs to `plot.ly` b/c `plot.ly` looks way better.  Many of my functions are dependent on the `t` (or `x` in `matplotlib`) being in `radians` instead of `degrees`.  **Can future versions add an argument like `units="degrees"` or `units="radians"`?** It is easy to keep track of everything in this simple example but once the layers start building up and the coordinates become more abstract it get's a little difficult. 
```
# Import
import plotly.offline as py
import plotly.graph_objs as go
import numpy as np

py.init_notebook_mode(connected=True)

# Plot polar
t = np.linspace(0, 2*np.pi, 100)
trace_radians = go.Scatter(t=t, r=np.sin(t), name="radians", mode="line", marker=dict(color="black"))
trace_degree = go.Scatter(t=np.rad2deg(t), r=np.sin(t), name="degrees", mode="line", marker=dict(color="red"))

data = [trace_radians, trace_degree]
fig = go.Figure(data=data)
py.iplot(fig)
```
![screen shot 2017-01-23 at 10 39 15 am](https://cloud.githubusercontent.com/assets/9061708/22217612/87448c3a-e158-11e6-9b8b-8762f2dd2549.png)

**Comment by cldougl** [comment]
Hi there,
This sounds like a cool request. This feature would have to be implemented in our core [Plotly.js library](https://github.com/plotly/plotly.js) rather than the python API.
I would suggest checking out existing polar issues there or creating an issue in the js repo under the milestone `on-par-polar`: https://github.com/plotly/plotly.js/milestone/2
