### ISSUE TITLE
way to preserve square aspect ratio

### ISSUE THREAD

**Issue by arsenovic** [plotly/plotly.py#70]
would be nice to have something equivalent to mpl's `axis('equal')` command to force a square aspect ratio.

**Comment by dab3-2014** [comment]
Hi...I would like to help implementing solution # 3 in 2nd post, this one:
------
3.throw it in the plot call,  py.plot(fig, equal_axes=True)  
------
So would it be possible if some one more familiar with the code let us know a good point to start to implement this option in the plot function? It would be great if you point us in the right direction.

**Comment by chriddyp** [comment]
@dab3-2014 - I think we're going to stay away from #3 but instead for people to set `width` and `height` in `layout`. My thought is that setting the size and the aspect ratio is setting the same number of things as setting the width and the height, so I don't see enough benefit at this point.

**Comment by SimonBiggs** [comment]
@chriddyp - An example of where axis equal would be a huge benefit is in what I am using plotly for right now:
https://plot.ly/~SimonBiggs/113/bivariate-quadratic-spline-fit-using-the-parameters-equivalent-width-and-equival/

Since the width and length axis are equivalent to one another, if I zoom in on the right hand plot the aspect ratio should be preserved. However, currently, and as a result both plots should zoom in together and mirror one another. That is not the case currently.

Any deviation from the width and length parameters not being equal provides a misleading representation.

**Comment by akhmerov** [comment]
Is there any update on this? The milestone is definitely not up to date.

We've encountered this issue trying to plot honeycomb lattice over [here](http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/a3fl4d6tlkkm4tc/unit_cells.ipynb). Funnily 3D plotting has equal aspect ratios automatically (for no obvious reason).

**Comment by lmannering** [comment]
echoing @akhmerov 's comment - is there any update on this?

**Comment by akhmerov** [comment]
Just for those who find this deserted place via google, I found that manually setting the plot aspect ratio through height and width is an acceptable (although fragile) workaround.

**Comment by lmannering** [comment]
A square plot area is seems difficult to achieve (perhaps I'm missing something) with a colorbar visible.

**Comment by priisdk** [comment]
Is there any news on this issue?
I would also greatly appreciate something like "equal_axes=True", "axes('equal')" or "set_aspectratio=1" in a 2D plot with plotly.
Has it been implemented? If yes, what exactly is the syntax?

**Comment by tachim** [comment]
+1, this screws up any attempt at visualizing things like surface normals in 3D point clouds

**Comment by tachim** [comment]
@akhmerov can you elaborate on your solution?

**Comment by akhmerov** [comment]
@tachim I don't remember anymore, it's been a while. Everything we've done is in github.com/adriaanvuik/solid_state_physics

**Comment by jackparmer** [comment]
Part of this issue is solved in the latest version of plotly.js via this "Axis Constraints" PR - https://github.com/plotly/plotly.js/pull/1522 - which enables optional fixed axes aspect ratio on zoom.

The other feature brought up in this issue (coordinated zoom on subplots sharing an axis) would also need to be solved in plotly.js. Issue here: https://github.com/plotly/plotly.js/issues/1549

Any companies interested in sponsoring this? 
https://plot.ly/products/consulting-and-oem/

**Comment by priisdk** [comment]
Can someone please give a simple  example of a scatter plot with fixed ratio on zoom?

**Comment by bcdunbar** [comment]
Example of fixed ratio here https://plot.ly/python/axes/#fixed-ratio-axes and reference info here https://plot.ly/python/reference/#layout-xaxis-scaleanchor

**Comment by Juanlu001** [comment]
The `fig['layout'].update(width=500, height=500, autosize=False)` is not working as expected for me, so I will have to manually set the aspect ratio of each axis (x, y, z) or do some other thing. It would be great to have this in plotly!

**Comment by Juanlu001** [comment]
...although `fig['layout'].update(scene=dict(aspectmode="data"))` did the trick!

**Comment by dragoljub** [comment]
@Juanlu001 thanks for the layout trick. Any idea how to change the scale of the Z axis (without multiplying)? Basically X/Y axis are on same pixel scale and Z is on another scale.

**Comment by Juanlu001** [comment]
@dragoljub you're welcome! does https://github.com/plotly/documentation/pull/1182 answer your question?

**Comment by dragoljub** [comment]
I ended up using this to get it working to my needs:
```
fig['layout'].update(scene=dict(
    aspectmode='manual',
    aspectratio=go.layout.scene.Aspectratio(
       x=x.ptp(), y=x.ptp()/y.ptp(), z=z.pyp()/x.ptp()*100)
    )))
```

This gives me X & Y axis on the same pixel scale and then I can tune the Z scale by a multiple while keeping the ticks on the X,Y,Z axis in the correct data scale.
