### ISSUE TITLE
Labels are lost when using iplot_mpl()

### ISSUE THREAD

**Issue by lucaventurini** [plotly/plotly.py#735]
Hello,
i use plotly usually in a jupyter notebook. My workflow is as follows:

```python
fig = plt.figure()
... some plotting with matplotlib or pandas
pof.iplot_mpl(fig)
```

This is quite easy for me and decently working. However, if I have specified labels, within a bar plot for instance, the converted plot just shows a sequence starting from 1 for them.

Is it a known issue?

**Comment by Kully** [comment]
@lucaventurini Would you mind including a simple example? This will make it easier for us to test.

**Comment by a113n** [comment]
I am also running into this issue. The official examples in Plot.ly official documentation are also affected by this bug.
https://plot.ly/matplotlib/bar-charts/#plot-a-bar-using-a-dictionary
https://plot.ly/matplotlib/bar-charts/#stacked-bar-chart-with-labels

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
