### ISSUE TITLE
Dashboard get_preview() position ID inconsistencies 

### ISSUE THREAD

**Issue by bcdunbar** [plotly/plotly.py#757]
The way in which `insert()` assigns position numbers as displayed by `get_preview()` seems inconsistent and confuses users. For example:

<img width="465" alt="2017-05-22" src="https://cloud.githubusercontent.com/assets/8393928/26320210/f8207a82-3eef-11e7-9284-9ea6975e8304.png">

Here, when the dashboard is uploaded the order is box_1 then box_2 below 1 as specified in insert https://plot.ly/dashboard/bdun9:1419/view.

However, when using `get_preview()` before uploading the dashboard, it gives the impression that box_2 is above box_1 (as seen in attached image).

**Comment by cldougl** [comment]
cc @Kully

**Comment by Kully** [comment]
@bcdunbar Yeah, I can understand users finding that confusing.

The way I initially made the dashboard api was so that box ids were assigned on the fly, meaning that the layout of boxes were looked at and the algorithm assigned box ids to them.

The documentation says that the box ids are generated on the fly (https://plot.ly/python/create-online-dashboard/#get-box) but perhaps this is not clear enough.

Do you think it's worth making the warning more explicit and obvious, or just add an improvement to fix the way IDs are generated?

**Comment by cldougl** [comment]
@Kully it's confusing the `'above'` and `'below'` result in the same preview.

**Comment by Kully** [comment]
Closing as the docs have been rewritten to clarify these issues.
i.e. box_1 _does not_ correspond to the `1` position in the dashboard layout. `box_1`, `box_2`, and `box_3` have been renamed in the docs to avoid this confusion: `box_a`, `box_b`, `box_c`, etc.

doc: https://plot.ly/python/create-online-dashboard/
