### ISSUE TITLE
subplot doesn't support angularaxis / polar

### ISSUE THREAD

**Issue by ahmadh84** [plotly/plotly.py#758]
It seems like having both a polar and a non-polar graph in the same subplot doesn't work. In the following simple code, the angular polar graph doesn't work:
```
import plotly
import plotly.graph_objs as go
import numpy as np

# make 2 plots sublplot
fig = plotly.tools.make_subplots(rows=1, cols=2, specs=[[{}, {}]])

# the first subplot: a histogram
trace1 = go.Histogram(
    x=np.random.uniform(1,6,size=62),
)
fig.append_trace(trace1, 1, 1)

# the second subplot: a polar graph
trace2 = go.Scatter(
    r = np.random.uniform(1,6,size=62),
    t = np.random.uniform(30,5,size=62),
    mode='markers',
)
fig.append_trace(trace2, 1, 2)

plotly.offline.plot(fig, filename='temp.html')
```
Note that if `fig.append_trace(trace1, 1, 1)` is commented out, the polar graph is plotted. [I have been told](https://community.plot.ly/t/cant-get-polar-scatter-working-in-a-subplot/) that subplot doesn't fully support polar graphs.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
