### ISSUE TITLE
numerical colormaps don't interpret numerical color in ff.facet_grid

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.py#789]
```
import plotly.plotly as py
import plotly.figure_factory as ff

import pandas as pd
tips = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/tips.csv')

colormap = 'Viridis' 
# colormap = [[0,'rgb(255,0,0)'], [1, 'rgb(0,255,0)']]

fig = ff.create_facet_grid(
    tips,
    x='total_bill',
    y='tip',
    color_name='size',
    colormap=colormap
)
py.iplot(fig, filename='facet - color by continuous variable')
```

Yields the generic "Reds" colorscale without the colorbar on the side:
![scatter_red](https://user-images.githubusercontent.com/10369095/27794069-9d185b00-5fce-11e7-8241-67cd995ce883.png)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
