### ISSUE TITLE
plot_mpl is not able to render specgram()

### ISSUE THREAD

**Issue by ghost** [plotly/plotly.py#808]
Matplotlib has a nice fuction specgram() http://matplotlib.org/examples/pylab_examples/specgram_demo.html , but the render function is not able to render this. Is it possible to add the missing function.

```
fig , ax = plt.subplots()
Pxx, freqs, bins, im = ax.specgram(x, NFFT=NFFT, Fs=Fs, noverlap=32)
dv = plotly.offline.plot_mpl(fig, output_type='div')
```
brings:
```dv = plotly.offline.plot_mpl(fig, output_type='div')
/usr/lib/python2.7/site-packages/plotly/matplotlylib/renderer.py:396: UserWarning:

Aw. Snap! You're gonna have to hold off on the selfies for now. Plotly can't import images from matplotlib yet!
```

`Empty data list found. Make sure that you populated the list of data objects you're sending and try again.  Questions? Visit support.plot.ly`

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
