### ISSUE TITLE
3D camera 'up' setting doesn't do anything

### ISSUE THREAD

**Issue by binaryfunt** [plotly/plotly.py#815]
If I try to set the camera 'up' direction to y (or x), nothing actually happens.

    layout = {
        'scene': {
            'camera': {
                'up': {'x': 0, 'y': 1, 'z': 0}
            }
        }
    }
    fig = go.Figure(data=data, layout=layout)
    iplot(fig)

the plot produced still has the default z-axis as the 'up' direction.

**Comment by binaryfunt** [comment]
I have noticed that during an animation or restyle, the graph sometimes briefly flips and obeys the camera 'up' direction, but then reverts to the default immediately

**Comment by miriamperkins** [comment]
I would also like to use the camera up attribute, but find it is not working. Can this issue be resolved?

**Comment by jonmmease** [comment]
To set the camera up direction you need to set the `layout.scene.dragmode` property to `'orbit'`, rather than the default value of `'turntable'`.  The turntable drag mode forces `z` to be up by definition, so this is overriding the specified up vector

```python
layout = {
    'scene': {
        'camera': {
            'up': {'x': 0, 'y': 1, 'z': 0}
        },
        'dragmode': 'orbit'
    }
}
data = [go.Scatter3d(x=[0.5, 0.5], y=[1, 1], z=[0, 1])]
fig = go.Figure(data=data, layout=layout)
iplot(fig)
```
![newplot 2](https://user-images.githubusercontent.com/15064365/45919505-53fe9380-be64-11e8-8297-21573c440aad.png)

**Comment by virgile-hogman** [comment]
Awesome @jonmmease thank you so much for this tip!
I've been searching for at least 2 hours the correct way to use this camera setup. So happy it now works so fine! :)

Btw not very clear also how the eye dict works. What are the units or what do they exactly refer to?
