### ISSUE TITLE
Assigning customdata for Scattermapbox lines

### ISSUE THREAD

**Issue by radumas** [plotly/plotly.py#818]
I'm trying to use the click/hover callbacks in dash with a mapbox map that displays lines. I create each line with something like
```python
go.Scattermapbox(
        lat=lats,
        lon=lons,
        mode='lines',
        hoverinfo='text',
        name=row.segment_name,
        customdata=row.segment_id,
        text=row.segment_id,
        showlegend=False
```
`segment_id` or `segment_text` appear nicely on hover, however in printing the callback I notice that the contents are
```json
{
  "points": [
    {
      "lat": 43.6464730064524,
      "curveNumber": 2,
      "lon": -79.4037543398975,
      "pointNumber": 28
    }
  ]
}
``` 
Is there a way to link `curveNumber` back to the data that created the map? If I assign a numeric variable to `customdata`, it doesn't appear in the callback. If I assign a string variable to `customdata`, only 1 letter appears per point on the line.

## Current workaround
My understanding is that whatever is consuming the `customdata` is iterating over it for each generating point. I tried creating an iterator for the variable I want that iterates infinitely, but this gave me errors that repeat() is not JSON seriablizable. So my workaround is to create a list from repeating the `segment_id` variable for the number of points there are in the line.
```python
customdata=list(itertools.repeat(row.segment_id, times=len(lats))),
```

**Comment by cldougl** [comment]
Hi there,
For dash support you can checkout our forum here: https://community.plot.ly/c/dash

**Comment by radumas** [comment]
While my problem with this occurred in Dash, `customdata` is actually part of the `plotly.py` API
:point_right: https://plot.ly/python/reference/#scattermapbox-customdata

**Comment by cldougl** [comment]
Right, but for callback issues and questions you'd have to refer to the dash repo or [plotly.js](https://github.com/plotly/plotly.js) 

If you encounter a bug with the attribute `customdata` in relation to the graph created with the python api I'm happy to address it here, otherwise we ask users to ask support questions in the [forum](community.plot.ly) or via [our support app](support.plot.ly)

**Comment by radumas** [comment]
Realizing that I didn't explain my problem with `customdata` and lines properly :point_up: 

For `lines` in `scattermapbox`, `customdata` is being treated as an array, and is assigning one item of that array to each point of the line, rather than the line as a whole. Also, if `customdata` is assigned a number, this assignment appears to fail silently, which doesn't seem ideal. This wasn't intuitive to me, and isn't explicit in the documentation. 
>Assigns extra data each datum. This may be useful when listening to hover, click and selection events. Note that, "scatter" traces also appends customdata items in the markers DOM elements

The documentation should make this behaviour explicit for lines. Also I'd recommend that, if `mode='lines'`, `string` or `numeric` values assigned to `customdata` should be automatically repeated for every point on a line.

**Comment by cldougl** [comment]
I see, assigning one `customdata` item to each point of the line is the expected behaviour. Based on the description we try to make it clear that this takes a list rather than single value,
![screen shot 2017-08-16 at 3 33 25 pm](https://user-images.githubusercontent.com/2789078/29381789-740fc2ec-8298-11e7-8672-ea922f263fe2.png)
but if you have suggestions on how to make that more clear it's definitely welcome-thanks!

Also, if you're interested in setting a consistent item across all points in a line you may want to consider the text attribute: https://plot.ly/python/reference/#scattermapbox-text (it looks like you may have added that in your code above, that can be set to a string and then attributed to all points in a line)

**Comment by radumas** [comment]
Unfortunately the text attribute doesn't get passed in a callback (but that's a Dash issue I guess).

Can I suggest something like the following change to the doc?
>Assigns each item from the `customdata` array as extra data to each mapped datum. This may be useful when listening to hover, click and selection events. For lines, these data are assigned to the line's component points. Note that, "scatter" traces also append customdata items in the markers DOM elements
