### ISSUE TITLE
is_bar() in mpltools breaks stacked bar charts

### ISSUE THREAD

**Issue by amhoov** [plotly/plotly.py#87]
The is_bar() function in mpltools appears to be checking whether a patch is a bar by checking the minimum y value to see if it's zero. I typically create stacked bars in matplotlib by changing the named parameter, "bottom" to be non-zero. However, the is_bar() check wipes out all patches for which the minimum y value is not zero. I'd be happy to submit some sample code that breaks when rendering using the iplot_mpl() function from plotly if necessary.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
