### ISSUE TITLE
ipython notebook-wide plotlying (ie  enable_notebook())

### ISSUE THREAD

**Issue by arsenovic** [plotly/plotly.py#90]
would be sweet to have a function like this
    http://mpld3.github.io/modules/API.html#mpld3.enable_notebook
which implicitly converts all mpl-plots to plotly.  

perhaps the plotly-plots could be  named based on the plot's title, if one exists, and other options (like private/public-ness) where arguments to `enable_notebook()`

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
