### ISSUE TITLE
Surface plot docs should link to 3d axes docs

### ISSUE THREAD

**Issue by ebigelow** [plotly/plotly.py#915]
Following the [3d surface docs](https://plot.ly/python/3d-surface-plots/), I was confused as to why my axis properties (e.g. title) were not rendering correctly, and spent a while tweaking this with no success. I was certain this was a bug in plotly.py until I happened upon the page for formatting [3d axes in python](https://plot.ly/python/3d-axes/) -- which really should be linked to in the 3d surface docs page to avoid this confusion.

Side question: is it possible to directly contribute to the [https://plot.ly/python](https://plot.ly/python) docs via github?

**Comment by cldougl** [comment]
Hi there,
You can open documentation issues in our doc repo here: https://github.com/plotly/documentation/issues (we request documentation issues go there since it's not quite an issue with the api library). Great idea- you can let us know where you think the link should go or add an example if you have one in mind!

Yes! We'd love to have documentation contributions. We have a [contribution guide](https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/README.md) that you're welcome to check out!
