### ISSUE TITLE
Properly import matplotlib errorbars

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#96]
When using matplotlib, error bars come in as bizarre looking scatter plots right now. This should be fixed in future releases.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
